### ISSUE TITLE
Revisit UI for Days & Edit Hours in Crew Corner

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#103]
Not sure the best answer here, but I still think it's pretty confusing that in the roster in CC we list Days, but in the header we have Edit Hours.  And the two are sort of running into each other layout-wise

![image](https://cloud.githubusercontent.com/assets/931031/7693380/6d13d982-fd85-11e4-965a-caa99d5b5e6c.png)

  I would suggest adding a column for Hours, and/or putting the button above the list so it doesn't look like a misplaced header without any data.   

I think this came about b/c Darrell's original design assumed we'd be entering days, not hours.

**Comment by davisagli** [comment]
Yeah, I think the mockup just says "Edit", and I changed it to "edit hours" since that what it actually does.

What would show in the hours column? A sum of the hours for all the work party's days? Is that available as a rollup on the registration object?

**Comment by mscholtz** [comment]
That's what I was thinking if we showed the column, yeah.  If there's not a rollup yet, we could make one.

**Comment by WaBirder57** [comment]
I like your idea of moving the Edit Hours to the Reporting Tab (someone just implemented this).  We had it on the Crew Corner tab in part as that was where there was the roster of volunteers.  But since the pop up window includes all the volunteers we can move this to the reporting tab where we are entering all the hours for the WP.

**Comment by davisagli** [comment]
I removed the button; it's now only accessible on the report tab.

**Comment by WaBirder57** [comment]
This works in the new location when the crew leaders is editing the report for the WP.
