### ISSUE TITLE
Can't login to my backpack on VMS staging server

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#104]
This morning I tried to login to My Backpack on the VMS Staging server and I got the message:

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /login.

Reason: Error reading from remote server

Apache/2.4.7 (Ubuntu) Server at staging.wta.org Port 80

**Comment by davisagli** [comment]
You must have hit the staging Plone site while it was restarting. It's working for me now.

**Comment by WaBirder57** [comment]
Yup , that must be it.
