### ISSUE TITLE
add Contact rollups to track whether medial/backcountry forms are complete

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#106]
The CL roster is supposed to indicate whether each registrant has completed the medical and backcountry experience forms (when those are required documents for the work party type).

It would be nice if we could get this info from fields on the contact so that we don't have to do separate queries to the tables for submitted forms.

I propose adding these rollup fields to Contact:
- a "Medical form date" rollup summary field, the max of the Date Submitted on related WP Medical Forms
- a "Backcountry experience form date" rollup summary field, the max of the Date Submitted on related backcountry experience forms (hmm...there doesn't appear to be an object for backcountry experience forms yet?)

Then in pyramid I can fetch those fields from the contact for each registration, and show a checkbox based on whether the date is within the past year.

Alternatively, I could also add formula fields which do the "within the last year" check and show a checkbox in Salesforce.

Is this okay, @mscholtz?

**Comment by mscholtz** [comment]
My only hesitation is that we have a limit of 20 on the Contact object.  (The usual limit is 10, they bumped us up to 20 on request, but probably won't up it any further.)  We're already using 12 fields, and will no doubt need more.  Contact is where we generally need them the most.

Could this be done w/ a subquery, rather than a separate query?

**Comment by davisagli** [comment]
I don't think it can be done with a subquery. I tried this:

    select (select Id FROM Contact__r.WP_Medical_Forms__r) from WP_Registration__c

but it complains:

    First SObject of a nested query must be a child of its outer query.

**Comment by mscholtz** [comment]
Oh, right.  You're pulling from Registration, not Contact.  Yeah, can't
turn that corner.
Yeah, OK, go ahead and do the rollups.  Please put in the field
descriptions what they're being used for.  We can revisit later if we end
up needing the rollup slots.



On Tue, May 19, 2015 at 3:04 PM, David Glick <notifications@github.com>
wrote:

> I don't think it can be done with a subquery. I tried this:
>
> select (select Id FROM Contact__r.WP_Medical_Forms__r) from WP_Registration__c
>
> but it complains:
>
> First SObject of a nested query must be a child of its outer query.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/106#issuecomment-103680706>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Okay. Any opinion on adding those checkbox formulas also, vs doing that calculation in pyramid?

**Comment by mscholtz** [comment]
I'd prefer you do that in Pyramid, since we don't have reason to think we
need it in SF.

On Tue, May 19, 2015 at 3:23 PM, David Glick <notifications@github.com>
wrote:

> Okay. Any opinion on adding those checkbox formulas also, vs doing that
> calculation in pyramid?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/106#issuecomment-103683629>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
This got finished up as part of story 209
