### ISSUE TITLE
Cancel from Workparty doesn't work, Pyramid seems to freeze at "Canceling....."

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#112]
When a registered Volunteer tries to cancel from a work party, they click on the red "Cancel" button.

This button changes to "Canceling..." and the nothing else happens and the Volunteer is NOT canceled from the work party.

**Comment by davisagli** [comment]
Which work party and which volunteer did you experience this with?

**Comment by davisagli** [comment]
And which user were you logged in as when you tried to cancel the volunteer?

**Comment by WaBirder57** [comment]
I did this with a couple work parties (all that I tried had the same behavior).  Logged in a FastCar ; a volunteer.

**Comment by davisagli** [comment]
Try now. I broke it while adjusting the cancellation code to handle cancellation from a group registration, but I think I've fixed the problem now.

**Comment by WaBirder57** [comment]
Yes, works now.  But now if a work party is full the WP info page doesn't show option to join waitlist, just says "Join Work Party".

**Comment by davisagli** [comment]
It shows "Join waitlist" for me now. Remember that it takes 30 seconds once the work party is full for its new status to be indexed. Until then the button still says "Join work party," but if the user submits the registration form it will find out from Salesforce at that point that it's full, and ask the user for confirmation that they want to be on the waitlist.

**Comment by WaBirder57** [comment]
Nope, doesn't work that way for me.  User "FastCar"  Below is screen shot.  If I click on Register it does as for confirmation that  I want to join the work party, it is just this WP Info screen that isn't showing the Join Wait List button.
![evans creek](https://cloud.githubusercontent.com/assets/8312206/7871821/4c0506b6-0547-11e5-9de1-1bcee2fc7cd9.JPG)

**Comment by davisagli** [comment]
Here's how it looks for me when logged out or logged in as my user:

![screen shot 2015-05-28 at 2 42 00 pm](https://cloud.githubusercontent.com/assets/49014/7871881/cfc618dc-0547-11e5-9411-f1ea5a6c3562.png)

Would you mind sharing the login for FastCar so I can investigate while logged in as that user?

**Comment by WaBirder57** [comment]
User: FastCar
PW: charlesk

**Comment by WaBirder57** [comment]
OK, so I logged out and then logged in and now it works as expected.

**Comment by davisagli** [comment]
It shows "join work party" for me when I log in as FastCar -- but now it looks like the work party is no longer full, so that's expected.

**Comment by WaBirder57** [comment]
Evans Creek  June 12: https://cs9.salesforce.com/a2eK0000000wL7P is full in Salesforce.

**Comment by davisagli** [comment]
Hmm, that's supposed to automatically set the "Set to Full" checkbox, which is what tells the pyramid app to show the work party as having a waitlist. Right @mscholtz and @ninetaLogik? Can you tell why that didn't happen in this case?

**Comment by mscholtz** [comment]
@davisagli I don't think that's right.  Set to Full is the manual override.  It's supposed to set the Place on Waitlist box (which is a formula.)  And that is currently set for that WP.   Can you make sure that your code is looking at the latter, and not the former?

**Comment by ebskopin** [comment]
this is working now
