### ISSUE TITLE
WP Registration Error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#113]
When trying to register as a volunteer using FastCar for the WP: http://staging.wta.org:6543/workparty/a2eK0000000wL7Z Aug (Aug 1 Lake 22 BCRT) I get the following error:

{"code": 500, "detail": "unsupported operand type(s) for +: 'float' and 'NoneType'", "title": "TypeError"}

**Comment by davisagli** [comment]
Try now

**Comment by WaBirder57** [comment]
Works now.
