### ISSUE TITLE
work party rollups include registrations regardless of status

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#114]
Work Party has some roll-up summary fields which are not filtering correctly by the registration status. They are currently either including all registrations for the work party regardless of status, or only including status = Registered (which is a problem since some of the fields are used for checking whether the wp has reached capacity, and "Payment Pending" and "Invited from waitlist" are also supposed to count toward the capacity).

The rollup fields are:

* Number of Youth Registrations
* Incentive Days Total
* Service Hours Total
* Total ACLs Registered
* Total Crew Leaders Registered
* Total Volunteers Registered
* Total Volunteer Work Hours

**Comment by mscholtz** [comment]
OK, here's what I did:

* changed all the "Total x Registered" fields to include those in status Payment Pending
* added rollup fields for "Total on Waitlist" and "Total Invited from Waitlist" - I wanted to have these separately
* changed the formula of "Number of Remaining Spots" so that it considers everyone on the waitlist (invited or not) to be holding a spot.  So if my capacity is 5, and I have 3 Registered, and 1 Invited from Waitlist, and 1 Waitlisted, Remaining Spots = 0
* This formula in turn feeds into the "Place on Waitlist" formula, which is what our code looks at when deciding what to do w/ a new registration

**Comment by mscholtz** [comment]
Note that the Waitlist Volunteers Only checkbox, which is what controls when we waitlist vols but let ACLs continue to register when we don't have the right ratio, is still only looking at the ratio among registered (and payment pending) people, not among anyone on the waitlist, including invitees.  I think this is OK, but let me know if anyone disagrees.

**Comment by davisagli** [comment]
So far so good.

What about the rollups for hours and incentive days? Have they been updated to only count registered statuses?

What about the check against the group capacity? It looks like WTA_VMS_WP_Registration_TriggerClass is still fetching all group registrations regardless of status.

**Comment by mscholtz** [comment]
Right, thanks, fixed the hours/days rollups too.
re: group capacity, that doesn't seem to be a part of this ticket.   Could you make a separate ticket for that?

**Comment by davisagli** [comment]
Okay, I made #125 for that one, and will close this one.

**Comment by davisagli** [comment]
I thought you fixed the hours/days rollups? I don't see any filter on:
- Total Service Hours - https://cs9.salesforce.com/00NK0000001giXq?setupid=ContactFields
- Total Incentive Days - https://cs9.salesforce.com/00NK0000001giXv?setupid=ContactFields

**Comment by mscholtz** [comment]
Those are fields on Contact.  This ticket was about fields on Work Party.
I will change these as well, though.

On Wed, Jun 10, 2015 at 12:04 PM, David Glick <notifications@github.com>
wrote:

> Assigned #114 <https://github.com/washingtontrails/vms/issues/114> to
> @mscholtz <https://github.com/mscholtz>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/114#event-327774333>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Oh, you're right. Thanks.

**Comment by mscholtz** [comment]
Done.
