### ISSUE TITLE
Work party registration confirmation email conditional field

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#117]
When the work party registration email is sent with work party details it currently includes:
**********************
Work party: Coyote Wall Trails
Date: 8/7/2015 - 8/7/2015
Days: 1
Name: Julie Cassata
Group Name:
Directions to Work Party: 
***********************

The line "Group Name" should only be included if there is a value for the field Group Name.  Otherwise  the line for "Group Name:" should not be included in the email.

**Comment by ninetaLogik** [comment]
Not sure why this is still assigned to me, it has the reviewing label. Will assign to Elliott to verify.

**Comment by ebskopin** [comment]
This is working now.
