### ISSUE TITLE
registration webservice not setting contact phone number

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#12]
From @WaBirder57: "I didn't see that the phone number entered during registration made it to the SF Contact. Other info like address did work ok."

I'm not sure which type of phone number Charles entered.

**Comment by WaBirder57** [comment]
This is the phone number on the Work Party Registration Page, a required field.  I had the default Mobil/Cell option selected.

 

When I choose Home Phone on this registration page it works and updates the contact info in Salesforce.

 

Charlie

**Comment by mscholtz** [comment]
@ninetaLogik can we debug this for this iteration?

**Comment by ninetaLogik** [comment]
This should now be fixed

**Comment by davisagli** [comment]
@WaBirder57 please confirm that this is working now, and then close this issue.

**Comment by WaBirder57** [comment]
This is working correctly now.

 

When I register for a work party I can choose which phone number to update in Salesforce.

 

Charlie

**Comment by davisagli** [comment]
Charlie, please click the "view it on GitHub" link at the bottom of this email, log into github, and click the "Close issue" button. This is how you indicate that you've tested and accepted our work to fix the issue.

**Comment by WaBirder57** [comment]
This is working now.

**Comment by WaBirder57** [comment]
Done.

 

Do you know which story shows the WP Registration for a logged in user pulling contact info from Salesforce?
