### ISSUE TITLE
registration email only sent for new registration objects

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#121]
Currently the workflow alert that notifies users once they're registered is configured to only fire for newly created registrations. I think the notice should also be sent for registrations that switch to the Registered status later (such as after accepting an invitation from the waitlist).

Workflow rule: https://cs9.salesforce.com/01QK00000001GEy

**Comment by mscholtz** [comment]
That makes sense to me.
@WaBirder57 can you think of any situations like this in which this shouldn't be sent?

**Comment by WaBirder57** [comment]
I can't think of any situations where the email should not be sent when the wait list volunteer has be added to the roster.

**Comment by mscholtz** [comment]
@WaBirder57 thinking this is high priority.  Let me know if you disagree.

**Comment by ninetaLogik** [comment]
I don't understand this ticket. The workflow already handles both new regs and changes in status. I also tested that this works. Can we close this?

**Comment by ninetaLogik** [comment]
Assigning to Charlie for verification.

**Comment by mscholtz** [comment]
Hmm, looks like the rule has been modified since this ticket was filed.  Maybe someone fixed this without remembering there was a ticket..

**Comment by davisagli** [comment]
I just tested by creating a waitlisted registration and then changing its status to Registered, and I received an email, so this appearts to be working now, unlike when I filed the ticket.
