### ISSUE TITLE
ACL Only Work party - Should indicate on WP that this is ACL Only

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#123]
When creating a Work Party based on a WP Type which is "ACL Only" there should be some indication on the work party that it is ACL Only.

Test: Create a new work party based on WP Type "ACL Training" which is set as ACL Only.  Fill out enough fields to create this WP.  Note that there is no way to tell that this is ACL Only other than by going back to the base WP Type.  Can we add a check box to WP that indicates if it is ACL Only?

**Comment by mscholtz** [comment]
@WaBirder57 you mean showing on the WP screen in SF?

**Comment by mscholtz** [comment]
@WaBirder57 bump...

**Comment by WaBirder57** [comment]
Yes, this would be visible in the WP screen in SF.

**Comment by davisagli** [comment]
I added an "ACLs Only" checkbox to the Work Party page layout which shows the value from the work party type.

**Comment by mscholtz** [comment]
Looks good to me.
@WaBirder57 will let you close this after your review.

**Comment by WaBirder57** [comment]
OK, looks good.  I also added Help Text for this field on the Work Party so that folks know what it means and where it is set.  I'm testing how these work parties are displayed in VMS.
