### ISSUE TITLE
group capacity check during registration ignores registration status

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#125]
There's code in WTA_VMS_WP_Registration_TriggerClass to determine the status for a new registration. If it's a group registration it checks to see if the group capacity has been reached. But currently it counts all registration objects, including cancelled. It should only count registrations with a status of Registered, Payment Pending, Invited from waitlist, or Waitlisted

**Comment by mscholtz** [comment]
@ninetaLogik could you take care of this this week if you have time?  Thanks!

**Comment by ninetaLogik** [comment]
sure, this is next on my list

**Comment by ninetaLogik** [comment]
So basically, any status<> Cancelled, right? or should I check for one of those 4 statuses: Registered, Payment Pending, Invited from waitlist, or Waitlisted

**Comment by davisagli** [comment]
There are currently 2 statuses that should not count: Cancelled and Payment Not Provided

**Comment by ninetaLogik** [comment]
@davisagli this should be done.

**Comment by davisagli** [comment]
Still not working as expected. I registered someone for this group: https://cs9.salesforce.com/a2yK00000006G3L which has a capacity of 8 and had 6 people registered. The new registration should have been Registered but it ended up Waitlisted.

**Comment by mscholtz** [comment]
I think this is happening because:

* you have no ACLs registered
* the WP starts within 7 days (which is what Waitlist Volunteers Window is
set to)
* so it's restricting vol registration until it gets more ACLs

You can tell this by the "Waitlist Volunteers Only" flag on the WP

On Mon, Jun 8, 2015 at 1:08 PM, David Glick <notifications@github.com>
wrote:

> Still not working as expected. I registered someone for this group:
> https://cs9.salesforce.com/a2yK00000006G3L which has a capacity of 8 and
> had 6 people registered. The new registration should have been Registered
> but it ended up Waitlisted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/125#issuecomment-110122916>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Got it; I forgot about that.

**Comment by ecmnineta** [comment]
So can this be closed then?

**Comment by ninetaLogik** [comment]
So can this be closed then?
