### ISSUE TITLE
Screen areas for multiple required documents run together

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#126]
in this screenshot the white squares for Medical and Backcountry forms are contiguous, should be separate.

![image](https://cloud.githubusercontent.com/assets/931031/7973568/eba3d166-0a0b-11e5-8dca-2b43a238ca8d.png)

**Comment by davisagli** [comment]
Fixed

**Comment by mscholtz** [comment]
This doesn't appear fixed for me.  I'm expecting some grey space in between the white boxes for medical and backcountry

**Comment by davisagli** [comment]
Sorry, I thought I had deployed this but I hadn't.
