### ISSUE TITLE
"Cookie value is too long to store" with many registrations

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#128]
After our recent refresh (copy from production server) of the Staging website I am no longer able to log into my Pyramid My BackPack.  Seems like Pyramid account is not synced with Plone account:  I get the error message: 
_______________________
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
________________________
Steps - for me - 
Goto: http://staging.wta.org:6543/   Choose to log into My BackPack.  Use my Plone credentials.

If I go to:  http://staging.wta.org and login to Plone I am successful.  However Pyramid doesn't know that I am logged in when I switch back to http://staging.wta.org:6543/ I am not logged into My Backpack.

**Comment by davisagli** [comment]
This has nothing to do with the switch to the new staging server.

I'm seeing this error in the logs which I think is related:

```
Traceback (most recent call last):
  File "/usr/local/pyramid/vms/eggs/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/usr/local/pyramid/vms/eggs/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/usr/local/pyramid/vms/eggs/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 220, in invoke_subrequest
    request._process_response_callbacks(response)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/request.py", line 84, in _process_response_callbacks
    callback(self, response)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/session.py", line 299, in set_cookie_callback
    self._set_cookie(response)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/session.py", line 374, in _set_cookie
    len(cookieval)
ValueError: Cookie value is too long to store (4492 bytes)
```

I suspect that the way we're storing the user's registration info in a cookie does not work once a user has as many registrations as yours does. We will likely need to change how this session data is stored, which is a moderately involved change. In the meantime you may be able to work around the issue by deleting some of your contact's registrations, or by logging in as a different contact.

**Comment by WaBirder57** [comment]
I cleared my cache, deleted all my WP registrations using that Plone account and restarted my browser.  Now no one in the office is able to access: http://staging.wta.org:6543/   The page doesn't load and the browser just says it is waiting for the server.

**Comment by davisagli** [comment]
Try now; I restarted the VMS process. I can't tell why it hung, which may or may not be a related problem; I'll have to set up a debugging tool so I can see what it's doing the next time that happens.

**Comment by WaBirder57** [comment]
OK, that did the trick and I'm able to log in to Pyramid with 2 different accounts.

**Comment by davisagli** [comment]
I'm reopening this because we still need to fix the problem with how we're storing the session info so that it works when a user has lots of registrations.

**Comment by davisagli** [comment]
Fixed
