### ISSUE TITLE
Form icons on Documents tab aren't clickable

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#129]
I'm registered for a WP that requires Medical and Backcountry forms (http://staging.wta.org:6543/workparty/a2eK0000000wLWT/) but when I go to the Documents tab, neither form area is clickable, so I have no way to complete the forms.  This used to work for the Medical form.

Would love to get this fixed ASAP so we can test if the Backcountry form is working.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Looks good and both forms are working.
