### ISSUE TITLE
Adjust registration trigger to handle status updates

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#134]
originally a task from story 257: 

1) make sure registrations can't be added with status of Payment Pending unless there's space - treat this the same as we currently treat Registered status (if there's not room, put them on the waitlist)

2) also check capacity when a registration status is updated to registered, payment pending, or Invited from Waitlist.  in this case, throw an error if no capacity exists

**Comment by ninetaLogik** [comment]
@mscholtz so is the solution we're wanting here to modify the trigger to handle status update? How should it react when we're trying to change the status but there is no room. Should it display an error that gets shown on the page? 
If we were to have an Invite From Waitlist button what behavior would that exhibit? Is the button something we want done for this ticket?

**Comment by ninetaLogik** [comment]
verified item 1 on the list : 1) make sure registrations can't be added with status of Payment Pending unless there's space - treat this the same as we currently treat Registered status (if there's not room, put them on the waitlist)  - This works as expected

**Comment by davisagli** [comment]
Verified item 2 for the case where status is manually changed from Waitlisted to Registered on a work party that doesn't have capacity.

**Comment by ninetaLogik** [comment]
@davisagli I was still working on this, but glad it's working already.

**Comment by davisagli** [comment]
I wasn't specifically trying to test it; I just tried to change a status while testing something else and noticed that it's working.

**Comment by ninetaLogik** [comment]
This is now done.

**Comment by skleinfeldt** [comment]
Should this be reviewed by @mscholtz or @WaBirder57 ?

**Comment by skleinfeldt** [comment]
I'm guessing @mscholtz so assigned to him.
