### ISSUE TITLE
hide "Add to My Backpack" button if I'm registered for a WP?

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#136]
Isn't the "Add to My Backpack" button meant as a way to save the WP to a "wish list" so I don't forget to sign up later?  If so, not sure it makes sense to show it if I'm already signed up.

![image](https://cloud.githubusercontent.com/assets/931031/8016904/f9075bf4-0b9e-11e5-9e69-2107b02f71a9.png)

**Comment by davisagli** [comment]
We haven't gotten to the stories for the wish list yet.

**Comment by davisagli** [comment]
I hid the button for now.
