### ISSUE TITLE
flesh out Medical History form in FormAssembly

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#14]
I think we want to finish this and make sure everything works, before we go on to the Backcountry Experience form

**Comment by WaBirder57** [comment]
I have fleshed out the Medical form.  I was not sure what some of the fields types should be especially for the longer text fields.

 

Note that this form is consistent for all volunteer participants so that it doesn’t vary (at this time) based on WP Type.

 

Charlie

**Comment by mscholtz** [comment]
OK, can you send the link to the form?

And do you maybe want to take on adding the additional fields to the
Medical Form object in SF, and doing the additional mapping in FA?  Then we
could check your work and make adjustments as necessary?

On Mon, Feb 9, 2015 at 4:22 PM, Charles Kahle <notifications@github.com>
wrote:

> I have fleshed out the Medical form. I was not sure what some of the
> fields types should be especially for the longer text fields.
>
>
>
> Note that this form is consistent for all volunteer participants so that
> it doesn’t vary (at this time) based on WP Type.
>
>
>
> Charlie
>
>
>
> From: Matthew Scholtz [mailto:notifications@github.com]
> Sent: Monday, February 09, 2015 2:44 PM
> To: washingtontrails/vms
> Cc: Charles Kahle
> Subject: [vms] flesh out Medical History form in FormAssembly (#14)
>
>
>
> I think we want to finish this and make sure everything works, before we
> go on to the Backcountry Experience form
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/washingtontrails/vms/issues/14> . <
> https://github.com/notifications/beacon/AH7VjjP0rccOalBoRyk2LEC3VwUBp-Vdks5nqS-8gaJpZM4DeAhT.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/14#issuecomment-73620467>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Here is the link to the form, is this what you need?

 

http://www.tfaforms.com/362208  <http://www.tfaforms.com/362208> 

 

I will work on figuring out how to map these additional fields (which I will add to SF).

 

Charlie

**Comment by mscholtz** [comment]
Yep, that's what I need.  It's looking good!

On Tue, Feb 10, 2015 at 8:49 AM, Charles Kahle <notifications@github.com>
wrote:

> Here is the link to the form, is this what you need?
>
>
>
> http://www.tfaforms.com/362208 <http://www.tfaforms.com/362208>
>
>
>
> I will work on figuring out how to map these additional fields (which I
> will add to SF).
>
>
>
> Charlie
>
>
>
> From: Matthew Scholtz [mailto:notifications@github.com]
> Sent: Monday, February 09, 2015 5:02 PM
> To: washingtontrails/vms
> Cc: Charles Kahle
> Subject: Re: [vms] flesh out Medical History form in FormAssembly (#14)
>
>
>
>
> OK, can you send the link to the form?
>
> And do you maybe want to take on adding the additional fields to the
> Medical Form object in SF, and doing the additional mapping in FA? Then we
> could check your work and make adjustments as necessary?
>
> On Mon, Feb 9, 2015 at 4:22 PM, Charles Kahle <notifications@github.com>
> wrote:
>
> > I have fleshed out the Medical form. I was not sure what some of the
> > fields types should be especially for the longer text fields.
> >
> >
> >
> > Note that this form is consistent for all volunteer participants so that
> > it doesn’t vary (at this time) based on WP Type.
> >
> >
> >
> > Charlie
> >
> >
> >
> > From: Matthew Scholtz [mailto:notifications@github.com]
> > Sent: Monday, February 09, 2015 2:44 PM
> > To: washingtontrails/vms
> > Cc: Charles Kahle
> > Subject: [vms] flesh out Medical History form in FormAssembly (#14)
> >
> >
> >
> > I think we want to finish this and make sure everything works, before we
> > go on to the Backcountry Experience form
> >
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/washingtontrails/vms/issues/14> . <
> >
> https://github.com/notifications/beacon/AH7VjjP0rccOalBoRyk2LEC3VwUBp-Vdks5nqS-8gaJpZM4DeAhT.gif
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/washingtontrails/vms/issues/14#issuecomment-73620467
> >.
> >
>
>
>
> --
>
> Matthew Scholtz
> Percolator Consulting
> (206) 289-0816 x3
>
> http://percolatorconsulting.com/
>
>
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/washingtontrails/vms/issues/14#issuecomment-73624729>
> . <
> https://github.com/notifications/beacon/AH7VjrBUkkz3YN-Xf6GS0kl9QrsIYnLlks5nqVAWgaJpZM4DeAhT.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/14#issuecomment-73735458>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by skleinfeldt** [comment]
@WaBirder57 and @mscholtz can this ticket be closed?

**Comment by mscholtz** [comment]
@WaBirder57 did you finish adding and mapping fields here?

**Comment by WaBirder57** [comment]
All fields are added but not all mapped to Salesforce.

**Comment by davisagli** [comment]
You'll probably want to map them to Salesforce before long so that you can test Carlos' work on printing out the medical form data stored in Salesforce.

**Comment by WaBirder57** [comment]
I’m working on mapping these fields but ran into an issue with Form Assembly.

**Comment by mscholtz** [comment]
Anything you need help with?

On Tue, Apr 21, 2015 at 4:32 PM, Charles Kahle <notifications@github.com>
wrote:

> I’m working on mapping these fields but ran into an issue with Form
> Assembly.
>
>
>
> From: David Glick [mailto:notifications@github.com]
> Sent: Tuesday, April 21, 2015 4:08 PM
> To: washingtontrails/vms
> Cc: Charles Kahle
> Subject: Re: [vms] flesh out Medical History form in FormAssembly (#14)
>
>
>
> You'll probably want to map them to Salesforce before long so that you can
> test Carlos' work on printing out the medical form data stored in
> Salesforce.
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/washingtontrails/vms/issues/14#issuecomment-94968178>
> . <
> https://github.com/notifications/beacon/AH7VjiZYZiIV8y2ofL7Gq2TEpGZINNSDks5oBs_pgaJpZM4DeAhT.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/14#issuecomment-94974390>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Yes, I think you all could solve this quicker.

 

I have updated the WTA Volunteer Medical Form  in Form Assembly (https://app.formassembly.com/forms/edit/summary/362208)  to have all the required fields.

I started adding the corresponding fields to the SF Object

Then I tried testing mapping the new Form Fields to the SF Fields I created.

 

At this point the new SF fields were not showing up in the FA Connector so I chose the option to Refresh the connection, thinking this would update the list of SF fields in FA so I could map them.

 

I get this error message:

 

https://app.formassembly.com/images/error.gifThe connector does not exist.

Please make sure you complete the connector classification on the connectors list page of the form first. 

 

Thoughts, ideas or help would be great.

Charlie

**Comment by mscholtz** [comment]
Hey @WaBirder57, I asked Barbara and she said this:

Yeah, it gives that error but it's not really gone-- you have to go back in to the connector from the home screen. I've commented about it to them before.

But that's not the way you refresh metadata. There is a link at the bottom of the form, in blue, "Get New Salesforce Objects"


Does that help?

**Comment by WaBirder57** [comment]
Looks good and got this to work.
