### ISSUE TITLE
When a new contact is created in Salesforce from VMS the Lead Source = Trail Work

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#141]
This is related to Story #184 or #172,  When ever VMS creates an new Contact in SF the Lead Source should be set to "Trail Work", not "Website" as it currently works.

Test: Add a new volunteer to a work party.  Check the Contact record created in Salesforce, check the Lead Source value. I'm not sure if this is a Salesforce or Pyramid issue.

**Comment by davisagli** [comment]
It's not related to story 184, which is about adding the contact as soon as someone registers for a My Backpack account (in which case we presumably want the lead source set to Website, yes?)

We should modify the registration webservice in Salesforce so that if it ends up creating a new Contact, it sets the lead source to Trail Work. Probably we should also do that if the user login webservice creates a new contact instead of matching an existing one.

**Comment by WaBirder57** [comment]
This may be more nuanced than you describe, if someone is browsing work parties and feels motivated to create a my backpack at that time that would be sufficient to have lead source = Trail Work.  Let me get some screen shots and circle back to this.

**Comment by davisagli** [comment]
If they're browsing work parties there are two ways they could end up creating a My Backpack account:

1. They fill out the registration form and check the box to create a My Backpack account. In this case the SF Contact will get created via the registration webservice, as I said above.

2. They click on a "log into my backpack" link that takes them to Plone, and then use the normal Plone registration form. Currently this does not immediately create an SF Contact; a contact would be created when they then log into VMS or fill out the registration form, and the lead source would get set correctly if we make the changes I described above. Once we do story 184, the SF Contact would get created immediately, and we would need to somehow keep track of the fact that the user came from VMS. I think we should handle that as part of story 184. There may be some ambiguous cases (what if the user clicks from VMS to log into my backpack, then browses around for a while, then creates a My Backpack account?)

**Comment by WaBirder57** [comment]
OK, Story 184 will do the trick then.
