### ISSUE TITLE
Work Party type needs Volunteer Capacity field

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#142]
The SF Work Party Type object needs the field Volunteer Capacity.   

The value of this fields should set the default value for Work Party.Volunteer Capacity when a new work party is created based on this Work Party Type.

**Comment by mscholtz** [comment]
@drewpiston could you take this ticket on this iteration?

**Comment by drewpiston** [comment]
Sounds good, I'm on it.

**Comment by drewpiston** [comment]
Hi @WaBirder57,

Should the Capacity field on a new Work Party also default to the value in the Work Party also default to the (existing) Work Party Type.Default Capacity field?

Thanks,
 Drew

**Comment by WaBirder57** [comment]
Hi @drewpiston , yes Capacity and Volunteer Capacity fields on a new Work Party should default to the value on the corresponding Work Party Type fields.

**Comment by drewpiston** [comment]
Hi @WaBirder57 , I had enough time to crank this one out this week, and did so.

**Comment by WaBirder57** [comment]
Looks good.
