### ISSUE TITLE
Rename Search Workparty Feature name

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#144]
In the Search Work Party Advanced options filter selection, change the name of "Free Day Pass" to "Earn Free Pass".

All volunteers get a free parking pass.  Certain work parties however will give the volunteer credit towards a free season pass (Discover or NW Forest Pass).  This should filter the WP list to only show WP which will give credit towards earning these season passes.

**Comment by davisagli** [comment]
This comes from the Features/Highlights multi-select picklist on the Work Party in Salesforce.

**Comment by WaBirder57** [comment]
Thank I have made the change and tested that it works.
