### ISSUE TITLE
Beyond_Capacity__c error in registration webservice

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#145]
@ninetaLogik, I got this error when trying to register someone:

```
System.DmlException: Insert failed. First exception on row 0; first error: INVALID_TYPE_ON_FIELD_IN_RECORD, Beyond Capacity: value not of required type: : [Beyond_Capacity__c]

Class.WTA_VMS_REST_CreateRegistration.createRegistrations: line 180, column 1
Class.WTA_VMS_REST_CreateRegistration.doPost: line 135, column 1
```

Matthew said it's probably related to the work you're doing for story 121. Can you take a look? (Or let me know when I can test again, if you're in the middle of working on that code.)

**Comment by ninetaLogik** [comment]
@davisagli I am in the middle of working on that code. will let you know when done

**Comment by ninetaLogik** [comment]
@davisagli it should work now.

**Comment by ninetaLogik** [comment]
@davisagli The Registration WS now takes a new param for the main participant as well as others. The new flag is called "beyondCapacity" boolean type.

**Comment by davisagli** [comment]
And if that's set to true then it won't do the normal capacity checks?

Can it default to false so that we don't have to change existing code that calls the webservice?

**Comment by ninetaLogik** [comment]
Yes, that is correct none of the capacity restrictions will apply if this flag is set to true.
No need to change existing code, flag defaults to false.

**Comment by davisagli** [comment]
Great!

**Comment by davisagli** [comment]
@cguardia this is the other change that needs to happen for story 121. IF the person filling out the "add person" form in Crew Corner is a crew leader (or admin), AND today's date is on or after the work party's start date, then it should pass beyondCapacity: true when it calls the registration webservice.

**Comment by davisagli** [comment]
@ninetaLogik I just tried again and got the same error. I think maybe when Apex deserializes the request it ignores the default value for beyondCapacity

**Comment by ninetaLogik** [comment]
@davisagli I changed the code to set the flag to false if it comes in as null.  Could you give it another try. If doesn't work then maybe something else is at play here.

**Comment by davisagli** [comment]
It works now. Thanks!
