### ISSUE TITLE
Load testing of registration

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#149]
I'm a bit worried that our system will not handle lots of people registering in a short period of time very well (like we need to do for volunteer vacation registration).

Concerns are:
1. Multiple calls to the registration webservice at once could hit lock timeouts on the work party, whose rollups need to be updated.
2. Multiple calls to the registration webservice at once could have a race condition that ends up allowing more people into the work party than are supposed to be allowed.

I want to write a test which hammers the registration form with a number of clients in parallel to flush out whether these problems are likely to occur in practice.

If the problems are real, we may need to find a way to throttle the calls to the registration webservice so only one can happen at a time.

**Comment by davisagli** [comment]
I wrote a [locust](http://locust.io/) test which simulates a crowd of clients all filling out the registration form at once, and directed it at this work party: https://cs9.salesforce.com/a2eK0000000wPXh

As you can see, we ended up with 6 more people registered than should be allowed. I think this is because the code that checks the rollups on the work party to determine if there is space left does not lock the work party, so other clients that try to check the same rollups before the first transaction completes see the same view of the database and reach the same conclusion that there's room. @mscholtz I'd like to try adding "FOR UPDATE" on the soql query that fetches those rollups from the work party, and re-run the load test. Okay?

**Comment by davisagli** [comment]
I went ahead and tried it with the "for update" option. With 50 clients hitting the site at an interval between .5s and 2s, that seems to solve the problem. With 250 clients hitting it at an interval between .2s and 1s, another problem becomes evident:

```
System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, WTA_WP_Registration: execution of BeforeInsert

caused by: System.QueryException: Record Currently Unavailable: The record you are attempting to edit, or one of its related records, is currently being modified by another user. Please try again.

Class.WTA_VMS_WP_Registration_TriggerClass.setWPStatus: line 122, column 1
Class.WTA_VMS_WP_Registration_TriggerClass.main: line 45, column 1
Trigger.WTA_WP_Registration: line 4, column 1: []

Class.WTA_VMS_REST_CreateRegistration.createRegistrations: line 181, column 1
Class.WTA_VMS_REST_CreateRegistration.doPost: line 135, column 1
```

IOW with the work party locked and a high volume of registration traffic the lock timeout becomes an issue. I think we should keep the "for update" because it fixes the race condition that can cause over-registration. There may not be enough traffic for the lock timeout to be a problem, and if there is we can solve it another way (e.g. make pyramid catch the lock timeout and try again).

**Comment by mscholtz** [comment]
Wow.  Lot to digest here.  After doing so, I think I approve of your methods (good to know about locust!) as well as your conclusions.  Agree that occasional retries are a better outcome than accidental overbooking.

One question: when you say "250 clients hitting it at an interval between .2s and 1s", do you mean that each of the clients is sending a request with that frequency, or does each client only send one request and that's the minimum gap between and 2 requests?

**Comment by davisagli** [comment]
Each client makes requests repeatedly until you stop the test, and it starts a configurable number of clients each second (20 in my test) until it reaches the target. Each client waits between the min and max delay (the numbers I gave above in my test) between requests. Each time it makes a request it picks randomly among the configured tasks, which in my test included loading the homepage, loading the work party list, and a viewing the work party in addition to loading and submitting the registration form....so not all of those requests actually hits the registration webservice. I could adjust the test so we only do that.

locust gives us stats on how long requests take. The results vary widely depending on how many threads I have pyramid's web server configured to use. This makes sense because if all the threads are waiting for a call to Salesforce (which appears to take an average of ~10 seconds for the calls to the registration webservice) then further incoming requests have to wait until a thread is available to process them. Fortunately, unlike Plone the system doesn't use a lot of RAM so there's no big reason we can't use a lot of threads...though we have to watch out for some limits on file descriptors and the `requests` library's connection pool.

**Comment by mscholtz** [comment]
Gotcha.  @WaBirder57 could speak to this better, and I could be completely wrong, but offhand that sounds like a higher load that we're likely to ever experience in production.

10s is way longer than I would expect the reg webservice call to take on average.  Are you sure that's just the time for the SF call and not for the entire pyramid request?  If so, I might want to look at what we could do to speed that up on the SF side.

**Comment by davisagli** [comment]
It's the time for the pyramid request, but the call to Salesforce is the only part of that that takes significant time (I'm guessing on that, and could profile to confirm if SF debug logs don't indicate similar times).
