### ISSUE TITLE
SSO shows login even if user already logged into Plone

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#15]
1. Log into Plone
2. Go to a work party in VMS and click the button to sign in.
3. Plone should immediately redirect back to VMS with the SSO token, but instead it shows the login form.

**Comment by davisagli** [comment]
This is now working.

**Comment by WaBirder57** [comment]
This works now but the Login cookie? is very persistent.  In Firefox, if the user Logs Out of my backpack and then logs in, they are not asked for User/PW.  They are just logged in (as the prior user).  I must clear the Firefox Cache, close and reopen the browser to login as a different user.

**Comment by davisagli** [comment]
Right - VMS uses a separate session cookie than the one used by Plone, and logging out of VMS does not currently log the user out of Plone. If you want to log in as a different user you currently need to log out of both VMS and Plone, then log back in.

**Comment by skleinfeldt** [comment]
I assume this is by design since @davisagli knows what he is doing - but this seems strange to me. I thought Plone and VMS were supposed to feel to the user like the same system?

**Comment by davisagli** [comment]
I think it would less confusing if we made sure that logging out in VMS also logs the user out in Plone. But we haven't done that yet.

**Comment by WaBirder57** [comment]
How does one log in/out of either VMS or Plone?  All we have on the UI is the MyBackback login.  Is that Plone or VMS?

**Comment by WaBirder57** [comment]
We should do this, can that be part of this ticket or do we need a new one?

**Comment by skleinfeldt** [comment]
Please make a new ticket for that @WaBirder57 - thanks.

**Comment by skleinfeldt** [comment]
In email @WaBirder57 said "How does one log in/out of either VMS or Plone? All we have on the UI is the MyBackback login. Is that Plone or VMS?"

I think that if you are on VMS (http://staging.wta.org:6543/) you are logging in/out of VMS with the links under the new style "My Backpack", whereas if you are on Plone (http://www.wta.org) you are logging in/out of Plone with the links under the old style "My Backpack". So yes it seems like this needs to be unified. I don't know if this is ticket-sized or story-sized, but make a ticket and ask whether it is big enough to be a story.

**Comment by cguardia** [comment]
Logging out from VMS should now log out from plone as well.

**Comment by WaBirder57** [comment]
Looks good.  Thanks!
