### ISSUE TITLE
Is there are way in Salesforce on a registration record to show the completion status of required forms?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#154]
When looking at a Work Party in Salesforce you can see the related list of registrations.  Is there a way to have this illustrate/indicate the completion status of the required forms.  This prototype page illustrates how VMS will show this information (http://07.wta.emptycan.com/volunteer/details/docs-required.html).

**Comment by mscholtz** [comment]
No, not easily.  You'd have to click through to the Contact and see which forms they've completed and when.
So if you want to show this in SF, we would need to write a new story for that.  It wouldn't be a huge story, but this is a new piece of functionality.

BTW, the wireframes show % complete but we decided just to show whether completed or not.

**Comment by WaBirder57** [comment]
Thanks for the answer.  We will leave it as is for now.
