### ISSUE TITLE
Join Wait List doesn't show next step, just stays on registration page

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#155]
When joining the wait list for a Work Party ( for example http://staging.wta.org:6543/workparty/a2eK0000000wOTM/) You click the join Wait List button at the bottom of the registration page, the button changes to "Submitting..." and then changes back to "Join Wait List".  The user is added to the WP wait list successfully but they stay on the VMS WP Registration Screen.

Also, it seems that email notification of the wait list registration is not generated.

**Comment by davisagli** [comment]
This should work now. My work on story 254 introduced a bug when registering a single person (NOT with friends/family).

> Also, it seems that email notification of the wait list registration is not generated.

We have an email notification that goes to the volunteer once they are fully registered, but this is the first I've heard of a requirement for them to be notified after they join the waitlist. Please add a story.

**Comment by WaBirder57** [comment]
Ah, I stand corrected regarding NO Email for Wait List sign ups.  Thanks for fixing the other bug.

**Comment by WaBirder57** [comment]
Looks like this Email to WP registrant when joining the WP Wait list is part of Story #31.  I will open a new ticket for that story for this particular use case of getting an email.

**Comment by skleinfeldt** [comment]
Assigning to @WaBirder57 to test and close.

**Comment by WaBirder57** [comment]
Working now.
