### ISSUE TITLE
Join work party button at bottom of Pyramid WP info tab returns error.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#156]
When looking at the Liberty Lake Trails Sept 12 work party (http://staging.wta.org:6543/workparty/a2eK0000000wPTG)  I was not able to join the work party using the "Join Work Party" button at the bottom of the Info Tab.  The "Join Work Party" button at the top of the page works correctly.

The error message is: 

Not Found

debug_notfound of url http://staging.wta.org:6543/workparty/register; path_info: u'/workparty/register', context: <vms.workparty.WorkPartyRoot object at 0x7fe815bef450>, view_name: u'register', subpath: (), traversed: (), root: <vms.workparty.WorkPartyRoot object at 0x7fe815bef450>, vroot: <vms.workparty.WorkPartyRoot object at 0x7fe815bef450>, vroot_path: ()

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Tested and this works again, thanks.
