### ISSUE TITLE
Story #31 - Work party Registration - Wait List Email is not generated

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#157]
When a volunteer registers for a work party Wait List (Guest or Logged in) they will get an email message acknowledging they are being added to the wait list and letting them know that when a spot opens up on the work party they will be notified via email by WTA.

**Comment by mscholtz** [comment]
@WaBirder57 so they're just not getting anything?  Have you tried this multiple times with different users logged in?  Was this working at some point and then stopped working?

**Comment by WaBirder57** [comment]
In talking with Drew it sounded like there is a process on  Salesforce which needs to be running to kick off these email sends (at least that is the case with the WP Reminder emails).  He restarted some of these processes so that may have fixed this at that time. 

 

I did just sign up, as a guest, for the wait list on the July 18 Sawtooth Logout (http://staging.wta.org:6543/workparty/a2eK0000000wL7h/) and didn’t get an email regarding being put on the wait lists for this WP.

 

Charlie

**Comment by mscholtz** [comment]
It looks to me like in all the back and forth we had on that story, we never built an email for waitlist confirmation, and only built one for registration confirmation.  If that's the case, we should probably write a new story.

@ninetaLogik can you verify when you're back from vacation?  You were the one who worked on that story.  Thanks!

**Comment by ninetaLogik** [comment]
@WaBirder57 do you remember which Iteration # and Story # you were testing here?

**Comment by davisagli** [comment]
@ninetaLogik story 31, like it says in the issue title

**Comment by ninetaLogik** [comment]
@mscholtz I reviewed story #31 and it looks like we only tasked out the status=Registered case. We will need to build an email and WF for Status=Waitlisted, so probably a separate story?

**Comment by ninetaLogik** [comment]
@davisagli Thanks, not sure how I missed that

**Comment by mscholtz** [comment]
@ninetaLogik yeah, that's what I saw too.  I'd say let's just do it under this ticket, unless you feel we need a new story.

**Comment by ninetaLogik** [comment]
@WaBirder57 do you have an email template that you would like to use for the Waitlisted scenario?

**Comment by WaBirder57** [comment]
I don't but something with text like:

Thank you for joining the Waitlist for [WorkPartyName] on [WorkPartyStartDate].  We will be in touch with you as soon as there is an opening on this work party.

WTA Trail Team

**Comment by ninetaLogik** [comment]
@WaBirder57 this should be ready to test.

**Comment by skleinfeldt** [comment]
Assigning to @WaBirder57 to test.

**Comment by WaBirder57** [comment]
As a volunteer I signed up for the waitlist of a work party.  I received email confirmation.  Looks like this is working.
