### ISSUE TITLE
VMS user loggout error when viewing work party with restricted access

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#158]
When viewing a work party with restricted access, such as an ACL only work party, as a user with permission to see this work party I get the attached error when I log out while viewing this work party.  Evidently once I am no longer authorized to see this work party, having logged out, VMS should redirect me back to the work party list screen rather than show this error.

![logout error on restricted work party](https://cloud.githubusercontent.com/assets/8312206/8416446/b3d50620-1e5a-11e5-91ce-e51ebc15326f.png)

**Comment by cguardia** [comment]
@davisagli I think the easy solution here would be to redirect always to home on logout. Do you think that would be acceptable? Other option would be to somehow check if a user has permission for a url before redirecting, but is it worth it?

**Comment by davisagli** [comment]
@cguardia I think that's acceptable.

**Comment by cguardia** [comment]
Fix is on master.

**Comment by ebskopin** [comment]
works, thanks
