### ISSUE TITLE
Safari/iPad bug - close "X" on Hours Worked pop up window doesn't close window

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#159]
When using an iPad with Safari, as a Crew Leader go to the Report Tab of a work party you are the CL for, and one with volunteers registered.  Go to the report tab, click (touch with finger) "Edit Volunteer Hours" button to open "Hours Worked" pop up.  The "X" circle on the top right should close this window but it doesn't respond to a finger touch on the iPod the way buttons do.  Nothing happens.  You can touch the "Save" button at the bottom to save and close this pop up.

**Comment by alecpm** [comment]
This should be fixed at the next deploy to staging.

**Comment by ebskopin** [comment]
works
