### ISSUE TITLE
Disable/remove story 43

### ISSUE THREAD

**Issue by skleinfeldt** [washingtontrails/vms#160]
This story turned out to be wrong, is replaced by story 273.

**Comment by drewpiston** [comment]
Code has been commented out! I left the templates in there in case we need them in the future, super easy to delete.

**Comment by mscholtz** [comment]
@drewpiston can we remove the field in WP Type too, as mentioned in #204 ?

**Comment by skleinfeldt** [comment]
I made an obvious notation on the story, but did not delete from Scrumdo since it contributed to our velocity in Iteration 12. I marked it "Done".

**Comment by drewpiston** [comment]
Field removed!

**Comment by mscholtz** [comment]
Thanks!
