### ISSUE TITLE
adding Crew Leader registration by hand does not update Leader field on WP

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#161]
we should either
1) prevent adding the registration by hand
or 
2) use trigger to fill in the Leader field

**Comment by mscholtz** [comment]
if we decide to go with #2, we will have to add validation on the registration object for the leader selected (paralleling story # 225)

**Comment by mscholtz** [comment]
we're going to go with option 2, and we also need code to prevent recursion so it does not attempt  to create a 2nd registration

**Comment by drewpiston** [comment]
Ready for review!

**Comment by WaBirder57** [comment]
Nice!
