### ISSUE TITLE
Crew Corner sign in sheet Review - gives error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#172]
When clicking on the Crew Corner - Sign In Sheet for work party: http://staging.wta.org:6543/workparty/a2eK0000000wPTG I get the following error, note i don't get this for other work parties.  This is the Sept 12, Liberty Lakes work party: 

Not Found

debug_notfound of url http://staging.wta.org:6543/workparty/sign-in.html; path_info: u'/workparty/sign-in.html', context: <vms.workparty.WorkPartyRoot object at 0x7fb120786f90>, view_name: u'sign-in.html', subpath: (), traversed: (), root: <vms.workparty.WorkPartyRoot object at 0x7fb120786f90>, vroot: <vms.workparty.WorkPartyRoot object at 0x7fb120786f90>, vroot_path: ()

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
It works, thanks.
