### ISSUE TITLE
Emergency Action Plan Shows Error not file

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#173]
Story #210 regarding the emergency Action plan.  I have the Beacon Rock Trail WP set up with a land manager that has an EAP document (MS Word File) attached.  Here is the link to the Work Park in VMs: http://staging.wta.org:6543/workparty/a2eK0000000wRBp

The Crew Leader corner show this document in the CL Tool Kit.  When i click Review VMS gives me this error:
debug_notfound of url http://staging.wta.org:6543/workparty/attachment/00PK0000002XtDz; path_info: u'/workparty/attachment/00PK0000002XtDz', context: <vms.workparty.WorkPartyRoot object at 0x7fb11c4d8fd0>, view_name: u'attachment', subpath: (u'00PK0000002XtDz',), traversed: (), root: <vms.workparty.WorkPartyRoot object at 0x7fb11c4d8fd0>, vroot: <vms.workparty.WorkPartyRoot object at 0x7fb11c4d8fd0>, vroot_path: ()

Here is a link to the SF Work Party https://cs9.salesforce.com/a2eK0000000wRBp?newid=a2qK0000000Eh2C

You can drill down as needed to get to the Trail Segment and then to Land Manager to see the EAP.  OR here is a link to the Land Manger: https://cs9.salesforce.com/001K000001CO5xv

Let me know if these documents need to be in a .PDF format rather than MS Word.

**Comment by davisagli** [comment]
This should work now.

**Comment by WaBirder57** [comment]
This works now.  Is it possible to have the EAP that is display to be the most recent one if there are more than one listed for a given land manager?

**Comment by davisagli** [comment]
That change can be done pretty easily. Based on the creation date of the EAP record?

**Comment by WaBirder57** [comment]
Yes, that would be great.  Creation Data of the EAP record in Salesforce for that land manager.  

I have added a second record to the Beacon Rock Land Manager: https://cs9.salesforce.com/001K000001CO5xv .  This can be tested from this Work Party: http://staging.wta.org:6543/workparty/a2eK0000000wRBp

Note the second, most current record, is a PDF file so we can test that this format is also working.

**Comment by davisagli** [comment]
Okay, if there are multiple EAPs for a land manager it now picks the most recently created one.

**Comment by WaBirder57** [comment]
Works great, thanks.
