### ISSUE TITLE
User Story #71 - Sign Parental Release Forms

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#175]
Testing instructions refer to several Testing instructions.  Both Scenario 1 and 2 have the following issue and error (Reported by Karen)

Scenario 1: I was able to add myself and a minor to Future Dirty Harry's Peak trail work party, and the parental release form button showed up in the documents tab for the minor, but when I clicked on the button, I got this error: {"code": 500, "detail": "'loginAccounts'", "title": "KeyError"}. I got this error in both Chrome and Safari.

**Comment by davisagli** [comment]
Give it a try now. I forgot to configure the staging server with the credentials for our (testing) docusign account.

**Comment by skleinfeldt** [comment]
Assigning to @WaBirder57 to test.

**Comment by WaBirder57** [comment]
I was able to sign up a Youth and complete the Parental Release force which is link to the Youth's SF record.  My Backpack show the forms as having been completed.
