### ISSUE TITLE
Work Party Roster doesn't include WTA Liability language

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#178]
The Work Party Sign-In sheet, accessed though the Crew Corner Tab, Crew Leader Toolkit  of a work party.  This lists the Land Manager Liability Language 2 times and does NOT include the WTA Liability Language.  It should show the WTA Liability Language first and then the Land Manager Liability Language, if any, second.

To reproduce go to any Work Party where you are the CL so you can access the Crew Corner, Crew Leaders Tool Kit.  Click on "review" next to Sign-in Sheet.  Here is an example from the Beacon Rock WP Sign-in sheet on Aug 29th.
![signinsheet](https://cloud.githubusercontent.com/assets/8312206/8680602/44bbc5f8-2a17-11e5-876c-f55e7c868b95.JPG)

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Looks good.
