### ISSUE TITLE
Registration trigger should not change "Payment Pending" to "Registered"

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#182]
When a new registration w/ status Payment Pending is inserted via the reg webservice, the registration trigger is appropriately checking if there's capacity, and resetting the status to Waitlisted if there isn't.  However, if there is capacity, it's resetting the status to Registered.  It shouldn't do this.  If there's capacity available, it should leave the status as Payment Pending, and another process will set to Registered when the payment is completed.

**Comment by mscholtz** [comment]
Hi @ninetaLogik any chance you could work on this ASAP tomorrow?  This is getting in the way of David writing a test for story 99.  Thanks!

**Comment by davisagli** [comment]
Yeah actually I'm hitting this with a WP Registration inserted in a test with the status set to Payment Pending. The registraiton webservice never specifies a status.

**Comment by ninetaLogik** [comment]
Sure, I can work on this right away.

**Comment by ninetaLogik** [comment]
@mscholtz and @davisagli so what should the correct behavior be when there is space in a work party and we're creating a WP Reg with the status set a certain value. Should the trigger always honor that value whatever it is?

**Comment by ninetaLogik** [comment]
@davisagli : have you recently modified WTA_VMS_TEST_UnitTestData? The version on the server does not match the version in git. The class shows Last Modified by you on 7/15/2015 5:27 PM. The version on the server is missing some methods. Do you think we could put back the git version? (I was trying to actually add a unit test in WTA_VMS_TEST_WP_Registration_TrigClass, but cannot save because WTA_VMS_TEST_UnitTestData is missing some methods).

**Comment by davisagli** [comment]
Please do put back the git version. I forgot to refresh before changing something. Sorry!

David Glick
(mobile)

**Comment by davisagli** [comment]
@ninetaLogik I think you're right that if there is space and the registration already has a status set, we should leave it as is.

**Comment by mscholtz** [comment]
@ninetaLogik yes I agree with what you said.  Leave the status as-is, except in the case where they're trying to set it to one of the statuses that claim a spot (which I believe are Registered and Payment Pending) and there's no space available.  In those cases, change to Waitlisted.

**Comment by ninetaLogik** [comment]
@davisagli This should be working now, so you should be unblocked.

**Comment by davisagli** [comment]
It's working; thank you!
