### ISSUE TITLE
tests failing in WTA_VMS_TEST_REST_EmailParticipants

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#188]
throwing an err on a callout, don't remember but may have to ensure it's using httpmock and not trying to do a real callout in the test

**Comment by mscholtz** [comment]
looks like this is a SF bug, known issue.  see 
		//	http://www.joe-ferraro.com/2014/04/apex-unit-testing-test-data-and-test-setmock/
		//  https://success.salesforce.com/issues_view?id=a1p300000008XHBAA2

tried putting the inserts into the test class, but didn't help.  May be due to an email WF on one of the objects, which could explain why this started failing.

let's give it some time and see if SF fixes this before worrying about a workaround.

**Comment by mscholtz** [comment]
This is still failing today.  Tried updating API version for all relevant classes to most recent version, no dice.  Going to submit a case b/c worried this is going to get in the way of deploy.

**Comment by mscholtz** [comment]
Forgot momentarily that contacting SF support is futile.  Asked Dave Manelski to look into this.

**Comment by mscholtz** [comment]
per Dave this likely won't be fixed until Spring.  so I think we have to deal with it now

**Comment by davisagli** [comment]
More discussion of the issue at http://salesforce.stackexchange.com/questions/3486/testing-httpcallout-with-httpcalloutmock-and-unittest-created-data

**Comment by davisagli** [comment]
I'm puzzled trying to figure out the difference between this one and WTA_VMS_TEST_FetchHikingGuideEntry, which also does a (mocked) callout after inserting. One difference is that its callout happens in a @future method.

**Comment by mscholtz** [comment]
[ ] - reactivate PB process for conf emails
[ ] - reactivate WF rule VMS Send email confirmation for waitlist

**Comment by mscholtz** [comment]
verified that disabling WF emails resolves the issue. so will need to implement a workaround so the WF doesn't fire during these tests

**Comment by mscholtz** [comment]
decided to just use the Pre VMS Registration flag, which we already implemented as an off switch for the emails for the sake of migration

works!
