### ISSUE TITLE
Work Party List View - ACL/CL Crew Count Summary right align

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#189]
For the Work Party List view the count of crew participants should be on the same line, right aligned, as the Crew Leaders name and be formatted as:   

Crew Leader:  [ First Last Name]                                               Crew Members: # (# youth)/ # ACL

Thus for this example (screen shot ) 
Crew Leader:  Charlie Kahle                                                     Crew Members: 6 (3 youth)/ 0 ACL

![wp list view](https://cloud.githubusercontent.com/assets/8312206/8751127/1a26fede-2c60-11e5-919d-76b4be1263db.JPG)

Goal is to make this a more compact list (same line as CL Name) also all WP will have a CL so don't need to include a count of them.

**Comment by skleinfeldt** [comment]
It might be nice to put some extra space and/or characters between the elements so it is easier to scan, for example;

Crew Leader: Charlie Kahle   |   Crew Members: 6 (3 youth)/ 0 ACL

**Comment by cguardia** [comment]
Fixed on master.

**Comment by WaBirder57** [comment]
Looks good.
