### ISSUE TITLE
CreateRegistration response is doubly serialized

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#19]
The CreateRegistration response has a quoted string containing JSON, like this:

```
"{\"status\":\"Waitlisted\",\"regId\":\"a2CJ0000000U8AjMAK\",\"othersRegs\":null}"
```

It needs to just return JSON, like this:

```
{"status":"Waitlisted","regId":"a2CJ0000000U8AjMAK","othersRegs":null}
```

I think the problem is that you're manually serializing the return value here -- https://github.com/washingtontrails/WTA-Salesforce/blob/master/classes/WTA_REST_CreateRegistration.cls#L143 -- but Apex already takes care of serializing the return value of a REST resource.

This is blocking me from being able to parse the response correctly so I can check the status for stories 30 and 146.

**Comment by davisagli** [comment]
I guess you also need to declare the method as `global static ReturnData doPost()` instead of `global static String doPost()`

**Comment by ninetaLogik** [comment]
Ok, we're now returning ReturnData , please try again. Just FYI the web service might misbehave again as I try to incorporate other pieces of functionality.

**Comment by davisagli** [comment]
Thanks, works correctly now.
