### ISSUE TITLE
Work Party registration email with Guest - Shows "MERGE" not data

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#193]
As a signed in Volunteer I registered for the Riverside State Park work party Aug 7th (http://staging.wta.org:6543/workparty/a2eK0000000wOTM/).  

I received an email confirmation which included the word "MERGE" as the value for the following fields.  It looks like this:
Your Party Size: MERGE
Number under 18: MERGE
Your phone: MERGE

I would have expected the work MERGE to be replaced with the actual values. Something like:
Your Party Size: 2
Number under 18: 0
Your phone: 206-419-7099

**Comment by davisagli** [comment]
With the exception of the Message Board, emails are built in Salesforce, not Pyramid.

**Comment by mscholtz** [comment]
@ninetaLogik this one too?

**Comment by ninetaLogik** [comment]
@WaBirder57 It appears that Rebecca modified the email template for the registration confirmation. It now has a new section with the actual words MERGE in the body and a section with the original content at the bottom of the email. Do you want to keep both? Or just the top new section she's added?

**Comment by mscholtz** [comment]
@WaBirder57 can we close this one too?
