### ISSUE TITLE
Work Party Friends registration email contains HTML code

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#194]
When I register a friend for a work party they get an email confirmation of the work party details and links to additional information.  There are several problems with this email. [I'm not sure if this is a Salesforce or Pyramid issue]

1) See Ticket # 193 for MERGE field issue
2) HTML code is showing, for example this is a section of the email: 

**********
If you have questions about WTA work parties, visit our list of Frequently asked questions at:

http://staging.wta.org:6543/volunteer/questions" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;" target="_blank"> http://www.wta.org/volunteer/questions
**********

3) The link to the WP Liability waiver shows HTML also and also returns an error when I clicked on the first URL shown below, the 2nd worked correctly.  I think the first <a> URL is malformed hence not working and showing the HTML code.

This the body of this portion of the email:
***********
When you arrive at the trailhead you will be asked to sign the WTA Liability Release. Please read it ahead of time by following the link below:
http://staging.wta.org:6543/workparty/a2eK0000000wOTM/waiver" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;" target="_blank">
http://staging.wta.org:6543/workparty/a2eK0000000wOTM/waiver
***********

**Comment by mscholtz** [comment]
@ninetaLogik could you also look into this one this week?

**Comment by ninetaLogik** [comment]
@WaBirder57 what email client are you using to read these emails?

**Comment by mscholtz** [comment]
@WaBirder57 as Nineta mentioned in ticket #193 these email templates have been edited recently by Rebecca, and that's why you're seeing what you're seeing.  Looks to me like she's in the process of drafting a new template.  Can you talk to her about where she's at with this?

**Comment by WaBirder57** [comment]
OK, this seems to be working correctly now.  Rebecca was setting up confirmation email templates based on work party type since they will need to contain different information.
