### ISSUE TITLE
Waitlist Registration Confirmation - can we customize to enphasize Waitlist status

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#195]
When signing up for a wait list the confirmation screen does list the registration status as "Waitlisted".

Is it hard to change the wording on the rest of the screen to indicate this status?  2 locations:
1) Blue message "Congratulations, [Vol name]! You're all signed up!  > Change to "Congratulations, [Vol Name]! You are now on the wait list."

2) text: "We have sent an email with your registration details to you."  > Change to "We have sent an email with your wait list information."

**Comment by davisagli** [comment]
That's easy; I made the change.
