### ISSUE TITLE
WP Display Land manager Logo OR Land manger Name - Not both

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#196]
On the Info Tab of a work party listing we show the Land manager Logo and the Land Manager Name.  See Beacon Rock Trail  http://staging.wta.org:6543/workparty/a2eK0000000wRBp/

We would like to show the Logo if available, if not then show the name.  We don't want to show both.

**Comment by alecpm** [comment]
This should be fixed at the next deploy to staging.

**Comment by WaBirder57** [comment]
Thanks,
