### ISSUE TITLE
Crew Roster should only show higest level incentive award icon

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#197]
In the crew roster each volunteer now shows an incentive award icon for all the incentive awards they have earned.  We would like to show only the highest level award.  See Beacon Rock Trail http://staging.wta.org:6543/workparty/a2eK0000000wRBp/

Note that Rebecca Lavigne is an example of a contact with lots of awards.

Also, one goal for this roster is a compact list view as possible. Can this award icon be placed next to the Volunteers name, on the same line that is?  

Any other ideas on how to make this compact so that a long list (30+) volunteers can be quickly scanned by the CL would be helpful.

**Comment by davisagli** [comment]
Okay, I made it show the most recently earned award (the system doesn't know which award is "highest level," but the most recently earned award should be the highest level one, right?)

I made a few other changes to make the list more compact:
- show award icon next to the volunteer's name and make it smaller
- show the icon which indicates that a volunteer has notes next to the volunteer's name (notes are now accessed as part of the "detailed person view" from story 17, by clicking on the person's name)
- decreased padding on the table cells
- show incentive days on the same line as certifications

Try it and let me know what you think.

**Comment by WaBirder57** [comment]
Very nice.

 

The folks that are Wait Listed have that detail view popup in a semitransparent box (Firefox v39) which is hard to read, can you change that to a solid background as with the registered volunteers?  Perhaps use a different color background for those on the wait list but keep it solid rather than transparent.

 

Charlie

**Comment by davisagli** [comment]
I will make a separate ticket for the semi-transparent text issue. Multiple issues in one ticket means we have to keep re-reading the entire thread of comments to remember what still needs to be done.

Please close this one if you're satisfied that the original issue is solved.
