### ISSUE TITLE
elasticsearch setup for staging server

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#2]
The staging server's elasticsearch configuration has a few issues:
- elasticsearch is run in the same process as the indexer, so it's not possible to update the indexer code without restarting elasticsearch
- it's storing data in /tmp

We should make a script that just does indexing without running elasticsearch, and make the staging server use this with a connection to the system elasticsearch.

**Comment by davisagli** [comment]
@alecpm https://github.com/washingtontrails/wta_ansible/commit/2f53e8f00c988889b97376a88a3817ad6cb9ca28 is my attempt at putting this in place. Does that look right, and how do I deploy it?

**Comment by alecpm** [comment]
That looks right.  To deploy you need to modify the linode_host file to point to staging.wta.org and then run the following command:

    ansible-playbook -v -i linode_host vms_server.yml

**Comment by davisagli** [comment]
Done
