### ISSUE TITLE
Fix semi-transparent text for waitlisted volunteers on roster

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#200]
Charlie said:

The folks that are Wait Listed have that detail view popup in a semitransparent box (Firefox v39) which is hard to read, can you change that to a solid background as with the registered volunteers?  Perhaps use a different color background for those on the wait list but keep it solid rather than transparent.

**Comment by davisagli** [comment]
I removed the semi-transparency and instead am showing the word "Waitlisted" with a gold color.

**Comment by WaBirder57** [comment]
The transparency fix is working.  I don't however see anything different on the detail popup between a registered volunteer and one who is on the wait list - no word "Waitlisted" for example.  Looking at the David Load test WP (http://staging.wta.org:6543/workparty/a2eK0000000wPXh/) signed in as an Admin, not registered for this work party.  attached are 2 screenshots of the detail popup.
![detailregistered](https://cloud.githubusercontent.com/assets/8312206/8993454/20808db8-36ba-11e5-9b9d-338ee504f364.JPG)
![detailwaitlisted](https://cloud.githubusercontent.com/assets/8312206/8993455/20922d48-36ba-11e5-9b87-e1e4edc97d73.JPG)

**Comment by davisagli** [comment]
This ticket was about the transparency issue in the roster, not about the popup with details about a volunteer. @WaBirder57, please please please don't add new issues to an existing ticket.
