### ISSUE TITLE
show WP registration status in detailed person popup

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#201]
In #200 Charlie mentioned that he'd like to see the registration status in the detailed person popup.

**Comment by WaBirder57** [comment]
David, on #200 you said "I removed the semi-transparency and instead am showing the word "Waitlisted" with a gold color."  I was just commenting that this didn't work - the word "Waitlisted" wasn't showing.  Please help me understand if that is adding a new feature when I comment that what you said worked - didn't work for me.

**Comment by davisagli** [comment]
I meant in the roster table, not in the popup:

![screen shot 2015-07-30 at 2 08 32 pm](https://cloud.githubusercontent.com/assets/49014/8995158/8baf1438-36c4-11e5-94ad-4b2c58226cfa.png)

**Comment by davisagli** [comment]
Oh! I just realized that your original report in #200 was about the popup, which I hadn't realized before. (The popup happened to be inheriting the transparency from the row in the roster, so when I fixed the latter, it also fixed the popup.) Sorry about the confusion!
