### ISSUE TITLE
What are the SF Work Party Type fields email template ID used for?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#204]
Hi, what are the 4 Email Template ID fields on the Work Party Type objects used for?
These are:
Email Template Group
Email Template Generic
Email Template My Backpack
Email Template Thankyou
@drewpiston do you know?

**Comment by drewpiston** [comment]
Yes I do!

Email Template Group -- Id of email template to use for reminder email sent to Group registrants
Email Template Generic -- Id of email template to use for reminder email sent to generic (non-Group and non-My Backpack) registrants
Email Template My Backpack -- Id of email template to use for reminder email sent to My Backpack registrants
Email Template Thankyou -- Id of email template to use for thankyou templates. I think this field is obsolete, as Story#43 has been undone.

Right now I think only one reminder email template has been set up, which is this one:
https://cs9.salesforce.com/00XK0000000Mg7E

Let me know if you have any more questions.

Cheers,
 Drew

**Comment by WaBirder57** [comment]
What is the value of the field we should enter?  Something like 00XK0000000Mg7E ?

 

Thanks,

 

Charlie

**Comment by drewpiston** [comment]
Yes, that's correct.

Since then I think I've found that we could also do it based on Email Template name, so if that is preferable we could implement it.

 Drew

**Comment by WaBirder57** [comment]
Yes, email template name would be much more useful.

Charlie

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by drewpiston** [comment]
Ok, I've assigned myself, might be good to throw a priority on there.

**Comment by WaBirder57** [comment]
OK, will do.  I also see that the template (when I did a sample merge from within SF editing the template) shows an error with the HTML tag for the DocuSign document.

 

Do you want me to write the ticket for this?

 

Charlie

 

It looks like this:


Please complete the Parental Release: https://demo.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=7cdfa327-2f53-4d51-90c9-c7b32622dfb5 <https://demo.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=7cdfa327-2f53-4d51-90c9-c7b32622dfb5&EnvelopeField_Youth> &EnvelopeField_Youth Id=003K0000010IT9EIAW&Participant Name=Charlie Kahle&WP Name=Beacon Rock Trail

**Comment by drewpiston** [comment]
Yes please! Thanks.

**Comment by WaBirder57** [comment]
Ticket #205 created for this 2nd item.

**Comment by mscholtz** [comment]
@WaBirder57  Just to weigh in here: one argument against using template name in lieu of ID is that template names are more likely to change when someone edits the template, which would break this.  People might not be aware that this is a problem.  IDs of course cannot change.

The idea here would be a custom UI that show you the template name for selection but stores the ID.  Pretty sure we don't have budget for that ideal, though.  Your call, Charlie, on which way to go here.

**Comment by mscholtz** [comment]
@drewpiston could we add the word Reminder to those template fields so it's clearer what they're for?  Fine to just put it in the label..

**Comment by davisagli** [comment]
> IDs of course cannot change.

They'll change when we deploy to production, no?

**Comment by mscholtz** [comment]
Yes, and that's one of the things we'll need to do on launch.  But after that, no.

**Comment by mscholtz** [comment]
so we don't forget: https://percolator.teamwork.com/tasks/4660481

**Comment by mscholtz** [comment]
And just to be clear, @drewpiston: the VF template you linked to should be the MyBackpack one, right?  Since we made it VF so that we could list which required forms they have?

So that would mean we would still need standard templates for Unauthenticated and Group?  
If that's right, @WaBirder57 is that something you and your staff could take on soon?

**Comment by drewpiston** [comment]
I made one VF component that is smart enough to figure out if the recipient is Generic, MyBackpack, or Group.  Right now all three templates reference VF component because it references the fields on the Trailhead, which aren't available easily on the Work Party.

Additionally, the VF handles the required docs as follows:

Generic: VF lists all the required docs
MyBackpack: VF lists the required docs and their completion status for each
Group: VF lists no required doc

So the template I linked to should work for all three scenarios.  If there are further differences among the three, though (like a link to MyBackpack for those users) then more templates should be created.

 Drew

**Comment by mscholtz** [comment]
@WaBirder57 I think we're waiting for you here to decide if we want to switch to template name instead of ID.   Please see this comment from above for my arguments against this https://github.com/washingtontrails/vms/issues/204#issuecomment-129640779

**Comment by WaBirder57** [comment]
Lets leave these as is with the ID. @ebskopin @mscholtz  I think this is OK to close but double check.

**Comment by WaBirder57** [comment]
Lets leave these as is with the ID. @ebskopin @mscholtz  I think this is OK to close but double check.
