### ISSUE TITLE
VMS WP Reminder email template includes broken link to Docusign

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#205]
When testing the SF Email Reminder Template: https://cs9.salesforce.com/00XK0000000Mg7E the email contains a broken hyperlink to the Docusign Document.  It looks like this in my test email:

Required Documents 

Please complete the Parental Release: https://demo.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=7cdfa327-2f53-4d51-90c9-c7b32622dfb5&EnvelopeField_Youth Id=003K0000010IT9EIAW&Participant Name=Charlie Kahle&WP Name=Beacon Rock Trail 

Note the space between "Envelope Field_Youth" and "Id=003K"...  That is where the hyperlink stops.

**Comment by davisagli** [comment]
That's probably my fault from when I adjusted it to generate the links for Docusign. It needs to urlencode the keys/values embedded in the URL using `EncodingUtil.urlEncode`

**Comment by davisagli** [comment]
This should work now.
