### ISSUE TITLE
Crew Leader volunteer roster - move protective action information

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#206]
When a member of a crew has a value in the SF Contact Protective Action field this is shown to the Crew Leader on the roster for their trip (non print roster only).  See Beacon Rock Trail WP (http://staging.wta.org:6543/workparty/a2eK0000000wRBp).

To make this more visible when the list is being scanned can this be moved to the "Status" column under the workparty registration value.  This will also reduce the row height to 2 lines down from 3, again trying to keep this list as compact as possible.

Lastly, no mater what the value of this Protective Action field on the contact record, just display "Protective Action".  This will be easier for CL to spot and should alert them for the need to call the office.  Some kind of context sensitive reminder to call the office would be helpful.
![rosterlistwithrepremand](https://cloud.githubusercontent.com/assets/8312206/9091353/a800de02-3b54-11e5-9c40-105f0083fc85.JPG)

**Comment by davisagli** [comment]
Not quite sure what you mean by a "context sensitive reminder"?

**Comment by WaBirder57** [comment]
Well I was thinking of a mouse over pop up but not sure how that would work on a mobile device.  Not sure what similar options there are for that platform.

 

Since this Protective Action is used so rarely I think CL’s will need a tip as to what it is when it appears since it is important.

**Comment by davisagli** [comment]
We could show a message above the table, something like "At least one volunteer for this work party is under Protective Action. Please call WTA at (xxx) xxx-xxxx for more information."

**Comment by WaBirder57** [comment]
That would work, thanks.

**Comment by cewing** [comment]
@WaBirder57 What phone number should be used here?  I have implemented the feature, but need a phone number to use for the alert paragraph at the top of the table @davisagli suggests above.

**Comment by cewing** [comment]
I have committed code to solve this problem, @davisagli please do not merge until @WaBirder57 has provided the correct Phone number for the message.

**Comment by davisagli** [comment]
This is deployed and seems to work.

**Comment by WaBirder57** [comment]
Looks good, thanks.
