### ISSUE TITLE
Youth Work Party, ie ACL Self Registraion = False add message when ACL tries to sign up

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#207]
User Story #287: When an ACL Tries to sign up for a WP flagged as "ACL Self registration"=False have a message appear  "WTA staff assigns ACLs for this type of work party, contact staff at volunteer@wta.org."  With out this message it would not be clear to and ACL why they couldn't register for that particular WP.

**Comment by davisagli** [comment]
If "ACL Self Registration" is unchecked then there is currently no way on the registration form to try to sign up as an ACL (we don't show the dropdown to choose between registering as an ACL and registering as a volunteer; it always registers as a volunteer in this case).

**Comment by WaBirder57** [comment]
Let me review with staff on how this works.

**Comment by WaBirder57** [comment]
@ebskopin Elliott can you review this and close the ticket if this is ok.

**Comment by ebskopin** [comment]
Done.
