### ISSUE TITLE
Work party 2nd reminder email template?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#209]
Does the 2nd reminder for a work party use the same email template as the first reminder?

**Comment by mscholtz** [comment]
@drewpiston I think this is a question for you..

**Comment by drewpiston** [comment]
Hi Charlie,

Yes, the first and second email template reminders are the same -- that decision came out of the email conversation we had on June 2nd.

Cheers,
 Drew

**Comment by mscholtz** [comment]
Assigning this back to you, @WaBirder57 .  Let us know if you want this to change.

**Comment by WaBirder57** [comment]
Thanks for the clarification.  This will work well.
