### ISSUE TITLE
chg text of Add button for registering friends?

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#21]
On the registration form, for the "Bringing someone with you" section, there's a green button labeled "Add" which adds another row.  You only need this if you're briging more than one friend.  I think we should relabel this to "Add Another Person" or something like that.  Because as it stands, it's ambiguous whether you need to click that after you fill in the first row (to "Add" your friend to the registration before you submit it.)

Minor issue, but clarity is good!

@WaBirder57 this is only a suggestion, your call as to whether to make this change.

![image](https://cloud.githubusercontent.com/assets/931031/6197076/c1080224-b394-11e4-8b64-33b9754e5ad5.png)

**Comment by WaBirder57** [comment]
We like your thoughts, make this "Add Another Person".

**Comment by davisagli** [comment]
Okay, done.
