### ISSUE TITLE
VMS Work Party header should include Start/End time

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#211]
In the WP Finder List View as well as the WP Detail View include with the Start Date the Start Time.  Also for multi day work parties include the End Time along with the current End Date.

For example: 
Sat Aug 29, 2015 8:30am.
or
Sat, Aug 22, 2015 8:30 am – Sun, Aug 30, 2015 4:30 pm

**Comment by davisagli** [comment]
@cguardia can you take this one? We'll have to index Start_Date_Time__c and End_Date_Time__c instead of Start_Date__c and End_Date__c, and update the existing places in the code that access `start_date` and `end_date`

**Comment by davisagli** [comment]
This should be working now.

**Comment by WaBirder57** [comment]
Looks good, thanks.
