### ISSUE TITLE
Email template for inviting friends/family parties from waitlist is group-focused

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#215]
This template: https://cs9.salesforce.com/00XK0000000Mgkk?setupid=CommunicationTemplatesEmail
is used in this WF rule: https://cs9.salesforce.com/01QK00000001HEB

That WF rule is for friends/family, not Groups, but the template references Groups fields.  Should show content for the f/f party instead

**Comment by mscholtz** [comment]
just to clarify, Groups in VMS is about large corporate or org-sponsored groups attending WPs.  It is different from f/f parties, which are small and not associated with an org.

**Comment by mscholtz** [comment]
@drewpiston  could you take on this one this week as well?
I think this is as simple as changing references to "your group" in the text to "your party", and then omitting the Group Name in the list of merge fields.    Could you also rename the template?   
Thanks!

**Comment by drewpiston** [comment]
Done!

**Comment by drewpiston** [comment]
PS Assigning back to you, Matthew.

**Comment by mscholtz** [comment]
@drewpiston I just looked at the template, and it looks like it hasn't been changed at all.  Mod date hasn't incremented.  Did you save a new version or something?

**Comment by drewpiston** [comment]
Hi Matthew,

I thought this had already been taken care of, and when I looked at that email template it wasn't used by any workflow rules.

I just ran another test, though, and it does look like there was a "group" label in this email template, which I have removed (and replaced with the smart Family and Friends field):
https://cs9.salesforce.com/00XK0000000Mg4U?setupid=CommunicationTemplatesEmail

Maybe that was the email template that was supposed to be part of this ticket?

Cheers,
 Drew

**Comment by mscholtz** [comment]
Ah.  I think what happened is the WF rule was switched to use the other template since I wrote this ticket.  In any case it looks good now.  I'm going to mark the Group template as deprecated.  Thanks, Drew.
