### ISSUE TITLE
fixes for Roster Requests facet and icons

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#22]
1. The orange hat for ACLs Needed should only appear in search results for users with a permission level >= ACL (not for anonymous or Volunteer)
2. I think the green hat for Extra Volunteers Needed is also supposed to show up in the results next to where the orange hat for ACLs Needed appears.
3. Please add a title attribute to the hat icons so the user gets a "Extra Volunteers Needed" or "ACLs Needed" tooltip when they hover over the hat icon. The meaning of the icons is not very clear otherwise.

**Comment by cguardia** [comment]
I looked for an icon with a legend for the green helmet, like the one for the orange helmet that has the word "needed" below, but did not find it. I think it would look weird to have one with a legend and one without.

**Comment by davisagli** [comment]
Okay, skip part 2 for now.

**Comment by cguardia** [comment]
Fixed for orange helmets.

**Comment by davisagli** [comment]
Looks good
