### ISSUE TITLE
Work party type filter check box "tip" box

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#220]
Did we have a clickable "?" to display information about each Work Party Type in the list of Work Party Types to filter the WP list?  I thought I recalled David setting this up with a cool way for staff to edit the text in each WP description box.   This is no longer displayed.

**Comment by davisagli** [comment]
Fixed. Let me know if there are any of the multiple-checkbox facets that you *don't* want a help button to show for, and I can remove it easily.

**Comment by WaBirder57** [comment]
Looks good, i will get the text for each of these updated.

**Comment by WaBirder57** [comment]
@davisagli , what formatting capabilities does this editor have?  Can we embed hyper links in the text?

**Comment by davisagli** [comment]
It's an HTML contentEditable area, which means that it can hold anything your browser can display, but it's not currently set up with a full-fledged HTML editor with buttons to easily control formatting. You might be able to copy a link from another browser tab and paste it here.

**Comment by davisagli** [comment]
Also, note that you can't access the editor for the "5 Reasons to Have a Backpack Account" that appears on the guest registration form, because it only shows up when you're logged out and don't have the privilege to edit the text. So just send me what you want for that one.

**Comment by WaBirder57** [comment]
Any tips on the format for pasting in HTML?  I pasted some into the VMS Find a Work party Work Party Type “?” tip field.  It just shows the HTML rather than render it.  Do I need to embed this inside other HTML tags?

**Comment by davisagli** [comment]
I didn't mean you can copy and paste HTML; I meant you can copy and paste formatted text as rendered by your browser.

**Comment by WaBirder57** [comment]
Thanks for that tip.  It is mostly working as you describe.  When I open the attached file (change file name to drop the ".txt") in a browser I can then copy and past the formatted content into this pop up editor window.  The odd thing is the Order List (1,2,3) element doesn't show the numbers when pasted into the edit window.
[TestHTMLText.htm.txt](https://github.com/washingtontrails/vms/files/9654/TestHTMLText.htm.txt)

**Comment by davisagli** [comment]
Hmm, I bet we need to add styles for ordered lists. Can you save one with the incorrectly displaying ordered list, and point me to where it is, and I'll take a look

**Comment by WaBirder57** [comment]
The site now: http://staging.wta.org:6543/ has the version i sent in that text file, look at the tip for Work Party Types to see how it renders.

**Comment by davisagli** [comment]
I fixed the ordered list styles.

**Comment by WaBirder57** [comment]
Thank you.

Is there a way to control or reduce the spacing after the ordered lists?
It leaves too much white space.  This is evident both on the this "tip" pop
up as well as the SF Text Area Fields used for content on the VMS WP Info
tab.

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by davisagli** [comment]
Yeah, I'm not sure why lists had such a large bottom margin. I fixed it to use the same margin as for paragraphs.
