### ISSUE TITLE
Contact Certification Status Field values use.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#223]
Contacts my have one or more Certifications.  These certifications have 2 "status" fields for which I have just changed the labels so it is clear that one is the Approval Process Status (Status__c) and the other current Certification Status [Active, Inactive] (Active_Status__c). @mscholtz, @drewpiston  Note that I made this change to these Salesforce labels as well as edited the certification related list on the contact to show both of these values.

In VMS the Volunteer Detail pop up page should show the Certification Status (Active_Status__c) value as well as the Process Status (Status__c).  (Currently this only shows Process Status).

Also, the roster should show only Certifications which have an Active_Status_c value of "Active".  I changed the CPR Certification for Charlie Kahle to Inactive and this CPR certification still shows on the roster.  [note this could be an issue with the staging server not refreshing]
![rostersnip](https://cloud.githubusercontent.com/assets/8312206/9417149/db86391e-47fe-11e5-8489-bb0043597d64.JPG)

**Comment by davisagli** [comment]
We didn't realize there were 2 different status fields so we'll have to make these adjustments.

**Comment by mscholtz** [comment]
Sorry about the confusion here.  These fields should have had clearer names to start, I didn't review this closely.

**Comment by davisagli** [comment]
This should be working correctly now.
