### ISSUE TITLE
"Sign in to My Backpack" button link inoperable in "Crew Corner"

### ISSUE THREAD

**Issue by chrisrossi** [washingtontrails/vms#227]
If you go to "Crew Corner" for a work party and are not signed in, you will see a header image with a translucent green button that says "Sign in to My Backpack".  The button is not actually clickable on Chrome.  This may be Z-index issue, such that it is actually behind the header image which is not entirely opaque.

FWIW, there is a "Sign in to My Backpack" button on the sidebar on the right hand side very nearby, that works just fine.

**Comment by davisagli** [comment]
This works now.

**Comment by WaBirder57** [comment]
This works in Chrome and other browsers.
