### ISSUE TITLE
fix formulas: Participants Registered and Number of Remaining Spots

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#23]
Currently this Work Party shows no Capacity, 3 Participants registered, and -4 for Number of Remaining Spots.

1. I think Participants Registered should be 4, because the work party has Julie set as the crew leader (in the Leader field, not as a registration).
2. Number of Remaining Spots should be empty if the capacity is empty.

@mscholtz I'm going to assign Salesforce issues to you and you can reassign to whomever will actually work on it.

**Comment by davisagli** [comment]
(Maybe we need to rethink how leaders are assigned to a WP. It seems bad to me if there's both a Leader field and the possibility of registering that person as a CL.)

**Comment by mscholtz** [comment]
Which WP?

**Comment by mscholtz** [comment]
re the Leader field.  Yes, that is currently redundant.  I think there are some good reasons for the redundancy, and later I expect we'll automate it so that they don't require separate data entry.

**Comment by davisagli** [comment]
Here's the WP I was looking at: https://cs10.salesforce.com/a27J0000001mAs4

**Comment by mscholtz** [comment]
@barbarachristensen could you make these tweaks when you have a chance?  I agree with David - Spots Remaining should be empty if Capacity is empty.  And Place on Waitlist should be false when Capacity is empty, unless Set to Full is checked.

**Comment by barbarachristensen** [comment]
Is there ever a case that capacity is not known but they let people register online anyway? A validation rule that requires capacity before they set the trip to publish might be useful.

The Spots Remaining formula is written w/ assumption that a leader is registered w/ a WP Registration of type Crew Leader, not using that leader field, per our discussion last week, @mscholtz. I might need to talk out what you want here regarding the formula change-- you want it to hold a spot for a WP Registration OR the Leader lookup, yes? They won't ever be different people? Thx!

**Comment by mscholtz** [comment]
>
> Is there ever a case that capacity is not known but they let people
> register online anyway? A validation rule that requires capacity before
> they set the trip to publish might be useful.
>

Yeah, I've asked Charlie about that elsewhere.  Let's not worry about that
for this yet.


> The Spots Remaining formula is written w/ assumption that a leader is
> registered w/ a WP Registration of type Crew Leader, not using that leader
> field, per our discussion last week, @mscholtz
> <https://github.com/mscholtz>. I might need to talk out what you want
> here regarding the formula change-- you want it to hold a spot for a WP
> Registration OR the Leader lookup, yes? They won't ever be different
> people? Thx!
>

No they won't be different.  Or shouldn't be.  Let's ignore the lookup
field for these formulas.  No change needed for leaders in the formulas.



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/23#issuecomment-74917772>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by barbarachristensen** [comment]
Formulas updated: 
Number of Spots Remaining will be empty if Capacity is empty.
Add to Waitlist will be unchecked if Capacity is empty.

Just verifying: If capacity set to 0 (vs. empty): As it stands, this will set Number of Spots Remaining to -1 (holding spot for leader) and check the Place on Waitlist. Is that ok for what @davisagli needs on his end? It would be true that a 0 capacity work party should be waitlisted, I'm assuming. Thanks!

**Comment by davisagli** [comment]
VMS doesn't look at the Number of Spots Remaining field at all; it just trusts the value of Place on Waitlist.

It makes sense to me that setting capacity to 0 should check Place on Waitlist.

**Comment by mscholtz** [comment]
I think Spots Remaining should never be less than zero.  Can you add another clause to the formula that if it would be a negative number, just set it to zero?

Thanks!

**Comment by barbarachristensen** [comment]
​Done.​

On Wed, Feb 18, 2015 at 4:19 PM, Matthew Scholtz <notifications@github.com>
wrote:

> I think Spots Remaining should never be less than zero. Can you add
> another clause to the formula that if it would be a negative number, just
> set it to zero?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/23#issuecomment-74977480>.
>



-- 
Barbara Christensen
*Certified Salesforce Administrator*


*Percolator Consulting**Every organization has a superpower. Ours is
engagement.*
percolatorconsulting.com
(206) 289-0816 x 5

**Comment by davisagli** [comment]
Looks good to me.
