### ISSUE TITLE
WP Time Zone Hours shifts

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#233]
When looking at a work party schedule from a different US time zone (eg Central) the Start and End time in the Find a Work party list are shifted.  So for a work party from 8:30am - 3:30pm it will be displayed as 10:30am - 5:30pm for a user in the Central Time zone.  These times should all display in Pacific Time (local to where the WP is).

**Comment by cewing** [comment]
This is related to and caused by the same problem as #234

**Comment by davisagli** [comment]
This should now work correctly.

**Comment by WaBirder57** [comment]
We checked this from the Central Time zone thanks the Tiffany who is working there.  Looks good.
