### ISSUE TITLE
"first thumbs up" email should link to the trip report that was upvoted

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#235]
This requires:
- [x] Salesforce needs a field on Contact to store the URL of the first upvoted trip report (First_Upvoted_Trip_Report_URL__c)
- [x] The celery task which batch updates Salesforce contacts needs to determine that url and include it in the uploaded data.
- [x] Merge this field in the email template

**Comment by mscholtz** [comment]
@skleinfeldt oh man, I would really like all tickets (or at least all tickets that impact SF) to be in one place.  Can we just make "MBP Budget" tags here?

**Comment by skleinfeldt** [comment]
Let's discuss in standup. The issue to me is that there are many more tickets than stories and they are more ephemeral, so the possibility of mis-labeling and mis-reporting time seems greater.

**Comment by skleinfeldt** [comment]
And the decision is: use this repo for everything. Which means

IF YOU CREATE A TICKET YOU HAVE TO GIVE IT THE RIGHT BUDGET LABEL!!!

**Comment by KindraRamos** [comment]
Question about this email during implementation. Do we have a way to not send this out to everyone who is ever written a trip report on when it first syncs. So that it will only send the congratulations you wrote your first trip report email to folks who are actually writing the FIRST trip report.

**Comment by davisagli** [comment]
That's a really good question. @mscholtz do you have a suggestion for how to best avoid that?

**Comment by mscholtz** [comment]
@KindraRamos  Yep, this email is sent via a SF workflow, and all we would have to do is deactivate it temporarily.  So I think the best bet will be to keep workflows like this deactivated at first until the initial sync is done.  I've added an item to our deploy plan for this, so we don't forget.

**Comment by davisagli** [comment]
This should work now.

**Comment by ebskopin** [comment]
are the SF workflow e-mails being suppressed presently?

**Comment by davisagli** [comment]
No. But remember this won't be triggered until the nightly sync of trip report info from Plone to SF.

**Comment by ebskopin** [comment]
Works.

**Comment by davisagli** [comment]
@mscholtz we are enabling the nightly sync from the production server sometime in the next week. Can you please confirm that those workflow emails are disabled in production SF for now?

**Comment by mscholtz** [comment]
Yep.  You mean these, right?  Checkbox is for Active

![image](https://cloud.githubusercontent.com/assets/931031/11546928/06434f64-9905-11e5-9816-0ac2034c4630.png)

**Comment by davisagli** [comment]
Yeah, those. Thanks. So it should be safe to enable those after the first nightly sync has run successfully?

**Comment by mscholtz** [comment]
​Yeah, I guess so.​

On Wed, Dec 2, 2015 at 3:00 PM, David Glick <notifications@github.com>
wrote:

> Yeah, those. Thanks. So it should be safe to enable those after the first
> nightly sync has run successfully?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/235#issuecomment-161460906>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Actually Kindra and Loren would like to not activate the email sends for these two:

 

MBP: Send Email on First Thumbs Up

MBP: Send Email on First Trip Report

 

Until after the first of the year.  Folks a getting a lot of email from us this holiday season and we want to hold off on this feature until we are ready.  Since this is in Salesforce it is easy for us to turn these on when we are ready.

 

Thanks,

 

Charlie

**Comment by davisagli** [comment]
Got it, we'll leave it to you to enable when you're ready.
