### ISSUE TITLE
New Salesforce Contacts from VMS should have leadsource = "Trail Work"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#237]
When VMS creates a new contact in Salesforce the Contact.LeadSource fields should be set to "Trail Work".  Currently it is setting this field to "Website".

**Comment by davisagli** [comment]
@mscholtz I think we should make the userlogin webservice accept the lead source as a parameter, since it may be called from either Plone or Pyramid.

**Comment by mscholtz** [comment]
Sure, makes sense.

On Wed, Sep 2, 2015 at 3:46 PM, David Glick <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> I think we should make the
> userlogin webservice accept the lead source as a parameter, since it may be
> called from either Plone or Pyramid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/237#issuecomment-137265822>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by mscholtz** [comment]
ok, just added this.  new param leadSource is in the login webservice.
it will not change leadsource if it finds an existing contact
if it creates a new contact, it will assign the given leadsource if there is one.  if not, it defaults to Trail Work.

@davisagli over to you to adjust your calls to the webservice.  when that's done plz assign to charlie for review

**Comment by davisagli** [comment]
The pyramid app now passes 'Trail Work' to the vmslogin webservice and the Plone site now passes 'Website'.

**Comment by WaBirder57** [comment]
I created a new SF contact by creating a guest WP registration.  The new contacts Lead Source is "Website" not "Trail Work".  Here is the new SF Contact that was created. @davisagli can you review this scenario, thanks.

**Comment by davisagli** [comment]
I tried the same thing and ended up with a lead source of "Trail Work": https://cs9.salesforce.com/003K0000015gTqx

Are you sure the name and email from the guest didn't match a contact that already existed previously?

Or did you maybe check the box to create a My Backpack account while registering, and maybe that's the case that isn't working right?

**Comment by davisagli** [comment]
I also tried one with the My Backpack account box checked, and it also ended up with a lead source of Trail Work. So I think you'll have to give me some more specific instructions to reproduce what you were doing.

**Comment by WaBirder57** [comment]
this seems to be working for me today.  Yea! and thanks.
