### ISSUE TITLE
ACLs viewing Work Parties can see the list of registered CL and ACL's

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#238]
If an ACL is logged into VMS, they will be able to see in the Crew Corner tab of a work party the list of registered CL and ACLs.  Note, the ACL does NOT need to be registered for that work party to see this list.

**Comment by cewing** [comment]
I apologize if this is clear to everyone but me, I want to make sure I understand, @WaBirder57.

Is this issue asking for us to remove the ability for ACLs to see this list, or to add it?  In other words, does this ticket describe a situation which now exists and should not, or does it describe a situation that does not exist but should?

Thanks for the clarification.

**Comment by cewing** [comment]
@davisagli, not sure, but perhaps you or @cguardia could chime in on my question above.

**Comment by davisagli** [comment]
Currently if a user with VMS_Permission_Level__c = 'Assistant Crew Leader' clicks on the Crew Corner tab for a work party they're not registered for, they see a prompt to register. So I'm pretty sure Charlie's describing a desired behavior that we haven't implemented yet.

Presumably it should do the same thing for VMS_Permission_Level__c = Crew Leader too. We already have something like this for a permission level of Admin.

**Comment by WaBirder57** [comment]
Chris,  this doesn't work this way now.   An ACL or CL signed into VMS
should be able go to any work party and see the list of CL and ACL signed
up.

Basically they can browser around,  see what work parties there ACL friends
have signed up for,  without having to join the WP.

I think the behavior now is that if you are not signed up for the WP you
can't see who is signed up.

Charlie

Charles Kahle
WTA Information Services Manager

**Comment by cewing** [comment]
Thanks, @davisagli and @WaBirder57 

That makes good sense, and I understand the goal.  I'll take this one on asap.

**Comment by davisagli** [comment]
This is deployed and working now.

**Comment by ebskopin** [comment]
this is working
