### ISSUE TITLE
Story #266 - Add Car Pool location

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#239]
Add a text box in the My Backpack User profile - VMS section - for user to store Car Pool Location in their profile.  Such as "Ravenna Park and Ride" or "Issaquah Transit Center" or other location information.

**Comment by davisagli** [comment]
And then use that as a default value for the car pool message/notes field on the VMS registration form?

**Comment by WaBirder57** [comment]
Yes, thanks for adding this clarification.

**Comment by mscholtz** [comment]
@davisagli do you want to tackle this one this week?  Sounds like our part is just adding a contact field, if there isn't one already for this..

**Comment by davisagli** [comment]
Sure. There's already a picklist, Work_Party_Carpool_Preference__c, but we also need a text field for carpool notes.

**Comment by mscholtz** [comment]
@drewpiston can you add a contact field for this, and then assign over to David?

**Comment by drewpiston** [comment]
I added "Work_Party_Carpool_Notes__c" to the Contact -- if the name should be something different, @WaBirder57 , let me know.
Assigning to David.

**Comment by davisagli** [comment]
This now shows up on the MBP profile, updates Salesforce when saved, and the carpool preference and notes from the Contact will be used to prefill the VMS registration form.

**Comment by WaBirder57** [comment]
OK, looks good.
