### ISSUE TITLE
return status info for "other volunteers" included in registration

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#24]
this was originally a task for story 37 that read:

Include in the WS response a list of outcomes for each of the "others". (IDs of reg, Status, Added/Not Added Indicator (Error Code))

**Comment by ninetaLogik** [comment]
It looks like we're already returning the reg Id and the status for the Others in the OthersResponse. Is this ticket just for also adding the error code if there is one? This error code would be an indicator that the registration was not created for whatever reason , correct?

**Comment by mscholtz** [comment]
@davisagli ?  

sorry, i probably should have checked if parts of this were done already

**Comment by davisagli** [comment]
Not sure, I don't think anyone has specified how the status of friends/family registrations should be shown on the confirmation screen.

**Comment by mscholtz** [comment]
@ninetaLogik  sounds like this one needs some more thinking.  let's skip it for now, and come back to it.  lemme know if you need another ticket to use up your horus.

**Comment by mscholtz** [comment]
@davisagli is this still something we need?  or was this taken care of?

**Comment by davisagli** [comment]
We don't need this unless they want to show the status for each family member on the confirmation page.

**Comment by mscholtz** [comment]
@WaBirder57 I'm going to assume for now that you don't need that.  Assigning this over to you to close or reopen as you see fit.
