### ISSUE TITLE
"thumbs up" implementation on trip report listings needs fixing

### ISSUE THREAD

**Issue by cewing** [washingtontrails/vms#243]
Although the total upvote badge is present, the textual display at the bottom of the listing needs fixing:

* find and add the icon to the theme, so it does not 404
* connect the upvote count to this text so it is properly displayed

**Comment by alecpm** [comment]
I'm pretty sure I finished wiring this up on the listings page.

**Comment by cewing** [comment]
oh, sweeeeeeeeet!

**Comment by davisagli** [comment]
Yep, this appears to be working.
