### ISSUE TITLE
change Clone WP routine to use Field Set

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#245]
Currently the clone Work Party code (for story 77) is written w/ the fields to clone hard-coded.  We should probably replace this w/ a field set so that WTA staff can adjust later which are cloned.

This was highlighted recently because we wanted to delete a field but it was included here so couldn't be deleted until we changed the code.  Not an exact scenario WTA is likely to run into, but reminded me we should probably do this differently.

**Comment by mscholtz** [comment]
@WaBirder57 please set a priority on this one

**Comment by drewpiston** [comment]
Done! To test, make sure that fields from this fieldset are copied over during a clone:
https://cs9.salesforce.com/setup/FieldSetEditor.apexp?tableEnumOrId=01IK0000000AUvJ&setupid=CustomObjects&retURL=%2F_ui%2Fcommon%2Fconfig%2Fentity%2FFieldSetListUI%2Fd%3FretURL%3D%252F01IK0000000AUvJ%253Fsetupid%253DCustomObjects%26tableEnumOrId%3D01IK0000000AUvJ%26setupid%3DCustomObjects&id=0IXK0000000CitT

**Comment by ebskopin** [comment]
looks good. thanks.
