### ISSUE TITLE
Pyramid: My Backpack dropdown menu over writes "Sign in Button"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#25]
Using Firefox v35.0.1, not logged in user viewing a work party.  The top right "MyBackPack" drop down menu's last item, "Write a Trip Report" over writes the "Sign Into My Backpack" button so the text "Report" is jumbled with this button's text.  See attached screen shot.
![mybackpackdropdownmenu overwrites signup button](https://cloud.githubusercontent.com/assets/8312206/6258817/c4da0a24-b780-11e4-976e-cc2f2681305c.JPG)

**Comment by davisagli** [comment]
Looks like this is because the menu is using the font "Helvetica Neue," but it's not installed on your computer and is not set up correctly to load as a web font. Didn't notice because it's on my computer.

Once we fix this here's how the menu's supposed to look:
![screen shot 2015-02-18 at 6 05 38 pm](https://cloud.githubusercontent.com/assets/49014/6260805/0a30cab4-b799-11e4-9e91-72590ae95b73.png)

**Comment by davisagli** [comment]
Any better now? I set it up to use Helvetica as a fallback when Helvetica Neue isn't available, so it should be much closer to the intended design.

**Comment by WaBirder57** [comment]
Thanks, looks like that is the issue.  I’ll retest when it is fixed.

 

Charlie

**Comment by WaBirder57** [comment]
David,

 

I’m still seeing the word “report” overlaid on the text of the Sign In button.  Perhaps the way the text wraps is the issue as your text is all on one line “Write a Trip Report” where as mine the word “Report” wraps to the next line.

 

See in this screen shot

**Comment by davisagli** [comment]
Charlie, github doesn't preserve attached screenshots when you reply to the thread by email. Can you please post the screenshot using the github web UI?

**Comment by WaBirder57** [comment]
Done. Update my last post with the screen shot in GitHub

**Comment by davisagli** [comment]
Try now; I adjusted the styles so the menu should expand to fit the menu entries if they're wider than the top level button.

**Comment by WaBirder57** [comment]
David,

 

This works for me.  The drop down widens to the left to have a consistent column width which accommodates the widest item in the drop down.

 

Charlie
