### ISSUE TITLE
Mutli Day work party registration fails to show days to register for.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#252]
When I try to register for a multi day work party, SF: https://cs9.salesforce.com/a2eK0000002OXYH and VMS: http://staging.wta.org:6543/workparty/a2eK0000002OXYH the registration form doesn't show which day I want to register for.  

The Work Party Type Weekend Work Party: https://cs9.salesforce.com/a2wK0000002GGl7 does have Allow single day registration checked.

**Comment by davisagli** [comment]
Should work now; this broke when we made the change to using date and time instead of just date.

**Comment by WaBirder57** [comment]
Works now.
