### ISSUE TITLE
Mulit day work party gets stuck on registration form, register button doesn't work.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#253]
When I try to register for a multi day work party, SF: https://cs9.salesforce.com/a2eK0000002OXYH and VMS: http://staging.wta.org:6543/workparty/a2eK0000002OXYH I click on the registration button it just flashes for a second "Registering" then returns me to the form with button reading "Register".  

This is the same for each of the several different users I tried to register.

The Work Party Type Weekend Work Party: https://cs9.salesforce.com/a2wK0000002GGl7 does have Allow single day registration checked.

**Comment by davisagli** [comment]
It was failing because specifying days is required but they were not on the form -- so this turns out to be the same issue as 252. Should work now.

**Comment by WaBirder57** [comment]
Works now.
