### ISSUE TITLE
Volunteer Thank you email from Crew Leaders - Story#42: Add Subject line with WP name & date

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#255]
After a work party the Crew Leader will send out a Thank you email to all crew members, see story #42.

Change the subject line so that it defaults to a standard:

Subject: Thank you for volunteering with WTA! [Work Party Name] – [START DATE]
where the [Work Party Name] and [Start Date] are pulled from the Workparty info.

**Comment by mscholtz** [comment]
@WaBirder57 i just tested this, and currently it allows the user (i.e. the leader) to enter a subject.  Does this change your mind at all?  If we want a boilerplate subject we should probably not allow them to enter that.

**Comment by WaBirder57** [comment]
The volunteer thank you email should start with a standard boiler plate subject line as we have described with WP name and start date.  If we can allow for a crew leader to change this if needed that would be great. 


Charlie 


Sent by Outlook for Android



From: Matthew Scholtz

Sent: Wednesday, September 23, 11:39 PM

Subject: Re: [vms] Volunteer Thank you email from Crew Leaders - Story#42: Add Subject line with WP name & date (#255)

To: washingtontrails/vms

Cc: Charles Kahle



@WaBirder57 i just tested this, and currently it allows the user (i.e. the leader) to enter a subject. Does this change your mind at all? If we want a boilerplate subject we should probably not allow them to enter that.

**Comment by mscholtz** [comment]
I believe that makes this an entirely pyramid ticket then.  @davisagli

**Comment by davisagli** [comment]
This is working now.

**Comment by WaBirder57** [comment]
Tiffany confirms that this works.  Thanks.
