### ISSUE TITLE
Won't allow me to publish summary report without image URL

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#257]
A get an error 'imageOrVideo' attempting to Save a report after setting Status to Publish if I don't have an image URL entered.  Saves OK if I leave it as Draft.  Don't think this should be required (@WaBirder57 can you verify?), but if it should be then it should be indicated on the form as such.

![image](https://cloud.githubusercontent.com/assets/931031/10066449/fe87d7fc-6247-11e5-9e8e-b7c22f41b3a5.png)

**Comment by WaBirder57** [comment]
Matthew,  the Summary report and email to volunteers does NOT require an image or video.  Just nice to have.

 

Charlie

**Comment by davisagli** [comment]
It was not required but some code was trying to access it even if it was not set. Should work now.

**Comment by mscholtz** [comment]
it's now giving me a "'SFType' object is not callable" err when attempting to change to Publish
http://staging.wta.org:6543/workparty/a2eK0000002OXaI/

**Comment by davisagli** [comment]
Sorry, that's caused by some unrelated refactoring I did this afternoon. Try now.
