### ISSUE TITLE
display of message/image in Summary Report repeated after publishing

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#258]
Immediately after publishing a summary report, my Message to Crew and the image show up twice on screen

![image](https://cloud.githubusercontent.com/assets/931031/10066529/a03d3e7a-6248-11e5-899a-cb609b224a3a.png)

If I navigate away or refresh the page, then the message only shows up once and the image isn't shown at all. 

This should be consistent.  Not sure if the image needs to be displayed or not.

**Comment by WaBirder57** [comment]
Seems like we don’t want that single image duplicated.

**Comment by cguardia** [comment]
It's not just the image, all the information below the "previous summary" heading is duplicated. I'm not sure I get the purpose of that section. Seems like it could be removed entirely, but maybe I'm missing something?

**Comment by davisagli** [comment]
I think the section below the "previous summary" heading is meant to show the report from the last time work was done on the same trail prior to the work party being viewed.

**Comment by cguardia** [comment]
I see. Then when it works I suppose it will not show anything if there's only one report. Do you know if there's a story for this?

**Comment by davisagli** [comment]
Right, the "previous summary" section should only show if there is a previous report! I don't think this got explicitly mentioned in any story, just implied by the mockup.

**Comment by davisagli** [comment]
So maybe best to always hide the "previous summary" section for now. Keep the "view all summaries" button though, since that works.

**Comment by davisagli** [comment]
Okay, we're no longer showing the "previous summary"
