### ISSUE TITLE
multiple report records saved for single WP report

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#260]
I just saved a draft WP report, saved it, made some changes, saved again, eventually published.
I ended up w/ 4 different Report recs in SF, 2 in draft, 2 in published. 
It's possible that the extra Published one is due to the bug in ticket #257 , not sure
But in any case in general we want the existing report to be updated once it exists, not create a new one with every edit.

![image](https://cloud.githubusercontent.com/assets/931031/10066784/24c454e2-624b-11e5-8e4b-be230a4de6c2.png)

**Comment by davisagli** [comment]
@mscholtz which WP was this?

**Comment by davisagli** [comment]
This was a bug affecting re-editing a report after it's created without reloading the page. Fixed.
