### ISSUE TITLE
WP not changed to Completed when final report Published

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#261]
just submitted a report in state Publish for a WP, and the WP status did not change.  IIRC, this should trigger it going to status Completed.  Not sure if the problem is on the pyramid or SF side, or if this has anything to do w/ the new Published status value in SF

**Comment by davisagli** [comment]
That's supposed to be handled by this workflow rule: https://cs9.salesforce.com/01QK00000001EjI

**Comment by mscholtz** [comment]
Ah, it didn't work b/c the end date was in the future.  This should be taken care of if we do ticket #262
