### ISSUE TITLE
Story #305: WP description fields.  Did we loose the Breakfast Spot feature?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#263]
The WP Breakfast Spot information (including directions) should show up on the WP Location Tab.  Seems like this is no longer displayed.  See WP "Testing 305a": https://cs9.salesforce.com/a2eK0000002OXTW?srPos=0&srKp=a2e  as shown in VMS as: http://staging.wta.org:6543/workparty/a2eK0000002OXTW/  This information should be included in the printed directions.

Note that the Before/After section of the description is for possible different activities so this is correctly displayed on the VMS Info Tab

**Comment by davisagli** [comment]
Okay on the Location tab I added the Breakfast Spot and removed the Before/After section. Did I get it right?

**Comment by WaBirder57** [comment]
Close.  The Breakfast spot info looks great. The field for the Before/After Party Location should be listed on the Info Tab under the section for Before/After Party description.  From my test it doesn't look like these directions are display anywhere.  check out this sample WP: https://cs9.salesforce.com/a2eK0000002OXTW

**Comment by davisagli** [comment]
Oops, I missed that there is both a Before/After description *and* a separate location. Will fix.

**Comment by davisagli** [comment]
fixed

**Comment by WaBirder57** [comment]
@ebskopin  This looks complete now.  Elliott can you double check also.

**Comment by ebskopin** [comment]
I'm seeing that this is complete as well.
