### ISSUE TITLE
Story #305: WP Description Rich Text Field Character Count display

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#264]
Is it possible to add a character count field to these fields in Salesforce so that users will know how many characters they can still enter?  It is currently a guessing game every time you save changes to see if the character limits have been exceeded.

**Comment by mscholtz** [comment]
No, not without a completely custom UI including Javascript, which would be a big job and almost certainly not worth it for this need.

**Comment by WaBirder57** [comment]
I'm going to have Aaron work on a solution to using Work Flows to calculate and display the number of characters used for these Rich Text Area fields.  It is a super pain when editing these and getting stuck not knowing how many characters you have used and i think his solution will work.

**Comment by mscholtz** [comment]
@WaBirder57 unless I'm misunderstanding, workflows won't work for this.  WFs only fire once the record has been committed (i.e. after you hit the Save button), and sounds like you want this feedback sooner, right?  It would need to be custom UI & javascript if you want it displayed as you type.

Or am I not understanding what you want here?  Doesn't SF tell you when you click Save if you've exceeded the limits on one of the fields?

**Comment by WaBirder57** [comment]
Matthew,

Aaron has worked up a work flow that displays the character count as well
as the limit for that field.  Yes, this only runs after the record has been
saved but it is better than no information.  Check out the field Default
Camping Information on the Work Party Type.  Just below this on the layout
is this new field: https://cs9.salesforce.com/a2wK0000002GGl5

Can you check that this work flow won't interfere with anything else going
on.  If it is OK I will have Aaron add this for the other Text Area fields
on the Work Party Type as well as Work Party.

Thanks,

Charlie

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by mscholtz** [comment]
Hmm, gotcha.
I see the issue.  However, if it were me, I don't think I would address it
this way.  Adding a bunch of additional fields to the object can muddy
things up, especially when it comes to reports.  And if you change the
length of any fields you'll have to remember to change the WF.

Also, it won't tell you how many chars you have if you go over the limit,
so you won't know how many you need to remove.

I would suggest:
a) for now, use an external means to count chars if you go over the limit.
You can use any number of text editors, MS Word, websites like this
http://www.lettercount.com/ etc.
b) for phase 2, we come up w/ a better solution.  I can think of a number
of approaches, including custom editing UI, or just a trigger to show a
better err message if you go over the limit.  Or there may be a browser
extension that would work.  I tried one Chrome one that didn't work in SF,
but there are more out there.

M.

On Thu, Oct 8, 2015 at 7:30 AM, Charles Kahle <notifications@github.com>
wrote:

> Matthew,
>
> Aaron has worked up a work flow that displays the character count as well
> as the limit for that field. Yes, this only runs after the record has been
> saved but it is better than no information. Check out the field Default
> Camping Information on the Work Party Type. Just below this on the layout
> is this new field: https://cs9.salesforce.com/a2wK0000002GGl5
>
> Can you check that this work flow won't interfere with anything else going
> on. If it is OK I will have Aaron add this for the other Text Area fields
> on the Work Party Type as well as Work Party.
>
> Thanks,
>
> Charlie
>
> Charlie Kahle
> Information Services Manager
> Washington Trails Association
> 705 Second Ave, Suite 300
> Seattle, Wa 98104
> 206.625.1367 - office
> 206.388.4511 - direct
> www.wta.org
>
> On Wed, Oct 7, 2015 at 5:26 PM, Matthew Scholtz <notifications@github.com>
> wrote:
>
> > @WaBirder57 <https://github.com/WaBirder57> unless I'm misunderstanding,
> > workflows won't work for this. WFs only fire once the record has been
> > committed (i.e. after you hit the Save button), and sounds like you want
> > this feedback sooner, right? It would need to be custom UI & javascript
> if
> > you want it displayed as you type.
> >
> > Or am I not understanding what you want here? Doesn't SF tell you when
> you
> > click Save if you've exceeded the limits on one of the fields?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/washingtontrails/vms/issues/264#issuecomment-146378750>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/264#issuecomment-146563780>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/
