### ISSUE TITLE
Auto-WP Registration creation/deletion on WP.Leader change

### ISSUE THREAD

**Issue by drewpiston** [washingtontrails/vms#265]
Right now, WP Regs are only auto-created when a WP.Leader is set from a null value to a non-null value.

WTA would like us to auto-handle WP Registrations when the WP.Leader field is changed from one value to another.  The specifics are TBD (should the old WP Reg be deleted?).

**Comment by WaBirder57** [comment]
If the WP Crew Leader changes, delete the old registration.

**Comment by davisagli** [comment]
Note: this is also story 223

**Comment by mscholtz** [comment]
@WaBirder57 since this is already a story, I'm tempted to close this ticket and deal w/ the story, which currently isn't prioritized very highly.  OK with you?

**Comment by WaBirder57** [comment]
Yes, this is covered by story #233 in Scrumdo.
