### ISSUE TITLE
Guest Signs up for BCRT - no way to access required documents

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#266]
When volunteer as a Guest to VMS signs up for a BCRT (or any work party with required forms - such as Medical or the Back Country Experience form) there is no way for them to complete the required forms.

**Comment by davisagli** [comment]
There should be a link to the forms in the reminder email they get prior to the work party's start.

**Comment by WaBirder57** [comment]
The Volunteer needs to get access to these forms when they sign up.  The reminder email may not come out for some time.  Seems like the logical place for these links would be the in registration confirmation email that goes out at the time of sign up.

**Comment by davisagli** [comment]
That makes sense to me. @mscholtz how hard would it be to include those links in the registration confirmation email too? I'm not sure if we are building those with a visualforce template yet.

**Comment by mscholtz** [comment]
Hey @WaBirder57 , is this something you definitely need before launch?  We talked this over when we first built it, and at that time, you thought it was good enough that they guest users could download the printable version of the form from the browser.  

We could include this in the registration confirmation email, but it would entail a decent amount of work, as we would need to change that from a standard email template to Visualforce.  We are running pretty short on time here, so need to be strict about what's top priority. Moving it to VF would also mean that it would be less easily modifiable by you after we launch.  

Also changing this from Bug to Enhancement.

**Comment by WaBirder57** [comment]
We are not going to support Guest sign ups for trips that require Medical or Back-country experience forms.  That will remove the need for this information in the Guest registration confirmation email.

We should explicitly change the Sign up UI for these types of Work Parties to let folks know they need to have a My Backpack account to register and prevent them from registering.

**Comment by davisagli** [comment]
That's a new story.

**Comment by WaBirder57** [comment]
VMS Story #317 has been created for this.

**Comment by WaBirder57** [comment]
Moved to ScrumDo Story 317.
