### ISSUE TITLE
VMS Registration Page layout issue for volunteer with no My Backpack

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#267]
When a non registered user (no my backpack) signs up for a work party the sign in screen encourages the user to create a my backpack.  See the attached screen shot where the area between "Create My Backpack Account?" and "5 reasons to have a Backpack Account" has an overlapping check box:

![layout issue](https://cloud.githubusercontent.com/assets/8312206/10085298/42afae80-62bd-11e5-96c5-120e925d389b.JPG)

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Thanks, looks good.
