### ISSUE TITLE
VMS Testing Platforms

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#27]
As I flesh out our testing procedures I'm curious to know what platforms our developers are testing with, or most often, so that we can make sure the others get good coverage.  

Here is a snap shot from Google Analytics where you can see the top 10 browsers folks are using to access our website.  Basically in order: Chrome (37%), Safari (36%), IE (12%) then Firefox (8%).

![browseranalyticssnapshot](https://cloud.githubusercontent.com/assets/8312206/6272940/50ada584-b820-11e4-896e-b832b4865168.JPG)

**Comment by davisagli** [comment]
So far I have been developing using Chrome and have not yet spent time testing other browsers. Clearly we need to decide how we're going to do that. The most efficient option in terms of developer time would be if your team does the testing on other browsers and reports the issues you find. But if you don't have time for that, we can discuss when it would make sense for our team to spend some focused time working on browser compatibility.

**Comment by WaBirder57** [comment]
Perhaps best if I bring this up during our Monday Standup meeting to poll everyone to see what platforms they are using to see what “coverage” we have now.  I would like to flesh out our testing so that we do cover the key platforms as well as Smartphone devices.

**Comment by davisagli** [comment]
@WaBirder57 what platforms is your team testing on?

**Comment by WaBirder57** [comment]
Primarily Chrome and Firefox.  Although we can start to adjust as needed.  Still mostly from PC and have not started using hand held devices.

**Comment by davisagli** [comment]
Okay. The ones that are most likely to have issues that need attention are Internet Explorer (especially older versions) and mobile devices.

It would be useful to see a breakdown of usage by IE version so we can decide which version we need to support. Especially IE8 and IE9 can take extra effort since they aren't as compliant with the standards.

**Comment by WaBirder57** [comment]
Here is break down of usage by IE version.  Overall this is just 11% of our visitors to our website.  I don't know that we have this data for our current VOLS site in case that this was different.

Of this IE v 11 is 67% of these users, followed by IE 9 and IE 10.  
![ie google analytics sessions](https://cloud.githubusercontent.com/assets/8312206/6698935/914c576c-ccba-11e4-92dc-2fef44e735d3.JPG)

**Comment by skleinfeldt** [comment]
@WaBirder57 do you now have the information you need so we can close this ticket? I think the summary is that the developers will continue to work/test primarily in Chrome and Firefox (on Mac and Linux); we will rely on your team to do more rigorous testing, especially on IE and on mobile browsers. We can do more focused cross-browser testing if you need us to, but at the cost of some development time.

**Comment by WaBirder57** [comment]
This sounds good.
