### ISSUE TITLE
problem accessing Crew Leader Corner

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#270]
from Charlie:

Julie@wta.org is trying to access her My Backpack Crew Leader Corner but all she see's is the My Workpartys tile.  Her SF Contact record is set to be VMS Admin as well as a CL.  Where else should I look to figure out why she can't see the Crew Leader Corner tile?  This works for me so i know this feature is funcational.

**Comment by WaBirder57** [comment]
Tiffany is having the same or similar problem.  Could be related to cookies and logging out from one user to logging in as another especially when switching to VMS.

**Comment by davisagli** [comment]
Has nothing to do with cookies. The sync of member properties from Salesforce to Plone was not working; I'm in the middle of fixing it.

**Comment by davisagli** [comment]
It worked for you since you're a Plone admin, Charlie, and in that case it doesn't look at the VMS permission level from Salesforce.

**Comment by davisagli** [comment]
Please have them try again; I've got the member property sync working and verified that Julie's Plone user knows it's a VMS admin now.
