### ISSUE TITLE
Land managers, staff and CL need to view Summary Reports for Trail Segments.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#273]
This is complex place holder for what may be several tickets with different priorities.

1) Staff need to be able to see historical WP Summary Reports for specific Trial Segments. We are not even able to build a SF Report to show this information.
2) Land managers need to be able to see Summary Reports for work done on Trail Segments they manage
3) CL and ACL need to be able to see Summary Reports by Trail Segment.

**Comment by davisagli** [comment]
Re 1, I'll leave it to @mscholtz for what the best way would be to do this in Salesforce.

Re 2 and 3, there is some ability to do this already: ACLs or CLs can click on the Report tab for a current work party, then click the "See All Summaries" button to get a list of summary reports for prior work parties on any of the work party's trail segments. Land Managers can also do this for work party's in their jurisdiction. And staff can do this if they are logged into the pyramid app with a permission level of Admin. This was stories 76 and 96.

The mockup for that page (http://07.wta.emptycan.com/volunteer/details/reports/cl/work-party-summaries.html) implies that the user should also be able to search for other trail segments. That is covered by story 95 which is currently in the phase 2 backlog.

**Comment by ebskopin** [comment]
It will be important that all parties (Staff, ACLs, CLs and LMs are able to access this info via a trail segment search function. As most of these parties won't have access to Salesforce this will be their only means of accessing this info, and it can't be dependent on an existing work-party to click through.

**Comment by davisagli** [comment]
Sounds like you need to move story 95 out of phase 2 to a fairly high priority in the main backlog, then.

**Comment by ebskopin** [comment]
Yep, will do.

*Elliott Skopin*
Volunteer Program Coordinator
Washington Trails Association
wta.org <http://www.wta.org/> l Facebook
<https://www.facebook.com/washingtontrails>
(D) 206-557-3406
(O) 206-625-1367

Help WTA celebrate 20 years of trail maintenance - Join a work party!
<http://www.wta.org/volunteer/trail-work-parties>

**Comment by WaBirder57** [comment]
I have moved this into the Backlog, #2 in the priority list.

 

Thanks for the tip David on the Story #.

 

Charlie

**Comment by mscholtz** [comment]
Is there still a ticket here, or does the story cover what you need?  IF the latter, can someone close this ticket?  Assigning back to @WaBirder57 for now to either close or clarify.

**Comment by WaBirder57** [comment]
Looks like this ticket has been covered elsewhere, thanks.
