### ISSUE TITLE
Add Captcha tool to reduce chance of bots signing up for Work Parties

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#274]
We need to add a re-Captcha tool to the WP Registration form to reduce change of BOTS signing up for Work Parties.

Note that we are not using this when a My Backpack is created.  Just add for the Guest registration page.

**Comment by davisagli** [comment]
This is now in place for guest registrations.

**Comment by WaBirder57** [comment]
Seems to work pretty smoothly.

**Comment by WaBirder57** [comment]
@davisagli Tiffany reports the following when testing this further.  Not sure if this is fixable.

Tiffany:
So when I did this, I accidentally forgot to add my state to the registration info and when I clicked the "I am not a robot" and hit register, I was given the message that I needed to add a state. But once I added a state and hit save I was given the message "You need to verify that you are not a robot." But I was not able to unclick and reclick the captcha. Not a huge deal--I just refreshed the page and reentered everything--but a little inconvenient.

**Comment by davisagli** [comment]
Hmm, @cguardia I think we need to do the recaptcha verification in the registration POST request, so that we can delay doing it until after the other validation is complete (once recaptcha has been verified, it can't be verified again using the same token).

Either that or set a flag in the user's session that we know they're human, and if that flag is present don't show the captcha or verify it again.

**Comment by cguardia** [comment]
@davisagli fixed on master

**Comment by davisagli** [comment]
@cguardia can you change it to check for the value in the session first so that we can avoid the external request when it's not needed?

**Comment by cguardia** [comment]
Oops, sorry about that. Fixed.

**Comment by davisagli** [comment]
@WaBirder57 the issue Tiffany found should be fixed now. Once you've completed a captcha you won't have to complete it again even if you have to adjust something on the form.

**Comment by WaBirder57** [comment]
Tiffany reports this is fixed, thanks.
:
Yep--problem fixed. I tried it in all the desktop browsers and didn't have a problem. I did notice that the Captcha on Firefox required me to pick a photo (of pizza!) whereas the other browsers just made me confirm I wasn't a robot with a check box. I don't know that it's very important, but thought I'd mention it.

**Comment by davisagli** [comment]
I think google does some A/B testing with different captcha approaches as they try to stay ahead of spammers, so that's probably why it was different in one case.

**Comment by cguardia** [comment]
During testing and development of this feature, I sometimes got the pictures, sometimes just the checkbox. No discernible pattern.
