### ISSUE TITLE
Work party registration confrimation screen shows todays date, not date of WP

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#276]
When you regester for a work party you directed to a Work Party registraion page (see attached).  The date on this screen shows the current system date (time) and not the date/start time of the work party.

When I registered for this work party: http://staging.wta.org:6543/workparty/a2eK00000000iUN/
I got this confirmation.  Note the difference in the dates.

![registration status payment pending](https://cloud.githubusercontent.com/assets/8312206/10205050/eb1cc868-6773-11e5-8ba0-d1600c539d01.JPG)

**Comment by davisagli** [comment]
Fixed.

**Comment by WaBirder57** [comment]
Looks good.
