### ISSUE TITLE
Mybackpack link for signed in user returns error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#277]
When i have signed into My Backpack and then click "My Backpack at the top of the screen next to my icon I get the following error rather than being take to my My Backpack dash board.

We’re sorry, but there seems to be an error…

Here is the full error message:

Display traceback as text

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module wta.content.backpack.backpack, line 459, in __call__
    Module Products.Five.browser.pagetemplatefile, line 125, in __call__
    Module Products.Five.browser.pagetemplatefile, line 59, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 93, in __call__
    Module z3c.pt.pagetemplate, line 149, in render
    Module chameleon.zpt.template, line 258, in render
    Module chameleon.template, line 191, in render
    Module chameleon.template, line 171, in render
    Module 790087eff12e97fa6c7033fd959eba8b, line 3840, in render
    Module 6383b766fc75550fe24e502b9ef18637, line 1399, in render_master
    Module 790087eff12e97fa6c7033fd959eba8b, line 3828, in __fill_content
    Module 790087eff12e97fa6c7033fd959eba8b, line 886, in render_main

AttributeError: 'str' object has no attribute 'year' - Expression: "python:isOwner and membership_end_date.year() >=1900 and membership_end_date <= (now + 30)" - Filename: ... /wta.content/wta/content/backpack/templates/backpacks.pt - Location: (line 108: col 69) - Source: ... python:isOwner and membership_end_date.year() >=1900 and membership_end_date <= (now + 30) ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) template: <ViewPageTemplateFile - at 0x7f77c1287090> views: <ViewMapper - at 0x7f77d5de9510> modules: <instance - at 0x7f77d6b08ef0> args: <tuple - at 0x7f77deaed050> here: <ImplicitAcquisitionWrapper wtaadmin at 0x7f77bf05adc0> user: <ImplicitAcquisitionWrapper - at 0x7f77bfaff5f0> loop: {...} (1) nothing: <NoneType - at 0x91a870> container: <ImplicitAcquisitionWrapper wtaadmin at 0x7f77bf05adc0> request: <instance - at 0x7f77bf05bf38> wrapped_repeat: <SafeMapping - at 0x7f77d5e1a520> traverse_subpath: <list - at 0x7f77c0e1acb0> default: <object - at 0x7f77dea044f0> context: <ImplicitAcquisitionWrapper wtaadmin at 0x7f77bf05adc0> view: <SimpleViewClass from /usr/local/plone/zeocluster/src/wta.content/wta/content/backpack/templates/backpacks.pt backpacks at 0x7f77d603db90> translate: <function translate at 0x7f77bfa98140> root: <ImplicitAcquisitionWrapper Zope at 0x7f77ca68dbe0> options: {...} (0) target_language: <NoneType - at 0x91a870>

**Comment by davisagli** [comment]
Which user's backpack?

David Glick
(mobile)

**Comment by WaBirder57** [comment]
Does this for me, charles@wta.org

 

Charlie

**Comment by davisagli** [comment]
give this another try now. The membership dates fetched from Salesforce were not getting converted correctly.

**Comment by WaBirder57** [comment]
Thanks, this is working again.
