### ISSUE TITLE
MBP: User Avatar (image) spacing - Website menu overlaps image

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#278]
When a user is logged into My Backpack their image from their profile is overlapped by the website menu.  See the following screenshot.
![avatarspacing](https://cloud.githubusercontent.com/assets/8312206/10208418/2912025a-6788-11e5-9854-05da64ea6714.png)
image should be sized or cropped to fix.

**Comment by davisagli** [comment]
The design has the avatar image overlapping the image collage, so I think this will work okay once the collage is in place.

**Comment by alecpm** [comment]
I think this is ready for review.

**Comment by WaBirder57** [comment]
Looks good.
