### ISSUE TITLE
MBP: Trip report list spacing is tight for USer name/Avatar and text below "hike 59 days ago"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#279]
When a user is looking at a list of trip reports the line spacing is to tight between the Users Avatar/Name and the following line with  "Hike ## Days ago".  See that attached screen shot.

![tripreportspacing](https://cloud.githubusercontent.com/assets/8312206/10208456/57c07c58-6788-11e5-86f8-09e6b7fabe18.png)

**Comment by alecpm** [comment]
This should be fixed on the dev server.

**Comment by davisagli** [comment]
Fixed the avatar image.
