### ISSUE TITLE
MBP: Edit Profile should include the ability to change newsletter subscriptions.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#280]
When a user is editing their My Backpack profile they should see a list of all the WTA newsletters and change their subscription status.  These 4 newsletters are located on the SF Contact record as picklist values:
Trail News
Trail Action Network
Green Hat
Families Go Hiking

**Comment by davisagli** [comment]
They're already there, down toward the bottom of the form:

![screen shot 2015-09-30 at 3 41 55 pm](https://cloud.githubusercontent.com/assets/49014/10208681/d6d0e3f6-6789-11e5-9b1e-ff07a1cccbcb.png)

**Comment by davisagli** [comment]
@WaBirder57 please either confirm that this is working and close the ticket, or explain why you don't think it's working. It does look like we need to replace the lorem ipsum text for the "Green Hat Newsletter"...can you supply that please?

**Comment by WaBirder57** [comment]
Edit profile does display subscriptions.  Thank you.  Will get the text for the Green hat news letter.
