### ISSUE TITLE
MBP: Edit profile should have Phone number "helper" fields to ensure complete phone numbers are entered

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#281]
When editing a My Backpack profile any value can be entered for any of the phone number fields.  There should be some input checking to check for valid phone numbers and format, see the attache example of to many numbers or text being entered for a phone number.
![profilephonenumbers](https://cloud.githubusercontent.com/assets/8312206/10208736/460cff0c-678a-11e5-8091-06f202942e62.JPG)

**Comment by alecpm** [comment]
I've added a fairly tolerant phone number validator to these fields.  It should allow entering phone extensions as well as various sorts of delimiting punctuation.

**Comment by WaBirder57** [comment]
OK, this works better now traps random invalid phone numbers.
