### ISSUE TITLE
VMS: List view for day work work parties should not include start and end times 

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#282]
When viewing the list view of work parties in VMS, Day Work parties should not show start and end times.  This will only be visible when a use clicks to open the details for that work party.  Multi Day work parties will still show the start and end times on the list view.
![listviewtimes](https://cloud.githubusercontent.com/assets/8312206/10209504/fa3fedc6-6790-11e5-8899-1354aab674db.JPG)

**Comment by davisagli** [comment]
This contradicts what you said in #211; did you change your mind?

**Comment by WaBirder57** [comment]
Yes, well Rebecca did.  Refining where these start and end times will be displayed.

**Comment by davisagli** [comment]
done
