### ISSUE TITLE
Move code for updating registration status after payment

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#286]
This issue is a follow-up to the discussion in #231.

We have code in an opportunity trigger that updates the registration status to Registered (for the main registrant and any friends/family) after the payment opportunity is created by Click and Pledge.

But sometimes Click and Pledge doesn't create an opportunity right away (i.e. if there's a potential matching contact that needs to be reviewed by WTA staff). In this case we need to update the registration status a different way: I'm planning to add code to the pyramid app to update the status of the main registrant after it receives confirmation of payment from Click and Pledge.

However, the Pyramid app only has the registration id for the main registrant, not any friends/family. So we need to move the code that updates the registration status for friends/family from the opportunity trigger to a registration trigger (i.e. if main registrant's status changes from Payment Pending to Registered, update the status for the friends/family too).

**Comment by mscholtz** [comment]
@ninetaLogik here's yet another one having to do with the registration trigger.  If you have time for this one too, great.  If not, I can do it.  Please do this one last of the tickets for this week.  And of course, let me know if you want to talk it over.

**Comment by mscholtz** [comment]
@drewpiston let me know if you have questions here.

**Comment by davisagli** [comment]
Removing the reviewing tag because there's a pyramid part to this too that still needs to be done.

**Comment by davisagli** [comment]
This is done but I'm not sure how to test it because in staging I don't think the Click and Pledge settings are set up to create a temporary contact when the address doesn't match like they are in production. @mscholtz or @WaBirder57 can you adjust those settings to match the production click and pledge settings so I can test? (I don't remember which of you has access to the Click and Pledge account we're using with staging.)

**Comment by mscholtz** [comment]
done

**Comment by davisagli** [comment]
@mscholtz okay, I don't understand how to trigger the scenario that was discussed in #231. I thought it says that if I register for a work party with a fee using a name and email that matches but an address that does not, I can expect Click and Pledge to create a temporary contact and no opportunity. But that's what I tried and it created an opportunity attached to the contact whose name and email matched.

**Comment by mscholtz** [comment]
@davisagli did the contact already have an address?  If both are blank it might allow a match.  Not entirely sure how it works, but try that if you haven't already

**Comment by davisagli** [comment]
Yes, it already had an address.

**Comment by mscholtz** [comment]
URL, please?

On Mon, Nov 2, 2015 at 2:56 PM, David Glick <notifications@github.com>
wrote:

> Yes, it already had an address.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/286#issuecomment-153184439>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
https://cs9.salesforce.com/003K0000010ImRr is the contact that I didn't expect CnP to match. Before I registered the street was "1541 NW 52nd St", not "bogus addr 123".
https://cs9.salesforce.com/006K000000DVAn1 is the opportunity that I didn't expect CnP to create.

**Comment by mscholtz** [comment]
Hmm, this is puzzling.  I'm not sure.
@WaBirder57 or @barbarachristensen got any ideas?  Settings are here:
https://cnp-paas.cs9.visual.force.com/apex/xmlsettings?sfdc.tabName=01rA000000061K5

and it's already set to "semi-automatic" and Street is included in the match fields.  My understanding was that if any of the match fields was a mismatch it would create a temp contact..

**Comment by barbarachristensen** [comment]
Looks like sandbox is set to Fully Automatic not semi-automatic Contact creation under the Contacts/accounts settings. That will ignore all matching and just create a contact.

**Comment by barbarachristensen** [comment]
Ignore this-- comment above, my bad. It pulled me into another logged in sandbox. Will look at VMS2

**Comment by barbarachristensen** [comment]
I can't see anything obvious; your assumptions of how it works are as I understand them, too. Of note-- when matching to an existing contact, it actually shouldn't have overwritten existing address info unless the fields were blank. You should have had to process the address via the C&P Alias page. Might be worth asking in the forum.

**Comment by mscholtz** [comment]
@barbarachristensen says she can look into this more next week.  We're not sure yet what's going on.

**Comment by barbarachristensen** [comment]
Hey @davisagli -- Will I get in your way at all if I delete and repost this transaction a couple times (c&P has a tool to wipe the slate and start again like the transaction is new). Will save someone having to set me up/show me how to create registrations in the real test environment. thx!

**Comment by davisagli** [comment]
Go ahead.

David Glick
(mobile)

**Comment by barbarachristensen** [comment]
I think I'm going to have to create a new registration to test this WTA issue further. I saw the strange behaviour once as David saw it, but now with a second test on the same records  to capture in a debug log, it's creating a temp contact like it should. I ran a third just to be sure, still working right. I'm gaming the system a bit by re-processing his record over and over, so should rule that out. Is it hard to show me where/how to create another registration, @mscholtz ?

**Comment by mscholtz** [comment]
This is pretty easy to do

* Go here: http://staging.wta.org:6543/
* Find a paid WP (look for Volunteer Vacations is the best bet)
* Click through to the WP, then click Join
* You'll be prompted to register for My Backpack (which is required for paid WPs) - go ahead and do that, and you should be brought back to the registration form.  Don't worry if you get certificate warnings.
* Register and pay, using usual fake CC # (4 + 15 ones), any exp and CVV.  
* Now check the same WP in SF.  Registration and payment and contact should all be in there!
* To repeat, either delete that registration/opp in SF, and try again w/ same WP, or register for a new WP.

**Comment by barbarachristensen** [comment]
Tested new registration, saw the no temp contact/overwrite of data 2x. Captured one w/ debug log, if you need it.  Something seems to be firing before the C&P triggers that sets the address from registration onto contact rec, so that when c&p goes searching for a match, it finds an exact one.

No workflows, Flows, or process touch address info on contact. 

There is a method-- WTA_VMS_REST_CreateRegistration.update_contact  that updates address on contact w/ registrations. That could be your culprit. 

Matthew pointed out that this could act different in production, of course. @mscholtz passing it back to the team at this point per your request. Yell if you need anything more. Thanks!

**Comment by davisagli** [comment]
If the registration webservice updates the address on the contact, then that would indeed happen before the user even gets a chance to fill out the payment form.

I think that the issue Matthew described in #231 was hypothetical rather than based on actual testing.

I'm going to close this and someone can open a new issue if there's still a problem.
