### ISSUE TITLE
MBP "Insufficient Privileges" when looking at Work Party Tile detail list of WP to click through to a WP.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#287]
Iteration 18, Story 301 generates the following error when trying to follow the instructions.

Testing instructions:
1. Log into mybackpack.wta.org
 as an ACL or CL and go to My Work Parties. The red hat icon should show
 up for work parties that still have "Alert ACLs Needed" checked in 
Salesforce.
2. The icon should also show up in the list on the Crew Leader Corner page.

Julie@wta.org reports the following:
When I log in as Soren Eagle, ACL, and click on "Crew Leader College," I am brought to a page that simply says, "Insufficient Privileges."

Same result when I log in as myself, Admin privileges. [JC 10/3]

**Comment by davisagli** [comment]
This should work now.

**Comment by ebskopin** [comment]
works
