### ISSUE TITLE
MBP Edit Profile text descriptions for news letter subscriptions

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#289]
Please update the Edit My Back Profile page to include this language for the news letter descriptions where folks and change their subscription status.

Green Hat:
"Send me periodic info about volunteering on trail with WTA"

Trail Action Network:
"Join the Trail Action Network to receive emails about how you can advocate for trails."

**Comment by davisagli** [comment]
done

**Comment by WaBirder57** [comment]
Thanks, looks good.
