### ISSUE TITLE
WP List shows overivew with HTML tags displayed

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#29]
Salesforce uses a "Rich-text", text field for the Overview language on a work party.  When displayed in the list view of Work Parties this doesn't display correctly.  It shows the HTML tags.  Oyster Dome work party is an example of this.

For example is shows:
"Oyster Dome.<br><br><u><b>Trail Facts:</b></u> [Pulled from Hike Summary in hiking guide]<br><span style="color: rgb(42, 42, 42); font-family: trebuchet ms,lucida grande,verdana,lucida,arial,sans-serif; font-size: 11.5200004577637px;">Oyster Dome is a "

When you open the WP in Pyramid and look at the Info tab this Overview information displays correctly.

**Comment by davisagli** [comment]
Fixed.

Hmm, do we really want to show the same text here as on the work party page, though? Seems like it would be too long in some cases. Do we need a separate summary field?

**Comment by davisagli** [comment]
Fixed, and my question about other fields is covered by #40
