### ISSUE TITLE
VMS: Edits to Work Party Type "Info" Fields 

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#290]
[VMS Info Tab Features and Fields.xlsx](https://github.com/washingtontrails/vms/files/8804/VMS.Info.Tab.Features.and.Fields.xlsx)

Let me know of any questions.
-Elliott

**Comment by mscholtz** [comment]
@drewpiston assigning this to you for now

@davisagli there is some pyramid work in here as well.  ok if we just go ahead w/ the changes on the SF side and then pass over to your team when that's done?

**Comment by davisagli** [comment]
@mscholtz please wait to delete fields until we're no longer referencing them in queries, so that we don't break the site and block them from testing. You can go ahead with the other changes.

**Comment by drewpiston** [comment]
Hi @davisagli  ,

I think this is ready for you -- some notes:
1. I added a "DEL" prefix to the fields being deleted, but didn't actually delete them (or change the API name).  Once they are removed from your code let me know and I'll delete them.

2. For name changes to fields, I changed the Field Label only -- the Field API name will remain the same, so no need for updates to your code.  @ebskopin , @mscholtz : if for any reason you all think the Field API name should change, let me know and David and I can probably coordinate the change.

3. I'm uploading an Excel spreadsheet with a new column for Salesforce Status.

David, I'll assign to you. 

Cheers,
 Drew

**Comment by drewpiston** [comment]
[VMS.Info.Tab.Features.and.Fields Perc Edit 10.7.2015.xlsx](https://github.com/washingtontrails/vms/files/9646/VMS.Info.Tab.Features.and.Fields.Perc.Edit.10.7.2015.xlsx)

**Comment by davisagli** [comment]
I'm done with the changes to the Pyramid app and it should be okay to actually delete the fields now.

**Comment by drewpiston** [comment]
Fields deleted!
Updated status sheet:
[VMS.Info.Tab.Features.and.Fields Perc Edit 10.7.2015.xlsx](https://github.com/washingtontrails/vms/files/11062/VMS.Info.Tab.Features.and.Fields.Perc.Edit.10.7.2015.xlsx)

**Comment by ebskopin** [comment]
This is complete.
