### ISSUE TITLE
Trip report creation - Hike list doesn't populate until after Submit is pressed

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#291]
When creating a trip report from the My Backpack drop down menu "Write a Trip Report" the user is asked to select the hike they are reporting on.  When a value like "Test" is entered nothing happens to prompt the user to select the hike.  After the trip report is complete and the user presses the submit button an error occurs and the user is asked to select their hike from a list of hikes containing "Test" that now appears at the top of the trip report form.  When a hike is selected the trip report can be submitted and no error appears.

**Comment by alecpm** [comment]
Does this work differently in current production?  We haven't made any changes here as far as I'm aware (which isn't to say this shouldn't be fixed, but it will be easier to fix if we know whether it's a regression or a pre-existing bug).

**Comment by WaBirder57** [comment]
In production when you enter part of a Hike name it does a real time look up and shows the available options to choose from.  The user can then choose before they move to the next field on the trip report form.  As this is working in MBP now where they user has to get an error first to see the list of hikes is not that good.

**Comment by alecpm** [comment]
OK, this should be easy to fix if it's just a regression from production.  Probably a JS bug, and hopefully one that's easy to track down.

**Comment by WaBirder57** [comment]
OK thanks for looking at this.  I didn't think this code needed to change
in the new MBP so I hope it is easy to track down.

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by davisagli** [comment]
Fixed. The dev site did not have AutocompleteWidget installed.

(@jessesnyder I guess that dependency is missing from the wta.content installation)

**Comment by WaBirder57** [comment]
Ah, working nicely now.

**Comment by jessesnyder** [comment]
@davisagli was this Products.AutocompleteWidget or plone.formwidget.autocomplete (or both)?

**Comment by davisagli** [comment]
@jessesnyder it was the trip report add form and it was Products.AutocompleteWidget that I needed to activate, not plone.formwidget.autocomplete which was already activated
