### ISSUE TITLE
Work party link to print information: Iteration 14, story 90

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#292]
Where is the link that this story refers to so that information on the WP can be printed?  There are no testing instructions on this story.

**Comment by davisagli** [comment]
There isn't a link shown in the design mockups (aside from the one on the Location tab which I think is meant to just print the directions) so I think we assumed that users will print using "File > Print" in their browser's menu. Alec implemented some styles specific to the printed format of the page. So the testing instructions are just to try that in different browsers and make sure it looks good.

**Comment by davisagli** [comment]
@WaBirder57 can you clarify why you removed the 'reviewing' tag and reassigned this to me? I'm not sure what action needs to be taken.

**Comment by WaBirder57** [comment]
I'm doing more testing on this, sorry have flipped at assignment.

**Comment by ebskopin** [comment]
working
