### ISSUE TITLE
VMS Forms preview document

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#298]
When a user is looking at the WP forms to complete (Back country Experience or the Medical) the volunteer is given the option for complete online or to see a printable version of the document.  this link goes to a Google doc placeholder (https://docs.google.com/document/d/1tbzM0psvryhzO8Wznf3aOfuPH9xOc73ueEt6ojKGvO4/edit?usp=sharing)

Where can I store the PDF Version of these documents to be accessed from these buttons?  Note that these forms will change from time to time so we will need to be able to update these files.

**Comment by davisagli** [comment]
Wherever you like. Somewhere in Plone would probably make sense.

**Comment by WaBirder57** [comment]
We have decided not to provide a blank printable view of these forms so this link will be removed.  See ticket #388 .
