### ISSUE TITLE
Find a Work Party Map and Calendar Tab content broken

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#30]
On the Find a Work Party web page the tabs for Maps and Calendar return an error message such as: 

debug_notfound of url http://staging.wta.org:6543/tabs/map.html; path_info: u'/tabs/map.html', context: <vms.auth.Root object at 0x7f979a6b4a50>, view_name: u'tabs', subpath: (u'map.html',), traversed: (), root: <vms.auth.Root object at 0x7f979a6b4a50>, vroot: <vms.auth.Root object at 0x7f979a6b4a50>, vroot_path: ()

**Comment by davisagli** [comment]
Right, those tabs are stories 6 and 4 which we haven't tackled yet.

**Comment by WaBirder57** [comment]
Ah, I thought this was part of Story #7, Iteration 2.

**Comment by davisagli** [comment]
No, story 7 covered adding the controls on the left to filter the list of work parties shown. That same filtered list will be used by the map and calendar, but actually displaying them is covered by stories 4 and 6.
