### ISSUE TITLE
Iteration #16, Story #27 - formating for mobile (narrow) device needs to be completed.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#300]
In Story #27 the formatting for a narrow screen device needs to be completed.  The attached screen shot is one example  Also the right hand side portlets will overlap the main body of the page on some devices.  Let us know if more examples are needed.
![mbpnarrowscreen](https://cloud.githubusercontent.com/assets/8312206/10352356/73032b0c-6d03-11e5-9137-296bd6c706b2.png)

**Comment by davisagli** [comment]
This belongs in the MBP budget, surely.

Images of some other examples would be useful just to make sure we cover all the issues you're seeing.

**Comment by davisagli** [comment]
I fixed the misplaced vertical line. Please file new issues with screenshots for other things that are not working well on mobile.
