### ISSUE TITLE
MBP: Can't see public saved hikes in others My Backpack

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#301]
When not logged into MBP I go to the My Backpack for another user, say Charlie Kahle (charles@wta.org) https://mybackpack.wta.org/@@backpacks/scrnm-Charlie%20Kahle%20WTA and it doesn't show the tile for saved hikes although Charlie Kahle (charles@wta.org) has "my hikes viewable" selected and indeed has a saved hike.

**Comment by davisagli** [comment]
Fixed
