### ISSUE TITLE
MBP: Hiking Guide correspondent showing on all My Backpack accounts

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#302]
The Hiking Guide Correspondent is showing on all My Backpack's regardless of setting on Salesforce contact.

Take EstelleG as an example:
My Backpack: https://mybackpack.wta.org/@@backpacks/scrnm-EstelleG
SF Contact: https://cs9.salesforce.com/003K0000014MMWX?srPos=0&srKp=003

**Comment by davisagli** [comment]
This is fixed

**Comment by WaBirder57** [comment]
This seems to work.  Question: If I change the Hiking Guide Corespondent check box in Salesforce, how long before that change will be reflected on the website?

**Comment by davisagli** [comment]
Values from Salesforce are currently updated in Plone nightly starting at 2 am.
