### ISSUE TITLE
MBP: Trip Report List formating changes

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#303]
In MBP the list of Trip Reports should have the following changes made:
- [x] The trip reporter photo is still stacked too closely to the date field. 
- [x] The dates should shift away from the "X days ago" model into actual dates after two weeks -- we should never see "15 days ago" or "254 days ago". 
- [x] Unbold date line treatment. 
- [x] Title and "Hiked X days" should align left. 
- [x] The title should not be underlined. 
- [x] There is an extra underlined, hyperlinked space in front of the trip reporter's name. 
- [x] The orange "eye" icon is missing from the design under the photos, and the # of photos font should be unbolded to a light grey (See listing here: http://www.wta.org/go-hiking/hikes/green-mountain). 
- [x] Photos icon and number of photos should align left. 
- [x] Remove the region and subregion line entirely, and replace the orange font treatment of the "Beware of" section with the font found on the Green Mountain listing above. 
- [x] We need the "View report text"/"Expand report text" and the "See report text" button in the expanded view.

**Comment by davisagli** [comment]
Note: the first bullet is covered by #279

**Comment by davisagli** [comment]
These changes could be summarized by saying that you want the styles to better match the design (http://wta.mybackpack.emptycan.com/profile/my-reports/) but also include some of the elements that are present in the existing listings (e.g. http://www.wta.org/go-hiking/hikes/green-mountain) but not in the MBP designs.

I've done a pass at that and it's a lot better, but still feels cluttered compared to the current site's trip report listing. I think this would benefit from having Ethical UX do a design mockup that includes all the elements. Is that possible at this point @WaBirder57 and @kuffelman?

Are you sure you want to remove the region/subregion entirely? On the current site it's omitted when looking at a hike (see green mountain page) but included below the title when looking at trip reports outside the context of a hike, such as the trip report search (http://www.wta.org/go-hiking/trip-reports)

**Comment by WaBirder57** [comment]
David, great catch on this.  Loren sends a thank you.

Loren will work on the designs for the 3 locations where trip report lists are used (Trip Reports, under a Hiking Guide entry and in My Backpack) and send a mock up to you all Monday.  Lets hold on other changes in this area until we get these designs.

**Comment by davisagli** [comment]
Okay. It will be easiest to implement if the 3 trip report listings look similar, but it's fine if some pieces should be omitted on some of the listings (i.e. no region on the hike's trip reports because it duplicates info from the hike; no author in the My Backpack listing because they're all the same...)

**Comment by WaBirder57** [comment]
All done, other tickets have addressed these issues too.
