### ISSUE TITLE
MBP: Default value for share work parties should be false in a users profile

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#309]
In My Backpack, the default value for "My Work Parties Visible" should be set to false.  Unless a user specifically clicks to share Work Parties these should not be view-able.  The same default should be used for "Saved Hikes", that is not share saved hikes by default.  

I want to double check that this is the way the MBP is setup to work when a new account is created.

We have concerns about Youth or other individuals inadvertently making available information about where they will be in the future.  "Privacy, by default".

**Comment by davisagli** [comment]
That should be the case. Please confirm it's working by registering a new user and checking to make sure that the settings are correct.

**Comment by WaBirder57** [comment]
Yes, this is working correctly.  Thanks.
