### ISSUE TITLE
WP Registration Page - needs to be Work Party Type dependent - changes to Add Another Person

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#31]
Not all work party types will support "add another person".  Also, text clarifying adding another person needs to be added based on WP Type.  Add this extra text after "Bringing someone with you?" and the first Name field.  Note MAX of 6 additional people may be added this way on this web page.  Note that if an individual added to a work party this way is an ACL or CL they should be added to the WP as an ACL.

WP Type: Day, Youth WP, Special Event WP - 
"For Day work parties or special events, you may register up to 6 people.  For larger party sizes please contact the WTA offices (insert contact info) or fill out this Group Inquiry form [yet to be created]."

WP Type: BCRT, Volunteer Vacation - 
"For back-country trips, you may register yourself and a spouse or partner [ie only one other person].  Otherwise each individual needs to register himself/herself.

WP Type: Youth Vacation, Training - 
No option to add another person so this should not be available.

**Comment by davisagli** [comment]
This sounds related to the Registration Policy story 69 from this iteration. @mscholtz

**Comment by davisagli** [comment]
Sounds like we need these changes:
- [ ] The registration policy (whether it's new fields on the Work Party Type, or a separate object) needs to include these settings:
  - [ ] Max additional people
  - [ ] Additional people help text
- [ ] Need to include these in the fields indexed for a work party
- [ ] The registration form needs to show the help text and respect the max add'l people setting (or not show it at all if it's 0)
- [ ] The registration webservice needs to set the additional registration's role to ACL if the matched contact has a permission level of ACL or CL

**Comment by mscholtz** [comment]
Can we come up with a name for this?  Calling it "additional people" isn't doing it for me.
"Guest Registrations"?  "Family Registrations"?  "Household Registrations"?
@WaBirder57

**Comment by davisagli** [comment]
We've already been using the term "guest registration" to mean someone registering while not logged in. "Family" or "household" is fine as a name for the feature, but isn't really accurate since you can use the feature to register friends too.

**Comment by mscholtz** [comment]
I thought we decided it was family members only.  No?

On Thu, Mar 26, 2015 at 11:56 AM, David Glick <notifications@github.com>
wrote:

> We've already been using the term "guest registration" to mean someone
> registering while not logged in. "Family" or "household" is fine as a name
> for the feature, but isn't really accurate since you can use the feature to
> register friends too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/31#issuecomment-86670024>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
From the description above, it's clear that that's the case for BCRT and Volunteer Vacations (spouse/partner only), but I'm not sure about Day/Youth/Special Event work parties.

**Comment by ninetaLogik** [comment]
@mscholtz or @davisagli : Could you please confirm that the items below are the ones needed on the SF side?
1. The registration policy (whether it's new fields on the Work Party Type, or a separate object) needs to include these settings:
    Max additional people
    Additional people help text
2. The registration webservice needs to set the additional registration's role to ACL if the matched contact has a permission level of ACL or CL

**Comment by davisagli** [comment]
That's what I think needs to happen; probably good to have @mscholtz sign off on it before implementing.

**Comment by mscholtz** [comment]
re #1, yes.   How about let's use the term "friends/family" instead of "additional people"?

re #2, @WaBirder57 do we really need this?  Does it really happen that someone who's not a CL/ACL themselves is going to register a friend who just happens to be a CL/ACL?  Or is this about ACLs registering other ACLs?

**Comment by ninetaLogik** [comment]
@mscholtz for #1, yes. How about let's use the term "friends/family" instead of "additional people"? 

do we need just a couple of new fields on Work Party "Max Friends/Family" and "Friends/Family Help Text".  Does the registration web service need to do anything with these?

**Comment by davisagli** [comment]
+1 for friends/family.

The fields should be on Work Party Type, not Work Party.

For bonus points the registration webservice could check that you aren't registering more than the max, but this validation will also happen in Pyramid, so it's not strictly necessary.

**Comment by ninetaLogik** [comment]
Do we want the "Friends/Family Help Text" to be long text are or rich text area?

**Comment by ninetaLogik** [comment]
@mscholtz  -- Do we need to handle registrations created by hand directly in SF or would those be created separately for each additional friend or family member? (As per David: For bonus points the registration webservice could check that you aren't registering more than the max, but this validation will also happen in Pyramid, so it's not strictly necessary.)

**Comment by mscholtz** [comment]
I don't think we have to worry about that manual entry thing.  So let's not
do that validation for now.

I'll leave the text type question to David

On Tue, Apr 21, 2015 at 9:51 AM, ninetaLogik <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> -- Do we need to handle
> registrations created by hand directly in SF or would those be created
> separately for each additional friend or family member? (As per David: For
> bonus points the registration webservice could check that you aren't
> registering more than the max, but this validation will also happen in
> Pyramid, so it's not strictly necessary.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/31#issuecomment-94867736>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Let's make it rich text in case they want to link somewhere.

**Comment by ninetaLogik** [comment]
Done. The new fields on Work Party Type have been created: Max_Friends_Family__c and Friends_Family_Help_Text__c

**Comment by ninetaLogik** [comment]
Still waiting to hear back on re #2, @WaBirder57 do we really need this? Does it really happen that someone who's not a CL/ACL themselves is going to register a friend who just happens to be a CL/ACL? Or is this about ACLs registering other ACLs?

**Comment by WaBirder57** [comment]
Re #2, If someone signs up a friend who happens to be an ACL they should be added to the WP registered as an ACL.  Note that if someone signs up a friend who happens to be a Crew Leader or Staff, they would be signed up as an ACL if the field Contact.Assistant Crew Leader check box is true, otherwise they would be registered as a VOL.  There could be Staff who are not ACL qualified, all Crew Leaders would be qualified.

It would be great if the ACL could later go in and edit their registration to change it to be a VOL but that isn't in the story (I will add a new low priority Story for this).  For now the ACL would have to contact staff and they would change their registration from ACL to VOL in Salesforce.

**Comment by mscholtz** [comment]
Just spoke to Charlie, and we agreed that this automatic ACL thing doesn't need to happen now, because it should be a rare occurrence.  I will create a new Low Priority ticket for it.

**Comment by davisagli** [comment]
@WaBirder57 you can now control this using these fields on the work party type:
Max Friends/Family - Set to the number of people that may be added in addition to the main registrant. Set to 0 if adding friends/family is not allowed for this work party type.
Friends/Family Help Text - Set to the help text you want to display for work parties of this type.

I attempted to fill these out for the existing work party types based on the guidance in this ticket's description, but you'll probably want to review the settings.

**Comment by WaBirder57** [comment]
Tested and it seems that this is working correctly.  Note the ACL issue is being handled in another ticker per Matthew.
