### ISSUE TITLE
MBP: Trip report Creator Field doesn't auto populate for logged in user

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#310]
When a logged in user selects Write A Trip Report from the My Backpack drop down menu they are taken to a blank Trip Report form.  The First Field, "Creator" is not filled in.  I would expect this to use the information from the currently logged in user.

**Comment by davisagli** [comment]
That field is only visible for admins, and if it's left blank it gets set to the current user when you save. So I think this is pretty low priority.

**Comment by WaBirder57** [comment]
Ah, this is a feature and a good one for Admin's only.  Please leave this as implemented.
