### ISSUE TITLE
MBP: Hiking guide Save to My Backpack button doesn't work

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#312]
When looking at a Hiking Guide Entry the button to "Save to my Backpack" doesn't work.  Also in some browsers the text doesn't display.  All we see is a colored button.  While the mouse pointer indicates the button is clickable, nothing happens when it is clicked.

![mbp - save to mbp not working](https://cloud.githubusercontent.com/assets/8312206/10469908/e3de3c18-71bd-11e5-8242-e84b9895ff72.JPG)

**Comment by davisagli** [comment]
Fixed.

**Comment by WaBirder57** [comment]
Thanks, working now.
