### ISSUE TITLE
MBP: Saved hike list adds green overlay to saved hikes which have been hiked.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#313]
In a users My Backpack we don't like the Green Overlay on the image for a Saved Hike that has been hiked.  Can you just show the white Check Mark but don't add the Green Overlay.

![mbp- saved hiked green overlay](https://cloud.githubusercontent.com/assets/8312206/10470030/0272bd9c-71bf-11e5-949c-1f108a97be83.JPG)

**Comment by davisagli** [comment]
I'm worried that the check mark by itself will be hard to see.

First I'll try adjusting the green overlay so it matches the border of the image like it's supposed to, and making it more subtle.

**Comment by WaBirder57** [comment]
Loren is concerned that the list of hikes that have been hiked shown with the Green overlay is not very attractive.  So bear this in mind as you try adjusting this.  Perhaps the image could be larger and that would help.

**Comment by davisagli** [comment]
Or maybe a thick green border around the image so it's obvious but doesn't obscure the image?

**Comment by davisagli** [comment]
You're right, the image is supposed to be larger; I'll look into that too.

**Comment by WaBirder57** [comment]
Yes that might be the trick.  Once you have that in place I will have Loren test it.

**Comment by davisagli** [comment]
Okay, it now uses a larger image and a green border instead of the semi-transparent overlay. I also added text shadow to the checkmark so it shows up on a light background.

**Comment by WaBirder57** [comment]
This looks GREAT!  Nice job.
