### ISSUE TITLE
MBP: Saved hikes add expand all notes toggle 

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#314]
In a users My backpack looking at the list of saved hikes.  Per the Wire-frame (page 18) we would like to have the "expand all" notes toggle at the top of the list.  See Wire-frame note #4 in attache screen shot. (Sorry if this is working but I can't add additional saved hikes to my MBP at this time to test with more than one Saved hike. See ticket #312 )

![expand all notes toggle](https://cloud.githubusercontent.com/assets/8312206/10470352/6de176d4-71c1-11e5-802a-631a05b1d606.JPG)

**Comment by davisagli** [comment]
Once clicked should it disappear or turn into "collapse notes"?

**Comment by WaBirder57** [comment]
Yes, that would work well.

**Comment by davisagli** [comment]
Which one?

**Comment by WaBirder57** [comment]
Once the "expand all" toggle is selected it will turn into "collapse notes" (or "collapse all" to be consistent with expand all.)  Let me check with Loren and get the final verdict.

**Comment by cguardia** [comment]
Added js toggle.

**Comment by davisagli** [comment]
This is working now.
