### ISSUE TITLE
MBP: Map view of Trip Report location needs default zoom to show more of Wa state

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#315]
The Map tab of a users My Backpack show the location of the selected trip reports.  This should default to a zoom level that shows more of Washington state.  Right now the map is zoomed in so tightly that users must click zoom out several times to see where the map pins are relative to the rest of the state.  When widely spaced TR pins are displayed this is OK, only if the TR selected for display are all close together does this zoom level to need to be adjusted.

**Comment by davisagli** [comment]
@alecpm is it possible to set a maximum zoom level for the map?

**Comment by alecpm** [comment]
OK, this is implemented and deployed.

**Comment by WaBirder57** [comment]
Looks correct now.
