### ISSUE TITLE
MBP: Menu for My Backpack doesn't link to Dashboard if browser size is not full screen

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#316]
When a logged in user reduces the size of their browser so that the down arrow appears next to the My Backpack menu text - clicking "My Backpack" doesn't take the user to the Dash board.  There doesn't appear to be a way to get to the My Backpack dashboard in this situation.  See the screen shot to see how this looks when it doesn't work.
![mbp not full screen](https://cloud.githubusercontent.com/assets/8312206/10470821/c3d8df02-71c4-11e5-9a09-fa35a05dbe13.JPG)

**Comment by davisagli** [comment]
I remember noticing that when implementing the nav bar, but forgot to mention it.

The user obviously needs a way to open the menu. What if we add 'dashboard' as a new link at the top of the menu?

**Comment by WaBirder57** [comment]
Yes, I think adding "Dashboard" as a menu option is a good idea.

**Comment by davisagli** [comment]
All right, the Dashboard link is there now.

**Comment by WaBirder57** [comment]
Looks good.
