### ISSUE TITLE
Include spam score when Salesforce Contacts are created and updated

### ISSUE THREAD

**Issue by jessesnyder** [washingtontrails/vms#317]
We have added some code to include a calculated spam score in the Lead record when new accounts are created. When VMS launches we will want the same data sent when Contact records are updated or created. See https://github.com/washingtontrails/wta_buildout/commit/daaa78147c03b72ecea9d38775dba399410cc5d6

Assigning this to David for now.

**Comment by davisagli** [comment]
We'll need to add a Spam_Score__c field to Contact in the sandbox like Aaron did in production.

**Comment by WaBirder57** [comment]
This field has been added to the contact object in the .vms2 sandbox.

I created Spam Score custom Number fields for both Contacts and Leads in the VMS sandbox to match the fields we added in production.  They are set to be Integers with a max length of 5 (as the spam scores only currently range from 0 to 17 according to Jesse).

**Comment by davisagli** [comment]
This also requires updating the vmslogin webservice in Salesforce to accept a spam score and add it to a contact if one is created. @mscholtz is it all right if I work on that?

**Comment by mscholtz** [comment]
Yep, just point me to the commit please when it's done.

On Wed, Oct 14, 2015 at 3:04 PM, David Glick <notifications@github.com>
wrote:

> This also requires updating the vmslogin webservice in Salesforce to
> accept a spam score and add it to a contact if one is created. @mscholtz
> <https://github.com/mscholtz> is it all right if I work on that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/317#issuecomment-148216750>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
This is in place on mybackpack.wta.org and the vms2 sandbox now.

@mscholtz https://github.com/washingtontrails/WTA-Salesforce/commit/92b34e47b45812f95c3b414aa5fbaf02b9b34c2b

**Comment by mscholtz** [comment]
Looks good to me!

On Thu, Oct 15, 2015 at 6:03 PM, David Glick <notifications@github.com>
wrote:

> This is in place on mybackpack.wta.org and the vms2 sandbox now.
>
> @mscholtz <https://github.com/mscholtz> washingtontrails/WTA-Salesforce@
> 92b34e4
> <https://github.com/washingtontrails/WTA-Salesforce/commit/92b34e47b45812f95c3b414aa5fbaf02b9b34c2b>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/317#issuecomment-148564435>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Excellent.  Spam, what a pain!
