### ISSUE TITLE
pyramid app is changing names of contacts in some circumstances

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#319]
placeholder for now, circumstances still under investigation
Ethan Scholtz used to be Jerome Scholtz used to be Matthew Scholtz

**Comment by davisagli** [comment]
Are you entering a new name into the registration form while logged in as an existing contact?

**Comment by mscholtz** [comment]
95% sure that's not it.

**Comment by davisagli** [comment]
Closing this since it's not actionable. Please reopen with info on how to reproduce the issue if you encounter it again.
