### ISSUE TITLE
Membership not reflected in fee for Volunteer Vacations

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#320]
From what I can see, someone who is marked a member in Salesforce is still prompted to pay the non-member price ($245) in VMS when they register for a Volunteer Vacation. The fee seems to be $245 for everyone.

**Comment by davisagli** [comment]
We need specifics so we can debug. Which contact did you try to register? Which work party? Were you logged in or not?

**Comment by ebskopin** [comment]
huh, scratch that, seems to be working as of my last test.

**Comment by davisagli** [comment]
Okay, well if you run into it again and want us to take a look, please provide the above info. It may be a specific case affecting some subset of work parties or users rather than a general problem.

**Comment by ebskopin** [comment]
Will do.  Thanks David.



*Elliott Skopin*
Volunteer Program Coordinator
Washington Trails Association
wta.org <http://www.wta.org/> l Facebook
<https://www.facebook.com/washingtontrails>
(D) 206-557-3406
(O) 206-625-1367

Help WTA celebrate 20 years of trail maintenance - Join a work party!
<http://www.wta.org/volunteer/trail-work-parties>
