### ISSUE TITLE
MBP: Registration form font should be same as current production

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#321]
The My Backpack Registration page: http://mybackpack.wta.org/@@register should use the same font (size and color) as the current production system: http://www.wta.org/@@register

This page was not designed by Ethical UX, we just assumed it would stay the same.

**Comment by davisagli** [comment]
This may be an unintentional change on our part, i.e. some styles that Ethical UX wrote for My Backpack that are applying a bit more broadly than intended now that they're active within the Plone site. We'll take a look.

**Comment by alecpm** [comment]
Looks like we can get rid of much of the form styling from mbp.css, since those are primarily coming from VMS or similar and aren't intended to be applied broadly within the MBP mockups.

**Comment by alecpm** [comment]
This change is deployed.  You may need to clear your browser cache or shift-reload.

**Comment by WaBirder57** [comment]
Looks better thanks.
