### ISSUE TITLE
MBP: Menu colors should be same as current production environement

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#322]
This is a change from the Ethical UX designs I think.

We would like the new MBP Menu to match our current production menu colors.

Our production Menu uses a gray/blue menu color, Orange for active menu and light orange/yellow for the active selected item on the pull down menu.
![productionmenucolors](https://cloud.githubusercontent.com/assets/8312206/10530215/10ad4818-735a-11e5-983f-65f1a64b47e6.JPG)

The current MBP development server has a different color blue, with the Gray/Blue for active selected menu item.  In the following screen shot you see how this blurs the pull down My Backpack selected item with the standard  Menu bar next to it.

![mbpdevmenucolors](https://cloud.githubusercontent.com/assets/8312206/10530228/533c9670-735a-11e5-9143-49d8b67a99dc.JPG)

**Comment by alecpm** [comment]
I see how this could be confusing, the designs didn't specify a highlight color for the top My Backpack menu items, but otherwise the current color scheme matches the designs:

http://wta.mybackpack.emptycan.com/profile/advanced/index-logged-in.html

Should we perhaps just change the top My Backpack menu item highlight color to the orange?  Or do you want to change that menu to match the color scheme of the navigation menu?

**Comment by alecpm** [comment]
I've made a quick tweak to use the orange highlight color on the dark blue menu.  Let me know if this works for you or if we should make it more similar to the nav menu.

**Comment by davisagli** [comment]
One thing -- notice that the My Backpack menu is orange when logged out but blue when logged in. I think it'd be a shame to lose that visual cue of whether you are are logged in or not.

**Comment by WaBirder57** [comment]
Loren reports:
Testers found the color behavior shift pretty jarring. 

David makes a good point, but I think the icon-to-profile image is enough of visual cue, and we've not had any problems with folks knowing whether they are logged in or not with the current static nav. 
If it becomes a problem, we have the solution mapped out for us. 

So lets stick (change to) with the Orange menu for MBP using the lighter active menu choice color.

**Comment by davisagli** [comment]
I've updated the colors for both Plone and the pyramid app. You might need to force-reload or clear your cache.
