### ISSUE TITLE
MBP:  Hyperlinks on WTA web should not have underlines - they appeard on Hike Names in some locations

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#323]
We should removed the underline from HikeName Hyperlinks.

If you go to your My backpack, look at Trip Reports and Click on a trip report.  The view of that Trip report opens with the Hike Name Underlined.

![trwithhikeunderlined](https://cloud.githubusercontent.com/assets/8312206/10530318/67efdc20-735b-11e5-9cb1-5eaac64ccca8.JPG)

This same Underlined Hike name is visible if you:
From the hiking guide open a hike.  Click on a trip report to open the detail of that Trip Report.  Screen shot is similar to the above.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Excellent!

**Comment by WaBirder57** [comment]
These underlines are showing up again.

Go to any users My Backpack, click to look at their Trip Report.
Click on a Trip Report to view details.
The Trip report details shows the Hike Name (hyperlink) with an underline.

**Comment by davisagli** [comment]
Not for me. Try clearing your cache and/or force-reloading the page.

**Comment by WaBirder57** [comment]
I stand corrected after clearing my browser cache and restarting this is displaying correctly.  Sorry about the false alarm.
