### ISSUE TITLE
MBP: Side Menu change section names in include "My".

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#324]
The My Backpack menu sections should be renamed to include "My" in 3 places.  This will be:
My Trip Reports
My Hikes
My Work Parties

![mbpsidemenu](https://cloud.githubusercontent.com/assets/8312206/10530394/767bd2fc-735c-11e5-9260-644fca8c7247.JPG)

User testing should users were confused and this should clarify this for them.

**Comment by davisagli** [comment]
But not if you're looking at a different user's backpack, right?

**Comment by WaBirder57** [comment]
Good point, I will have more on this tomorrow.

**Comment by davisagli** [comment]
I made this change for when users are looking at their own backpack; not when they are looking at others. I also noticed that when looking at another user's backpack, the Hikes and Work Parties links showed up even if they are not public; that's fixed too.

**Comment by WaBirder57** [comment]
Ah that is good and you added the owners name to the top.  I see that since Trip Reports are always public that the UI is different when I look at someones Trip Reports V Saved Hikes.

When a non-logged in user looks at My Backpack (http://mybackpack.wta.org/@@backpacks/scrnm-Charlie%20Kahle%20WTA) they can click on Hikes to see those with this new Sidemenu.  Looks good although my name is too long so that wraps funny.  Also I don't see the corresponding SideMenu option for Trip Reports.  Seems like this should be there for consistency.

When I look at the Trip Report tile, then I see the list of Trip Reports in that Backpack but the side menu isn't there.  I think it should be.

**Comment by davisagli** [comment]
> Looks good although my name is too long so that wraps funny. 

That's going to be a bit tricky to fix since the design assumes the header has a fixed height.

> Also I don't see the corresponding SideMenu option for Trip Reports. Seems like this should be there for consistency.

An oversight on my part; fixed.

> When I look at the Trip Report tile, then I see the list of Trip Reports in that Backpack but the side menu isn't there. I think it should be.

When you click to see a different user's trip reports, we agreed it should take you to the main trip report search rather than My Trip Reports. So you're no longer in the My Backpack section.

**Comment by WaBirder57** [comment]
Regarding the last point on the TR List in My Backpack directing the user
back to a filtered list of Trip Reports in the TR section...

How many Trip report lists are there?  Loren is working on designing these,
are there 2 or 3 locations this is used, she is trying to describe the
variations on showing regions, maps, user names, etc.:
1) - Trip Report Section
2) - List under a give Hike
3) - My Backpack list of a users TR

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by davisagli** [comment]
That's the correct list of locations. When you're looking at your own backpack and click on My Trip Reports it takes you to the 3rd one, but if you're looking at someone else's backpack and click on Trip Reports it takes you to the 1st one with a search for only that user's trip reports.

**Comment by WaBirder57** [comment]
The side menu now includes "My" as requested.
