### ISSUE TITLE
MBP: MBP Side Menu subsections should be hidden unless user is in that part of MBP

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#325]
When a user is in MBP the side menu should collapse to only show the main menu choices unless they are in that section of MBP.  This only currently is illustrated with My Work Parties or Crew Leader Corner.

We don't want the average user to be confused by seeing "Forms" under Work Parties when they are looking at their My Hikes as an example.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Looks good.
