### ISSUE TITLE
MBP: Save Hikes filter should show three options

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#326]
When a user is looking at their My Hikes the drop down option to filter the list should include 3 options:
All Hikes
Hiked
Want to Hike

Currently this shows:
Saved Hikes
Completed Hikes

I think what should be displayed for each of these filter settings is self evident but please ask if there are questions.

![myhikeslistfilteroption](https://cloud.githubusercontent.com/assets/8312206/10530506/6ccc5faa-735d-11e5-8514-eea9ecd232b1.JPG)

**Comment by davisagli** [comment]
So "Want to hike" is the hikes that have been saved but not completed?

**Comment by WaBirder57** [comment]
Yes, that is correct.

**Comment by davisagli** [comment]
Done

**Comment by WaBirder57** [comment]
Looks nice.
