### ISSUE TITLE
MBP: Edit Profile Instagram fields needs "@" symbol

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#327]
The Edit Profile Screen of MBP field for Instagram should include the "@" symbol as does the Twitter field.

![mbpprofileinstagramfield](https://cloud.githubusercontent.com/assets/8312206/10530569/de19fd2a-735d-11e5-8a0e-231f7309aa60.JPG)

**Comment by alecpm** [comment]
Should be fixed.

**Comment by WaBirder57** [comment]
Looks good
