### ISSUE TITLE
MBP: Edit profile Birth Date date picker for iOS

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#328]
In MBP when you are editing the logged in users Profile the Birth Date field has a date picker to help enter a correctly formated Birth Date.  This works for web browsers from a desktop and Android phone.  How ever on iOS when editing this date field the user is presented with the full keyboard to enter the date.  Can we hook up an iOS date picker for this platform?

**Comment by davisagli** [comment]
Did you work on this one @alecpm?

**Comment by alecpm** [comment]
This should be fixed now.  Browsers (like iOS Safari) with native date picker support should use the native date picker.

**Comment by ebskopin** [comment]
This works.
