### ISSUE TITLE
MBP: What is the green "Public" icon for on the MBP

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#329]
What is the Green "Public" icon for in the MBP just under the users images? 

![mbppublicicon](https://cloud.githubusercontent.com/assets/8312206/10549567/ae0e3184-73f6-11e5-8bbb-ab85a917f7ac.JPG)

**Comment by davisagli** [comment]
Not sure...just a reminder that this page can be viewed by other users I guess? We copied it from the design mockups.
