### ISSUE TITLE
MBP/VMS: My Backpack Tile for Work parties doesn't display

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#330]
Logon to MyBackpack.wta.org.  View your MBP Dashboard.  There is no Work Party tile or My Work Party, or Crew Leader Corner option on the side menu.

**Comment by davisagli** [comment]
@alecpm did you do a deploy using ansible? You probably need to update so that it runs mybackpack_dev.cfg instead of staging.cfg (the former has VMS features enabled and the latter does not).

I'll fix it.

**Comment by davisagli** [comment]
Fixed; Charlie, you were seeing My Backpack as it's meant to work once we deploy to staging.wta.org

**Comment by WaBirder57** [comment]
Right, it is back working now.  Also good to verify that the code for MBP to launch before VMS is working.
