### ISSUE TITLE
MBP: Side Menu overlaps main drop down menu when in Hikes, Trip Reports or Work Parties

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#331]
The attached screen shot shows how the top right square "barred" part of the green MBP side menu displays over the main (top) drop down menu. This should not display over the drop down menu.

![mbpmenuoverlap](https://cloud.githubusercontent.com/assets/8312206/10584781/d6d3efc4-7648-11e5-8990-5ddf605b7034.JPG)

**Comment by davisagli** [comment]
Only admins see enough menu items to make it overlap, so this is probably not high priority. Shouldn't be hard to fix though.

**Comment by davisagli** [comment]
Should work now if you reload.

**Comment by WaBirder57** [comment]
It is better now but now we can see that the right edge of the drop down menu is not inline with the top menu box.  Looks like the drop down top Mybackpack menu is about 1px to narrow.  See if this is evident in this screen shot.

![mbpmenuoverlapaverageuser2](https://cloud.githubusercontent.com/assets/8312206/10586869/4b1b683a-7653-11e5-92f5-a37abd42b3ba.JPG)

**Comment by davisagli** [comment]
Fixed (there was a 1px right border on the My Backpack button)

**Comment by WaBirder57** [comment]
Looks good.
