### ISSUE TITLE
VMS: Group work party Docusign Group MOU Error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#333]
When you click the "Send MOU" button on a Work Party Group (for example: https://cs9.salesforce.com/a2yK0000000BwB4 ) you get the following Error:

![docusignerrorgroupmou](https://cloud.githubusercontent.com/assets/8312206/10592099/be37684e-766e-11e5-836e-eaac28821098.JPG)

**Comment by mscholtz** [comment]
I verified this issue is occuring for me as well.
@davisagli or @ninetaLogik you both worked on the docusign stuff, yes?  Which of you should take this on?

**Comment by davisagli** [comment]
I did not work on the MOU story.

**Comment by mscholtz** [comment]
@ninetaLogik can you take a look?

**Comment by davisagli** [comment]
Who was testing this? The button does work for me so I suspect you need to set up the Salesforce user as a Docusign user.

In Salesforce switch to the "Docusign for Salesforce" app, go to the Docusign Admin tab, and click on Users. In the list of "DocuSign Inactive Users", select the user you want to activate and click the "Add Users" button.

**Comment by mscholtz** [comment]
Ah.  @ebskopin can you look into this and see if that solves it?

**Comment by ebskopin** [comment]
This worked once I had set-up the Docusign user as was recommended.  thanks
