### ISSUE TITLE
VMS: Group Work party capacity should hold slots in WP and also shows ACL needed

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#334]
For a Group Work party we need to have the number of slots for the Group Capacity saved so that others (in public work parties) can't take those spots.  

Also, for Private or Public group work parties if the slots have been saved for a group (even if we don't know the specific names of the volunteers yet) we need to show that we need ACL's, based on the size of the group so that ACL will know they are needed even before we know all the names of the volunteers from the Group.

**Comment by mscholtz** [comment]
@WaBirder57 @ebskopin are we sure we want to hold aside the entire group capacity?  When we were working on this, it wasn't clear that the group would always take all of those spots.  If the group doesn't fill them all, but we're holding them aside, then the public can never take those spots.

Depending on your answer to that, I'll address the ACL thing.

**Comment by ebskopin** [comment]
Group work-parties can either be open to the public or private.  In the instances that they are private we can safely "reserve" all slots for the group and the WP should only be open to ACL registrations.  For open to the public group work parties some number of slots (say 10 of 20) would be saved for the group and 10 would be available for the public, with registration available to ACLs to regardless. We occasionally shift the number of slots reserved if the group expands or contracts.

**Comment by mscholtz** [comment]
@ebskopin ok, and you're saying that those slots to hold aside in the public WP case (the 10-20) would be the same number as the group capacity?

**Comment by davisagli** [comment]
IIRC, currently when someone registers we check that it doesn't put the work party as a whole over capacity, and if the registration is associated with a group we check that it doesn't put the group over capacity. It sounds like we also need a check for non-group registrations to make sure that enough spots are remaining to fulfill the group capacity.

**Comment by mscholtz** [comment]
@davisagli we'll handle it on the SF side

**Comment by davisagli** [comment]
@mscholtz sorry yeah, by "we" I meant "the registration trigger code in Salesforce"

**Comment by mscholtz** [comment]
OK, gotcha.  Yes, that is what we're saying.  FWIW, I'm planning to work it into the capacity calculations, so the registration trigger shouldn't need updates.

**Comment by ebskopin** [comment]
Correct.

**Comment by davisagli** [comment]
>  I'm planning to work it into the capacity calculations, so the registration trigger shouldn't need updates.

Hmm, okay...just make sure you don't break registration of group members.

**Comment by mscholtz** [comment]
This should be working now.  @ebskopin over to you for review.

**Comment by ebskopin** [comment]
This is working.
