### ISSUE TITLE
VMS: WP with Reguired forms - auto un-check "allow guest registration"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#335]
When a Work Party Type has required documents other than Parent Release auto Un-check the Allow Guest Registrations field.  We will not allow guest registrations for WP Type that have these other required documents so this is just a check that this field is set correctly.

**Comment by mscholtz** [comment]
@drewpiston could you work on this one?

**Comment by mscholtz** [comment]
@drewpiston I think we would also want validation so if the WP already has required docs assigned, it won't allow checking the Allow Guest Reg box

**Comment by drewpiston** [comment]
On it.

**Comment by drewpiston** [comment]
Ready for review!

**Comment by ebskopin** [comment]
This seems to be working correctly, as when I attempt to click the "Allow Guest Reg" box I was alerted to the fact that the work-party type does not allow it. Regarding how this manifests on MBP, these work-parties will still allow 1 guest (spouse/partner) to be registered but no more, correct?

**Comment by davisagli** [comment]
In our system's terminology a spouse/partner is not a guest. A guest is a user who is not logged in. A spouse or partner is "friends/family". The number of friends/family allowed is controlled by the "Max Friends/Family" field.

**Comment by ebskopin** [comment]
Gotcha, then this is good.
