### ISSUE TITLE
VMS/MBP:  MBP Work Party Summary should show WP Name

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#336]
Attached is a screen shot of the WP Summary list.  The WP Name should be included before the date.

![wpsummaryreportsneedwpname](https://cloud.githubusercontent.com/assets/8312206/10614208/d0946d6c-770d-11e5-9a63-e859e84bcad3.png)

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Thank you
