### ISSUE TITLE
VMS: Volunteers Needed tool tip (pop up text) should read "Extra Volunteers Needed"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#337]
When a user mouses over the Green Hat icon in the WP List view indicating that we want to draw attention to a work party the tip that shows in the text pop up should read "Extra Volunteers Needed", currently it reads "Volunteers Needed".

![extravolunteersneededtip](https://cloud.githubusercontent.com/assets/8312206/10614878/7bb171ba-7711-11e5-9d97-2b31a50808f2.png)

**Comment by davisagli** [comment]
fixed

**Comment by WaBirder57** [comment]
Looks great.
