### ISSUE TITLE
VMS: WP payment screen layout for iPad

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#340]
Tiffany reports this issue with the WP Payment screen on iPad:

I just tried to sign up for White Bluffs on my iPad and couldn't find a way to actually make the pretend credit card payment. I tried Firefox and the button showed up but chrome and iPad didn't provide me with a pay now button. 

(Also, the expiration and code Info on the payment page looked a bit weird on my iPad in portrait mode--picture attached) 

![ipadviewofpmtscreen](https://cloud.githubusercontent.com/assets/8312206/10622989/f2eba466-773f-11e5-8a96-1d445b04f2f3.png)

**Comment by davisagli** [comment]
Both should work better now. If it doesn't look any different you might need to clear the mobile Safari browser cache in system settings.

**Comment by WaBirder57** [comment]
Tiffany says it is better.  However, test with any payment for a WP and the "Pay Now" button doesn't show on iPad or iPhone.  (perhaps hidden behind time remaining bar)

**Comment by davisagli** [comment]
I moved the time remaining bar so it's just below the step 1/2/3 header, so if you're still seeing it at the bottom you have an old cached page.

**Comment by WaBirder57** [comment]
@davisagli Does the Time remaining bar float over the content of the page?  When the browser window is sized so it is not tall enough, the Pay Now button is hidden by this floating bar.  I think that is confusing folks and they can see the "Pay Now" button (unless the think to try the vertical scroll bar).  I think this is impacting mobile devices as those screens are smaller and scrolling may not be obvious.

**Comment by davisagli** [comment]
It was floating, but I fixed that a couple days ago.

**Comment by WaBirder57** [comment]
Well this is frustrating...
Tiffany just did a screen share to show me her Chrome browser and how the Time remaining Bar is static/fixed but is on top of the Pay Now button.  changing the size of the browser window gives you a vertical scroll bar but that doesn't reveal the Pay Now button.

However on my computer with Chrome the time remaining bar is locked at the bottom of my browser window.  When I scroll the page up and down the Pay Now button become visible if i scroll it up.  I have tried all kinds of clearing cache etc (also in iPad) as has Tiffany and we both have different experiences.  I will study this more to see if I can give you better info on how to reproduce.

I will let this

**Comment by davisagli** [comment]
How about now? I'm sorry, when I made the fix the other day I did it in the wrong file and it didn't make it onto the server. I just tried it in Safari on the ipad and it worked okay.

**Comment by WaBirder57** [comment]
This looks much better. @davisagli however the security code field on my iPad is to narrow to see 3 digits. Can this be positioned closer to the card expire month and date fields to give it room to be wider?

I LOVE the new position for the Time Remaining banner.  Great idea.
