### ISSUE TITLE
VMS: Multiday WP Edit hours only shows one day rather than each day of WP to enter Hrs

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#342]
As a CL when wants to enter the hours worked for a multi day work party the Edit Hours button on the Report tab opens up the pop up for this.  However, only one day is shown (see attached).  There should be (and there was before) a column available for each day of the work party with a row for each registered participant.  Here is a link to a work party which shows this problem http://staging.wta.org:6543/workparty/a2eK00000000iUN/

![mulitdaywphrseditshowsonlyoneday](https://cloud.githubusercontent.com/assets/8312206/10651225/231b6d38-7803-11e5-8c03-42de757914b5.JPG)

**Comment by davisagli** [comment]
Fixed, this was another accidental side effect of the switch to showing start/end times in addition to dates.

**Comment by WaBirder57** [comment]
Looks good.
