### ISSUE TITLE
VMS: WP Edit Hours should show hours entered for each Volunteer for each day if already entered

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#343]
When a CL on the Report Tab for a Work party wants to "edit" the Hours Work they should be able to click the Edit button to review the data that has already been entered for each volunteer, for each day.  Currently if hours worked has been entered and saved, these values are not shown again if the CL again clicks on Edit Hours, rather they show 0 for hrs worked.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Thanks, showing each day now.
