### ISSUE TITLE
VMS: Work Party list should not list work parties either 2 or 5 days before start date

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#346]
On the Find a Work party list, work parties should not be displayed if they are close to starting.  For One Day or Two Day work parties, they should not be displayed 2 days prior to the start date.

For longer work parties (typically Volunteer vacations, BCRT's etc) they should not be listed 5 days prior to the start date.

**Comment by davisagli** [comment]
Sounds like a new story -- that hasn't come up before, has it?

What if the user has explicitly chosen "this week" or a custom date range that includes the next 2-5 days?

**Comment by davisagli** [comment]
What's the motivation for this? i.e. what's the "so that I can Z" part of the "as an X, I can Y, so that I can Z" user story format?

**Comment by WaBirder57** [comment]
@ebskopin I would have to dig up the reference to this in the discovery process.  Basically the motivation for this is that Work Parties need lead time for planning.  Day Work (or weekend) parties 2 days, longer work parties need 5 days.  Custom Date range selection should still honor this black out period and not show work parties that fall in this range.  Any additional ACL's that are needed during this black out period would be manually added by staff via Salesforce.

**Comment by davisagli** [comment]
Yes, but you don't know that users are searching for the purpose of registering. They might be trying to find a work party that's happening tomorrow so that they can see the directions and other info.

**Comment by davisagli** [comment]
If the goal is to keep people from registering too close to the start of a work party, we should implement that, not hide work parties from the search.

**Comment by WaBirder57** [comment]
Yes, you are correct.  Goal is to keep folks from registering.  Lets implement that as you suggest.  Great idea, thank you.

**Comment by davisagli** [comment]
Do you need to be able to override this registration cutoff period for particular work parties, or is it enough to have a number of days configured on the Work Party Type?

After the cutoff should people be allowed to join the waitlist, or not sign up at all?

Does this new feature have any correspondence with the existing Work Party Type setting for "Waitlist Volunteers Window" which controls the time at which volunteers will be waitlisted if there aren't enough ACLs?

**Comment by ebskopin** [comment]
The number of days can be configured on the work party type. It will generally be 2 days prior for day WPs and 5 days for Backcountry trips (VV, BCRTs, YVV etc).

I would say that registration should be cut-off, even for the waitlist. 

I'm not sure about the correspondence between this and the waitlist volunteer window.

**Comment by davisagli** [comment]
> The number of days can be configured on the work party type.

You mean that you want us to add a field for that, not that one already exists. Right?

**Comment by ebskopin** [comment]
Correct, it would be a new field as there is no field (as far as I know) for WP type that presently dictates when a WP should close for registration.

**Comment by skleinfeldt** [comment]
This is now story 323. @ebskopin if that looks OK please close this ticket.

**Comment by ebskopin** [comment]
Closing. Now represented by story 323.
