### ISSUE TITLE
VMS: Work party registration with required forms add language to Friends/Family sign up

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#347]
When a volunteer is signing up for a Work Party that requires forms they can also include a registration for a Friend or Family member.  This person will also need to complete these required forms and we should mention this on that part of the registration form.

"You may register yourself and a spouse or partner.  Each participant will need to complete the required forms accessed through My Backpack.  Otherwise each individual needs to register himself/herself."

![volvacfriendssignupincludemorelanageonformsneeded](https://cloud.githubusercontent.com/assets/8312206/10736738/d3943764-7bcb-11e5-97e8-9f7339a6ebb0.JPG)

**Comment by davisagli** [comment]
We already made this help text configurable as part of the Work Party Type. Edit the "Friends/Family Help Text" field on the work party's Work Party Type.

**Comment by ebskopin** [comment]
Thank-you for pointing this out, David.  Closing this story.
