### ISSUE TITLE
MBP/VMS - My Backpack Menu title wraps

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#348]
When a user logs into VMS the My Backpack menu wraps as shown in the screen shot below.  The "MY" is in the Menu but the "Backpack" wraps and is displayed over the background image.  If the drop down menu is displayed this wrapped text disappears.  When the screen size is reduced is it possible to reduce the size of the font so that menu text doesn't need to wrap?  Not sure what the best approach is to these situations.

![mybackpackmenuheadingwrap](https://cloud.githubusercontent.com/assets/8312206/10737365/fa7e826e-7bce-11e5-9626-0b724d23657d.JPG)

![mybackpackmenutrucation](https://cloud.githubusercontent.com/assets/8312206/10737299/a3c684f8-7bce-11e5-8a49-54f03495c37b.png)

**Comment by davisagli** [comment]
Which browser is this?

**Comment by WaBirder57** [comment]
Firefox and also reported in Chrome.  Works OK in Internet Explorer.

**Comment by davisagli** [comment]
And are you seeing it on VMS (http://staging.wta.org:6543), Plone (http://mybackpack.wta.org) or both?

I'm not seeing it, so another possibility is that Chrome & Firefox are rendering the font slightly differently on Windows vs OS X.

I'll try to make the button slightly wider or able to adjust to the width of what's inside it, but it'll be easiest to get right if I can reproduce the problem.

**Comment by WaBirder57** [comment]
This is just for staging.wta.org:6543   .

**Comment by davisagli** [comment]
How does it behave now? I haven't been able to reproduce the issue, but I changed the space between the two words to a non-breaking space so the browser should not add a line break there now.

**Comment by WaBirder57** [comment]
Seems to have fixed the problem.  Thanks.
