### ISSUE TITLE
VMS: When a WP is full we should not display how many slots there are left (a negative number)

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#349]
In the find a work party list view we should not show the number of spaces available if the WP is full.  Currently the system is showing a negative number if there is a wait list and this is confusing.  We think we should just not show the number of slots anymore once the WP is at capacity.

![wplistshowsnegativeslotswhenwaitlist](https://cloud.githubusercontent.com/assets/8312206/10738035/9e4a2256-7bd2-11e5-9ba5-1fbab510af40.png)

**Comment by davisagli** [comment]
Should we show the number of people on the waitlist instead?

**Comment by WaBirder57** [comment]
Yes, lets do that. For a work party that is full in the Find a WP list view show the number of volunteers on the wait list.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
Works. Excellent.

**Comment by davisagli** [comment]
Reopening this because we should also do this on the detailed work party view, e.g. http://staging.wta.org:6543/workparty/a2eK0000000wbal/

**Comment by davisagli** [comment]
Fixed on the work party details page too.

**Comment by ebskopin** [comment]
works
