### ISSUE TITLE
VMS: Volunteer Detail view missing WP dates

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#351]
In VMS when a Crew leader looks a the roster and clicks on a volunteer a detailed view of that volunteer is displayed.  On this, the list of prior work parties doesn't display the dates of the work parties.  That column is blank.

![volunteerdetailviewmissingwpdates](https://cloud.githubusercontent.com/assets/8312206/10738442/bd6d73a2-7bd4-11e5-8c8a-325067421f12.png)

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Great.
