### ISSUE TITLE
VMS: Find a Work party list shows a place holder ad for more information

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#352]
Per the prototype design: http://07.wta.emptycan.com/volunteer/ there is a space near the top of the list of work parties with a banner like "ad" for a visitor to get more information on what a Work Party is and click through to additional information.

I don't think this ever got implemented or perhaps a story never generated for this.  Is this feature hard to implement?  Can we have the content (text and image) editable by staff, change change based on the season?

![findawpbannerad](https://cloud.githubusercontent.com/assets/8312206/10739186/3cd52f2e-7bd8-11e5-8520-fcfbc5c2d96a.JPG)

**Comment by skleinfeldt** [comment]
@WaBirder57 you're right, I don't think we ever wrote a story for this. It reminds me of story 138, MBP Crew Leader corner (where staff can create a new CL message and image) - except this is in VMS, not MBP.

**Comment by WaBirder57** [comment]
Can we add this to our check in this afternoon.  I guess my question is crafting a story/ticket for this so we can capture this functionality.  Kind of like #138 but I think simpler in that is it just an image with hyperlink.  WTA staff can change the image (with embedded text) from time to time. I just don't know how hard this is with Pyramid.

**Comment by skleinfeldt** [comment]
This is now story 324. @ebskopin if that looks OK please close this ticket.

**Comment by ebskopin** [comment]
Closing. Now represented by story 324.
