### ISSUE TITLE
VMS: Crew Corner message board - where did this go?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#353]
I thought we had implemented the Crew Corner message board as a way for the crew leader to send messages to the full crew and have a record of the messages show in the WP Crew Corner tab.

See the design: http://07.wta.emptycan.com/volunteer/details/crew-corner/cl/

**Comment by davisagli** [comment]
It got accidentally disabled due to a faulty permission check. Fixed.

**Comment by WaBirder57** [comment]
Yea, it is back!
