### ISSUE TITLE
MBP: My Hikes page format changes

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#354]
In the My Backpack - My Hikes page here are some subtle changes to the design to make these consistent with the rest of the site.

1) Font change: change the region font to light grey (#99999)
![mbphikeregion-subregionfont](https://cloud.githubusercontent.com/assets/8312206/10742788/3870369a-7bec-11e5-86ba-dda34fcbef5c.JPG)

2) Love the new "Hiked" state (green outline and check). Is great. Thank you!!

3) On the pop-up box prompting people to write a new trip report, remove the "No, thanks" text and put small, standard X close icon in the top right of the box. 

![mbpwriteatrpopup](https://cloud.githubusercontent.com/assets/8312206/10742806/54dad9de-7bec-11e5-940f-6b0200542d13.JPG)

**Comment by davisagli** [comment]
Done. You might need to force-reload for uncached styles.

From now on I'll deploy My Backpack fixes to staging.wta.org, and not necessarily update mybackpack.wta.org unless you ask for it.

**Comment by WaBirder57** [comment]
These changes look as we described.  I will check with Loren on the new big Write a Trip Report button.
