### ISSUE TITLE
MBP: Dashboard design tweeks

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#355]
For the My Backpack Dashboard we have 2 tweaks:
1) Delete: the mysterious "Public" button
2) Text change: "Completed" to "Hiked" under the My Hikes tile. 
![mbpdashboard](https://cloud.githubusercontent.com/assets/8312206/10742906/fb49fe1c-7bec-11e5-8ae7-8efad076b6d2.JPG)

**Comment by davisagli** [comment]
done

**Comment by WaBirder57** [comment]
Great, thanks.
