### ISSUE TITLE
MBP: My Trip reports display

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#356]
For a user logged in, on their own My Backpack Trip Report List make the following design tweaks:

1) Delete the thin grey horizontal rule within a report
2) In the Highest Upvote box, combine the total upvote title and count on one line: TOTAL UPVOTES: 1
3) Remove the option to delete a trip report from this list display.

![mbpmytrlist](https://cloud.githubusercontent.com/assets/8312206/10743134/72867ec8-7bee-11e5-967f-af7f8c1c4d1d.JPG)

**Comment by davisagli** [comment]
done

**Comment by WaBirder57** [comment]
Looks good.
