### ISSUE TITLE
MBP: Main Trip report list design tweaks

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#357]
- [x] Remove the tabbed List/Map display and restore the pagination (100 per page)

![mbptrlistpagination](https://cloud.githubusercontent.com/assets/8312206/10743686/0377a800-7bf2-11e5-8a59-e889d76540a3.JPG)

- [x] Restore the region - subregion (in grey) [See above screen shot]

- [x] Restore the spacing for the "Beware of..." text (still drops to it's own line on a responsive display.   This text should be indented so it doesn't appear adjacent to the icon's.
![mbptrbewareindentation](https://cloud.githubusercontent.com/assets/8312206/10743750/5e53c31c-7bf2-11e5-8c24-fdbdb4881db2.JPG)

- [x] Fix the font size for the expanded trip report text (looks too large), should match current production font.
![mbptrexpandedtexttolarge](https://cloud.githubusercontent.com/assets/8312206/10743879/2a305518-7bf3-11e5-8423-7ac636b623ba.JPG)

- [x] Delete the light grey horizontal rule within a report (per My trip reports)[see below]
- [x] As a logged in user viewing my own trip reports in this list, delete the option to either edit or delete from this list display. [see below]
- [x] Text change: "Useful" to "Helpful" on the "2 PEOPLE FOUND THIS REPORT HELPFUL" text. 

![mbptrexpandededittrremove](https://cloud.githubusercontent.com/assets/8312206/10743907/55580358-7bf3-11e5-9973-cd4e511e1e83.JPG)

**Comment by davisagli** [comment]
Done

**Comment by WaBirder57** [comment]
Looks good.
