### ISSUE TITLE
MBP: Hiking guide Trip Report List design tweaks

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#358]
For the Trip Report List under a Hike (these are very similar to the changes with screen shots described in Ticket #357 )

- [x] Remove the tabbed List/Map display and restore the pagination (5 per page)
- [x] Restore the spacing for the "Beware of..." text (still drops to it's own line on a responsive display. 
- [x] Fix the font size for the expanded trip report text (looks too large)
- [x] Delete the light grey horizontal rule within a report (per My trip reports)
- [x] As a logged in user viewing my own trip reports in this list, delete the option to either edit or delete from this list display. 
- [x] Text change: "Useful" to "Helpful" on the "2 PEOPLE FOUND THIS REPORT HELPFUL"

**Comment by davisagli** [comment]
done

**Comment by WaBirder57** [comment]
Great!
