### ISSUE TITLE
VMS: Waitlist confirmation pop up doesn't also cancel the friend and family registration.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#359]
When signing up for a work party with one slot left, if i also register a "+1" friend I will get the red pop-up to confirm that i want to join the wait list.  If I cancel at that point, the primary person's registration is marked "canceled" but the +1 friends registration is still marked Waitlisted.

I would expect that "canceling" at this point would cancel both registration records.

Here is Julie's bug report with screen shots:

BUG - I was signing up myself and a +1 for a work party. Let's say I did not notice that there was only 1 spot remaining. After I click, "Register," I get the red box saying "We have added you to the waitlist," with the options to either say ok or cancel registeration (http://prntscr.com/8v0myb). When I select, "cancel registration," it only cancels my registration, and my +1's status is "waitlisted." My +1 should also be cancelled.
THis screenshot shows that I'm cancelled, but my +1, at the top, is "waitlisted." http://prntscr.com/8v0nym

**Comment by ebskopin** [comment]
Per Julie: "I just retested this. It cancelled both registrations in SF, which is correct, but I still got an email telling me I'm on the waitlist. I should not have received that automatic email. 1) This is the screen where I declined being added to the waitlist: http://prntscr.com/99z9eg (I clicked cancel registration), 2) In SF, it correctly lists me as "cancelled," not "waitlisted."

**Comment by davisagli** [comment]
It adds you to the waitlist immediately, which triggers the email. If you click cancel it then cancels the registration. This is what we discussed back when we implemented waitlisting and it'd be a rather big change to not actually add their registration until they click Ok.

**Comment by ebskopin** [comment]
gothca, makes sense
