### ISSUE TITLE
MBP: Trip Report Comment displays Code instead of authors screen name

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#360]
In MBP when you post a comment to a trip report that comment is displayed at the bottom of the trip report.  Where it says "Posted By" you instead see code (see screen shot).  Note that I did tick yes to be notified if anyone else made a comment.

![mbptripreportcommentcodedisplay](https://cloud.githubusercontent.com/assets/8312206/10764388/26e5767a-7c8b-11e5-9294-73809146e95f.JPG)

**Comment by davisagli** [comment]
Fixed. This was a hard-to-track-down bug in caching that was added related to the switch from showing user ids to screen names. @jessesnyder you might want to cherry pick this fix to master.

**Comment by davisagli** [comment]
Turns out the problem was due to something we added for My Backpack, not something that's on the production site. So we're all set now.

**Comment by WaBirder57** [comment]
Good trouble shooting, working now.
