### ISSUE TITLE
MBP: Hiking Guide Hike Icon list is vertical not horizontal

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#363]
On staging.wta.org when looking at the Hiking Guide list of hikes (Find a Hike, Hiking Guide) the icon's that represent the hike's features are lined up vertically not horizontally as they are on the production server.  Compare the two screen shots to see the difference.

![mbphikingguideiconlist](https://cloud.githubusercontent.com/assets/8312206/10772613/3a6c4718-7cb4-11e5-8073-3d3b543dad73.JPG)

![mbphikingguideiconlistproduction](https://cloud.githubusercontent.com/assets/8312206/10772616/3c42ef42-7cb4-11e5-939a-572e63355a07.JPG)

**Comment by davisagli** [comment]
Fixed. Also added tooltips on mouseover like we added for these icons on trip reports.
