### ISSUE TITLE
VMS: Crew Corner Tab - list should show only the logged in volunteers information.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#364]
Currently when a Volunteer who has signed up for a work party looks at the Crew Corner Tab of the Work Party the see the following:

![vmscrewcornertab](https://cloud.githubusercontent.com/assets/8312206/10773224/607cbe1c-7cb7-11e5-9508-189b44b4a23b.JPG)

This should be changed to show:
1) Don't list the CL, they are listed above so don't need to show the volunteer the CL again.
2) Show the Volunteer (currently the logged in registered Volunteer doesn't see their own name.)
3) Show the Volunteer's +1 if any
4) For Car Pool this should show everyone who is interested in car pooling.

**Comment by davisagli** [comment]
Which work party and user is the above screenshot from?

**Comment by WaBirder57** [comment]
http://staging.wta.org:6543/workparty/a2eK0000000wbav/  The User is with email address: wabirder57@live.com  screen name WaBirder

**Comment by davisagli** [comment]
1 - I made this change.
2 and 3 - These were working before but got broken; should work again now.
4 - To see other carpoolers, the volunteer must change their own carpool preference to indicate interest in carpooling. Maybe we need help text to that effect?

**Comment by ebskopin** [comment]
looks good.
