### ISSUE TITLE
VMS: Crew Corner tab for Group leaders

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#365]
Group leaders have their own view of the Crew Corner Tab: http://prntscr.com/8uxuzc (also attached screen shot) This should not include the CL (again, it's redundant) nor ACL's, nor the statement at the bottom, "5 Registered Volunteers." They should only see the people they signed up. 
![vmscrewcornerforgroup](https://cloud.githubusercontent.com/assets/8312206/10773365/3f8f1ba4-7cb8-11e5-953e-14c4fb87ab8e.png)

**Comment by davisagli** [comment]
Being a group leader only gives you access to see registrations in your group, but users with a permission level of Assistant Crew Leader, Crew Leader, or Admin can also see the work party's crew leader and assistant crew leaders (as requesteed in #238). I assume the above screenshot is from the group leader for the Helio Sequence group, "Seymour Mountains," who has a permission level of Assistant Crew Leader. https://cs9.salesforce.com/003K0000012FBqh

**Comment by ebskopin** [comment]
working
