### ISSUE TITLE
VMS: Email invitation to join WP has links the return an error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#367]
From the waitlist invite email, the following links results in an error: 
Accept the invitation: 
http://staging.wta.org:6543/workparty/a2eK0000000wZT8/confirm?r=a2oK0000000mRTl

The blank white error page says this: {"code": 500, "detail": "u'a2oK0000000mRTl'", "title": "KeyError"}
The decline link results in the same error. 

Here is a link to the screen shot of this email invitation: http://prntscr.com/8v0yge

**Comment by mscholtz** [comment]
@davisagli can you look into this one?  The registration had been moved to Cancelled, but I switched it back to Invited from Waitlist, and am still getting this error on that URL

**Comment by davisagli** [comment]
This works now. Missed converting 18-char ids to 15-char ids to match the id in the URL.

**Comment by ebskopin** [comment]
Looks good.
