### ISSUE TITLE
VMS: Story #95 - Landmanager Summary reports from VMS WP Reports Tab.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#371]
As Julie Reports:

BUG - For Land Manager, it's getting stuck on "Loading," after clicking Reports. From the Reports tab, when you click on "See All Summaries," it gets stuck on "Loading..." I tested many work parties (CHrome and Firefox) with the same result. (These all should work; they're all work parties on the specific land manager's trail segments.) The only time it DID work was for a work party that the LM was actually registered for. Not sure if that was the key for it to work or just a coincidence. I tested this with Land Manager Al Pine. This is the work party it worked: http://staging.wta.org:6543/workparty/a2eK0000002OXmm/. 
All other work parties on trail segments he managers got stuck on "Loading ..."
Loading error screenshot: http://prntscr.com/8sgwgh
Example of work party that had this error: http://staging.wta.org:6543/workparty/a2eK00000000iUh/

**Comment by davisagli** [comment]
I think I've fixed this.

**Comment by ebskopin** [comment]
working. Thanks.
