### ISSUE TITLE
VMS: MBP Workparty Summary Reports Page advance not working

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#372]
Julie reports:

In Firefox and Chrome, in MyBackpack, logged in as a crew leader (myself), I click on summary reports. It is not letting me get beyond the first page: Nothing happens when I click on any of the other page numbers or "Next 10 items." (The reports can be funny, I want to move onto the next page and read more!)

**Comment by davisagli** [comment]
This now works.

**Comment by ebskopin** [comment]
works
