### ISSUE TITLE
MBP: MyBackPack side menu needs to handle users name wrap by expanding height

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#374]
When viewing a My Backpack for any user if their name is to long the top of the green side memu will wrap.  Such as "Loren Drummond's Backpack" (see screenshot).  The darker green header behind this name should expand in height.

Here is a link: http://staging.wta.org/@@backpacks/scrnm-Loren%20Drummond/photo-gallery

![mbpmenutitlenametolong](https://cloud.githubusercontent.com/assets/8312206/10798357/74435034-7d64-11e5-8196-3fe5fc10f24a.png)

**Comment by davisagli** [comment]
Fixed
