### ISSUE TITLE
MBP: Photo Collage not including TR Photos

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#375]
In MyBackpack on the Dashboard page the Images at the top should include photo's from that users Trip Reports.  This is not working for my own My Backpack.  WaBirder57 is my screen name: http://staging.wta.org/@@backpacks/scrnm-WaBirder57

I only see the general place holder image.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Nice!
