### ISSUE TITLE
MBP: My Backpack Trip report sort by upvotes truncates result set

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#376]
In My Backpack Trip reports if i choose to sort my Trip Reports by Up Votes it truncates the results to that not all TR are shown.

For Kindra for example, she has 13 trip reports, 6 have received up votes.  When she chooses this sort option the 6 TR with up votes are shown (sorted correctly) then only one with no Up votes.  so just 7 of the 13 are shown.

For WaBirder57 MyBackpack i have 2 trip reports and only one has an up vote.  When i sort by Up Votes only the one TR with a vote is shown.

**Comment by davisagli** [comment]
We need to reindex the positive_ratings index (which tracks the number of upvotes) for all existing trip reports...something we need to add to the deploy process. It's a bit tricky to do since there are so many trip reports. I'll work on it.

**Comment by davisagli** [comment]
This should be working now.

**Comment by WaBirder57** [comment]
looks good, thanks
