### ISSUE TITLE
MBP: As a logged in user viewing someone elses saved hikes i can toggle if the trip was hiked

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#377]
As a logged in user to MBP I can view another persons My Backpack with shared hikes.  While looking at the list of hikes i can click "Hiked", add notes and even start a trip report.  i think we want these features disabled when the user is viewing others My Backpacks.

Check out Kindra's saved hikes: http://staging.wta.org/@@backpacks/scrnm-Kindra/hikes to try this out.

**Comment by davisagli** [comment]
These are available if you're logged in as a Plone admin looking at another user's My Backpack, but not for normal users looking at another backpack.

**Comment by KindraRamos** [comment]
Thanks
