### ISSUE TITLE
Work Party detail view shows error message

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#38]
When viewing the details for the West Fork Pasayten Trail Logout Work Party pyramid only show the following error message:

{"code": 500, "detail": "'NoneType' object has no attribute '__getitem__'\n\n - Expression: \"\n        function initialize_maps() {\n          var trailhead = new google.maps.LatLng(${location['location']['latitude']},\n                                                 ${location['location']['longitude']});\n          var mapOptions = {\n            center: trailhead,\n            zoom: 14,\n            mapTypeId: google.maps.MapTypeId.TERRAIN,\n            panControl: false,\n            scaleControl: false,\n            zoomControl: true,\n            zoomControlOptions: {\n              style: google.maps.ZoomControlStyle.LARGE\n            }\n          };\n          var map = new google.maps.Map(document.getElementById('google-map'),\n                                        mapOptions);\n          var marker = new google.maps.Marker({\n            position: trailhead,\n            map: map,\n            title:\"${location['name']}\"\n          });\n          $('.ui.tabs li a[rel=#location]').unbind('click', initialize_maps);\n        }\n        $(function () { $('.ui.tabs li a[rel=#location]').click(initialize_maps); });\n      \"\n - Filename:   /usr/local/pyramid/vms/src/vms/templates/workparty.pt\n - Location:   (line 205: col 14)\n - Source:     ... \n                   ^\n - Arguments:  alert_low_registration: False\n               alert_acls_needed: False\n               overview: Great wilderness area with lots of tress to logout...\n               actions: {...} (1)\n               member_fee: <NoneType - at 0x920190>\n               renderer_info: <RendererHelper - at 0x7f4f8821d510>\n               show_documents: True\n               trailhead: <NoneType - at 0x920190>\n               react_props: {\"wp\": {\"alert_low_registration\": false, \"alert_ac...\n               work_party_type: {...} (2)\n               place_on_waitlist: False\n               documents: <list - at 0x7f4f86be5f80>\n               layout: <Layout - at 0x7f4f88273d50>\n               features_highlights: <list - at 0x7f4f86be31b8>\n               req: <Request - at 0x7f4f86f1fb90>\n               plone_hike_url: http://www.wta.org/go-hiking/hikes/west-fork-pasay...\n               wp_trail_segments: <list - at 0x7f4f86bf18c0>\n               location: {...} (2)\n               waitlisted: False\n               logged_in: False\n               start_date: <date - at 0x7f4f88236e90>\n               status: <NoneType - at 0x920190>\n               repeat: {...} (0)\n               renderer_name: vms:templates/workparty.pt\n               end_date: <date - at 0x7f4f882365f0>\n               views: {...} (0)\n               registered: False\n               fee: <NoneType - at 0x920190>\n               directions: <NoneType - at 0x920190>\n               path: /workparty/a27J0000001nBsjIAE/\n               non_member_fee: <NoneType - at 0x920190>\n               panel: <instancemethod render_panel at 0x7f4f86f51f50>\n               unregistered: True\n               name: West Fork Pasayten Trail Logout\n               what_to_bring: Sneakers and gloves.\n               request: <Request - at 0x7f4f86f1fb90>\n               leader: {...} (1)\n               image_url: http://www.wta.org/site_images/hikes/west-fork-pas...\n               main_template: <PyramidPageTemplateFile - at 0x7f4f881c19d0>\n               context: <WorkParty a27J0000001nBsjIAE at 0x7f4f88273ed0>\n               _id: a27J0000001nBsjIAE\n               view: <function workparty at 0x7f4f882d46e0>", "title": "TypeError"}

**Comment by davisagli** [comment]
Fixed. It wasn't handling the case where a work party has a location (trailhead or trail segment's start point) but it doesn't have a lat/long set.

Please close this ticket once you've confirmed it now works.
