### ISSUE TITLE
MBP: IE profile pic crop error 

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#380]
In Internet Explorer all  profile picture is not cropping correctly. See attached photos 

Firefox correct view
![mybackpack avatar crop correct](https://cloud.githubusercontent.com/assets/15238703/10805553/c293a24e-7d8b-11e5-827d-f1c4efd495d0.PNG)

IE bad crop
![mybackpack avatar crop issue](https://cloud.githubusercontent.com/assets/15238703/10805554/c3c440ba-7d8b-11e5-85a0-80d1d30e1b4d.PNG)

**Comment by davisagli** [comment]
Which version of IE?

**Comment by KindraRamos** [comment]
![ie version number](https://cloud.githubusercontent.com/assets/15238703/10805782/b274b838-7d8d-11e5-849f-b7e709695e32.PNG)

**Comment by davisagli** [comment]
Try now (might need to clear your browser's cache to get up to date CSS).

**Comment by KindraRamos** [comment]
Looks good thanks
