### ISSUE TITLE
VMS: Story #320 - URL to Pre-filtered list of Work Parties

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#381]
This is working great.  A question; I see that the URL parameter "text=" never goes away after you removed text from the search box.  All the other filters have their parameters field names removed from the ULR when they are un-checked.  I don't think this affects the functionality of this feature but just wanted to double check.

Here is an example of the URL after I remove text from the Keywords text box and then have a region selected to filter on.

http://staging.wta.org:6543/?regions=Central%20Cascades&text=

**Comment by davisagli** [comment]
It's probably treating it as input of length zero rather than no input at all. If it's giving the same results I don't think it's a concern.

**Comment by WaBirder57** [comment]
If it isn't broke don't fix it. thanks for answering lets leave it as it.
