### ISSUE TITLE
MBP: Story #268 Plone-salesforce sync Trip Report Metrics

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#382]
I am not seeing much of any data syncing from Plone to Salesforce around these Trip report metrics. I created a view in .VMS2 sandbox on Contacts to show these metrics.  https://cs9.salesforce.com/003?fcf=00BK0000000SATz&rolodexIndex=-1&page=1

It is really only the SF contacts Carlos and Cris that have data at this point.

Should I expect all the Plone data to sync into Salesforce?
Also, i set Anna Roth (https://cs9.salesforce.com/003K0000016StkJ?srPos=0&srKp=003) as a Hiking Guide Correspondant.  The next day I don't see this showing up in her My Backpack (http://staging.wta.org/@@backpacks/scrnm-Anna%20Roth)

This all make me think that the Sync is just not turned on at this point.

**Comment by davisagli** [comment]
We probably missed something in setting up syncing when we deployed to staging.

**Comment by davisagli** [comment]
Syncing should work now -- Salesforce has a whitelist of which IP addresses can connect, and the staging server was not on this list.

Some caveats:
1. The sync of info from Salesforce to Plone (membership status, hiking guide correspondent, contact info, etc) and from Plone to Salesforce (including metrics) happens nightly, and only for Plone users that are connected to Salesforce contacts. This connection is set up when an unconnected user logs into Plone. So Anna's info won't sync unless she logs in now that I've fixed the issue with the network connection to Salesforce.
2. Connecting Plone users to Salesforce contacts is based on the Plone user id. mybackpack.wta.org had newly created users with email addresses as user ids. But staging.wta.org has old user accounts that were created before the switch to email addresses as user ids. So they won't match contacts in Salesforce that are connected to users of mybackpack.wta.org.

**Comment by WaBirder57** [comment]
@davisagli I tested this over night and I don't think the sync is working.  I had Anna Log in to staging.wta.org yesterday.  She now has (as expected) 2 SF contacts:
https://cs9.salesforce.com/003K0000016UXSE?srPos=1&srKp=003
https://cs9.salesforce.com/003K0000016StkJ?srPos=0&srKp=003

However neither of these synced the Trip Report stats with her Plone account:
http://staging.wta.org/@@backpacks/scrnm-Anna%20Roth

I would expect her SF Contact record to show a Trip Report count of 25.

**Comment by davisagli** [comment]
Her Plone user did not get marked as connected to Salesforce (even though it clearly created that contact in Salesforce) so I need to look into why not.

**Comment by WaBirder57** [comment]
I also checked with Kindra, she has 2 SF Contacts.  Yesterday in My Backpack she changed her MBP profile Work Phone number.  This morning this change was reflected in her SF contact record with the Website ID of "kindra" not the one with "kindra@wta.org"

https://cs9.salesforce.com/003K000000wTpoC?srPos=1&srKp=003
https://cs9.salesforce.com/003K0000014MNWN?srPos=0&srKp=003

So best I can figure there is a sync working but not to the SF Contact I would expect.

**Comment by davisagli** [comment]
Okay, this works now (and I just ran the sync manually). The scheduled task that does the sync was failing to authenticate because of an obscure problem with how authentication was set up in Plone. That's now fixed on staging and I added #385 to make the same fix to production before launch.

**Comment by davisagli** [comment]
> So best I can figure there is a sync working but not to the SF Contact I would expect.

The contact with Website ID = "kindra" is the one I would expect, because that is her user id in the production and staging sites. (Note: user id is different from login! when you switched to email logins the user's logins were changed but not their user ids. user ids can never change in Plone because it's how users are referenced internally throughout the system)

**Comment by WaBirder57** [comment]
This sync is so CooL !!
Thanks

**Comment by davisagli** [comment]
I agree! Perfect use for the Salesforce Bulk API.
