### ISSUE TITLE
MBP: Story 242 First Thumbs up Email

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#383]
This isn't working.

I created the First Trip Report for (CKahle) (wabirder57@gmail.com).  I then logged in as a different users and gave the CKahle trip report a thumbs up.  

No email as been delivered. I will check again tomorrow to see if the email arrives.

 I think this is related to story #268 - Plone-Salesforce Sync Trip Reports.

**Comment by davisagli** [comment]
The "first thumbs up" email is triggered when the "Number of Trip Report Thumbs Up" changes from 0 to 1. And Plone only updates this count in Salesforce once a night. So the email is not expected to go out until then.

**Comment by WaBirder57** [comment]
This worked one the sync to Salesforce was fixed.
