### ISSUE TITLE
VMS: Story #121 - Add Volunteers post-work party  -  Error when clicking Add

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#384]
As a Crew Leader go to a work party you are the CL for.  On the Crew Corner tab enter a name of a new volunteer for the work party.  I was testing on this work party: http://staging.wta.org:6543/workparty/a2eK0000000wbSd/

You get the following error when you click the "Add" button.

![claddvolunteer](https://cloud.githubusercontent.com/assets/8312206/10834685/9b1e83f0-7e58-11e5-9e61-85d9dc7d90db.JPG)

**Comment by cewing** [comment]
@ebskopin 

To Test:

log in as a crew leader and add a new member to your roster via the crew-corner.  Verify that the form does not throw the described error, and that the newly added member appears in the roster after the form is submitted.

**Please Note** that the data for the newly added registration is not in sync with any data that might be known about that contact in salesforce.  You should not expect, for example, to see a correct list of the new additions "days of experience" or list of awards/certifiations.

**Comment by ebskopin** [comment]
I just tested now and received the same error.

**Comment by ebskopin** [comment]
Tested on this WP: http://staging.wta.org:6543/workparty/a2eK00000000iUN/

**Comment by davisagli** [comment]
Please try again, I think something went wrong with deploying this change earlier, and I just tried it again.

**Comment by ebskopin** [comment]
This works. Thanks.
