### ISSUE TITLE
MBP: Email on First Trip Report, First Thumbs Up tweaks

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#386]
1) These email's should be "from" Loren ( loren@wta.org ).
2) The First Thumbs up email should indicate that at 25 thumbs up you will get a Gold Star recognition.  Plus this number should be used in the code to actually show this on that users My Backpack.

Question: Is the body text of these emails something that we can edit?

![mbpemailfirstthumbsup](https://cloud.githubusercontent.com/assets/8312206/10855774/c44b145c-7f00-11e5-800d-907daa423763.JPG)
![mbpemailfirsttripreport](https://cloud.githubusercontent.com/assets/8312206/10855776/c5d847ea-7f00-11e5-8244-f8a382339074.JPG)

**Comment by davisagli** [comment]
The messages come from these Email Templates:
https://cs9.salesforce.com/00XK0000000MlCY
https://cs9.salesforce.com/00XK0000000MlGk

The workflow Email Alerts that use those templates are here, and you can edit them to change the From address:
https://cs9.salesforce.com/01WK00000004bhf
https://cs9.salesforce.com/01WK00000004bjM

**Comment by WaBirder57** [comment]
Thanks for this info and links.
