### ISSUE TITLE
VMS: WP Document Tab - change wording for required documents

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#388]
When a visitor looks at the Document tab of a WP that has required documents we need to update what they see so that it is more informative with links to take action.

This is what is currently displayed:

![vmswpdocumenttab](https://cloud.githubusercontent.com/assets/8312206/10859116/a94d2804-7f17-11e5-8ea9-27eb836159a6.png)

The following is an example of what we would like. Although note that we will not being supporting the Option to have a printable version.  So in the following strike the line "Printable Version" that appears in 2 places.

![vmswpdocumenttabideas](https://cloud.githubusercontent.com/assets/8312206/10859127/bb6cd1b0-7f17-11e5-8693-ec30aefdabc8.png)

The green box should link to the Form Assembly form to be completed.

Lastly the 1st box, Preview Waiver text link should display the same Liability Waiver that is displayed from the registration form when the user clicks the "release waiver" link just above the Register button.

If the user has not logged in the text in the Green box should read: "Sign in to complete online."  this green button should link to the My Backpack Log in or Sign Up menu.

**Comment by davisagli** [comment]
> So in the following strike the line "Printable Version" that appears in 2 places.

To remove the "printable version" link, edit the Required Document objects in Salesforce and clear the "Printable Form Link" field:
https://cs9.salesforce.com/a2pK0000000d9ph
https://cs9.salesforce.com/a2pK0000000dAgj
https://cs9.salesforce.com/a2pK0000000boQc

> The green box should link to the Form Assembly form to be completed.

Yeah, that's supposed to be working already so we'll have to look into what's not working.

> Lastly the 1st box, Preview Waiver text link should display the same Liability Waiver that is displayed from the registration form when the user clicks the "release waiver" link just above the Register button.

Doesn't it already work like that?

> If the user has not logged in the text in the Green box should read: "Sign in to complete online." this green button should link to the My Backpack Log in or Sign Up menu.

Good idea.

**Comment by davisagli** [comment]
The green "complete online" buttons should now be appearing for users who are not registered. I also added a "sign in to complete online" button for users who are not logged in, but it was too wide for the individual document boxes, so I put it above all the documents.

**Comment by WaBirder57** [comment]
@davisagli Are you able to address the removal of the "Printable Version" link which we don't want to support.  All volunteers will need to fill out the online form.

**Comment by davisagli** [comment]
@WaBirder57 see my comment above. Once you edit the Required Document records in Salesforce to remove their "Printable Form Link," the "printable version" link will no longer display in the pyramid app.

**Comment by WaBirder57** [comment]
You are so right, sorry to have overlooked this.  Works great!
