### ISSUE TITLE
MBP/VMS: Crew Corner work party summary total Hrs worked not working

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#389]
When a Crew leader is logged into My Backpack Crew Corner tab and clicks on Summary Reports.  The side panel Roll Up Report always shows Zero hours worked.  Seems this should the actual number of hours work across those reports.

Also the paging action doesn't work.  Although it shows 1 2 3 (etc) and Next 10 Items, you are not able to advance to the next page of results.

![vmsworkpartysummaryscreen](https://cloud.githubusercontent.com/assets/8312206/10859637/c2101432-7f1c-11e5-97bf-1dd27869566c.JPG)

**Comment by davisagli** [comment]
The pagination issue is already covered by #372

**Comment by davisagli** [comment]
@cguardia I fixed this one. The value it was trying to read was not included in the work party index.

**Comment by WaBirder57** [comment]
Excellent, work party hours is fixed.  Will close this knowing that #372 will handle the pagination.
