### ISSUE TITLE
WP Description Info Tab & Location text doesn't wrap correctly

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#39]
Looking at the Wynoochee Lakeshore Trail work party the text on the Info and Location Tab doesn't wrap correctly.
![workpartytextwrapissue](https://cloud.githubusercontent.com/assets/8312206/6475406/a8728c9c-c1be-11e4-815a-31e5f4c035f1.JPG)

**Comment by davisagli** [comment]
Charlie, in the future it would be helpful if you can include a link to the work party when you report an issue -- saves us time in finding it especially as more work parties get added. This one is http://staging.wta.org:6543/workparty/a27J0000001nBzCIAU/

**Comment by davisagli** [comment]
This is because the rich text entered in Salesforce contains a table with its width fixed at 1072 pixels. I'm puzzled as to how that got in there, since the rich text editor in Salesforce doesn't appear to have a table feature. I guess you probably copied this text in from somewhere else?

For best results you want this field to end up with clean HTML that doesn't override styles, so that the text can pick up styles from the VMS stylesheet. @mscholtz does Salesforce make it possible to configure ckeditor at all? It supports cleaning pasted markup but maybe Salesforce doesn't expose that functionality.

**Comment by mscholtz** [comment]
@davisagli, nope, I have no idea if it's possible to configure the rich
text editor in SF.  Likely the answer is no.  So I concur that best bet is
not to cut/paste rich text from other sources, and instead paste in plain
text and then re-style it in the editor.

Also, we don't want to include images inside the field, although SF will
allow you do that.  Right, David?

On Tue, Mar 3, 2015 at 4:21 PM, David Glick <notifications@github.com>
wrote:

> This is because the rich text entered in Salesforce contains a table with
> its width fixed at 1072 pixels. I'm puzzled as to how that got in there,
> since the rich text editor in Salesforce doesn't appear to have a table
> feature. I guess you probably copied this text in from somewhere else?
>
> For best results you want this field to end up with clean HTML that
> doesn't override styles, so that the text can pick up styles from the VMS
> stylesheet. @mscholtz <https://github.com/mscholtz> does Salesforce make
> it possible to configure ckeditor at all? It supports cleaning pasted
> markup but maybe Salesforce doesn't expose that functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/39#issuecomment-77071600>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Looks like the answer is yes if you use a custom visualforce page: http://salesforce.stackexchange.com/questions/18701/how-to-upgrade-ckeditor-premium-version

On my Mac I can paste text without styles using Cmd+Shift+V. Not sure if there's an equivalent on Windows.

What sort of markup does it end up storing if you insert images? Are they added as inline data URIs in the src attribute, or as a reference to another URL?

**Comment by mscholtz** [comment]
Don't know re the images.  I would have to test.

On Tue, Mar 3, 2015 at 4:51 PM, David Glick <notifications@github.com>
wrote:

> Looks like the answer is yes if you use a custom visualforce page:
> http://salesforce.stackexchange.com/questions/18701/how-to-upgrade-ckeditor-premium-version
>
> On my Mac I can paste text without styles using Cmd+Shift+V. Not sure if
> there's an equivalent on Windows.
>
> What sort of markup does it end up storing if you insert images? Are they
> added as inline data URIs in the src attribute, or as a reference to
> another URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/39#issuecomment-77075583>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Looks like you've fixed the wide table and there is another ticket (#40) regarding the text field for work parties, so I'm going to close this one.
