### ISSUE TITLE
MBP: Main navigation menu design tweaks

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#392]
- Color shift in logged in/logged out state. Just want to check on this ticket, to make sure it is going to maintain color behaviors when logged in.   This should stay the Beige/Orange color and not change to Blue when logged in.  Avatar icon or image will indicate logged in state as well as who is logged in.

- Change transparent lines between menu heading sections into solid white - 5 places. 

![mbpmenuchanges](https://cloud.githubusercontent.com/assets/8312206/10891658/0881d8ae-8154-11e5-948b-da3357597e42.JPG)

**Comment by davisagli** [comment]
> Color shift in logged in/logged out state. Just want to check on this ticket,

It's ticket #322; we haven't gotten to it yet because it's Medium Priority and there have been other High Priority tickets. Please change the priority if you want us to get to it sooner rather than later.

**Comment by WaBirder57** [comment]
@KindraRamos can you review the priority of this ticket as well as #322 .

**Comment by KindraRamos** [comment]
I went ahead and updated the priority. I think it is important to keep the look and feel consistent and not having the lines white looks like  a glitch and lessens the visual cue of the menu.

**Comment by davisagli** [comment]
This change is done.

**Comment by KindraRamos** [comment]
Looks good in firefox, chorome but is not updating in IE 
![ie version number](https://cloud.githubusercontent.com/assets/15238703/11042773/ef50e346-86cd-11e5-9168-6eedd67fad52.PNG)

**Comment by davisagli** [comment]
Did you try clearing IE's cache?

**Comment by KindraRamos** [comment]
That did the trick. I had to do a hard clear the refresh didn't work. thanks

**Comment by davisagli** [comment]
Yeah in IE refreshing the page doesn't help if the page is in the browser cache.
