### ISSUE TITLE
MBP: Trip Report - removed the pop up text from up vote "Yes" link 

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#393]
Currently when looking at the a trip report when you hover you mouse over the Up Vote "Yes" link a pop up  with the word "Title" appears.  Please remove this, no text is needed.

![upvotepopuptext](https://cloud.githubusercontent.com/assets/8312206/10891994/f10fb1da-8155-11e5-82a1-6454c1471c20.JPG)

**Comment by davisagli** [comment]
fixed
