### ISSUE TITLE
MBP: Trip Report trail conditions hard to read when many are selected

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#394]
When looking at a trip report when the user has selected many issues with the Trail Condition the list runs together and is hard to read.  Change the display so that each items is indented and on its own line.  the indentation for each should start in the same column.

For example (see  http://staging.wta.org/go-hiking/trip-reports/trip_report.2015-10-29.4745865834 )

Can we changet this look something like this:

```
Trail  Trail difficult/impossible to navigate: 
         Trees down across trail, 
         Difficult stream crossing(s), 
         Bridge out, 
         Muddy or wet trail, 
         Overgrown in places, 
         Mud/Rock slide or washout
```

![tripreporttrailuissueslist](https://cloud.githubusercontent.com/assets/8312206/10892197/f6e0a60e-8156-11e5-91ea-de2322b88e12.JPG)

**Comment by cguardia** [comment]
Fixed in mybackpack-buildout branch.

**Comment by davisagli** [comment]
Deployed to staging.wta.org. If it looks good there we can deploy to production.

**Comment by WaBirder57** [comment]
These entries need to have a little more spacing between them.  Here is an example to make the same spacing as the list members on the locations list.

![mbptripreporthazardspacing](https://cloud.githubusercontent.com/assets/8312206/11670708/3dcafec0-9db8-11e5-8b24-5ece5f33e223.JPG)

**Comment by cguardia** [comment]
@davisagli Pushed a simple fix for this to mybackpack-buildout branch.

**Comment by davisagli** [comment]
Deployed this to the live site with the line spacing adjusted.

**Comment by ebskopin** [comment]
fixed
