### ISSUE TITLE
MBP: In My Hikes list reduce space between Search area and Hike List

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#395]
•	Can we reduce the space between the "Search My Hikes" box and the list displays below, so that they feel related to each other. 

![myhikesspacebetweensearchandlist](https://cloud.githubusercontent.com/assets/8312206/10892319/a06b9f8a-8157-11e5-958f-24693dc1f709.JPG)

**Comment by davisagli** [comment]
done
