### ISSUE TITLE
MBP: Make avatar image a circle not oval.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#396]
Change from oval to default circle presentation of icon on main profile AND (more importantly) on trip report list displays.

This is lower priority, but enough people have repsonded to it negatively that I would like to address it. We will default to a circle (which happens when people upload a square image) and add a bit of help text around the profile image upload to say that a square image works best. 

![mbpavatarimagetocircle](https://cloud.githubusercontent.com/assets/8312206/10892429/3779ab7e-8158-11e5-8ae5-0c838dc7fb48.JPG)

Add text: "Square image works best".

![profileaddpicturetext](https://cloud.githubusercontent.com/assets/8312206/10892498/9825cc78-8158-11e5-89df-e1eefac52392.JPG)

**Comment by davisagli** [comment]
Done (and also on the My Backpack nav button)

**Comment by KindraRamos** [comment]
Thanks these look great but I think the nav button should stay a square.

**Comment by davisagli** [comment]
That means the image will get a circular crop in some places but a square crop in the nav, which may be confusing to users. Not hard to try it if you want though.

**Comment by KindraRamos** [comment]
Thanks for looking out for the users David but I think visually it is stronger to keep the clean lines of the square up top.

 

Kindra Ramos – director of communications and outreach 

Washington Trails Association 

wta.org * 206-965-8563 

 

WTA is powered by hikers like you!

**Comment by davisagli** [comment]
Okay, we're back to square images in the nav.

**Comment by KindraRamos** [comment]
Looks great thanks
