### ISSUE TITLE
No easy path back to WP/registration after being routed to Required Documents screen

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#399]
If I'm attempting to register for a Work Party that requires forms ahead of time, like Vol Vacations, here's what happens now:

1) I click Join
2) I may be asked to log in
3) routed to required forms page (which seems to have no onscreen context re which WP I was trying to sign up for):
![image](https://cloud.githubusercontent.com/assets/931031/10894071/24c593b8-8161-11e5-9755-b48d96ae86ea.png)

4) if I click to complete a form, FormAssembly form shows up in new tab
5) when I submit that, all I see in new tab is "Thank you. Your response has been processed successfully."  Not obvious to me that I need to close that tab and go back to my previous tab.
6) Even if I figure that out, the original tab hasn't been refreshed and the document still shows required
7) If I hit the refresh button, then VMS takes me to register for the WP.  But I don't think many users are going to know to hit the refresh button.

Spoke w/ @davisagli about this.  We're not sure what the best answer is.  We think we either need a redirect after the FormAsssembly submission (which we're not sure is natively possible) or we need to include some widget (button/link) on the required documents page for users to click on after they've completed the forms, which will take them to the registration form.

@WaBirder57 @ebskopin please assign priority.

**Comment by mscholtz** [comment]
If we can specify what the "thank you" message is in FA, that might help too.  We could advise users to go back to their original tab.  Although that's still tricky..

**Comment by davisagli** [comment]
> If we can specify what the "thank you" message is in FA, that might help too.

Keep in mind that there are multiple ways users can access these forms (they're also on a page in My Backpack)

**Comment by mscholtz** [comment]
Good point.

On Mon, Nov 2, 2015 at 1:04 PM, David Glick <notifications@github.com>
wrote:

> If we can specify what the "thank you" message is in FA, that might help
> too.
>
> Keep in mind that there are multiple ways users can access these forms
> (they're also on a page in My Backpack)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/399#issuecomment-153156168>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ebskopin** [comment]
I agree that this flow is not ideal. I vote for a button on the forms page indicating the when the forms are complete they can click to proceed. It might also indicate that they need to refresh their browser to see if the form are complete...

**Comment by mscholtz** [comment]
I would also suggest that we include some sort of instructions on the required forms page so the user knows it'll open in a new tab, and that they should close and go back to this tab when they're done.

**Comment by mscholtz** [comment]
BTW, it does look like FA can do a redirect, but don't know if we can parameterize it.  @davisagli let me know if you want me to look into that.

**Comment by mscholtz** [comment]
https://help.formassembly.com/knowledgebase/articles/340545-thank-you-page-or-redirect

**Comment by davisagli** [comment]
That links to https://help.formassembly.com/help/article/link/340547-smart-processing-with-formulas#examples, which looks like it's supposed to be an example of how to do this, but is missing the actual example. :(

**Comment by mscholtz** [comment]
Looks like it'll work.  I think I can figure it out.
If we can make it work, is that the desired solution?

On Mon, Nov 2, 2015 at 3:07 PM, David Glick <notifications@github.com>
wrote:

> That links to
> https://help.formassembly.com/help/article/link/340547-smart-processing-with-formulas#examples,
> which looks like it's supposed to be an example of how to do this, but is
> missing the actual example. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/399#issuecomment-153186990>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
@mscholtz I'm also worried that if we redirect the user directly back to a page that shows document status, FormAssembly will not have had a chance to communicate with Salesforce yet, so the status may still show as incomplete.

**Comment by mscholtz** [comment]
Hmm, there is that.
Well, your call.  Let me know if you need anything from me.

On Mon, Nov 2, 2015 at 3:15 PM, David Glick <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> I'm also worried that if we
> redirect the user directly back to a page that shows document status,
> FormAssembly will not have had a chance to communicate with Salesforce yet,
> so the status may still show as incomplete.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/399#issuecomment-153188404>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by cewing** [comment]
@davisagli, @ebskopin I've added a button that reads "I have completed the documents" that will reload the page.  As for customizing the text on the required docs page, there is a customizable text component there, which currently holds some lorem ipsum text.  It could serve to provide the instructions that @mscholtz [refers to above](https://github.com/washingtontrails/vms/issues/399#issuecomment-153186074), no?  

If there is still a desire to make the forms themselves redirect back to the register view, that can be done, but I'd love to get a read on this update first. If we can avoid spending that time, all the better.

**Comment by ebskopin** [comment]
Cris,
I'm not seeing this button on the required documents page.  Perhaps I'm missing something.

Thanks,
Elliott

**Comment by cewing** [comment]
@ebskopin: It will only appear on the page that you are sent to when you try to register for a work party that requires documents that you do not yet have.  It does not appear on the documents tab for a workparty.

**Comment by ebskopin** [comment]
![image](https://cloud.githubusercontent.com/assets/14843712/11099717/d0fea7ee-8861-11e5-96e3-90ff4c832d53.png)

It this where is should be?

**Comment by cewing** [comment]
@ebskopin yep.  Indeed.  What work party and user is that?  I will try to figure out why it isn't appearing.

**Comment by ebskopin** [comment]
User- George Eliot: 
eliot.george99@yahoo.com
georgewta123

WP: http://staging.wta.org:6543/workparty/a2eK00000000ibG/

It seems to be the case for any BCRT or Volunteer Vacation I attempt to register him for.

**Comment by davisagli** [comment]
Please remember that this is a public issue tracker so it's not a good idea to post logins!

**Comment by ebskopin** [comment]
whoops. ok. thanks.

**Comment by cewing** [comment]
I've deleted.  I'm in.

**Comment by cewing** [comment]
I've found the culprit.  Apologies for the problem.  When @davisagli deploys next it should be fixed.

**Comment by davisagli** [comment]
Deployed.

**Comment by ebskopin** [comment]
Yep, looks good. Thanks.
