### ISSUE TITLE
Salesforce Workparty Object doesn't contain Info Text field

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#40]
The Salesforce WP Object doesn't contain a field for the text description for the Info tab in pyramid.   This info tab should contain the "overview" information that shows on the Find a Work Party webpage but then also shows additional information.

See the prototype: http://06.wta.emptycan.com/volunteer/details/volunteer-vacation/ for types of information that needs to be formatted and displayed.

**Comment by davisagli** [comment]
Currently the text from the Overview is shown in both places. It makes sense to me that you would want a field with additional information for the work party's Info tab.

Do you want a separate field for each of the sections shown in the mockup (Difficulty, What to Bring, Application Process, Restrictions, Fees, Contact)? Or do you just want one big text field that is shown following the overview, and you can put whatever section headings you want in that field?

**Comment by WaBirder57** [comment]
David I think your idea of one "big" text field that gives us flexibility it good.  We will have to see what formatting options Salesforce gives us and how that will be displayed.

Also, based on Work Party Type, this field will be per-populated with the "default" language for a work party.  When a new work party is created that text is copied in and then can be customized.

In summary for the WP Info Tab there are 3 "blocks" of information, top to bottom:
1) Marketing over view which is also display on the Find a Work Party screen.  (Current "Overview" field.
2) Hike description from the corresponding Hiking Guide Entry.
3) Big Text Field with the body of the information (current "What to Bring" field - should be renamed.)

**Comment by davisagli** [comment]
@mscholtz how hard is it to do what Charlie requested re setting default text copied from the Work Party Type?

@WaBirder57 getting the hike description from the hiking guide entry will probably add a few hours work since we have to make sure we have a good way to fetch that info from Plone based on the hiking guide URL. Are you thinking of this as a critical need, or more of a nice to have? Also, could you take a screenshot of a hiking guide entry and highlight the part that you'd like to have included here, to make sure we're clear on that? Thanks.

**Comment by WaBirder57** [comment]
@davisagli I have attached a screen shot of a PDF of the Plone screen shot for a hiking guide entry page.  I can email the full PDF if that would be helpful.  The field that we want to use in the WP Info tab is the "Hike Summary" field.  Is it possible given the URL for this Hiking Guide page for you to pull the contents of this field so that it can be used in VMS in the Info Tab with it's own heading.

This is a really "nice" to have (almost critical) that helps link info between our WP and Hikes.  Yes, it is worth a couple hours.

![hikingguideeditscreeninplone](https://cloud.githubusercontent.com/assets/8312206/6509777/6e2bc02c-c316-11e4-9714-bb1a52a88f75.JPG)

**Comment by mscholtz** [comment]
Should this be a rich text field?  Have we decided that works OK to pull via API and display?

**Comment by mscholtz** [comment]
and @davisagli am I seeing that you're now pulling in hiking guide info directly to pyramid at runtime?  We had been planning to pull this into SF, and there's a story for it here: https://www.scrumdo.com/projects/project/wta/iteration/110416#story_910401

**Comment by davisagli** [comment]
Yes, rich text. We need to figure out a way for them to enter headings in the text too.

I'm not yet pulling in the hike title and description, but I was planning to have it fetch that from Plone when the work party is displayed. If I can get it from Salesforce when the work party is indexed that would be fine too.

**Comment by mscholtz** [comment]
@WaBirder57 do you need the Hiking Guide description in SF for any reason?  Or would it be fine if David pulled it from pyramid and it only showed up in VMS and not in SF?  (We can decide this later, just asking the question while I'm thinking of it)

**Comment by davisagli** [comment]
One potential reason we would want to have it at indexing time instead of when the work party is viewed is if we want users to be able to search for work parties by text that is in the hiking guide summary.

**Comment by skleinfeldt** [comment]
Since we're already talking about pulling the region/subregion info from Plone hiking guide to SF (the new story), I'd think we'd at least want Title? And I think @davisagli 's reasoning above is pretty compelling.

**Comment by mscholtz** [comment]
What to Bring field renamed to Detailed_Description__c

**Comment by davisagli** [comment]
And the pyramid app is updated so it shows the overview and detailed description on the full work party view.

**Comment by WaBirder57** [comment]
@mscholtz @davisagli  Do we know if there is a Rich Text editor in Salesforce which would support the full range of HTML formatting that the Salesforce Rich Text field supports?  The current default doesn't.

**Comment by mscholtz** [comment]
I don't know of any 3rd party editors you can integrate into SF.  Haven't
gone hunting, either.  I assume you can do that, but let me know if you're
looking for help.

On Tue, Apr 21, 2015 at 11:34 AM, Charles Kahle <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> @davisagli
> <https://github.com/davisagli> Do we know if there is a Rich Text editor
> in Salesforce which would support the full range of HTML formatting that
> the Salesforce Rich Text field supports? The current default doesn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/40#issuecomment-94898321>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
We have gone with the route of adding more smaller SF Rich Text fields.
