### ISSUE TITLE
MBP/VMS: Logged in staff/CL gets error in Crew Corner tab, My Work party list

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#400]
When i log into My Backpack as charles@wta.org, i go to MyBackpack, Crew Corner Tab and click the right hand menu for My Work Parties.    I get the following error:

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module wta.content.backpack.backpack, line 921, in __call__
    Module Products.Five.browser.pagetemplatefile, line 125, in __call__
    Module Products.Five.browser.pagetemplatefile, line 59, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 93, in __call__
    Module z3c.pt.pagetemplate, line 149, in render
    Module chameleon.zpt.template, line 258, in render
    Module chameleon.template, line 171, in render
    Module e1c87d130f8ee7170989c86fc474fa2b, line 1372, in render
    Module ab4b94344b5b771bdac01a970e4c7fd1, line 1399, in render_master
    Module e1c87d130f8ee7170989c86fc474fa2b, line 804, in __fill_content
    Module chameleon.tal, line 471, in __call__
    Module Products.CMFPlone.PloneBatch, line 140, in __getitem__

KeyError: 0

**Comment by davisagli** [comment]
Looks like it's not handling the case where you have no work parties correctly.

**Comment by davisagli** [comment]
Fixed.

**Comment by ebskopin** [comment]
works.
