### ISSUE TITLE
MBP: Internet Explorer Dashboard display error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#402]
When viewing anyone's MBP Dashboard in Internet Explorer (11.0.9600) the display of icons or # of Trip reports is not correctly formatted.

The following screen shot shows how the number for the # of Trip Reports is formatted in a color that is invisible unless selected (drag mouse across).  Also, the icon for the Hiking Guide Correspondent doesn't seem to display.

![mbpieprofilepagedisplayerror](https://cloud.githubusercontent.com/assets/8312206/10896974/38ff4af2-8172-11e5-9bdd-9a8f969b27c0.JPG)

Here is the same users Dashboard using Firefox:
![mbpfirefoxprofilepagedisplayerror](https://cloud.githubusercontent.com/assets/8312206/10897040/a958f21c-8172-11e5-849b-0fa1d49aa3c3.JPG)

**Comment by davisagli** [comment]
I think I've fixed this.

**Comment by KindraRamos** [comment]
looks good
