### ISSUE TITLE
VMS: Work Parties with zero value for "Max Friends/Family" inhibit registrations

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#404]
Per Tiffany's Recent Testing Results - 

Short version: work party types in SF with no value or a value of zero in the "max friends/family" box creates online registration problems for users of Firefox and IE. Registration just doesn't happen in Firefox and in IE registration happens but the user does not see a confirmation screen. No problems noticed in Chrome or Safari. iphone/ipad not tested.

Long version: I set up a work party type with a very high ACL:volunteer ration and inadvertently left the "allow guest registrations" box unchecked and left the "max friends/family" field blank. Am I correct in understanding that these two fields are related? 

I tried to register for the WP and had problems with IE and Firefox.  

Firefox: hit submit button, was not brought to a confirmation screen and was not registered for party. Hit submit again, same result, 
IE: hit submit button, was not brought to a confirmation screen but WAS registered for the party and received an email. Hit it again and briefly saw the "contact already registered" message before it brought me right back to the registration screen. No confirmation screen.
Chrome and Safari: hit submit and registration happened exactly as it should. 

Since other work party types were working fine, I figured it was a problem with the one I had set up and I started changing the fields one by one to match a known, working, WP and eventually found that adding a number greater than zero to the "max friends/family" field fixed the problem and allowed me to register.

**Comment by davisagli** [comment]
I can't reproduce this one so far. I tried registering for David's Test WP (http://staging.wta.org:6543/workparty/a2eK0000000wNzA/) whose Work Party Type has a blank Max Friends/Family, and it worked fine (in Firefox).

We need more details to reproduce the issue:
1. Which work party did you encounter this on?
2. Were you logged in or not?
3. What did you enter in each field in the form?

It sounds like maybe the system is hitting a javascript error that prevents further processing. Do you know how to view your browser's javascript console to check if there was an error?

**Comment by ebskopin** [comment]
From Tiffany - 

"I am using this work party: https://cs9.salesforce.com/a2eK00000000jt9

But the errors are encountered when I mess around with the max friends/family field in this WP type:  https://cs9.salesforce.com/a2wK0000003uPLl

So this WP is the same type and I get the same issues: https://cs9.salesforce.com/a2eK00000000jtx

There's always the possibility that something else in that WP type is screwing things up but I started going through fields one by one and when I changed max friends/family I was good to go. "

**Comment by davisagli** [comment]
I was able to register for that work party too. I know it's tedious but can Tiffany please list what she entered for each form field, as well as whether she was logged in or not?

**Comment by davisagli** [comment]
(Or maybe a screencast of filling out the form would be easier?)

**Comment by ebskopin** [comment]
"I am logged in as a My Backpack user with VMS permission level Volunteer and I don't add any info to the pre-populated stuff except checking the box that says I've read/understand. It pre-populates with first name/last name/phone/phone type/address/city/state/zip. 

Under 18 is left unchecked; carpool is "no thanks" and "have a question" is blank. 

Then I check the box that says I understand

I attached an image of what it looks like before I check the "I understand" box and hit submit."

![image](https://cloud.githubusercontent.com/assets/14843712/10951881/bc0acad8-82f4-11e5-80ff-2d1b31231c14.png)

**Comment by davisagli** [comment]
Still not sure what causes it to not work. :( Can you email me the login and password for "George Eliot" so I can try in case it's something specific about this user? (Don't post it here; these issues are public.)

**Comment by davisagli** [comment]
Thanks for sending the login for George Eliot; I'm now able to reproduce the issue. The registration is failing because the user already has an existing registration, and the real problem here is that that error isn't getting shown to the user like it's supposed to.

**Comment by davisagli** [comment]
This is now fixed so that errors will be reported correctly.

**Comment by ebskopin** [comment]
Yep. Tested and it works.  Thanks.
