### ISSUE TITLE
Unit tests for WTA_VMS_Hours_RollUp_To_WP_Reg are failing

### ISSUE THREAD

**Issue by ninetaLogik** [washingtontrails/vms#405]
Due to new validation rule requiring WP Reg Status to be set.
WTA_VMS_TEST_Hours_Rollup_To_WP_Reg

**Comment by davisagli** [comment]
Changing this to high priority since we're hoping to deploy to production in a couple weeks and that can't happen with failing tests.

**Comment by mscholtz** [comment]
Yep, was about to do that too.

**Comment by mscholtz** [comment]
Fixed. I am baffled by this one, though.  The validation rule was not new - it's been in there since April.  And I'm pretty sure this wasn't failing a month ago.  And I can't see recent changes to any of the classes that would have caused it to start failing.  Very odd.  Anyway, passing now.
