### ISSUE TITLE
VMS: Membership expiration date not displaying on MBP

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#406]
As per Tiffany's Testing (I am also not seeing on my MBP) - 

NOT WORKING: I am not sure where mybackpack is pulling info from to determine if a membership is active or expiured. For instance, both Loretta Ross and Nellie Bly show up as expired even though they have membership expiration dates and/or gift dates that should bring their membership through to now: https://cs9.salesforce.com/003K0000014kntn and https://cs9.salesforce.com/003K0000014sQlj

NOT WORKING: I don't see any dates of expiration passed or expiration upcoming

NOT WORKING: I don't see any difference between never been a member and expired membership. So someone who has been a membe and someone who has not get the same message (expired membership)

**Comment by davisagli** [comment]
> NOT WORKING: I am not sure where mybackpack is pulling info from to determine if a membership is active or expiured. For instance, both Loretta Ross and Nellie Bly show up as expired even though they have membership expiration dates and/or gift dates that should bring their membership through to now: https://cs9.salesforce.com/003K0000014kntn and https://cs9.salesforce.com/003K0000014sQlj

We pull these fields from Salesforce: Household_Membership_Status__c, HouseholdMembershipJoinDate__c, and HouseholdMembershipEndDate__c. Why do you say these should have a membership that's still active? They both have expiration dates in the past and that looks correct based on their membership opportunities which were over a year ago.

I still need to look into the other issues. It'd be helpful if you can provide the backpack URL of someone who is a current member and someone who is expired.

**Comment by davisagli** [comment]
> NOT WORKING: I don't see any dates of expiration passed or expiration upcoming

The date of upcoming expiration was only visible for a user looking at their own backpack, and only if it's within the next 30 days. I changed it so it is now also visible to admin users looking at someone else's backpack.

And I added the date for expired members.

> NOT WORKING: I don't see any difference between never been a member and expired membership. So someone who has been a membe and someone who has not get the same message (expired membership)

I think this is fixed.

**Comment by ebskopin** [comment]
Any idea why I wouldn't be able to edit any of the fields under the Membership Information heading in Salesforce except "Life Member."

**Comment by davisagli** [comment]
@ebskopin I think they are formula fields calculated from the corresponding fields on the contact's household.

**Comment by davisagli** [comment]
And those in turn are based on the membership opportunities associated with the household.

**Comment by ebskopin** [comment]
Ok thanks for clarifying this. Here is what I'm seeing:  

For George Eliot - https://cs9.salesforce.com/003K0000014OxHr

His membership is current.
![image](https://cloud.githubusercontent.com/assets/14843712/11101956/8540717c-886e-11e5-88bb-cf56f206f8bd.png)

But is not reflected in MBP.
![image](https://cloud.githubusercontent.com/assets/14843712/11101015/6afeba62-8869-11e5-8dc3-0ae1e2749769.png)


For myself - https://cs9.salesforce.com/003K0000015g4x9?srPos=0&srKp=003
![image](https://cloud.githubusercontent.com/assets/14843712/11102032/f4e5f024-886e-11e5-9969-c8f6b8c3cc79.png)

Displays this in MBP:
![image](https://cloud.githubusercontent.com/assets/14843712/11102041/0e826364-886f-11e5-993b-94b9f40169c9.png)

**Comment by davisagli** [comment]
Are those screenshots from mybackpack.wta.org or staging.wta.org?

**Comment by davisagli** [comment]
The date of membership expiration is only shown if it's within the next 30 days. So I think George Eliot's status is showing correctly, no?

**Comment by ebskopin** [comment]
Yep, you're correct about George's.  The screen shots are from mybackpack.wta.org.

**Comment by davisagli** [comment]
Okay, forgive me if I'm missing something that's obvious to you, but what part isn't working right then?

**Comment by ebskopin** [comment]
The membership for my record (https://cs9.salesforce.com/003K0000015g4x9) is set to expire on 11/18/2016, but MBP would lead me to believe that my membership expired on Nov 5, 2015.  

Maybe I'm not understanding how these two things are suppose to communicate...

**Comment by davisagli** [comment]
Oh, I see; yeah that doesn't look right. I think it's confused because the membership status is Current but the start date is in the future. Will take a look...

**Comment by davisagli** [comment]
For some reason the nightly sync from Salesforce to Plone was not running on mybackpack.wta.org. I ran it manually and restarted the process so we'll see if it works tonight.

**Comment by davisagli** [comment]
Still didn't run. I switched it to a different approach for running the nightly tasks, and will check again tomorrow.

**Comment by davisagli** [comment]
Nightly sync is working now.

**Comment by ebskopin** [comment]
working
