### ISSUE TITLE
MBP: Unable to Load Photos into MBP Gallery

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#407]
Note: Still unable to load photos into my photo gallery. error message" The error has been logged as entry number 1445885331.080.513410462434." 

![image](https://cloud.githubusercontent.com/assets/14843712/10950065/e3bcd4ea-82ea-11e5-9722-81bce14881c6.png)

**Comment by davisagli** [comment]
What's your username @ebskopin?

**Comment by ebskopin** [comment]
For MBP? EBSkopin

**Comment by davisagli** [comment]
http://www.wta.org/hiking-info/gallery/images has a permission set to allow members to add photos, and we missed doing this when we set up http://mybackpack.wta.org/hiking-info/gallery ...should work now.

I just noticed that http://www.wta.org/hiking-info/gallery has a "Add your photos" portlet that links to create a photo in http://www.wta.org/hiking-info/gallery/images/2015 ... I guess we should change the link in My Backpack to go to the same place as that portlet, eh?

**Comment by ebskopin** [comment]
Confirmed that this works.  Thanks.  Yes, link should be changed to the same portlet in that instance.

**Comment by davisagli** [comment]
It now has the correct link to add a photo. Test this on staging.wta.org rather than mybackpack.wta.org because only staging has the full gallery folder structure.

**Comment by ebskopin** [comment]
Looks good. Thanks.
