### ISSUE TITLE
Find a Work Party List view - Work Party status text changes

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#41]
The Find a Work Party List view should indicate the following call to action status indicators.  These should all be in the current Gray.  "See Details" (not the current "Open"), "Full - Join Waitlist" (not the current "Waitlist", and "Preview" (for WP in preview mode).  See current screen shot for items that need to be changed (see: http://staging.wta.org:6543/)
![findawplistview](https://cloud.githubusercontent.com/assets/8312206/6475561/806ca352-c1c0-11e4-8b64-ce151d3fd3ae.JPG)

**Comment by davisagli** [comment]
What is preview mode?

If the user is logged in with a permission level of ACL or CL and the work party is waitlisting volunteers but still open to ACLs, should it still show "Full - Join Waitlist", or something else?

**Comment by davisagli** [comment]
Done, except for the preview mode, which I think we need a new (small) story for.

**Comment by WaBirder57** [comment]
Preview should be set from the Work Party Status Field.  This would be a new value for that Pick List.

Preview means that the WP and details are searchable and visible but that no one can register for it.

**Comment by davisagli** [comment]
Preview is story 192. I believe the rest of this is done, so I'm closing it.
