### ISSUE TITLE
No map view of sorted hikes in MBP

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#411]
When I navigate from the dashboard to "My Hikes" I get a list of all my hikes and, when I click the map tab, a map of all the hikes. So far so good. 

However, when I then try to filter, by region or by hiked/want to hike, the maps no longer work. If I am in the maps tab and I choose a filter, it automatically bumps me back into the list view where the filter seems to be working correctly. But if I then hit the maps tab, I am told no hikes match my search. If I then hit the list tab, it tells me there that no hikes match my search. BUT, if I again hit "search" from the maps tab (not having changed any search criteria), I am again bumped into list view with the correctly filtered hikes.

I tried several times to get back to the original viewing where I could see my unfiltered hikes on the map by changing the filters to "all saved hikes" and then hitting seach but this did not work. Only after I hit "clear form" was I given the correct view.

**Comment by davisagli** [comment]
This should work better now.

**Comment by KindraRamos** [comment]
thanks
