### ISSUE TITLE
"X Registered Volunteers" count under Crew Corner tab should read "X Registered Green Hats"

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#416]
When viewing a roster as a CL, ACL, or admin, you see a line at the bottom of the roster, "X Registered Volunteers." As far as I can tell, "X" is the number of participants minus the leaders (CLs and ACLs). It's misleading and confusing to refer to these folks as "registered volunteers," because ACLs (and some CLs) are volunteers too. Since this line should only be seen by those with leaders and admin permissions (maybe land managers too?), I suggest we go ahead and revise that line to be, "X Registered Green Hats." I sometimes call them "regular volunteers," to distinguish them from volunteer leaders, but "regular volunteers" is kind of weird. "Green Hats" is not perfect because it's insider lingo, but it's better than this line being confusing/misleading.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
This is working. Thanks.
