### ISSUE TITLE
VMS: Consistent language across VMS and SF, for summary reports / work party reports

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#417]
In order to have consistent language, can we change all places in SF that references "work party report" and instead be consistent with VMS in calling it "summary report"? 
To illustrate the inconsistency, this is in VMS: http://prntscr.com/8w2p74
And this is in SF: http://prntscr.com/8w2ok8

**Comment by mscholtz** [comment]
Nineta, do you mind taking this one?

**Comment by ninetaLogik** [comment]
@ebskopin : Since this object in SF will be used for more than just VMS stuff we are thinking it would be too generic to call it Summary Report. Our recommendation is : If it occurs in a VMS Email template call it Summary Report otherwise (Salesforce) call it Work Party Summary Report. Thoughts?

**Comment by ebskopin** [comment]
That sounds workable to me.

**Comment by ninetaLogik** [comment]
@ebskopin I changed the "Work Party Report" labels in Salesforce to say "Work Party Summary Report". I could not find any instances of the string "Work Party Report" in any of the email templates. Could you please take a look and let me know if this is any better with this new label?

**Comment by mscholtz** [comment]
Elliot, by "label", Nineta means that that's what it shows on-screen
whenever you see a reference to a record of this kind.  Internally the name
hasn't changed, but what it displays to the user has changed.

On Wed, Dec 9, 2015 at 9:58 AM, ninetaLogik <notifications@github.com>
wrote:

> @ebskopin <https://github.com/ebskopin> I changed the "Work Party Report"
> labels in Salesforce to say "Work Party Summary Report". I could not find
> any instances of the string "Work Party Report" in any of the email
> templates. Could you please take a look and let me know if this is any
> better with this new label?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/417#issuecomment-163340468>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ebskopin** [comment]
looks good
