### ISSUE TITLE
VMS: Confirmation E-mails Not Being Sent

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#419]
It appears, as of 11/11, that confirmation e-mails for WP registrations are not being sent.

**Comment by davisagli** [comment]
Based on his comment in #210 I think @drewpiston may be doing some work on the confirmation emails today.

**Comment by drewpiston** [comment]
That's correct! Also, the new design means that a value must be selected from the new Email Registration Template field on the Work Party Type in order for emails to be sent out.

**Comment by ebskopin** [comment]
Gotcha.  I'll assign those "Email Template Name Registration" fields to the respective work party types.

Thanks.
