### ISSUE TITLE
WaitList Work Party Info Tab

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#42]
The info tab for a Full Work Party should show the button text "Join the Waitlist" - not Join the Work Party.  All red colors should be Gray.  Note that this is in 2 locations, see screen shot for http://staging.wta.org:6543/workparty/a27J0000001nBgBIAU/

![workpartydetailforwaitlist](https://cloud.githubusercontent.com/assets/8312206/6475598/fbd1c554-c1c0-11e4-8f5c-33cb6e38d3b7.JPG)

**Comment by davisagli** [comment]
This should work better now.

**Comment by WaBirder57** [comment]
Can the text in both button's be the same "Join Waitlist"?  The one in the Info Tab now reads "Join the Waitlist".  Thanks

**Comment by davisagli** [comment]
Okay, they now both say "Join Waitlist"
