### ISSUE TITLE
MBP: WP Calendar renders wrong day/date on Internet Explorer

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#420]
For Example: In IE, the Thanksgiving Day Work-party is on the correct date (Nov 26th) but the day of the week is incorrect (Tue rather than Thurs).
https://mail.google.com/mail/u/0/?ui=2&ik=4af4fdd411&view=att&th=150f75ccef7fab71&attid=0.1&disp=safe&realattid=f_igv0o3ib0&zw

**Comment by davisagli** [comment]
That's a link to your inbox, which of course I can't see. Can you post a screenshot or URL for the work party here?

**Comment by ebskopin** [comment]
![ie calendar 1](https://cloud.githubusercontent.com/assets/14843712/11099351/b10dbdd2-885f-11e5-8c2b-064d019b92f8.JPG)

**Comment by davisagli** [comment]
Ha, it's wrapping wrong and only showing 6 days per row.

**Comment by davisagli** [comment]
Fixed (clear your cache)

**Comment by ebskopin** [comment]
looks good.
