### ISSUE TITLE
MBP: prevent users from upvoting their own trip reports?

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#423]
Should we hide the "thumbs up" widget when a user is looking at a trip report that they created themself?

**Comment by ebskopin** [comment]
I would vote yes, we should.  I just testing #235 and thinking it a little strange that I could upvote my own trip report.

**Comment by davisagli** [comment]
That's how I noticed it too.

**Comment by davisagli** [comment]
Done. If you view your own trip report it should now say "[n] people found this trip report helpful." and not give the option to vote. (You probably need to force-reload/clear your cache.)

**Comment by KindraRamos** [comment]
Works in Chrome and Firefox. In IE it looks this:
![ie view of my trip report upvote](https://cloud.githubusercontent.com/assets/15238703/11197552/029e4bd2-8c73-11e5-8bab-ac80bf15a6b8.PNG) 
Text is correct but the thumb is one the wrong side. Yes I did a force clear of the cache.

**Comment by davisagli** [comment]
Okay, that's a different issue but we'll work on it.

**Comment by davisagli** [comment]
Okay, clear your IE cache and it should display correctly now.

**Comment by KindraRamos** [comment]
looks good
