### ISSUE TITLE
VMS: Work Party End Date should be displayed on VMS work-party map

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#427]
Presently, multi-day workparties (VV, BCRT, Weekend) only display the start dates on the MBP workparty map: 
![image](https://cloud.githubusercontent.com/assets/14843712/11153305/d699edd0-89ec-11e5-902e-f5f47be6895d.png)
 
It would be helpful to have the end date displayed for these workparties in this context.

**Comment by skleinfeldt** [comment]
@ebskopin does this ticket really come under MBP budget? It is about work parties...??

**Comment by davisagli** [comment]
I fixed the labels.

**Comment by ebskopin** [comment]
whoops, thanks for adjusting.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
looks good
