### ISSUE TITLE
Date appears twice on trip report

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#428]
When reading a trip report – Under the trip reporter name it says “Hiked Aug 18, 2015, Aug 18, 2015”. one is linked the other is not. 
![trip report date appears twice](https://cloud.githubusercontent.com/assets/15238703/11156616/cc4e5c70-8a01-11e5-9602-e57617f9cbce.PNG)

**Comment by davisagli** [comment]
This is now more consistent between the trip report listing and the detail view of a trip report. It shows a relative date (e.g. '5 days ago') if it was under 2 weeks ago, otherwise the full date. If it's a relative date you can mouseover the date to see the full date.

**Comment by KindraRamos** [comment]
Looks good
