### ISSUE TITLE
VMS: Edits needed to Registration Form (all users)

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#431]
![image](https://cloud.githubusercontent.com/assets/14843712/11157342/b4c69000-8a05-11e5-9abf-8fb3e76a4247.png)

Changes:
- [x] Replace the help text underneath the Carpool message field with: “Please list your preferred meeting point such as a park & ride, neighborhood or town.” [current text is too Seattle-centric]
- Under Bringing someone with you, replace the 2nd sentence with “For larger party sizes please contact us.” Insert a hyperlink for “contact us” that goes to volunteer@wta.org. [Someday we could replace this with a link to a group inquiry form].

Other important note:
- We would like the ability to edit headers and especially help text in the future. Will we have access to do this? If not, let’s add a story for Phase 2 to make this possible.

![image](https://cloud.githubusercontent.com/assets/14843712/11157349/c0b95f96-8a05-11e5-91bb-20056d340f81.png)
Changes:
- [x] “Work Party” in the “Have a question or comment…” header should be all lower case 

![image](https://cloud.githubusercontent.com/assets/14843712/11157365/cd3f275a-8a05-11e5-8d74-3e2f0ce6cafd.png)
Changes:
- [x] Remove headers for Sentient Life Verification and One Last Thing
- [x] Remove rule [line] separating the robot section from the release waiver section. This can be combined in one “section” of the form.

**Comment by davisagli** [comment]
@ebskopin the help text under "Bringing someone with you?" comes from the "Friends/Family Help Text" field on the Work Party Type.

**Comment by ebskopin** [comment]
gotcha, thanks

**Comment by davisagli** [comment]
I took care of the other changes.

**Comment by ebskopin** [comment]
done
