### ISSUE TITLE
"Dynamic Breadcrumbs" and volunteer tab highlight to match wta.org

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#434]
Anytime you are within VMS, the "Volunteer" tab under the main navigation should be highlighted in Orange when , just like the behavior on wta.org.

Current VMS, which doesn't highlight "Volunteer" in orange: 
![image](https://cloud.githubusercontent.com/assets/14843712/11159422/15a5b2f8-8a14-11e5-9cad-2f60a30f0177.png)

Correct highlighting behavior on wta.org with "Volunteer" in orange: 
![image](https://cloud.githubusercontent.com/assets/14843712/11159427/1dfb17ae-8a14-11e5-8048-f8836631a8f4.png)

VMS should match the same dynamic breadcrumbs that we currently see on wta.org. We want the look and feel to be the same, in addition to the breadcrumb list.
Breadcrumbs (which are at the very top of the page, below the header) should display on all VMS pages as Home >> Volunteer >> [page name] >> etc
Breadcrumbs need to be addded to the top of the Find a Work Party page
When you click into the work party detail, the breadcrumbs at the top of that page need to be updated to match the look and feel of wta.org, and to display as Home >> Volunteer >> Find a Work Party >> [work party name]

![image](https://cloud.githubusercontent.com/assets/14843712/11159405/f0504554-8a13-11e5-8261-2846900b32d4.png)

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
Looks good. Thanks.
