### ISSUE TITLE
VMS: iOS bug when "?" on Work Party filters clicked

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#435]
When the "?" next to the sub headings for the work party filter is clicked on iOS the screen is overlayed with a grey box that is difficult to navigate out of.

![image](https://cloud.githubusercontent.com/assets/14843712/11159537/4c6fb15c-8a15-11e5-978b-cbd8e14e55a4.png)

**Comment by davisagli** [comment]
Should work better now. This wasn't working in the design mockup either; I had to switch to a different way of styling the modal dialogs.

**Comment by ebskopin** [comment]
This is working as intended now.
