### ISSUE TITLE
Share (e-mail, FB, Twitter) feature on WP currently inactive 

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#436]
![image](https://cloud.githubusercontent.com/assets/14843712/11159659/b911f468-8a16-11e5-9f33-971d6994ae58.png)

Thinking that it should be activated or removed prior to launch. Not sure if the activation needs to happen now...

**Comment by davisagli** [comment]
These are stories 88 & 89 which are in the phase 2 backlog.

**Comment by ebskopin** [comment]
gotcha, figured they were in there but couldn't find them

**Comment by davisagli** [comment]
I hid the "share" block for now, as well as the unimplemented "Apply For Scholarship" block that shows up for youth work parties (I'm not even sure we have a story for that one)
