### ISSUE TITLE
Error when attempting to register 5th guest on day WP

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#437]
Trying to register 5 people on my day work party. Get this error when I finally click "Register". Same thing doing this logged in vs. doing it as a guest. No problem when I'm not registering for more people.

This is the work party: http://staging.wta.org:6543/workparty/a2eK00000000kDF/

Not sure if this is a bug or they are just messing with the code...

Error Code 500. Response content: [{u'errorCode': u'APEX_ERROR', u'message': u'System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn\u2019t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 301K0000000CwSM. Contact your administrator for help.: []\n\nClass.WTA_VMS_REST_CreateRegistration.createRegistrations: line 260, column 1\nClass.WTA_VMS_REST_CreateRegistration.doPost: line 151, column 1'}]

**Comment by davisagli** [comment]
Maybe related to the flow @drewpiston was working on for registration confirmations?

**Comment by mscholtz** [comment]
@drewpiston can you check into this one?  Guessing it's already resolved by now, but let's verify.

**Comment by drewpiston** [comment]
I was unable to reproduce this error -- but I did find another limits error with the NPSP, which I've now fixed.

I've asked @mscholtz to code review.

**Comment by mscholtz** [comment]
code review is done.  @ebskopin , please close this one if you don't see the error happening any more.

**Comment by ebskopin** [comment]
tested earlier today and no longer getting an error. thanks.
