### ISSUE TITLE
VMS: Edits needed to Registration Form (Guest users)

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#439]
![image](https://cloud.githubusercontent.com/assets/14843712/11160136/13117854-8a1b-11e5-8c42-dd0af6990509.png)

Note: The view above is the expanded view you see when you click the “+” symbol next to “5 Reasons to Have a Backpack Account”

Changes:
- [x] Replace “Do you already have a My Backpack account?” text with “Already have an account?”
- [x] Remove the “5 Reasons to Have a Backpack Account”
- [x] Remove the entire expanded section including “Value of My Backpack Account” [this will be covered lower down on the form] and the “Get My Backpack” button

![image](https://cloud.githubusercontent.com/assets/14843712/11160139/1c87f0d4-8a1b-11e5-8405-7284369c3627.png)

Note: This is the account section that is lower down on the form. The view above is the expanded view you see when you click the “+” symbol next to “5 Reasons to Have a Backpack Account”

My Backpack section changes:
- [x] “Create My Backpack Account?” checkbox: default this to checked. [Guests can uncheck it if they don’t want to create an account.]
- [x] “5 Reasons to Have a Backpack Account” text: Replace this text with “Why Create an Account?”
- [x] Expanded “Value of My Backpack Account” section: replace the header and numbered list with a single text sentence: “With an account, you’ll be able to manage or cancel your work parties, track your days on trail, file trip reports or make notes on trails you’ve saved to your My Backpack.”
- [x] “Get My Backpack” button: Remove this button. This is a duplicate of the checkbox. [With the checkbox checked, the account will automatically be created when you register for the work party.]
- [x] Screen Name field help text: Change this text to: “This will appear on your My Backpack page, on Trip Reports you write and on any comments you post at wta.org.” Font size should match the help text under the Carpool field above. Also note that wta.org should always be in lower case.

Other important note:
•	We may need to edit the last sentence in this section (“We’ll send you an email…”) prior to launch, pending final changes to the new My Backpack system.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
done
