### ISSUE TITLE
Story #85 When existing user signs up for a work party they have already registered for errors

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#44]
1) The registration form doesn't populate with all the information on that user in Salesforce.  Doesn't include address and phone which are required fields for the registration.
2) If the volunteer is already registered for the work party the following error appears at the bottom of the registration page:
Error Code 500. Response content: [{u'errorCode': u'APEX_ERROR', u'message': u'WTA_REST_CreateRegistration.RegistrationAlreadyExistsException: Contact already has a registration for this workparty\n\nClass.WTA_REST_CreateRegistration.throwException: line 268, column 1\nClass.WTA_REST_CreateRegistration.doPost: line 121, column 1'}]

**Comment by davisagli** [comment]
I'm waiting for Percolator to fix #26 so I can solve part 1 and #7 so I can fix part 2.

**Comment by davisagli** [comment]
Part 1 was fixed in #26.

Re Part 2, it now reports the fact that the user is already registered in a more readable way: "Contact already has a registration for this work party"

**Comment by WaBirder57** [comment]
This works as described, thanks!
