### ISSUE TITLE
VMS: Edits needed to Registration Form (My Backpack users)

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#440]
![image](https://cloud.githubusercontent.com/assets/14843712/11160243/1694ba1c-8a1c-11e5-9bd7-e472af3c3ea6.png)

Changes re: Birth Date:
- [x] Remove the “Birth Date” field and associated text from this view for logged in users. 

Changes/issues for “Congratulations”:
- [x] Move the “Congratulations!” section lower down on the form so that it appears right above the “Have a question or comment about this work party?” [This makes it more intuitive for users to add a comment under the “have a question” section below if they need to.]
- [x] The Congratulations section deploys conditionally [I assume just for the hard hat and saw?] depending on what award has been earned. In this particular instance, where the user has earned their vest, it is not deploying correctly. For people who have earned their vest, they should be able to select the vest size, as shown. However, they should NOT see the editable text field that says “write a message here about earning the vest.” 
- [x] Under the “Congratulations” header, there should be descriptive text, formatted like the text below the “Bringing someone with you?” header, that says “Our records show you’ve reached a new milestone. We hope to have your award ready for your next work party.”   
- For people who have earned their hard hat (not shown), they should have a field in place of “Vest Size” that allows them to enter a nick name for their hat. [This probably exists, I just haven’t been able to test it.]
- If we have concerns about this not deploying correctly, we may need to hold off for launch. (Though it is important, particularly with the hard hats, to get it working.)

**Comment by davisagli** [comment]
Are you sure about removing the birthdate field? There was a whole story for adding it (story 87). Note that it only shows up when "under 18" is checked and we don't yet have a birthdate on file (story 291).

**Comment by davisagli** [comment]
Oh, I guess you mean don't show that part in the case where we already know the birthdate.

**Comment by ebskopin** [comment]
correct.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
thanks.
