### ISSUE TITLE
VMS: Adjustment to Region vs. Location wording

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#443]
The search filter on the Find a Work Party page shows "Regions." However, those regions are labeled as "Location" in the List view and in the Work Party Detail header.

Here are the changes needed:
On the Find a Work Party List view, replace "Location" with "Region" under each work party.
On the Work Party Detail header, "replace "Location" with "Region."

**Comment by davisagli** [comment]
Not sure why you put MBP in the title of this one and labeled it Plone. It's in the pyramid app part of VMS.

**Comment by ebskopin** [comment]
To be honest, I could use some clarity as to what is what. Please adjust tags at will.

**Comment by davisagli** [comment]
For the Plone and Pyramid tags: The work party search and detailed view of a work party are served by the pyramid app, as well as anything you access from them (registration form, crew corner, summary reports) *except* via the top nav bar. Everything else is served from Plone. If in doubt, just don't add a tag for the technology and we'll add it.

For the budget tags: anything to do with work parties is VMS Budget regardless of whether it's an issue in Plone, Pyramid, or Salesforce. Everything else is MBP budget.

**Comment by davisagli** [comment]
Oh -- and if the URL says http://staging.wta.org:6543, it's the pyramid app. If it says http://staging.wta.org (no port number) or mybackpack.wta.org, it's Plone.

**Comment by ebskopin** [comment]
thanks.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
fixed.
