### ISSUE TITLE
Features Vs Highlights Language

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#444]
The search filters include "Features" and the Work Party Info uses the word "Highlights" for the same thing. 

Please replace "Highlights" with "Feature." in the List view on the Find a Work Party page and on the Work Party Detail.

![image](https://cloud.githubusercontent.com/assets/14843712/11196019/174002f0-8c6a-11e5-9672-8260dbac739d.png)

![image](https://cloud.githubusercontent.com/assets/14843712/11196023/1c45f570-8c6a-11e5-80f4-c023360aa5da.png)

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
fixed.
