### ISSUE TITLE
VMS: add online listing fields to Clone WP

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#445]
When cloning a workparty in Salesforce, the "Text for Online Listing" should be cloned.  This includes the Overview, Project Description, etc.

**Comment by mscholtz** [comment]
@drewpiston want to take this one, since you worked on these fields?
There's a class WTA_VMS_EXT_CloneWorkParty that handles this - the button is overridden

And why don't we go ahead and do #245 while you're in there?

**Comment by drewpiston** [comment]
Done! Assigning to @ebskopin  for review, let me know if I should assign to @WaBirder57  instead.

**Comment by ebskopin** [comment]
works, thanks
