### ISSUE TITLE
VMS: Further Edits to Sign-In Sheet

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#446]
Please see below.  The most important item is the language/spelling.

# VMS Sign in Form

## Changes to all instances of the form (via registration form “terms of use” and via “Crew Corner”): 

- [ ] First sentence of liability language needs a merge field inserted that displays the Land Manager associated with the (primary) Trail Segment for the work party. Updated sentence should read: “By signing this form you are releasing Washington Trails Association and Land Manager from any and all liability…” (New text is shown in bold but shouldn’t be bolded in final version).

- [ ] Remove the indent at the start of the first paragraph so the entire paragraph is left-aligned.

- [x] Replace entire 2nd paragraph with this text. (Current version has numerous spelling errors and typos.)

I wish to participate in projects sponsored by Washington Trails Association (WTA). By participating in these projects, I enhance my enjoyment of the outdoors, provide access to underdeveloped wilderness and mountainous areas for myself and others, and meet others with similar interests. I am aware that projects sponsored by WTA involve the construction and maintenance of trails and recreation facilities, and that participation in these projects poses certain dangers, including, but not limited to, the hazards of traveling in and hiking in wilderness and often steep mountainous terrain, using hand or motorized construction tools (and of working in the proximity of such tools when used by others), injury or illness in remote places without medical aid, lifting and working on often narrow and precipitous trails and unforeseen events caused by the forces of nature. In consideration for permitting me to participate in projects sponsored by WTA, I, for my family, my estate, and myself, hereby waive any right of recovery and claims of liability against WTA, its officers, employees and agents, including claims for bodily injury, including death, personal injury and/or damage to property, and release WTA, its officers, employees and agents and release from such claims and any claims made by others for personal injury or property damage allegedly caused by me. Further, I will hold WTA harmless from any loss or damages resulting from the foregoing waiver and release. This Release and Indemnity Agreement is a contract not a mere recital and this it shall remain in effect for all projects sponsored by WTA. The undersigned gives his/her permission to be photographed/filmed and have his/her image used by WTA and their partner agencies, without royalty or compensation. I HAVE READ THIS RELEASE AND INDEMNITY AGREEMENT.

## Changes to sign in form accessed via “Crew Corner” for review and printing:

- [x] All text should be the same sans serif font and same font size. (Currently Project Location, Date, Sign In header, and Walk Up Volunteers are in a different serif font and a smaller size).
- [x] Project Location, Date and “Sign In and Liability Release” header at the top of the form should all be bolded. 
- [x] Date (top right) should include the year.
- [ ] Add “Page #” in the top right of each page.
- [x] Eliminate spacing between 1st and 2nd paragraph.
- [x] Condense line spacing within the paragraphs. (It takes up way too much space on the page currently.) 
- [x] Page 1 needs to fit at least 12 volunteers. This may be feasible by displaying the roster in 2 columns. (More condensed line spacing for the liability language will help.) 
- [ ] If the release goes into a 2nd page, the release language should be displayed at the top of each subsequent page.
- [x] WTA logo should be re-sized to match our brand guide. Height should be 1.3 inches. Text should be wrapped with 0.25 inch spacing below and to the right of the logo.

## Changes to sign in form accessed via “terms of use” on the registration form:

- [x] Remove WTA logo. (This already appears on the navigation header on the web page. It is distracting to duplicate it.)

## Other issues:

- [x] We periodically (up to annually) need to update our sign in language. How will we be able to do that?
- [ ] Haven’t been able to test this yet with a Land Manager who has custom liability language in addition to WTA’s standard language…

**Comment by davisagli** [comment]
The language for the liability waiver comes from Salesforce so it's up to you to enter it as you like. For each trail segment it looks for the corresponding land manager and displays the text from its "Liability Waiver Text" field. If that's blank it looks for a value in parent land managers. In addition, it shows the global liability waiver which comes from this record: https://cs9.salesforce.com/a2sK0000000HWkB

So you can take care of some of this there, like editing the language and adjusting the logo. You also control the text formatting to some degree here, so we're limited in how we can change the formatting on the pyramid side.

How about you do a pass at updating the language and formatting there, and then we'll take a look to see if we can fix any of the above items that you can't take care of.

**Comment by ebskopin** [comment]
ok, thanks.

**Comment by ebskopin** [comment]
Ok, I've edited the text and have removed those components from the story.  Let me know if there is anything further I can do.

Thanks.

**Comment by davisagli** [comment]
I've taken care of some of the above.

I still need to look into adding page numbers and repeating the waiver text on each printed page. Are you sure about the latter? I'm not sure if it's possible, but even if it is, the waiver text may be too long if there are multiple land managers each with their own text.

These items are still for you, I think, @ebskopin:
- Remove the indent at the start of the first paragraph so the entire paragraph is left-aligned. (This is in the field in Salesforce.)
- Eliminate spacing between 1st and 2nd paragraph. (This is a blank line in the field in Salesforce.)
- WTA logo should be re-sized to match our brand guide. Height should be 1.3 inches. Text should be wrapped with 0.25 inch spacing below and to the right of the logo. (This might be easier to handle if we take the logo out of the field in Salesforce and instead add it to the sign-in sheet template in the pyramid app. Let me know if you want me to do that.)
- Haven’t been able to test this yet with a Land Manager who has custom liability language in addition to WTA’s standard language… (Please do.)

**Comment by davisagli** [comment]
I looked a bit more into adding page numbers and repeating the waiver text on each page. Unfortunately browsers have no support for doing this.

**Comment by ebskopin** [comment]
Thanks David. If we could pull the logo into the pyramid app with that sizing that would be great. I've taken care of the other items on that list and will test with land manager language.

**Comment by davisagli** [comment]
Okay the logo is now part of the sign-in sheet template rather than part of the waiver text in Salesforce.

**Comment by ebskopin** [comment]
closing, a few more edits needed but will write new ticket likely w/ lower priority.
