### ISSUE TITLE
VMS: Further Edits to Registration Form

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#447]
For all instances of the form:
Change the label for the Birth Date field to Birthdate. We use it as one word in the new My Backpack and that is the more common useage.
For Guests:
Under the "Create My Backpack Account" section:
Remove the 2 rules [lines] above and below the Screen Name field. (This only appears when the account checkbox is checked.)

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
done.
