### ISSUE TITLE
Work Party Volunteer sees fellow Carpool emails

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#45]
As a volunteer signed up for a work party - not signed up for carpool -  I see the list of all crew members who have signed up for car pooling.  This should *only* be visible if i have signed up for carpooling.

**Comment by davisagli** [comment]
"signed up for carpolling" means entered something other than "no thanks" ?

**Comment by WaBirder57** [comment]
That is correct.  When a volunteer shows as "no thanks" they should not see car pool information for other crew members.

**Comment by davisagli** [comment]
This should be fixed now. Please confirm and then close the issue.

**Comment by WaBirder57** [comment]
Look good.
