### ISSUE TITLE
photo pull from trip reports to profile dash should be pulling more recent photos

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#451]
The photos pulled into the profile photo bar should be from the most recent trip reports not randomly selected.

**Comment by skleinfeldt** [comment]
[Story 295 in iteration 19](https://www.scrumdo.com/projects/project/wta/iteration/130352#story_1027325): "Use trip reports first, image gallery if they don't have enough trip reports; max 3 images, use the images from the most recent trip report each time you view the page; automatically cropped to fit the space." Later @davisagli added a comment: "Charlie says for now: 3 trip report images, chosen randomly and scaled/cropped to fit. Or images from gallery if there are no trip reports." 

Just making sure we want to reverse course.

**Comment by KindraRamos** [comment]
Hi Sally – 

 

Yeah Charlie and I talked about this but I don’t think he had a chance to update. Learning from Facebook’s memories work we don’t want to pull up photos of exs or the deceased. I think most recent is the best course here. thanks

 

Kindra Ramos – director of communications and outreach 

Washington Trails Association 

wta.org * 206-965-8563 

 

WTA is powered by hikers like you!

**Comment by skleinfeldt** [comment]
Goodness I hadn't considered that possibility... Point taken.

**Comment by cguardia** [comment]
Fixed on mybackpack-buildout branch.

**Comment by KindraRamos** [comment]
looks god
