### ISSUE TITLE
mobile upload of profile pic doesn't orient 

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#452]
When I upload a photo from my iphone5 it displays sideways. I think that Jesse fixed a similar issue on trip reports for us earlier this year.

**Comment by davisagli** [comment]
@jessesnyder any pointers on this?

**Comment by jessesnyder** [comment]
@davisagli I don't know if you have an opportunity to "touch" the image during this process, but if you do, calling wta.content.imageorientation.autocorrect(theImage) might do it.

**Comment by davisagli** [comment]
Thanks. We can try doing that in the user preferences form code.

**Comment by davisagli** [comment]
This works now.

**Comment by KindraRamos** [comment]
looks good thanks
