### ISSUE TITLE
VMS: Medical & Backcountry Experience Info should not be visible on crew corner roster

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#454]
Presently, a crew leader can click on the names of those individuals registered for their work-party under the Crew Corner Tab and "Crew" subheading, and view information regarding their certifications, awards, etc.  Included in this info is the Medical Info and Backcountry Experience info from respective forms filled out by the contact:

![image](https://cloud.githubusercontent.com/assets/14843712/11226191/2b553750-8d33-11e5-994f-035bf82d21b9.png)

We no loner want this info to display here. The Crew Leader can view this info under the "Crew Leader Toolkit," and we don't want this medical info to be visible.

**Comment by cguardia** [comment]
Fixed on master, but not deployed yet.

**Comment by ebskopin** [comment]
looks good, thanks
