### ISSUE TITLE
VMS: "Edit" button on Reports tab should not appear for ACLs

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#455]
Logged in as an ACL, viewing the "reports" tab, it's a little misleading that there's an "edit" button. The system correctly does not allow an ACL to edit the summary report, but the button is still there. Nothing happens when "edit" is clicked. If possible, it would be nice to not have the "edit" button display for ACLs.

![image](https://cloud.githubusercontent.com/assets/14843712/11227329/30c3738a-8d3a-11e5-91c0-35f5f646d34f.png)

**Comment by cguardia** [comment]
Fix is on master, but not yet deployed.

**Comment by ebskopin** [comment]
I'm seeing that the "Edit" button at the top of the form is no longer visible for ACLs, but the same button at the bottom of the form is still visible.  Can that button be removed as well? Thanks.

**Comment by davisagli** [comment]
@cguardia can you take care of that too? ^

**Comment by cguardia** [comment]
Fixed. Sorry about  that oversight.

**Comment by davisagli** [comment]
Thanks, deployed the fix.

**Comment by ebskopin** [comment]
Thanks, looks good.
