### ISSUE TITLE
prevent mass entry of registrations from different WPs / family groups

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#456]
Currently, the trigger which enforces capacity on WPs expects only a few registrations to be inserted or modified in one transactions, and it expects them to all be for the same WP.  (and part of the same family group, although that last is slightly less important).  VMS registrations, as well as individual registrations hand-entered by staff, should all fit this pattern.

What won't fit is imports or other mass entry.  Even if we told staff they shouldn't import registrations, someone will forget some day.  And the trigger doesn't prevent imports, but it will produce unexpected results (probably by putting everyone on the waitlist!)

So as a failsafe, I propose:

1. Include a mechanism (either a checkbox on the reg record, or a custom setting) that will bypass the capacity check entirely
2. Have the trigger check to see if either a) there is more than one WP represented in the batch, or b) the batch size is larger than x
3. If 2 is true, but 1 is not set, then throw an err.  The import will fail, with a helpful error message, and the user will have to bypass the capacity before importing.

**Comment by mscholtz** [comment]
It's possible this should be a story.  But @ebskopin or @WaBirder57 please prioritize.

**Comment by davisagli** [comment]
I think we already have a mechanism to bypass the capacity check for a registration -- the Beyond_Capacity__c field. We added this so the pyramid app can pass it when the CL adds someone to the roster after the work party has started (i.e. to handle if someone shows up who wasn't registered).

**Comment by mscholtz** [comment]
OK, right.  So then we just need 2 and 3 above.

**Comment by ebskopin** [comment]
I would envision that we will be doing a good bit of mass entry during the Data Migration & Creation stage, when registrations are needing to be transferred from our existing system onto VMS, but perhaps this doesn't fall under the "imports or other mass entry" category.  If it doesn't then I wouldn't see this as a especially pressing, but if some aspects of our transition will likely involve imports I would say this is a high priority story.  Should I write up the story and place it in the backlog?

**Comment by mscholtz** [comment]
Should have specified: for the data migration prior to VMS launch, we'll be doing a mass creation of historical registrations, based on the Vol Jobs you already have in there.  The problem described here isn't a problem for that process, as we already have a way to disable the capacity checks during the migration.  So I'm thinking of this as a failsafe against a future day, when you guys might try to do an import without remembering this issue.

**Comment by ebskopin** [comment]
Ok, with that in mind it seems that 2 & 3 are sufficient.  Thanks for clarifying.

**Comment by mscholtz** [comment]
OK, but even 2 and 3 aren't built yet, so we still need to either write a story, or prioritize this ticket for that.

**Comment by ebskopin** [comment]
Ok, I wrote a story and placed it in the backlog. I will move it the the appropriate rank now.

**Comment by mscholtz** [comment]
Great, thanks.  Closing this.
