### ISSUE TITLE
map view of my trip reports is not showing reports

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#457]
When I look at the map view of my trip reports it says that it has found all 12 but only displays one. 
![my trip reports not showing up on map view](https://cloud.githubusercontent.com/assets/15238703/11247091/7973f7c2-8dcf-11e5-964e-8152690227cc.PNG)

**Comment by davisagli** [comment]
I think it's only displaying trip reports that have a Trailhead Location set. I guess we need to inherit the Trailhead Location from the trip report's (first) hike if the trip report doesn't have a Trailhead Location set?

**Comment by davisagli** [comment]
Fixed.
