### ISSUE TITLE
Menu Bar formatting bug in Chrome and Firefox

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#458]
The menu bar on Chrome and firefox is not as smooth as the other browsers. The Membership option shows up under Find a Hike instead of to the far right. (see attached)

It especially makes it difficult on Chrome where, in order to reach the submenus under "find a hike" I have to click on it instead of just mouse over. 

![image](https://cloud.githubusercontent.com/assets/14843712/11289177/2482ed3e-8edf-11e5-9739-06c69fd48775.png)

**Comment by davisagli** [comment]
It works fine for me unless I zoom out on the View menu. Can you confirm this only happens for you when you've zoomed out from the default zoom?

**Comment by ebskopin** [comment]
Yep. That was an observation of Tiffany's. I find the same thing you do, David.  The Membership tab flips once I zoom out.  Is that an expected quirk? Should I close ticket?

**Comment by davisagli** [comment]
Not expected, or desirable, but may be hard to avoid. I'll at least check and see if there's a quick fix.

**Comment by davisagli** [comment]
Should work better now.

**Comment by ebskopin** [comment]
Thanks for taking a look, David.  I'm still seeing this manifest on my MBP account: 

![image](https://cloud.githubusercontent.com/assets/14843712/11345267/a8b135aa-91ca-11e5-828a-96437eca1737.png)

**Comment by davisagli** [comment]
Close the ticket if it works on staging. I probably just didn't deploy the fix to mybackpack yet.

**Comment by ebskopin** [comment]
Will do. Thanks.
