### ISSUE TITLE
VMS: Salesforce-Plone Hiking Guide Sync not occuring

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#460]
In Salesforce, when the URL for a Hiking Guide Entry from staging.wta.org is entered under a Trail Segment Hiking Guide Entry to a trail segment the additional information is not being fetched from Plone and populated under the trail segment.  

An example: https://cs9.salesforce.com/a2kK0000001MOEy

**Comment by davisagli** [comment]
Hmm, @smcmahon it looks like on the staging server the apache configuration directs urls starting with /wsv to port 9080, where nothing is running. Did you miss updating this when you changed the ports on staging to match the ports on production?

**Comment by davisagli** [comment]
I fixed the port issue, edited your example and it populated successfully.

@ebskopin remember that you need to mark a Trail Segment Hiking Guide Entry as primary in order for it to update the fields on the Trail Segment.

**Comment by ebskopin** [comment]
Works.  And thanks for the note on checking primary.
