### ISSUE TITLE
full nav menu won't display on mobile

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#461]
Doing some more mobile testing and I can't pull up a menu on the staging site. The "my backpack" menu comes up and I can get to my dashboard but when I hit the three horizontal lines for site menu it just gives me a search option instead of the full menu.
![mobile nav](https://cloud.githubusercontent.com/assets/15238703/11477495/187a2cd0-973d-11e5-8de6-67359e24440b.PNG)

**Comment by davisagli** [comment]
Sorry, I broke this when I fixed #458. Should be fixed now.
