### ISSUE TITLE
MBP: WTA Home Page top item hyperlink style not working

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#463]
On the WTA Home page we have a top level item (article) that displays just below the main menu bar.  This is set to cycle through server different articles.  In each article the main heading is a hyperlink but when you mouse over it the text doesn't change color as it does in production.

Here is a screen shot from todays production home page with the heading circled in red.  This does change color when you point to it with the mouse.

![wtahomepagetitlelinkerror](https://cloud.githubusercontent.com/assets/8312206/11547584/f1687920-9909-11e5-8009-dfbb429d5520.JPG)

Here is a screen shot from Staging.WTA.org which shows the header circled in red which doesn't change color when you mouse over it.  This should behave the same is in production.

![stagingwtahomepagetitlelinkerror](https://cloud.githubusercontent.com/assets/8312206/11547612/1cb30726-990a-11e5-8f59-afe3d8ddb0e5.JPG)

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Looks good.
