### ISSUE TITLE
MBP: My Backpack for a user has a tile "My Backpack 101"  text needs to be edited

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#464]
When you look at a users My Backpack "home page"  ( eg: http://staging.wta.org/@@backpacks/scrnm-WaBirder57) there is a tile "My Backpack 101".  This currently talks about Organizing WTA Work parties ie VMS which is not implemented yet.  Is it possible to make the text in this box editable by staff?

![mbphomepagetile](https://cloud.githubusercontent.com/assets/8312206/11566928/6f9d5876-9999-11e5-971f-b6db3615dcb8.JPG)

Also the link in this tile to: http://staging.wta.org/about/my-backpack doesn't exist.  Is this content that we need to create or does the link need to be changed?

**Comment by davisagli** [comment]
> When you look at a users My Backpack "home page" ( eg: http://staging.wta.org/@@backpacks/scrnm-WaBirder57) there is a tile "My Backpack 101". This currently talks about Organizing WTA Work parties ie VMS which is not implemented yet. Is it possible to make the text in this box editable by staff?

It's probably easiest if we pull the text from a news item like we're doing at the top of the Crew Leader Corner and for the ad in the work party results. Can you add a news item on www.wta.org with the text you want, and give me its URL?

> Also the link in this tile to: http://staging.wta.org/about/my-backpack doesn't exist. Is this content that we need to create or does the link need to be changed?

As far as I know it hasn't been created.

**Comment by KindraRamos** [comment]
Ok you can find the text here: http://www.wta.org/connect/help/internal-promos/my-backpack-101 

I also pasted it below as I am not sure how it pulls. (The all caps is button text)
My Backpack 101
Plan and organize your hikes, track your trip reports and share your adventures with the hiking community. Thanks to your suggestions and support we have added some exciting new features to My Backpack. Have feedback or questions? Tell us what you think.

MY BACKPACK TIPS & FAQS

**Comment by davisagli** [comment]
@KindraRamos please either make the "MY BACKPACK TIPS & FAQS" text actually be a link to where you want the button to go, or remove it.

**Comment by KindraRamos** [comment]
Ok we wanted keep the button look and feel so interested the image and linked it. Let me know if that works.

**Comment by davisagli** [comment]
Oh I was actually going to apply button styles to the link. In any case, I can take it from here...

**Comment by davisagli** [comment]
Okay, this is in place. I made a copy of your item which is used on staging (http://www.wta.org/connect/help/internal-promos/my-backpack-101) so you can test how the tile looks in someone's dashboard there. 

And I also edited the one on www.wta.org so that it will get the correct styles applied once we launch.

**Comment by KindraRamos** [comment]
this is great thanks
