### ISSUE TITLE
Change highest upvote language

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#466]
Our user tests today showed we should change the upvote language on trip reports. Change Highest Upvote to Top Helpful Rating.
![highest upvote2](https://cloud.githubusercontent.com/assets/15238703/11578679/7f489b44-99dc-11e5-93d0-d6ab34b9f182.JPG)
![highest upvote](https://cloud.githubusercontent.com/assets/15238703/11578681/80f0c962-99dc-11e5-8f66-c5775774f541.JPG)

**Comment by davisagli** [comment]
done

**Comment by KindraRamos** [comment]
thanks

**Comment by davisagli** [comment]
Maybe we should not show this when the user's Top Helpful Rating is 0. What do you think, @KindraRamos?

**Comment by KindraRamos** [comment]
I think that is a good idea. Thanks
