### ISSUE TITLE
Backpack hikes marked "hiked" see to vary by instance(?)

### ISSUE THREAD

**Issue by jessesnyder** [washingtontrails/vms#467]
Both the total and the hikes marked with the green box and checkmark vary on refresh, and are lower than the total number I marked as hiked, as if each time I marked one as hiked, it was saved in a different place.
<img width="325" alt="screen shot 2015-12-03 at 8 46 46 pm" src="https://cloud.githubusercontent.com/assets/63560/11582163/d5ed53c2-99ff-11e5-8e59-e1b3060f9ddd.png">
<img width="325" alt="screen shot 2015-12-03 at 8 46 59 pm" src="https://cloud.githubusercontent.com/assets/63560/11582166/dee3c51a-99ff-11e5-84f9-d6b6756f7cd5.png">
<img width="327" alt="screen shot 2015-12-03 at 8 47 11 pm" src="https://cloud.githubusercontent.com/assets/63560/11582167/e34236d2-99ff-11e5-8d5d-3050563931f8.png">

**Comment by WaBirder57** [comment]
Related to this although perhaps different for this tickets topic is that when you click "Hiked" button for a saved hike a popup opens to ask if you want to write a trip report.  If you leave that open and then clicked "hiked" once to clear the setting and then click "Hiked" once again you get another pop up asking if you want to create a trip report.  It you repeat this you keep getting additional popups.  Seems like the behavior should be that if the "hiked" box is deselected and the Trip Report pop up is present, the trip report pop up should be closed. 
![tripreportpopuperror](https://cloud.githubusercontent.com/assets/8312206/11602771/bdfcf08c-9a91-11e5-9266-67bf19c211c1.JPG)

**Comment by davisagli** [comment]
That's a different issue @WaBirder57; can you please put it in a separate ticket?

**Comment by WaBirder57** [comment]
OK, moved this new item to it's own ticket #475

**Comment by davisagli** [comment]
Jesse's issue is fixed.
