### ISSUE TITLE
Upcoming Trail Work Parties portlet

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#468]
I noticed the site currently has a portlet with upcoming work parties that looks like it pulls from VOLS:

![screen shot 2015-12-03 at 11 56 25 pm](https://cloud.githubusercontent.com/assets/49014/11584548/92da31f8-9a19-11e5-864d-effbf3a50de9.png)

If you want to keep this we'll need to do a story to load them from VMS instead.

**Comment by ebskopin** [comment]
Yes, it would be good to have this.  Thanks for pointing out. Should I write a story? Where should it be?

**Comment by davisagli** [comment]
If it's a story then it won't get done unless we schedule more iterations. But it's definitely more work than a typical ticket.

**Comment by skleinfeldt** [comment]
If you're feeling good about the state of tickets and testing, we could consider doing a 2-3 day iteration for this story and one or 2 others from the backlog - if there are any Pyramid/Plone stories you particularly care about. Jazkarta still has plenty of time. (I'd want to do that next week or the next, not put it off until January.)

If this is the only story-ish thing you want to get done then it might as well stay a ticket, even though it is large.

**Comment by skleinfeldt** [comment]
Jazkarta can do a ~20 hour mini-iteration next week, say Tue-Wed-Thu; we could tackle this story, another backlog story if there is one (92?), and tickets. @mscholtz does Percolator have hours next week to join us and tackle story 328? (carpool list automated email).

**Comment by mscholtz** [comment]
TBD, Sally.  Already having a separate convo w/ them over email about what
we're doing this week and next.  But we don't have a ton of time for
stories, as there are already a bunch of tickets we're working on.

On Wed, Dec 9, 2015 at 11:37 AM, Sally Kleinfeldt <notifications@github.com>
wrote:

> Jazkarta can do a ~20 hour mini-iteration next week, say Tue-Wed-Thu; we
> could tackle this story, another backlog story if there is one (92?), and
> tickets. @mscholtz <https://github.com/mscholtz> does Percolator have
> hours next week to join us and tackle story 328? (carpool list automated
> email).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/468#issuecomment-163367740>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
This was implemented as story 330 and can be tested on mybackpack.wta.org

**Comment by WaBirder57** [comment]
Should we put this portlet on vms.wta.org?  It seems to work great on mybackpack.wta.org

**Comment by davisagli** [comment]
you mean on www.wta.org. I'll deploy it there as part of the final launch next week.

**Comment by WaBirder57** [comment]
Here is an example of what I currently received with the new info at the bottom.  Note if you could improve the time formatting that would make this more readable also:

Subject: Directions for TEST Day Work party - Taylor Mountain

Charlie Kahle sent you directions to the TEST Day Workparty - Taylor Mountain work party on 2016-02-29T08:30:00-08:00.

From I-90 take exit 17 (Front Street), and turn right (south) onto Front Street and continue south through Issaquah. Front Street becomes Issaquah-Hobart Road as you leave town. Continue south along this road to its junction with State Route 18. Cross under SR 18 and drive another 0.25 mile, passing Holder Creek at SE 188th Street. Park near Holder Creek. 

Special Event Spot
Country Pride Restaurant, in North Bend
From Seattle, head east on I-90 to exit 34 468th Ave SE. From exit ramp turn left and cross over the freeway. Go north 0.3 miles and turn left into the parking lot for the restaurant at 46600 SE N Bend Way, North Bend, WA 98045.

**Comment by davisagli** [comment]
Got it, thanks.
