### ISSUE TITLE
Display GPS track on work party map

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#47]
If a hiking guide URL is configured, we should be able to determine the URL for a kmz file which we can use to display a GPS track on the map.

sample path for kmz file: /home/wta_kml/lake-ann.kmz (for this hike: http://www.wta.org/go-hiking/hikes/lake-ann) ...we need to figure out what URL this is served at for the hiking guide map, and possibly add CORS headers so it can be loaded from the VMS domain)

**Comment by WaBirder57** [comment]
An actual example of this working in the hiking guide is for Bandera Moutain.  Go to http://www.wta.org/go-hiking/map, search on "Bandera", click on the trail head icon.  A GPS track will be displayed over the Topo map showing the hike track.

**Comment by davisagli** [comment]
This is now set up when looking at the Location tab for a particular hike. It's based on the work party's Plone Hike Url.

Example: https://cs10.salesforce.com/a27J0000001nByO has Plone Hike Url = http://www.wta.org/go-hiking/hikes/mount-si, so it loads http://wta.org/kml/mount-si.kmz and shows it on the map.

**Comment by WaBirder57** [comment]
Ticket #47 works with GPS track.  This is closed now.
