### ISSUE TITLE
MBP: Table Styles

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#472]
We find that with the new MyBackpack install our existing table styles have changed rendering them not readable.  Seems like a colored background has been added and all text is in caps.  

Here are pages with some examples:
https://www.wta.org/hiking-info/outdoor-leadership/workshops
https://www.wta.org/action
https://www.wta.org/go-hiking/hikes/amendment.2015-12-04.4787074982/edit

**Comment by davisagli** [comment]
Fixed. Sorry about that, there were some MBP table styles that were meant just for the Crew Leader directory but were not targeted specifically enough.

**Comment by WaBirder57** [comment]
Perfect, thanks.
