### ISSUE TITLE
MBP profile external urls are all linking back to wta.og

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#473]
If someone has entered an external website, to be displayed on their My Backpack page. It shows their url but links back to wta.org
![url](https://cloud.githubusercontent.com/assets/15238703/11598630/f0ffa1b0-9a77-11e5-9d53-95e5cc09b6ed.JPG)

**Comment by davisagli** [comment]
Fixed.

**Comment by KindraRamos** [comment]
thanks
