### ISSUE TITLE
generic avatar 

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#474]
The generic hiker avatar (full body) seems to have changed to just a big head.
![man face](https://cloud.githubusercontent.com/assets/15238703/11602722/5175b886-9a91-11e5-978e-45ee00b3d4db.JPG)
![hiker](https://cloud.githubusercontent.com/assets/15238703/11602750/7f872e8a-9a91-11e5-8bda-9a1e46aea56f.JPG)

**Comment by davisagli** [comment]
Hmm, the head is the default Plone avatar image, so my guess is that these users already had that saved, so it's using it rather than the MBP default. Will investigate.

**Comment by davisagli** [comment]
This fixed itself; I think CloudFlare had the old image cached.

**Comment by KindraRamos** [comment]
thanks
