### ISSUE TITLE
Annotation on backpack hike lost/hidden

### ISSUE THREAD

**Issue by jessesnyder** [washingtontrails/vms#476]
I have added notes to a few hikes in my backpack, and though they show up right after adding them, they do not appear after refreshing, or navigating away and  then returning to the listing, even after refreshing until the "hiked" mark appears. (The note never re-appears regardless of how many times I refresh the page.)

<img width="703" alt="screen shot 2015-12-04 at 4 41 55 pm" src="https://cloud.githubusercontent.com/assets/63560/11604809/3b49bdc2-9aa6-11e5-9193-0ce943e3e6a1.png">

Then later...

<img width="701" alt="screen shot 2015-12-04 at 4 42 37 pm" src="https://cloud.githubusercontent.com/assets/63560/11604810/3b4bbc9e-9aa6-11e5-83f5-7ba950fa7a72.png">

**Comment by jessesnyder** [comment]
assigned to Charlie for verification/prioritization

**Comment by davisagli** [comment]
That doesn't match what I saw when I tested yesterday (for me it was saving/removing the note fine even when a change to the 'hiked' flag wasn't showing up). This is almost certainly related to #467 (they are stored in the same place) and I think must be related to the fact that we now have more than one Zope instance. Beyond that, I'll have to dig in and do some debugging. I'll take a look later this evening.

**Comment by davisagli** [comment]
fixed

**Comment by davisagli** [comment]
(Jesse please confirm it's working and then close the issue.)

**Comment by jessesnyder** [comment]
Confirmed fixed! Woot!
