### ISSUE TITLE
MBP: Login via other user Backpack dash board gives error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#479]
When a non logged in user navigates to a different users MyBackpack dashboard there is the Sign In button.  

![backpackdashboardsigninbutton](https://cloud.githubusercontent.com/assets/8312206/11637902/0ac3d98c-9cd9-11e5-8a74-bfd38fb8c46b.JPG)

Here is this users Dashboard:
https://www.wta.org/@@backpacks/scrnm-cascadesdj

When the user clicks this to Sign In using their own credentials they are logged in but get the following screen.  Seems like the user should be logged in but stay at that others users MBP Dashboard.  Note there are some instances when this works correctly.  To reproduce this error user a different browser or clear your cache.

![backpackdashboardsigninerror](https://cloud.githubusercontent.com/assets/8312206/11637852/b4e82374-9cd8-11e5-8b25-a18850a9b132.JPG)

**Comment by davisagli** [comment]
This is a general problem with how the site redirects back to where you were after you log in, and it's been this way since before the launch (i.e. I don't think the problem is related to the MBP project). We have time to take a look if you want, though.

**Comment by WaBirder57** [comment]
I do think we should take a look at this and see if we can resolve.

**Comment by davisagli** [comment]
Fixed

**Comment by WaBirder57** [comment]
Looks good.
