### ISSUE TITLE
VMS Find a Work Party Screen only shows 10 WP, no way to fetch next set of WP

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#48]
The Find a Work Party Webpage shows the 10 next work parties.  There is no way to "advance" the display list to show additional work parties.  Per the Web Prototype: http://06.wta.emptycan.com/volunteer/ there should a display of total WP found and a way to advance to the next screen full (is this 50 at a time?).

I have attached a screen shot from this prototype page.

![findaworkpartypageadvance](https://cloud.githubusercontent.com/assets/8312206/6669858/87ae600e-cbb8-11e4-9a4c-0054c16422f6.JPG)

**Comment by davisagli** [comment]
I adjusted it to show 100 work parties. Will work on the pagination later this week.

**Comment by davisagli** [comment]
Carlos added pagination and it's now on staging.

**Comment by WaBirder57** [comment]
Looks good with pagination.
