### ISSUE TITLE
Apply Dec 8 Plone security patch

### ISSUE THREAD

**Issue by skleinfeldt** [washingtontrails/vms#480]
@davisagli and @jessesnyder to coordinate on this one please

**Comment by davisagli** [comment]
I would have thought this is @smcmahon's responsibility? If not I can do it of course.

**Comment by WaBirder57** [comment]
Yes, steve should be in the loop on this.

**Comment by skleinfeldt** [comment]
Sorry, make that @smcmahon, @jessesnyder, @davisagli please coordinate on this.

**Comment by smcmahon** [comment]
Indeed, my responsibility, and on my morning list.

**Comment by smcmahon** [comment]
Let me amend that: I'm updating www.wta.org now. I'd be happy to leave the staging and backpack instances to @davisagli and/or @jessesnyder

**Comment by davisagli** [comment]
This was done.
