### ISSUE TITLE
VMS: Adjustments to Work Report Function

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#481]
1. Please have the defaults for site preparation and administrations both be 1 hours each, rather than 0. 

2. In the work report, please have this check box checked by default, "On 'Publish' email to crew members and post to Crew Corner"

3. Is it possible to have decimal point values for Travel Time, Site Preparation & Administration Time? This is important to have. 

4. When editing the work report, at the bottom of the page, there's a pull down menu for Status. It's current default is Draft. Can the default be Publish?

**Comment by cguardia** [comment]
@mscholtz for step 3 of this issue, I was able to save decimal point values, and get them back later when querying SF, so that seemed to work. However, on the SF side, the screen where I can see the report, shows rounded-up values instead of the decimals. Is there something you need to do there?

**Comment by mscholtz** [comment]
@cguardia can you send me an example (link to SF record and which fields to look at)?

**Comment by cguardia** [comment]
@mscholtz https://cs9.salesforce.com/a2vK00000005oFa

Look at the hours section at the top. Admin hours, site prep hours and travel hours have floating point values that display correctly on the vms side, but are whole numbers here.

**Comment by cguardia** [comment]
@mscholtz sorry, correct link to report is https://cs9.salesforce.com/a2vK00000005ocZ

**Comment by mscholtz** [comment]
@cguardia OK, updated all of these fields to 2 decimal places.  Please take a look again.

**Comment by cguardia** [comment]
@mscholtz thanks, it's working now.

**Comment by davisagli** [comment]
This should all be working now.

**Comment by ebskopin** [comment]
Everything looks good, but for some reason the "Message to Crew" only shows up when you have the "Status" set on Draft. The default values should remain the same but the Message to Crew needs to be visible with the status set as "Published."

**Comment by WaBirder57** [comment]
We will do some user testing on this feature to see if we want the default value to be "Draft" or "Published".  I'll keep this closed until we have specific instructions.  This will impact @ebskopin comments on when the Message to Crew fields are visible.
