### ISSUE TITLE
VMS: Registration confirmation e-mails should not issue following WP close

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#482]
When a contact is added to a WP in Salesforce following the WP date, the confirmation e-mail is still  issued.  It is important that this not occur, as we will often add/subtract people after the fact.

**Comment by mscholtz** [comment]
@drewpiston could you take care of this one?

@ebskopin could you verify whether you want emails to not go out a) once the WP status has been changed to "Completed", b) once the End Date of the WP has passed, or both?

**Comment by mscholtz** [comment]
@ebskopin @WaBirder57 at this point, if you add a SF-related ticket, could you @ me in the comments so I make sure to see it?  Thanks!  Wasn't as important earlier in the project, but every day is of the essence now.

**Comment by ebskopin** [comment]
I would say "both" to your earlier question @mscholtz, and I'll be sure to @ you on future Salesforce tickets, thanks.

**Comment by drewpiston** [comment]
Ready to review.

**Comment by ebskopin** [comment]
looks good. Thanks
