### ISSUE TITLE
VMS: Addition to Location/Directions Tab

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#483]
![image](https://cloud.githubusercontent.com/assets/14843712/11672638/2e89eb92-9dc7-11e5-8782-6639cddd5f8c.png)

Directly above the Google Map Image the following disclaimer should be added: "Warning: Always use the written directions (above) to get to a trailhead. The location of the pinpoint below is only approximate. Using mapping websites and gps navigation to get to trailheads could mislead you."

**Comment by cguardia** [comment]
Fixed on master.

**Comment by davisagli** [comment]
done

**Comment by ebskopin** [comment]
looks good. thanks.
