### ISSUE TITLE
VMS:  "Send to my phone" button doesn't work

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#488]
The "Send to my phone" button doesn't work in VMS. It prompts me to put in my email address, but when I do that I get a dialog box that says "Error: error." I also tried entering my phone number in case that would work but same thing happened.

![image](https://cloud.githubusercontent.com/assets/14843712/11751209/f4aced02-9fec-11e5-9c89-7e6d743a4d1f.png)

This happens if you are registered for the work party. Also happens if you are not registered for the work party.

**Comment by davisagli** [comment]
@cguardia I fixed a couple things but this still isn't working. Now it says that the email was sent, but I don't see anything in the mail log on the server. Any ideas?

**Comment by davisagli** [comment]
fixed

**Comment by WaBirder57** [comment]
Tested on vms.wta.org.  Works great and includes just the test.  I didn't verify yet to make sure that any special event directions are included, eg Work party breakfast.

**Comment by davisagli** [comment]
Currently it just includes the trailhead directions.

**Comment by WaBirder57** [comment]
Can you easily add any text from the special event info that would be displayed on that location tab of the workparty page also?

**Comment by davisagli** [comment]
How do you want the email formatted? Any text introducing the second set of directions?

**Comment by WaBirder57** [comment]
Here is an example of the Work Party this this Special Event directions.  If you can capture all that text which displays on the web page that would be great.  

HEre is the Salesfroce URL: https://cs9.salesforce.com/a2eK00000000kDK

Or webpage: http://staging.wta.org:6543/workparty/a2eK00000000kDK/

**Comment by davisagli** [comment]
@WaBirder57 can you please be more specific about what you mean by "all that text"? If you could give an example of the email you would expect to receive for that work party, that would be perfect.

**Comment by davisagli** [comment]
Charlie posted on a different ticket:

Here is an example of what I currently received with the new info at the bottom. Note if you could improve the time formatting that would make this more readable also:

Subject: Directions for TEST Day Work party - Taylor Mountain

Charlie Kahle sent you directions to the TEST Day Workparty - Taylor Mountain work party on 2016-02-29T08:30:00-08:00.

From I-90 take exit 17 (Front Street), and turn right (south) onto Front Street and continue south through Issaquah. Front Street becomes Issaquah-Hobart Road as you leave town. Continue south along this road to its junction with State Route 18. Cross under SR 18 and drive another 0.25 mile, passing Holder Creek at SE 188th Street. Park near Holder Creek.

Special Event Spot
Country Pride Restaurant, in North Bend
From Seattle, head east on I-90 to exit 34 468th Ave SE. From exit ramp turn left and cross over the freeway. Go north 0.3 miles and turn left into the parking lot for the restaurant at 46600 SE N Bend Way, North Bend, WA 98045.

**Comment by davisagli** [comment]
okay, updated

**Comment by ebskopin** [comment]
works, thanks.
