### ISSUE TITLE
Day Work Parties - set end data equal to start date on creation

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#49]
When creating a new day work party, automatically set the end date to equal the start date.

**Comment by davisagli** [comment]
@mscholtz, how hard?

**Comment by mscholtz** [comment]
Super easy, if you don't need the End Date to appear until you hit Save.
If you want it to appear as soon as you enter the Start Date, that would
take custom UI.

On Mon, Mar 16, 2015 at 4:20 PM, David Glick <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz>, how hard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/49#issuecomment-81986594>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Lets go with Super Easy.  

Is it possible to have the various Work Party types have a default end date set, eg weekend would be Start Date + 1, Week Long would be Start Day + 6 and still be super easy?

**Comment by mscholtz** [comment]
Still fairly easy, but I think that should be a story.  A small one, but
not a ticket.

On Tue, Mar 17, 2015 at 9:00 AM, Charles Kahle <notifications@github.com>
wrote:

> Lets go with Super Easy.
>
> Is it possible to have the various Work Party types have a default end
> date set, eg weekend would be Start Date + 1, Week Long would be Start Day
> + 6 and still be super easy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/49#issuecomment-82434169>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
New Story #224 created.
