### ISSUE TITLE
still have ipsum text on Documents tab of WP

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#490]
also text says "Documents must be complete 48hrs before Work Party start day." is that really true?  I thought it was the case that sometimes they just bring printed forms to the WP.

@davisagli @ebskopin

**Comment by davisagli** [comment]
I think that text came from the design mockup. Currently the forms must be completed before registering.

**Comment by mscholtz** [comment]
Only for some WP types, right?

**Comment by davisagli** [comment]
For all work parties that require you to be logged in to register, see story 318.

**Comment by mscholtz** [comment]
But this text shows even for WPs that don't require login, yes?

On Fri, Dec 11, 2015 at 11:28 AM, David Glick <notifications@github.com>
wrote:

> For all work parties that require you to be logged in to register, see
> story 318.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/490#issuecomment-164026634>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
It shows all the time and is inaccurate most of the time. Should I just remove that line @ebskopin?

**Comment by davisagli** [comment]
I removed that line.

**Comment by ebskopin** [comment]
Thanks. I've updated the ipsum text.

**Comment by davisagli** [comment]
@ebskopin did you update it on the staging or live copy of VMS?

**Comment by ebskopin** [comment]
staging, should I be editing in live VMS now?

**Comment by davisagli** [comment]
You can edit text on vms.wta.org now; it's the site that we will actually launch.

**Comment by ebskopin** [comment]
got it. will do
