### ISSUE TITLE
VMS: Unable to add friends & family group from waitlist

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#494]
I registered myself, and 2 friends + family, to a full work party's wait-list - https://cs9.salesforce.com/a2eK00000000k93. However, when I free up enough room for the entire group of 3 I am met with this error when attempting to add myself (any my plus 2+) from the waitlist in SF - 
![image](https://cloud.githubusercontent.com/assets/14843712/11791425/e023b968-a255-11e5-80ab-ed60bf8128f8.png)

Thoughts, @mscholtz 

Additionally, there is mention of a group being able to opt "Not" to stick together when registering for a wait list at the same time. I'm no seeing any evidence of this. Am I missing something?

**Comment by davisagli** [comment]
> Additionally, there is mention of a group being able to opt "Not" to stick together when registering for a wait list at the same time. I'm no seeing any evidence of this. Am I missing something?

Did you enter an email address for each person? That option is only shown if the email is known for each person.

**Comment by ebskopin** [comment]
I did enter an e-mail for the 2 guests and still didn't see the option to split the group.

**Comment by mscholtz** [comment]
@ebskopin did something change since you wrote the ticket?  That WP is now showing completely full.

**Comment by ebskopin** [comment]
ahh, sorry.  I was fiddling with it. It's now back to the state in which I am experiencing the error. Thanks @mscholtz .

**Comment by mscholtz** [comment]
Confirmed this is a bug.  Seems to be in line 254 - that false should be true.  But first write a test that exposes it.

**Comment by davisagli** [comment]
> I did enter an e-mail for the 2 guests and still didn't see the option to split the group.

Ah, there was a bug in the logic that checked if they all had email addresses. Should work now.

**Comment by mscholtz** [comment]
This should be fixed.  Back to you @ebskopin for testing.

**Comment by ebskopin** [comment]
Yep.  Works well.
