### ISSUE TITLE
VMS: IPhone bug when viewing crew corner as CL

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#495]
On iphone you need to turn your phone to get the green and red check boxes to show up in iphone. Otherwise it looks like this: http://prntscr.com/921giv

**Comment by davisagli** [comment]
The design (from Ethical UX) was not for the table to collapse on narrow devices but for it to be scrollable -- you can drag it horizontally with a finger to see the other columns.

**Comment by ebskopin** [comment]
ok, that works.
