### ISSUE TITLE
Number of chars for "Schedule" field are different in WP vs WP type

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#496]
"Default Schedule" in WP Type is 750 chars
"Schedule" in WP is 500 chars

@ebskopin or @WaBirder57 which one should it be?

BTW, if we change it to 500, and if you have any recs in production w/ more than 500 chars, it'll truncate it.  So we should watch out for that

**Comment by mscholtz** [comment]
This is high priority b/c it can throw a script err if the WPT field has more chars than the limit on the WP field, when it tries to copy it over

**Comment by mscholtz** [comment]
also @WaBirder57 and @ebskopin it looks like Rebecca has been editing WP types in the sandbox recently.  This one (https://cs9.salesforce.com/a2wK0000002GGl6) was edited by her on Fri.  Just want to make sure no-one is confused about production vs sandbox and where we need the data now.

**Comment by WaBirder57** [comment]
I'll get an answer today.  

Rebecca has been working on the production WPT records and I think testing in the sandbox but I will double check she is doing this correctly.

**Comment by WaBirder57** [comment]
Good catch @mscholtz .  We will go with 500 as the length for this WorkParty.Schedule and WorkPartyType.Default Schedule field.

There is no production data that will be truncated if we change this at this time.  I would make the change myself but wasn't sure if there were any other places that needed to be updated.  Please make this change to the Work Party Type.

**Comment by WaBirder57** [comment]
I stand corrected.  We will use the field lengths set in the Work Party Type object for the corresponding fields in Work Party.  Evidently there are more than 1 affected fields.  I will make this change now as we are needing to test work parties which have longer text values in these fields.

**Comment by mscholtz** [comment]
@WaBirder57 could you also make the same changes in the sandbox?  Otherwise it may get overridden when we do another deploy

**Comment by WaBirder57** [comment]
Yes, I have updated both the production and .vms2 environments.

**Comment by mscholtz** [comment]
Great, thank you!

On Tue, Jan 5, 2016 at 3:25 PM, Charles Kahle <notifications@github.com>
wrote:

> Yes, I have updated both the production and .vms2 environments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/496#issuecomment-169167372>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/
