### ISSUE TITLE
VMS: Parental Release form using Production Docusign Account

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#497]
VMS in development is using the demo.docusign.com account.  Does this information need to be migrated to the WTA Docusign account for production or can we just start using our current, existing, Docusign Parental Release form?

Is there anything unique or special API information in used in this demo.docusign.com version of our parental release form?

**Comment by davisagli** [comment]
We need to recreate the Parental Release and MOU templates in your production Docusign account, and make sure that the Required Document records in production Salesforce reference them rather than the ones in the demo account.

**Comment by davisagli** [comment]
We also need to copy the Docusign Connect settings from the demo account to your real Docusign account. The demo Docusign account writes updates to the sandbox, not production Salesforce.

**Comment by mscholtz** [comment]
@ninetaLogik did you work on the docusign MOU?

**Comment by mscholtz** [comment]
tentative plan is for David to do the parental release and nineta (or whoever worked on it) to do the MOU

**Comment by ninetaLogik** [comment]
@WaBirder57 I will need from you an account (username and password) for your docusign production account where you will have the templates uploaded as well as the SF user account you want to use for the SF <-> DocuSign connection. 
What's the best way for you to share these with me? Lastpass? Email? of we can do it over skype or phone? Thanks!

**Comment by WaBirder57** [comment]
Do you all have a method of encrypting email, such as PGP?  Alternatively we can use different technology, such as email for part and skype for the other part.

**Comment by ninetaLogik** [comment]
@WaBirder57 I'll call you on skype a bit later and get this info, what time works for you?

**Comment by WaBirder57** [comment]
Let me figure out the answer to your questions first.  I'll get back to you later this afternoon, 3:30ish.

**Comment by ninetaLogik** [comment]
@WaBirder57 I updated the Template Id (for the MOU) and the Signers so please re-test by Navigating to a Work Party Group and clicking Send MOU. The MOU template should be auto-populated and the senders should include you and the WP Group Organizer.

**Comment by ninetaLogik** [comment]
@WaBirder57 it looks like the permissions issue is now resolved and I was able to test the Send MOU. I used this record : https://wta.my.salesforce.com/a3DA00000009cCq
It works and you'll see that it prepopulates the Template and the Signers for you.

**Comment by WaBirder57** [comment]
@ninetaLogik We need to have this completed MOU create the Docusign Status related record on the Work Party Group record.  As you will see this includes information from Docusign on the status of this MOU document as well as a link to the envelope.  Here is a screen shot: 
![efdocusignstatusrecord](https://cloud.githubusercontent.com/assets/8312206/11877578/04a660e6-a4a5-11e5-89a6-4a929d9d8652.JPG)

**Comment by ninetaLogik** [comment]
@WaBirder57 Ok, this should work now.

**Comment by WaBirder57** [comment]
OK the MOU portion of this ticket is fixed and working.  That leave the Parental Release form.  Excellent progress!

**Comment by ninetaLogik** [comment]
@WaBirder57 please note that from your docusign account you will need to mark the users that you want to have integration for. 
These are the instructions to follow. https://support.docusign.com/guides/dfs-admin-guide-add-ds-status-to-custom-object
In addition when you do this you need to mark users otherwise they're are not going to get the docusign status records.

**Comment by davisagli** [comment]
I started setting this up but the Required Document layout in production Salesforce doesn't show the fields I need to set for the parental release. @mscholtz did you miss deploying that page layout?

**Comment by mscholtz** [comment]
Possibly.  But it's really easy to add fields to a layout.  Could you or
Charlie do that today?  I am travelling most of the day today.

On Fri, Jan 8, 2016 at 10:06 PM, David Glick <notifications@github.com>
wrote:

> I started setting this up but the Required Document layout in production
> Salesforce doesn't show the fields I need to set for the parental release.
> @mscholtz <https://github.com/mscholtz> did you miss deploying that page
> layout?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/497#issuecomment-170200690>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
@WaBirder57 the parental release form should be set up correctly in your production DocuSign account now. I wasn't sure if it was okay to touch the existing parental release there, so I added a new template called Work Party Parental Release which is used by a new Powerform.

To test this you'll need to have someone complete the parental release on the live VMS site (vms.wta.org) and confirm that the youth contact's "Parental Release Date" field gets updated in production Salesforce (as well as the signed release being attached).

**Comment by WaBirder57** [comment]
Where do I launch the Parental Release form to test in this vms.wta.org?

**Comment by davisagli** [comment]
You would need to set up a work party using a work party type that requires the Parental Release document, then register a contact under 18 for it and go to the documents tab.

**Comment by WaBirder57** [comment]
The Parental Release form is not attached to the SF Contact (youth).  Here is the testing process:

First: I made a new contact, Sixteen Yearoldboy in the production site to test the form. 

When signed in to My Backpack, I clicked "Join this work party" and was immediately taken to this page: http://vms.wta.org/workparty/a2mA00000009HNr/register

Clicking "Complete Online" took me to this page to complete the Powerform: https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=a7eafb2d-846a-45a2-aad6-c4ff05e06e9f&EnvelopeField_Youth%20Id=003A000001i6EqE&Participant%20Name=Sixteen%20Yearoldboy

I filled out the form using my regular Salesforce contact (andrea@wta.org). I was able to complete the form, but it did not attach to Sixteen Yearoldboy's contact record.

**Comment by WaBirder57** [comment]
Please note that we will be changing the Parental Release for to one that is valid for the full year for a work party any where in the state and not a specific trail.

**Comment by davisagli** [comment]
@WaBirder57 It actually did work when you filled it out via the PowerForm. But you can't see that because the "Parental Release Date" field and "Parental Releases" related lists aren't currently visible on the Contact page layout. (It's a different related list than the one where you usually see docusign forms, because the contact is related to the form as a youth rather than as a signer.)

You can add them to the layout, or I imagine Percolator will update the page layouts when they launch next week.

You should be able to see that the parental release status is now completed if you look at the documents tab on the work party in VMS when logged in as Sixteen Yearoldboy.

**Comment by WaBirder57** [comment]
Ah, I didn't think to look for these fields/lists, I was just looking for Docusign info.  Thanks for point these out and I have update the Contact Layout.  .VMS2 and production are updated.

**Comment by mscholtz** [comment]
Yes, David is right.  We left the contact layout in production set to the old pre-VMS layout at Elliot's request.  We can cut over to the VMS-friendly layout at any time, but certainly should do so when we launch if not before.
