### ISSUE TITLE
Clarification needed ASAP on ACL/CL eligibility

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#498]
Hi @ebskopin and @WaBirder57, something came up today w/ the data migration that I wanted to clarify.

As part of the discussion for this ticket: #124 we finally decided that for ACL-only WPs, it doesn't matter what someone's "VMS Permission Level" field is set to, if staff is registering them.  (Although it does matter if they expect to go online and register themselves as ACL.)

My questions are:
 
1. can I assume the same is true for CLs?  (they only need the CL checkbox if staff is assigning them, not the "Crew Leader" VMS Permission Level?)
2. I noticed a record (https://wta.my.salesforce.com/003A000000rmiH3) where both the Crew Leader and Crew Leader Inactive box are checked.  (Seems like a contradiction..)  We're not looking at the Inactive box, only the Crew Leader one.  Is that OK?  Should this contact be eligible to be a CL?
3. I don't think we came up with a step in the migration plan for setting the VMS Permission Level field.  And it's currently blank for everyone.  Do we need to script initial data for this field?  Or will you guys just set it by hand for current ACLs/CLs?

Could you answer this ASAP on Thurs morning if possible?  Want to get this clarified (at least 1 and 2 above) before I proceed w/ the rest of the data migration.

Thanks!

**Comment by WaBirder57** [comment]
Matthew,

 

Answers first and then a bit of commentary.

 

Yes, your description of story #124 is correct.  VMS Permission Level is just used to set someone’s access to VMS.

 

1)     Yes, your assumption is correct, CL Check box controls if they can be added to a WP as a CL. 

2)     We are working on tightening up how we use these fields.  If CL Inactive is checked then they should not be allowed to be added as CL to a work party.  If your code could check this also that would be great.

3)     Yes a script to set the VMS Permission level would be very helpful.  We will run a clean-up report afterwards to spot in inconsistencies.

 

For this VMS Permission Level Script  you can look at the 3 contact Fields (in this order): Assistant Crew Leader, Crew Leader and Land Manager.  If someone is ACL use that VMS Permission level, if they are CL (not inactive) use that Permission Level and then lastly if they are Land Manager us that Permission Level.  Thus, if someone is set as both ACL and Land Manager; VMS Permission Level should be set to Land Manager.  We will run a clean-up report after you get this data imported to check for inconsistencies.

 

We want to add an ACL Inactive and ACL Inactive Date field to SF but were going to wait until you all were done so we don’t add more confusion.  Lastly our goal to clean up these fields would be to have the Inactive Check box automatically clear the corresponding check box when set (we can add that code).  That would prevent the inconsistency you noted in #2.

 

Charlie

**Comment by mscholtz** [comment]
OK, sounds good.  I will try to do the script to set the Permission Level, but we'll have to see if there's time.

I created a separate ticket here #499 for the Inactive checkbox, please prioritize it.

**Comment by davisagli** [comment]
What's the reason for having a second checkbox that causes the first one to be unchecked, instead of just unchecking the first one?

**Comment by mscholtz** [comment]
BTW, for the purposes of the migration, you may remember that since crew leaders aren't explicitly marked in the Volunteer Job, we're guessing at the CL by looking for the first person on the roster who has the CL checkbox.  Currently that is not disqualifying someone if they have the CL Inactive box checked.  Furthermore, unless you object, I'd like to keep it that way, because even if they're inactive now, they may very well have been active when the WP in question happened.  

Does that sound OK?

I could imagine a more complicated script that would look at all of the potential CLs on each roster, and try to pick the best one, taking into account dates, the Inactive box, and other factors.  But we really don't have time to start down that road now.

**Comment by WaBirder57** [comment]
Yes, sounds ok and keep it simple (er).  Thanks.

**Comment by WaBirder57** [comment]
David,  We want to keep track of who "was" or perhaps who could be again a CL.  Thus, if a CL moves out of the area they would be flagged as Inactive CL.  If they move back then there status would reverse.  Also we use these flags when sending out email to current and/or former CL's.

**Comment by davisagli** [comment]
Ah, got it. Thanks Charlie.
