### ISSUE TITLE
Trailhead Salesforce Object needs text box for driving directions to that trailhead.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#50]
In Salesforce the Trail head object needs a text box for a description of the driving directions.  These driving directions need to be pulled into all associated Work Parties and displayed on the "Location Tab" of the WP view.  These are the directions that the volunteer will be able to print or send to their phone.

**Comment by davisagli** [comment]
The directions on the Location tab are currently loaded from the "Directions" field on the work party. Do you want to remove that and always get the directions from the new field you're asking for on the trailhead object?

**Comment by WaBirder57** [comment]
The driving directions are relevant to the Trail Head.  It may be useful to have those available on the Work Party object, but that data should be pulled from the Trail Head directions.  When the directions change, all WP using that Trail Head would have their directions changed.

**Comment by davisagli** [comment]
So there's never a case where you want a work party to use an existing trailhead, but with different directions? In that case you would create a new trailhead object?

**Comment by WaBirder57** [comment]
Yes, we would create a new trailhead object.

**Comment by davisagli** [comment]
Okay. @mscholtz / @barbarachristensen please coordinate with me when you have a chance to make this change.

**Comment by mscholtz** [comment]
done on SF side, still named Directions__c

**Comment by mscholtz** [comment]
@WaBirder57 now that we have Directions on the trailhead, do we still need Street Address and Zip Code?  (I'm assuming we should keep City and State..)

**Comment by davisagli** [comment]
Okay the pyramid app now fetches the directions from the trailhead.

**Comment by WaBirder57** [comment]
@mscholtz We do not need any address information on the Trail Head, not even City and State.  Please take those off and we can wrap this up.

**Comment by skleinfeldt** [comment]
Are you sure @WaBirder57 ? City and State for possible reporting purposes? They can be optional and blank for now. And if in the future you want to do a bulk data add, a script could get the city-state from the lat-long...

**Comment by WaBirder57** [comment]
Well no harm in leaving these fields in Salesforce.  We can leave them off the layout for now. @mscholtz

**Comment by WaBirder57** [comment]
OK good as is now, thanks.
