### ISSUE TITLE
VMS: Work Party start/end times not displayed on "Find a Work Party" page

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#500]
Presently, for multi-day trips (weekend, vol vac, BCRT), the start and end times are displayed on the main "Find a Work Party" page. Example: 

![image](https://cloud.githubusercontent.com/assets/14843712/11901846/a5018c56-a562-11e5-883d-2021dcc3376f.png)

These times should only display on the work party details page that the volunteer reaches when they have clicked through. These times do not need to display on the main schedule page for any work party.

**Comment by davisagli** [comment]
This is as requested in #282, so please confirm if you want a change from that.

**Comment by ebskopin** [comment]
Yes. Sorry about the contradictions. We would like this to be changed from what was in #282.

Thanks.

**Comment by davisagli** [comment]
fixed

**Comment by ebskopin** [comment]
fixed
