### ISSUE TITLE
VMS: Staff email when waitlist spot opens up - SF Workflow?

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#502]
When a spot opens up so that someone can be invited to join the work party from the wait list an email is generated to staff with links to invite the next person.

Where is this email generated (eg is this a SF Workflow and SF email)?  In particular I want to know where we control who this email is sent to.

**Comment by davisagli** [comment]
@mscholtz

**Comment by mscholtz** [comment]
@WaBirder57 I can look this up for you.  But I was thinking that this would be a good thing to document while we have some time for that.  There are a bunch of emails that go out, and they use various mechanisms.  I think it would be good for us to catalog what emails there are, what settings you guys can change, where you would go to change the content, etc.  We could answer this question as part of that effort.  

What do you think?

**Comment by WaBirder57** [comment]
Yes, documenting the email flows and details that you have described was high on my list of things that need to be documented.

**Comment by mscholtz** [comment]
OK, we can do that.  I did send you an email yesterday w/ general questions about documentation.  Could you reply to that before we get started here?

**Comment by WaBirder57** [comment]
Done, I added comments.  I think you have good ideas.

**Comment by mscholtz** [comment]
marking this closed as this will be answered by documentation..
