### ISSUE TITLE
MBP: Plone gallery feature is broken as of yesterday 1/4

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#507]
@davisagli , @jessesnyder Just as we were discussing the photo gallery tool that we use yesterday it appears that is is now broken.  Loren say that some folders may be missing.

Loren reports: The upload function is totally gone now, and I'm wondering who I should check in with or who I should alert to the issue. 

User report:
Hi there, I was interested in sharing a recent photo I took at Hurricane Ridge, which happens to capture my enthusiasm for the place, and tried the "upload a photo" option here on the website. I got a "this page does not seem to exist" error, and thought I would report it. I got it whether trying to follow the link from the homepage, or from following the featured photo and clicking the upload button.

**Comment by davisagli** [comment]
It appears to link to a folder for the current year (/hiking-info/gallery/images/2016) so you probably just need to create that 2016 folder. @jessesnyder may know more from previous years.

**Comment by WaBirder57** [comment]
Added:  http://www.wta.org/hiking-info/gallery/images/2016/folder_contents and it works.  Thanks.
