### ISSUE TITLE
Join Work Party Button broken - gives blank screen

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#51]
Select any work party and choose the Join Work Party button.  You are taken to a blank screen.

**Comment by davisagli** [comment]
Oops, fixed.

**Comment by WaBirder57** [comment]
This is broken again. Thursday 11am, March 19.

**Comment by davisagli** [comment]
Which work party? Which browser? It's working for me on http://staging.wta.org:6543/workparty/a27J0000001nByOIAU/

**Comment by WaBirder57** [comment]
Are you NOT logged in?  I have tried on Firefox, IE and Chrome.  If you logged in it works as expected.

**Comment by WaBirder57** [comment]
Opps should still be open.

**Comment by davisagli** [comment]
Ah okay, I missed the note that it's only a problem when not logged in.

Why did you close this? I still need to fix it for users who aren't logged in.

**Comment by davisagli** [comment]
Actually it's working for me even when logged out. Are you trying to register for "David's Weekender Trip" or a different one?

**Comment by WaBirder57** [comment]
Sorry, clicked to quickly when I accidentally closed this.  Also, I tried being logged in and then logging out.  It still worked as expected in this situation.

**Comment by WaBirder57** [comment]
Had the issue with any work party.  Going to try a full reboot.  Perhaps an odd caching issue.

**Comment by davisagli** [comment]
It doesn't sound likely to be a caching issue if it's happening in multiple browsers. Even if it was, the solution would be to clear your browser cache, not reboot.

Can you please give me the URL of a specific work party that is not working for you? Even if it seems like they are all not working, I want to make sure I am trying the same one as you and see if I can reproduce the issue.

**Comment by WaBirder57** [comment]
OK, did a reboot.  Does that clear a Firefox browser cache?

 

Here is the work party: http://staging.wta.org:6543/workparty/a27J0000001nMEyIAM/

 

Click “Join Workparty”, get a blank screen (with just the header showing).

**Comment by davisagli** [comment]
Okay, I can reproduce the problem in Firefox but not Chrome. Thanks.

**Comment by WaBirder57** [comment]
Seems to be working now.

**Comment by davisagli** [comment]
Give it a try now. The problem had a different cause this time; I merged the code for the payment form yesterday and it had a bug.

**Comment by davisagli** [comment]
Ah, sorry, our messages keep passing each other. I see you already discovered it works now. :)

**Comment by WaBirder57** [comment]
Thanks!
