### ISSUE TITLE
VMS:  WP Crew Corner Toolkit - Document Reviews return error not document

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#510]
When clicking to view the Emergency Action Plan for the work party: http://staging.wta.org:6543/workparty/a2eK00000000iVz/

This is for:  Emergency Action Plan: Beacon Rock State Park

I get the error: 

Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

We get this same error for many of the documents we try to review.

**Comment by davisagli** [comment]
fixed

**Comment by WaBirder57** [comment]
Thanks for the quick fix.  Training starts tomorrow, Jan 7!
