### ISSUE TITLE
VMS: SF What to Bring field extended to 1,000 characters

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#511]
Information only:

The WorkPartyType.DefaultWhatToBring and WorkParty.WhatToBring fields are now set to 1,000 characters up from 500 in both .VMS2 and Production.  With the way this information is displayed in VMS we needed to allow for longer text fields.

**Comment by davisagli** [comment]
Okay. As long as you made the change in both Salesforce instances it doesn't sound like any action is required.
