### ISSUE TITLE
VMS: Crew Corner roster list not showing registered volunteers in some cases

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#513]
For some work parties we see that the WP Crew Corner Tab doesn't show the list of registered volunteers.  Seems like these may be WP where Rebecca is the Crew Leader (and ones she has been editing in SF recently).  Note that you can click on Review to see the Sign In Sheet with all volunteers listed.

Here is an example Work Party for Rebecca:
http://staging.wta.org:6543/workparty/a2eK00000000u70/

And in Salesforce:
https://cs9.salesforce.com/a2eK00000000u70

Here is an example that works correctly:
http://staging.wta.org:6543/workparty/a2eK00000000iVz/

Note this is for me: charles@wta.org and rebecca@wta.org

**Comment by davisagli** [comment]
Fixed. It was breaking because it didn't know how to handle a certification without a start date (which Rebecca had). I fixed it to only validate the certification start date if one is set.

**Comment by WaBirder57** [comment]
@davisagli What does it mean for a certificate to have a valid start date?

**Comment by davisagli** [comment]
That it has any start date; Rebecca's certificate didn't have one set at all.
