### ISSUE TITLE
VMS: MyBackpack Crew Corner Lists of My Workparties - filter + sort order

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#522]
When a logged in Crew Leader go to MyBackpack, Crew Leader Corner, My Work Parties there are a couple fixes needed in the List of work parties for that person.

The drop down for "Summary Reports Needed" should only show work parties for that Crew Leader which need a summary report.  Right now it shows all work parties which need a summary report.

The list of WP should be sorted by start date with the most recent at the top of the list.  This should be the same sort order for any of the drop down settings.  Currently these lists do not seem to be sorted by date.

**Comment by davisagli** [comment]
Should work now.

**Comment by WaBirder57** [comment]
Looks good, thanks.
