### ISSUE TITLE
VMS: MyBackpack Crew Corner Lists of My Workparties - info displayed

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#523]
For a user in MyBackpack when viewing the list of their workparties (for all users) the list view should include the following fields:
Crew Leader
Description

![mybackpackworkpartlist](https://cloud.githubusercontent.com/assets/8312206/12213457/1c033e0a-b62d-11e5-98c6-7397b01f2ec9.JPG)

**Comment by cguardia** [comment]
Fixed on master.

**Comment by davisagli** [comment]
@cguardia can you point me to the commit; I can't find it.

**Comment by cguardia** [comment]
@davisagli sorry, pushed to my issues/531 branch by mistake. I pushed to mybackpack-buildout now.

**Comment by WaBirder57** [comment]
This is working now but we would like the formatting and information consistent with the Find a Work Party list.  Specifically:

•	"Leader" should say "Crew Leader"
•	The crew leader's name should be bolded
•	Underneath the description it displays "# volunteers." It would be much better if the display matched the "Find a Work Party page" where it displays "Crew Members: # (# youth)/# ACLs." THis is on the same line as the crew leader, but right-aligned.

**Comment by davisagli** [comment]
Okay, updated

**Comment by WaBirder57** [comment]
Looks great, thanks.
