### ISSUE TITLE
VMS: Additional Text to Certifications tab in My Backpack

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#525]
We would like to add the following text to the "Certifications" page on the My Backpack page (pertains to ACLs & CLs):

![image](https://cloud.githubusercontent.com/assets/14843712/12244929/c5a5d3c6-b85a-11e5-9d85-06a802023b56.png)

"Please e-mail volunteer@wta.org to update your certifications and add new certifications."

If it is possible to simply insert an editable text box that would be ideal.

Thanks.

**Comment by cguardia** [comment]
@davisagli if we use the textbox, where would you say it should go?

**Comment by davisagli** [comment]
@cguardia I think he's talking about one of the configurable help text components that we have in the Pyramid app, but not in Plone. So don't worry about that part for now and just add the hardcoded help text.

**Comment by cguardia** [comment]
Fixed on mybackpack-buildout branch.

**Comment by ebskopin** [comment]
Thanks.
