### ISSUE TITLE
VMS: Edits to Crew Corner Banner

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#527]
Is the Crew Corner banner something that we can edit?

![image](https://cloud.githubusercontent.com/assets/14843712/12246912/04d8bed6-b866-11e5-9511-708557fda5f4.png)

If not, we would like the text to read: "You must be part of this crew and have a My Backpack account to see the Crew Corner." And it would be nice to have this image - http://www.wta.org/go-hiking/trip-reports/trip_report.2015-08-02.9871652864

**Comment by davisagli** [comment]
We haven't set it up to be editable at this point. I made these quick changes.

**Comment by ebskopin** [comment]
thanks, looks good.
