### ISSUE TITLE
VMS: Suppressing "Hiking Guide Summary" under Trail Segment

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#529]
Currently there is a "Hiking Guide Summary" field on the Trail Segment object in Salesforce. Currently this information is displayed in VMS at the bottom of the Info tab in the "From the Hiking Guide" section.

This information is basically a duplicate of what we want to show in the "About the Area" field that is on the Work Party object and is displayed toward the top of the Info tab.

Here is an example:
http://staging.wta.org:6543/workparty/a2eK00000000uUr/
https://cs9.salesforce.com/a2kK0000001MOeu

I would suggest that we suppress the "Hiking Guide Summary" field from displaying in VMS, but know that we can store content here in Salesforce cut and paste from that field when we are creating work parties. The help text on the field should say: "This information will not be displayed on the WTA website but can be pasted into the About the Area field for a related work party. Note that any Hiking Guide content copywrited by Mountaineers Books cannot be used for work party purposes."

**Comment by davisagli** [comment]
I removed display of the Hiking Guide Summary from the work party page in VMS.

**Comment by davisagli** [comment]
I also adjusted the help text in both Salesforce instances.

**Comment by ebskopin** [comment]
Thank-you. Looks good.
