### ISSUE TITLE
VMS: My Backpack menu differs

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#531]
Might be the nature of the different systems, that will be remedied upon launch, but Rebecca reports:

Once you have logged into My Backpack, the My Backpack menu you can access from the upper right looks different depending on where you're at on the site. It should look the same, regardless of whether you are "in" My Backpack or are on the Find a Work Party page (or elsewhere).

Here is a screen shot when I am "in" My Backpack. See the orange drop down in the upper right - it includes "Dashboard" and "Write a Trip Report." 

![image](https://cloud.githubusercontent.com/assets/14843712/12251272/7cf90d5a-b882-11e5-9508-23e510ee60a1.png)

Now here is a screen shot from the "Find a Work Party" page. The "Dashboard" option disappears. Fortunately, you can still get to your Dashboard if you just click on "My Backpack." 

![image](https://cloud.githubusercontent.com/assets/14843712/12251274/896a4586-b882-11e5-8da4-9ca78024d8ee.png)

**Comment by davisagli** [comment]
This will take some work. The pyramid app currently has just a few hardcoded links for that menu rather than loading all the menu items from Plone.

**Comment by davisagli** [comment]
@cguardia I had to do some more work to make sure that the nav JSON is not cached incorrectly in Varnish and to make sure that cookies are sent for the cross-origin ajax request. It's working now.

**Comment by ebskopin** [comment]
Thanks. This looks good.
