### ISSUE TITLE
VMS: Find a Work Party button added to My Work Parties

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#532]
In order to make My Backpack a "one-stop shop" for our crew leaders, it would be good to have a "Find a Work Party" button (location indicated below) that would navigate from the "My Work Parties" page to the "Find a Work Party" window.

![image](https://cloud.githubusercontent.com/assets/14843712/12251408/9c85f8d0-b883-11e5-8adc-1de763cc4079.png)

**Comment by cguardia** [comment]
Fixed on mybackpack-buildout branch.

**Comment by ebskopin** [comment]
looks good. Thanks for adding.
