### ISSUE TITLE
VMS: Live Site Login & Register Error

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#534]
When attempting to login to My Backpack, click the "Join Work Party" button on the vms.wta.org site the following error occurs: 

![image](https://cloud.githubusercontent.com/assets/14843712/12252298/d2cec80c-b88a-11e5-9b58-15684c34ce62.png)

**Comment by davisagli** [comment]
fixed

**Comment by ebskopin** [comment]
working, thanks.
