### ISSUE TITLE
VMS: vms.wta.org My Backpack Login error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#535]
When I go to vms.wta.org and click on My Backpack / Login I get directed to the URL:  http://127.0.0.1:6543/

Returns the Page can not be found error.

**Comment by cewing** [comment]
This is a duplicate of the error reported in #534

**Comment by WaBirder57** [comment]
Opps, thanks.  Elliott was quicker than me.  Sorry not to have checked first.
