### ISSUE TITLE
VMS: Invite from Waitlist notification E-mail for Staff

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#536]
@mscholtz The notification e-mail to staff alerting them to the fact that someone should be invited off the waitlist for a workparty seems to be tied to the "Remaining Spots for New Registrants" field in the WP and only issues when this value is greater than 0. This presents a problem, because when there is a waitlist, this value is often a negative value, and staff are not alerted when there is in fact a spot on the waitlist.  

Here is a walk through of what is occurring (testing on the following WP (https://cs9.salesforce.com/a2eK0000003Oz8l):  

![image](https://cloud.githubusercontent.com/assets/14843712/12272020/e979d9d8-b912-11e5-8432-dd180674ea03.png)

![image](https://cloud.githubusercontent.com/assets/14843712/12272026/f36048a6-b912-11e5-9206-d9fdff532514.png)

**Comment by mscholtz** [comment]
@ebskopin I will review this.  But just wanted to check: the steps in your screenshots start w/ D, are we missing steps A, B, and C?

**Comment by mscholtz** [comment]
@ebskopin bump..

**Comment by ebskopin** [comment]
Sorry for the delay.  That was a cut and paste and A-C are redundant.

**Comment by mscholtz** [comment]
Well diagnosed, @ebskopin!  This was indeed buggy in the way you suggested.  Fixed now, please try it again.

**Comment by ebskopin** [comment]
I've fiddled with that WP a bit and am not getting the automated "Invite from the Waitlist" e-mails.  Any chance they are being suppressed?

**Comment by mscholtz** [comment]
Don't think so.  You sure you're changing it from a state where there's no room for folks to be invited from waitlist to a state where there is room?

**Comment by ebskopin** [comment]
Huh. I'm not sure why it wasn't prompting the emails for this WP (https://cs9.salesforce.com/a2eK0000003Oz8l). However, I tested on a number of others and this is now working correctly. Thanks.
