### ISSUE TITLE
VMS: Question on recommended flow for Youth Vacations

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#537]
Youth Vacations follow a different flow for processing registrations which we didn't have budget to specifically build into this first version of VMS.  I wanted to review this flow to make sure I am not overlooking some feature of VMS that will provide unexpected (overlooked) behavior.

The basic concept is the participants for Youth Vacations in 2016 will submit an application (Online form via our website) for one or more of the posted Youth Vacations.  Staff will review these and build a vacation crew that has a good mix of participants.

Staff will manually register youth to these work parties which will start the VMS email/work flow.  Also participants could check My Backpack for info on these work parties and make sure their forms are complete (Parental Release, Teacher Reference, Medical and Back country experience).  Staff will also collect payment outside of the VMS system so in VMS we will not have any cost associated with these trips.  Note that this includes a Scholarship payment option.

Emails will be sent as scheduled by the Work Party type.  Crew Leader will complete the WP Summary report when the trip is complete and set Thank you Email to the crew.

Does this seem like a process that will work as I have described?

Attached is a flow diagram from the youth team that describes this whole flow.

![2016 youth vacaton flow diagram](https://cloud.githubusercontent.com/assets/8312206/12274043/dc142d42-b91d-11e5-925e-4619afbc4e15.JPG)

**Comment by davisagli** [comment]
I think that sounds workable. You'll want to try it out on the staging site to make sure it works. @mscholtz should probably look this over too.

**Comment by mscholtz** [comment]
I don't see any major problems with what you describe, Charlie.  I'm not
sure I totally understand the flowchart, though.  It's not obvious to me
which parts are SF/VMS.

On Tue, Jan 12, 2016 at 1:24 PM, David Glick <notifications@github.com>
wrote:

> I think that sounds workable. You'll want to try it out on the staging
> site to make sure it works. @mscholtz <https://github.com/mscholtz>
> should probably look this over too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/537#issuecomment-171060168>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Thanks for looking this over.  Eventually this may become a VMS 2.0 feature.  That is the ability to have applications which we assign to work parties or even have a lottery system to assign WP Slots to lottery winners.
