### ISSUE TITLE
VMS: All participants in Crew Corner Roster viewable to ACLs

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#538]
This may contradict previous thinking, but all individuals registered for a WP (whether the ACL is registered or not) should be visible to ACLs on the Crew Corner Roster (presently only fellow ACLs and CLs are displayed). This links associated with peoples names should not be clickable by ACLs, however.

**Comment by davisagli** [comment]
Okay, should work like this now.

**Comment by ebskopin** [comment]
Works, thanks.
