### ISSUE TITLE
IE v 11 doesn't load VMS Find A work Party Page

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#54]
Using IE v 11 the VMS home page, Find a Work Party, doesn't completely load.  I have attached a screen shot which shows the text "Loading"....

![ie vms home page doesn t load](https://cloud.githubusercontent.com/assets/8312206/6699416/0e245dbc-ccbf-11e4-8551-077a0818c579.JPG)

**Comment by davisagli** [comment]
Fixed -- should work now.

**Comment by WaBirder57** [comment]
This loads in IE 11 now, thanks.
