### ISSUE TITLE
Confirm setup of FormAssembly forms

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#541]
@WaBirder57, I noticed that the FormAssembly-based Required Documents (Medical History and Backcountry Experience) have the same Form Link URL entered in production SF as in the sandbox.

I suspect that those forms are still configured to submit data to the sandbox, not to production SF. Is that true, and if so are you planning to update them to submit to production, or create new forms that submit to production?

Once you think you have them configured correctly you should test each of these forms once from the live VMS instance to make sure the data gets recorded correctly.

**Comment by WaBirder57** [comment]
We created (copied existing ones) new Form Assembly forms for use for VMS production.  Here are there names and the URL's to use.  Can you update vms.wta.org to use these new URL, thanks.

WTA Volunteer Medical Form - Production
https://www.tfaforms.com/405830

Back country Experience - Production
https://www.tfaforms.com/405819

Volunteer Questionnaire - Production
https://www.tfaforms.com/rest/forms/view/405827

These are the Sandbox ones:

WTA Volunteer Medical Form - Sandbox
https://www.tfaforms.com/362208

Back country Experience - Sandbox
https://www.tfaforms.com/362616 

Volunteer Questionnaire - Sandbox
http://www.tfaforms.com/rest/forms/view/370446

Here is your sample BCRT work party which I was attempting to register for:
http://vms.wta.org/workparty/a2mA00000009HRj

**Comment by davisagli** [comment]
@WaBirder57 you can update the Form Link field for these required document records in production SF:
https://wta.my.salesforce.com/a37A0000000GcKM
https://wta.my.salesforce.com/a37A0000000GcKL

And the Feedback Survey URL is in a custom setting which you can update here: https://wta.my.salesforce.com/setup/ui/listCustomSettingsData.apexp?id=a2z

**Comment by WaBirder57** [comment]
Thanks again (sorry I spaced on those links).  We have it working now.
