### ISSUE TITLE
Request higher Salesforce API call quota

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#543]
@WaBirder57, we had discussed requesting a temporary increase in Salesforce's limit on API calls for the first few weeks that the live copy of VMS is running, until we have a better idea of what typical usage looks like and can figure out if we need to pay for more calls permanently or optimize the system.

Can you make this request to your account rep?

Your current limit is 36,000 per 24 hours (1000 per user license). The live instance of VMS is currently using about 12,000 calls per day for indexing but user interaction will use more and we don't know how heavily the system will be used. I'd suggest requesting an increase to 100k/day through the date that signup for volunteer vacations begins.

/cc @mscholtz

**Comment by WaBirder57** [comment]
Thanks for the reminder.  I have sent off this request.

**Comment by WaBirder57** [comment]
Looks like they will give us a 30day trial with 100,000 API calls per day.  Once we nail down our launch date (looking like Jan 25th) I will ask them to start then.

**Comment by davisagli** [comment]
Perfect! thanks.

**Comment by mscholtz** [comment]
@WaBirder57 did this get done?

**Comment by WaBirder57** [comment]
I will have this start Monday when we launch.
