### ISSUE TITLE
WTA Website - New Logo Needed on Jan 15th

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#544]
(From Loren) 
@KindraRamos 
By noon on Jan 15, we need to replace the logo file here (http://www.wta.org/logo.gif) with the attached logo (Note: the source file is a gif, and I've attached both jpeg and gif versions - not sure if that matters)

I'd also like to replace the website tab icon with the attached logo mark (named bug) at the same time. 

If it can happen easily at the same time, I would love for these image files to be sourced in our contents, so that when staff need to switch it again, I can change the source file. Right now, I can't get at it. 

![wta_50_black](https://cloud.githubusercontent.com/assets/8312206/12305721/13eab1f0-b9eb-11e5-81d1-47d3df6e59e5.jpg)
![wta50_bug_black](https://cloud.githubusercontent.com/assets/8312206/12305722/13ec1bb2-b9eb-11e5-9285-2148d524012a.jpg)
![wta_50_black](https://cloud.githubusercontent.com/assets/8312206/12305723/140809da-b9eb-11e5-98ce-520576f3df73.gif)

**Comment by skleinfeldt** [comment]
1. This work should be reported on the WTA Support Freshbooks project
2. The actual switch needs to happen around 11AM Pacific on Friday Jan 15

@davisagli how should we do this?
- swap the new logo/favicon for the old one in the location that exists now and deal with improvements later
- change where the theme finds the logo so that it can be content, and explain this to Loren so that she can do the switch at the appointed hour

A different approach may be needed for the logo vs the favicon...

**Comment by davisagli** [comment]
I'll work on preparing this tomorrow. I might be able to set it up to load these from content items, but this isn't much advance notice and I have other tasks on my plate too, so we may have to settle for just swapping out the files in the theme for now.

After this change the desktop header will look like this:
![screen shot 2016-01-13 at 2 04 14 pm](https://cloud.githubusercontent.com/assets/49014/12309323/d987325e-b9fe-11e5-8862-dad5e2180553.png)


And mobile like this:
![screen shot 2016-01-13 at 2 05 37 pm](https://cloud.githubusercontent.com/assets/49014/12309316/d3861302-b9fe-11e5-88b3-f3c2fc82c5e1.png)


Is that correct?

**Comment by KindraRamos** [comment]
Thanks David - I really appreciate you getting to this at such a busy time. The mobile looks great but the desktop header looks like it is squishing the logo. Let me know if you need us to send you a file that is cropped differently? Thanks again!

**Comment by davisagli** [comment]
@KindraRamos Ah, you're right, the new logo is a different aspect ratio than the space in the header that holds it. The space is 114 pixels wide by 132 pixels tall so if you want to prepare a file at that aspect ratio I can use it. Or I can take care of that and just leave a bit more white space between the logo and the banner.

**Comment by KindraRamos** [comment]
Thanks David if you can fix it with a bit more white space that is fine, as long as it is the right shape and center anchored (so it doesn't look like it is floating).

**Comment by davisagli** [comment]
@KindraRamos for the logo in the footer do you want the margins around the shield transparent so the blue shows through?

**Comment by KindraRamos** [comment]
It would be great if it didn't look like it was sitting on a white square.

**Comment by davisagli** [comment]
@KindraRamos how's this?

![screen shot 2016-01-14 at 4 28 17 pm](https://cloud.githubusercontent.com/assets/49014/12342093/e153712c-badb-11e5-8d79-9587618b0bb3.png)

**Comment by KindraRamos** [comment]
that works thanks

**Comment by davisagli** [comment]
@KindraRamos and Loren, I've got the new logo and favicon in place on http://staging.wta.org if you want to take a look, and I'm ready to deploy them to production at 11.

I did switch them to load from content items (/wta_logo.png and /favicon.png); however content images may be cached in users' browsers for up to 4 hours with no way to invalidate them if the image changes, so I'm going to take care of this change to make sure that it happens at the right time.

**Comment by skleinfeldt** [comment]
Awesome, thanks @davisagli

**Comment by KindraRamos** [comment]
Thanks David

 

Kindra Ramos – director of communications and outreach 

Washington Trails Association 

wta.org * 206-965-8563 

 

WTA is powered by hikers like you!

**Comment by davisagli** [comment]
The new logo is live.

**Comment by KindraRamos** [comment]
awesome thanks so much!
