### ISSUE TITLE
VMS: Salesforce Permission sets question

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#546]
@mscholtz @davisagli If we restrict access to certain information, such as the Medical Forms, and then set up a Permission Set for those individual SF Users who need access will this impact programmatic access to this information?

**Comment by mscholtz** [comment]
As long as you don't change the permissions for the profile that VMS itself
is using, it shouldn't affect it at all.

On Thu, Jan 14, 2016 at 12:03 PM, Charles Kahle <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> @davisagli
> <https://github.com/davisagli> If we restrict access to certain
> information, such as the Medical Forms, and then set up a Permission Set
> for those individual SF Users who need access will this impact programmatic
> access to this information?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/546>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/
