### ISSUE TITLE
VMS: Special Event spot Font 

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#547]
The driving directions for the Special Event spot does not display in the same font as the "main" driving directions that display on the Location tab. I see it as a smaller font size, which is not what we want. 

See this example:

http://staging.wta.org:6543/workparty/a2eK00000000v2u#location
Here is the work party in Salesforce: https://cs9.salesforce.com/a2eK00000000v2u
Here is the special event spot in Salesforce: https://cs9.salesforce.com/a38K00000003iiu

I think the reason for this is that the Directions field on the WP Special Event Spot object does not have the special HTML text editor like all of the other fields do.

**Comment by cguardia** [comment]
This work party has the text wrapped in a span tag with font-size of 12.8px. This is what makes it different from the special event text size (1em). All other work parties I checked do *not* have this text wrapped  in a span tag, so the main directions look the same as the special event text.

If the editor styles are used to set font size, there's no way we can keep up with that, even if we add a text editor to the special event field.

**Comment by davisagli** [comment]
I edited the trailhead directions for that work party to remove the font that was hardcoded in the field value in Salesforce.

I also adjusted the work party view to automatically add paragraph tags to both of these fields in the same way that we do for the fields shown on the Info tab.

**Comment by ebskopin** [comment]
Thanks. Looks good.
