### ISSUE TITLE
VMS:  Pyramid Find a Work Party text seach questions

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#549]
The Find a Work Party has a text search field under the advanced search option.

Questions are:
1) What text is included in this search?
2) If the WP text is updated in Salesforce, how long before we should expect this to be searchable?  Say the crew leader for the WP changes.

**Comment by davisagli** [comment]
It currently includes all text fields that are fetched from Salesforce and indexed in elasticsearch for a work party, which is quite a few (but does not include names of registrants, only the leader). I can look up a full list if you want.

The index is currently updated once a minute, assuming something didn't break.

**Comment by WaBirder57** [comment]
Does this tool support search phrases in quotes?   Such as "lake meade".
Do you have a link to info on this elastic search so I can document it?
Thanks.

**Comment by davisagli** [comment]
elasticsearch is a widely used and quite flexible search engine: https://www.elastic.co/products/elasticsearch

Yes, phrases in quotes should work. Try it on VMS staging and if it's not returning the results you expect, we can talk about how to tweak the search so it works better. We haven't spent time tuning elasticsearch but it can do a lot.

**Comment by WaBirder57** [comment]
Thanks for this info.

**Comment by WaBirder57** [comment]
How best to communicate thoughts on how to tune this search tool?  For example I would expect that putting a test string in quotes would only search for exact matches of that quoted text. For example searching for "Lake 22" returns WP that mention just "Lake".  I don't want you all to work on this tuning in a one off fashion. Should I develop a list of search syntax that we would like to use and pass that along?

Ideally we would be able to have all the test search boxes on the WTA site work that same way.  Do you know if they use the same elastic search and if they did could it be standardized?

**Comment by davisagli** [comment]
Hmm, a phrase search like that should work; we can check on why it isn't.

It's possible to make text search in Plone use elasticsearch (or solr, which is similar), but it takes some effort to set up. This is one of the possibilities we discussed when Sally was in town.

**Comment by davisagli** [comment]
This should work better now; I told elasticsearch to use a different way of parsing the search query. Here's a list of the special characters you can use with the new way: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-simple-query-string-query.html#_simple_query_string_syntax
