### ISSUE TITLE
VMS: Work party Registration status: No Show

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#553]
We would like to add a Work Party registration status value of "No Show".  Crew Leaders in the field or staff would change the registration status to "No Show" for volunteers who don't show up for a work party.  CL's would use this rather than "canceling" a volunteer who doesn't show up or reporting Zero hours for that volunteer.

This will help us have a consistent way track if there are volunteers who routinely don't show up by seeing a series of Registration Status values of No Show.

Can we just add this as a new value for the Salesforce Registration Status field to work as have described?

**Comment by davisagli** [comment]
I think it's a bad idea to add a new registration status value this close to launching the site. There are a LOT of places in both Salesforce and the Pyramid app that check for particular status values, so we need to review them to make sure they handle the new value properly. That takes time and we're also bound to miss some on the first pass, so it will want careful testing.

Also, if your goal is for crew leaders to be able to edit this then we also need to build UI for doing that.

So this sounds like a new story to me, not a quick ticket that's doable before launch.

**Comment by davisagli** [comment]
If you're okay with limiting it to staff for now a much less risky option would be adding a new checkbox No Show field rather than adding an option to the existing status field, and add the UI for crew leaders later. Do you agree, @mscholtz?

**Comment by WaBirder57** [comment]
Thanks for answering my question, I thought it might be more complex than just adding a new pick list value to the Status field.  I will close this ticket and figure out if we need a new story.  This idea of a check box for Staff to use would be something that I could implement if we need something ASAP.
