### ISSUE TITLE
VMS: SF Deployment question on Account object

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#554]
@mscholtz I have been customizing, in production Salesforce, the Account dependent pick lists for the various land manager fields; Government Type, Managing Agency, Jurisdiction and District. 
I trust these will not be impacted by your final deployment of SF customization to production from .VMS2.  Let me know if this is not the case so I can figure out what to do.

**Comment by mscholtz** [comment]
Hmm.  It would be ideal if this were done in sandbox too, but I will try to work around it.  Thanks for the heads-up.
