### ISSUE TITLE
Salesforce Lat/Lon conversion error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#58]
The Map PinHead for a Trail Head is misplaced.

When entering in a Lat and Lon into a Salesforce Trail Head a decimal value is expected.  Enter the following:  47.502039, -122.077463.

When saved Salesforce shows: 47°30'0''N 122°4'48''W

This is not correct it should be:  47°30'07.3"N 122°04'38.9"W

To get the correct value I used Google Maps the right click on any map location.  Select What's Here.  Map shows decimal Lat/Lon for that location (top left corner).  Enter that Lat Lon into the maps search box and it returns Lat Lon as Deg, Min, Sec.  These are different than what Salesforce Shows.  Also when viewing the Trailhead map pin it is in a different location than specified from data gleaned from Google Maps.

**Comment by davisagli** [comment]
Can you please give the link to this particular trailhead in Salesforce

**Comment by WaBirder57** [comment]
https://cs10.salesforce.com/a28J0000000gbJ8

**Comment by davisagli** [comment]
Looks like the field in Salesforce is configured to round the value to 2 decimal places but I think that can be fixed. /cc @mscholtz

**Comment by WaBirder57** [comment]
Ah, in my experience 6 decimal places is sufficient and necessary to get accurate mapping results.

**Comment by mscholtz** [comment]
Done.

**Comment by WaBirder57** [comment]
The Trail Segment also uses Lat/Lon for the start and end locations.  This same "fix" is needed for this object for both start and end fields. @mscholtz

**Comment by mscholtz** [comment]
Done.
