### ISSUE TITLE
createregistration webservice should validate duplicate registrations

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#6]
I tried registering myself for a work party that I was already registered for, and the webservice created another registration. It should return an error in this case.

Also, it created this registration even though waiverSigned was false. Should that be allowed?

**Comment by mscholtz** [comment]
@WaBirder57 can you verify what should happen w/ the waiver?  Should it simply not allow registration at all if they haven't signed it?

@davisagli do you need the webservice to validate this?  Or can you just validate on the front end?

**Comment by davisagli** [comment]
I'm already validating it on the front end. Just wanted to be thorough in case we forget to do that sometime. Maybe the validation should be done in a way that also applies to WP Registrations created through the Salesforce UI.

**Comment by WaBirder57** [comment]
Yes,  on the front end is sufficient.  

 

If staff are adding folks on the back end using usually it is moving folks from one WP to another (so they will have already ticked the box) or they are on the waitlist and being added to a WP.  To be on the Waitlist they will have had to check the tic box).

 

In any case our “official” waiver is the signed release at the trail head.

 

Charlie

**Comment by ninetaLogik** [comment]
Ok, this is now done. We are throwing an exception if there is already a reg for the contact for that wp.

**Comment by davisagli** [comment]
Okay. Before I close this I want to make sure that VMS reports the error in a user-friendly way, and in order to do that I need the error code (see #7)

**Comment by mscholtz** [comment]
Then you'll have to keep it open for now.  We're not going to get to #7
immediately.

On Wed, Feb 11, 2015 at 11:09 AM, David Glick <notifications@github.com>
wrote:

> Okay. Before I close this I want to make sure that VMS reports the error
> in a user-friendly way, and in order to do that I need the error code (see
> #7 <https://github.com/washingtontrails/vms/issues/7>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/6#issuecomment-73943352>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Changed my mind. I confirmed that it throws the exception. We can deal with error reporting in #7 and I'll close this.

**Comment by davisagli** [comment]
It's throwing this exception even if the contact's existing registration has Status = Cancelled. It should not throw an exception in that case.

**Comment by ninetaLogik** [comment]
This should be addressed now, it will not consider Cancelled registrations , therefore will not throw exception.

**Comment by davisagli** [comment]
Yep works now. Thanks!
