### ISSUE TITLE
Clicking to open certain work parties from Find a Work Party give Error # 500

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#60]
Clicking to open certain work parties from the Find a Work Party Web page gives the following error message:

{"code": 500, "detail": "'NoneType' object is not iterable", "title": "TypeError"}

Here are couple WP that I tried which gives this error:
Karen's Awesome Work Party
Spokane-Area Work Parties

Here are some WP that don't give this error message:
David's Test
Oyster Dome - - day wp content test

**Comment by davisagli** [comment]
Fixed.

@alecpm's fix for #55 was not handling work parties with no trail segments assigned.
