### ISSUE TITLE
Workparty Report of Volunteer Hours - need to enter 1/10 hour increments

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#62]
When Crew Leaders are entering volunteer hours worked per day on a work party we need to have 1/10 hour increments.  Currently this is only set to whole numbers.

**Comment by davisagli** [comment]
I can change this in the pyramid app once these changes are made in Salesforce:
- [ ] change the field that stores hours to accept a decimal place
- [ ] change the type of the webservice parameter that holds hours

**Comment by kuffelman** [comment]
Charlie - I thought we were going to wait on this while Julie analyzes what the impact of more rounding would have to her stats and if that would be a problem for the parties who consume the stats (and the question she's pondering is if 1/2 days will work as the smallest increment). Do your funders and partner agencies actually require you to be accurate to the order of 6 minute increments for volunteer time? That seems rather lawyerly:)

**Comment by WaBirder57** [comment]
For entering hours worked per day I was working on the assumption that choices were whole numbers, 1/10ths or 1/100ths.    Given this we have concluded that 1/10ths were good.

 

RE Julies research:

 

The ½ days research is to answer the question about calculating “days of credit” given x hrs of trail work.  If someone is on trail for 4 days and works, 7, 7, 4 and 3 hrs, how many days credit do they get?

 

Should have an answer for this soon (tomorrow?).

 

Charlie

**Comment by ninetaLogik** [comment]
@mscholtz and @WaBirder57 : I assume we are talking about the Work Party Hours object here and the Hours Completed field, correct?

**Comment by davisagli** [comment]
@ninetaLogik that's right. And also the input for the webservice that is called to update a bunch of Work Party Hours at once.

**Comment by ninetaLogik** [comment]
@davisagli this should be fixed now, could you give it a try and let me know. I put the Reviewing tag on it , is that what I am supposed to do?

**Comment by davisagli** [comment]
Looks like it works @ninetaLogik; thank you. I'll let Charlie close this after WTA has tested it.

**Comment by skleinfeldt** [comment]
@ninetaLogik you are correct, set the Reviewing tag when you finish a ticket and it is ready for WTA test.

**Comment by WaBirder57** [comment]
This now works correctly.  Note that I changed the Salesforce Work Party Hours.Hours Completed field to have 1 decimal digit down from 2 so that it matches these changes.
