### ISSUE TITLE
Work Party Info Page footer should show name of Hiking Guide hike, not work party name.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#63]
Currently the "footer" of the Work Party detail page shows "Learn about Evans Creek ADA - 4/11 & Read recent trip reports."  Where  "Evans Creek ADA - 4/11" is the name of the work party which links to the Hiking Guide entry for Evans Creek Preserve.  This link name should be the name of the hike (Hike Name in plone) for the referenced hiking guide entry.

Thus it should read: "Learn about Evans Creek Preserve & Read recent trip reports."

**Comment by davisagli** [comment]
This should now show correctly once hiking guide entries are entered as per stories 206 and 207.

**Comment by WaBirder57** [comment]
I am not able to get this information to display at the bottom of the work party info tab.  The Correct information is pulled into the Trail Segment Hiking Guide Hiking Guide entry, but doesn't show up on the VMS Info tab.  Check out May 23 Spokane Area (http://staging.wta.org:6543/workparty/a2eK0000000wLTKIA2/) or May 8th Evans Creek WP (http://staging.wta.org:6543/workparty/a2eK0000000wL7HIAU).  Note that content on WP descriptions are updating on the Info tab but Trail Segment Hiking Guide info is not showing up.

**Comment by davisagli** [comment]
It's showing up now. @mscholtz the Process Builder that takes care of copying these values to the trail segment was present in the new sandbox, but not activated. Maybe an additional step that needs to happen when deploying to a new instance? You may also want to review to make sure any other Process Builder flows that should be activated are.

Also copying these values to the work party and displaying them on the work party layout is an outstanding task from story 206 that we didn't get to yet.

**Comment by WaBirder57** [comment]
Thanks, working now.
