### ISSUE TITLE
SF Workparty Registration changes not updating in WorkParty CrewCorner tab roster

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#64]
When changes are made in Salesforce to a Workparty registration (for example Status or Role) these are not reflected in the workparty crewcorner tab.

In SF check a workparty registration list, compare to crewcorner tab in pyramid - should match.  Change a registration status in SF from Registered to Waitlist.  Crewcorner tab is not updated to reflect this change.  Same for changing Role in SF.  Also when entering new registration in SF.

I tried refreshing browser, clearing cache, logging out and logging in (as Crew Leader).  Roster in CrewCorner tab doesn't update.

Note that I can update the Directions in SF and see these changes reflected in the Location Tab but in this same time period the Roster is not updated.

**Comment by davisagli** [comment]
After you view the roster in crew corner, the result from Salesforce is cached for 10 minutes to avoid using so many API calls. So it will take up to 10 minutes for changes to registrations made in Salesforce to be visible in crew corner.

**Comment by WaBirder57** [comment]
This works as David describes.  Thanks.
