### ISSUE TITLE
Crew Corner Roster Sort Order

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#65]
In Crew Corner the Roster should be sorted by Role first (CL, ACL then everyone else)  Then sorted by Status so that Registered Volunteers appear first and then Wait-list, etc. 

Bonus points if the UI can have a bold line or small separation between the groups based on Role and Status.  With a list of 20+ individuals this will make the roster easier to scan and read.

**Comment by davisagli** [comment]
It's currently sorted by role, then name (last, first). So I think the change you're asking for is adding the sort by status. Right?

**Comment by WaBirder57** [comment]
Yes, that is correct.

**Comment by davisagli** [comment]
This now works as described.

**Comment by WaBirder57** [comment]
The associated Work Party pop up box to edit hours should show the crew members in the same order.  Does that need to be a new ticket?
