### ISSUE TITLE
Find a Work Party Map doesn't show the correct locations for the selected regions

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#67]
By default the Find a Work Party map is only showing a subset of work party locations - Not all that are available to display.

If you select the regions you want to filter on while in the list view and then click Map, it will show the correct locations (try North Cascades and South Cascades).  Then change to Map Tab.  If you then click All Regions the maps goes back to the incorrect limited number of locations.

So it seems you first need to be in the list view to change the filter criteria for the map locations.  Although this isn't always the case.  So, hard to be more specific.  Let me know if you need additional, alternative steps to reproduce this behavior let me know.

**Comment by davisagli** [comment]
Fixed. It was hitting an error on work parties with no trail segment start point set, that preventing adding markers for subsequent work parties to the map.

**Comment by WaBirder57** [comment]
Works now.  Thanks.
