### ISSUE TITLE
Sign In sheet doesn't display WTA logo from Salesforce Rich Text liability field in IE and Chrome - works with Firefox

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#68]
Printing the Crew Roster (Story #16) looks ok in IE, Chrome and Firefox except that the WTA logo in the Salesforce rich text Liability field only displays in Firefox. In IE and Chrome it only displays the Alt Text and an image place holder.

**Comment by davisagli** [comment]
The image you put in the liability text is served out of Salesforce. So it's only going to be shown to users who are logged into Salesforce (I'm guessing you were in Firefox, but not in the other browsers).

I'd recommend not including images in text in Salesforce that's going to be displayed outside of Salesforce, for this reason.

**Comment by WaBirder57** [comment]
We want to have the WTA logo on then Sign In Sheet.  I will try changing this image to use a source that is open to the public to see if it will work.

**Comment by davisagli** [comment]
That should work. We could also hardcode the logo in the sign-in sheet template.

**Comment by WaBirder57** [comment]
Using a public resource like www.wta.org/logo.gif works.  HTML code is required in text box to correctly wrap text around image.
