### ISSUE TITLE
CreateRegistration webservice not returning error codes

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#7]
We're adding the numeric code to the Exception object, but it's not appearing in the repsonse sent back via the API.  David's getting this:

```
Error Code 500. Response content: [{u'errorCode': u'APEX_ERROR', u'message': u'WTA_REST_CreateRegistration.ContactNotFoundException: Contact with this contactId could not be found\n\nClass.WTA_REST_CreateRegistration.throwException: line 132, column 1\nClass.WTA_REST_CreateRegistration.doPost: line 76, column 1'}]
```

Possible approaches include:
* little more research into whether it's possible to include this in response
* don't throw an exception, instead include status and err code in our response object
* just put the code as first part of the message, let David parse it

**Comment by davisagli** [comment]
Done; see https://github.com/washingtontrails/WTA-Salesforce/commit/5e409d69f9e55a25ca49e150b0aebf67ad79b6c8. I used the 2nd approach (don't throw an exception, instead include status and err code in our response object)

@ninetaLogik note that you'll need to refresh WTA_REST_CreateRegistration and WTA_TEST_REST_CreateRegistration
