### ISSUE TITLE
ACLs should be charged for work parties that require payment

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#71]
What does VMS use to flag that a work party registration requires a payment?

**Comment by davisagli** [comment]
The Member Fee and Non-member Fee fields on the work party in Salesforce. The former is used if the user registering is a member; otherwise the latter. If it's not empty and not 0, payment is required.

**Comment by WaBirder57** [comment]
Volunteer registering for a work party as a Volunteer or ACL should be charged for a WP registration if the Member or Non-member Fee fields are not blanks or Zero (see David's comments above).

Test: sign up as an ACL for a Volunteer Vacation WP (which has fee's assigned).  You will not be prompted for payment.  Cancel registration and re-sign up as a Volunteer, you will be prompted for payment.  Both of these cases should be prompted for payment.

**Comment by mscholtz** [comment]
@davisagli it's not clear to me what SF changes are needed here

**Comment by davisagli** [comment]
@mscholtz the registration webservice sets the registration status to Registered or Payment Pending depending on whether payment is required. Currently it never goes to Payment Pending when registering an ACL, but it needs to do that in the case of ACLs registering for Volunteer Vacations. So we probably need some flag on the work party type for whether ACLs must pay, and the registration webservice needs to honor that.

**Comment by WaBirder57** [comment]
@davisagli @mscholtz ACL's will need to pay same as volunteers for work parties that require payment.

**Comment by ninetaLogik** [comment]
@WaBirder57  Are CLs in the same situation as ACLs and Vols? Will they need to pay for Work Parties that require payment?

**Comment by mscholtz** [comment]
No. CLS are assigned by staff in the back end. They don't register online.

**Comment by ninetaLogik** [comment]
Gotcha. Thanks!

**Comment by mscholtz** [comment]
assigning to charlie for review

**Comment by WaBirder57** [comment]
Tiffany reports the following problems are still occurring.  I have attached an MS Word file with the following content plus hyperlinks to the various objects so you can more quickly reproduce her test.

[Re Testing Ticket #71.docx](https://github.com/washingtontrails/vms/files/3969/Re.Testing.Ticket.71.docx)
ACL:
•	I logged in as Margaret Sanger, ACL 
•	I registered as an ACL for Sawtooth Logout - VV content test and was able to register myself and my friend Rebecca West with no payment for either of us. 
•	For the pay to play 4.0 party chose the volunteer option instead of ACL, did not try to register a friend and was prompted for payment.
Volunteer:
•	logged in as Sarah Weddington, a volunteer, and registered myself and my friend Nellie Bly. Prompted for payment for both when I registered for Sawtooth Logout - VV content test

CL:
•	logged in as a CL, Estelle Griswold.  
•	Registered for Sawtooth Logout - VV content test, a WP with a different CL. Given the option of ACL or volunteer. Chose ACL and registered without payment prompt.  
•	Registered for VV Registration Process Test, another WP with a different CL. Chose volunteer instead of ACL and was prompted for payment

**Comment by mscholtz** [comment]
@davisagli you want first crack here re users not getting prompted for payment?

**Comment by davisagli** [comment]
@mscholtz the problem is here: https://github.com/washingtontrails/WTA-Salesforce/blob/master/classes/WTA_VMS_REST_CreateRegistration.cls#L245

The Work_Party_Role__c picklist value is 'Assistant Crew Leader', not 'ACL'

**Comment by mscholtz** [comment]
@ninetaLogik could you please make this change this week?  Thanks!

**Comment by ninetaLogik** [comment]
This should be fixed now.

**Comment by WaBirder57** [comment]
Looks good, thanks.
