### ISSUE TITLE
Find a work party calendar view needs to handle up to 13 + work parties on a single day

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#72]
The calendar view needs to handle up to 13 or more work parties on a single day.  Perhaps adding a "see more" link to a pop up window will work. I don't think there is a UI designed for this case.

**Comment by cewing** [comment]
This is ready to review once @davisagli merges the pull request and deploys the changes.

## To Test
1.  Ensure that some days have more than two events scheduled
2.  Click on the calendar tab of the search page
3.  Note that on a day with more than two events the text "See all *n* scheduled events" appears (where *n* is the number that are on that day)
4.  Click on the day (or on the text) to open the pop-up
5.  Verify that all events scheduled for that one day appear and that no other events do.
6.  Click any event to view the detailed listing for that event
7.  Click the 'close' (X) button at the top right of the pop-up to dismiss the pop-up and return to the calendar view
8.  Note that if you have moved to a non-default page of the calendar (some months in the future), that page is still displayed (you are viewing the same thing you were when you opened the pop-up)

**Comment by WaBirder57** [comment]
Nice, works well and correctly matches filtered results.
