### ISSUE TITLE
Referal Relationships not created for new Volunteer added as a Friend during registration.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#77]
Story #37, Iteration #3 describes a referral relationship that will be created when a logged in user adds an individual new to Salesforce to a work party.  I assume this is would should up in the Salesforce Relationship object.  This isn't working.

**Comment by davisagli** [comment]
@mscholtz FYI, Elliot changed this one to High Priority.

**Comment by mscholtz** [comment]
@ebskopin just for my own peace of mind, can you say why this one is high priority?  doesn't seem like the most important thing in the world on the face of it.

**Comment by ebskopin** [comment]
The request was made for me to start flipping some medium priority stories to high priority. This one seemed more important than some of the medium priority stories, but likely still ranks as medium priority...

**Comment by skleinfeldt** [comment]
@mscholtz FYI in one of the meetings last week we (Jazkarta) were out of high priority tickets to work on and we asked @ebskopin if he'd like us to work on some medium priority ones. He said yes and agreed to change priorities for selected tickets he wanted us to work on.

**Comment by mscholtz** [comment]
Ah, got it.  I would actually prefer if you guys would just put comments on
the ones you want and say "do this one first" or whatever.  That way a) we
know what's really high priority looking back, and b) if new actual high
priority ones come in, we know those take precedence.  But no big deal
either way.

On Tue, Nov 10, 2015 at 1:37 PM, Sally Kleinfeldt <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> FYI in one of the meetings last
> week we (Jazkarta) were out of high priority tickets to work on and we
> asked @ebskopin <https://github.com/ebskopin> if he'd like us to work on
> some medium priority ones. He said yes and agreed to change priorities for
> selected tickets he wanted us to work on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/77#issuecomment-155574637>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by skleinfeldt** [comment]
Good point - sounds like a case for another label that we can search on. I created "Med-High Priority" and assigned to this ticket. @ebskopin can you apply this to other tickets you flipped? I will email the troups.

**Comment by ebskopin** [comment]
Will do.

**Comment by skleinfeldt** [comment]
OTOH @davisagli dislikes having another priority to search for, so I'll just label these med-high ones Medium as well so they show up in that search. The med-high label can just serve as a priority bump.

**Comment by mscholtz** [comment]
@drewpiston can you work on this one?   I think this will have to be in the registration trigger class, which I am continuing to work in as well.   So let's try to time the work around each other, and commit often!

**Comment by drewpiston** [comment]
Ready for testing/review!

**Comment by ebskopin** [comment]
Done.
