### ISSUE TITLE
Dynamic Limit to work party not stopping volunteers from signing up.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#78]
Based on Story #182 Iteration #4, while the Work Party Waitlist Volunteers Only flag gets set correctly when the ratio of Volunteers to Crew leaders is not met in the Waitlist Volunteers Window.  This doesn't stop Volunteers from registering for the Work Party.  They should be only able to join the wait list.

Follow the testing instructions for this story, I would expect the "Work Party Full - Waitlist" only icon to display for the work party in VMS.  Also, new volunteers should not be able to join this work party.

**Comment by ninetaLogik** [comment]
@mscholtz what needs to be done on the SF for this ticket?

**Comment by mscholtz** [comment]
It's described in Charlie's comment, above.  

"new volunteers should not be able to join this work party."
"They should be only able to join the wait list."

**Comment by mscholtz** [comment]
So if the flag he mentions is set, new (non-ACL) vols should be put on the waitlist

**Comment by davisagli** [comment]
But specifically, that restriction should only happen if we're within the "Waitlist Volunteers Window" and the new registration would put the ratio of volunteers to leaders above the limit.

**Comment by mscholtz** [comment]
There are already mechanisms that control when that flag gets set.  We don't need to worry about that here.  If the box is checked, do the thing.

**Comment by davisagli** [comment]
Gotcha

**Comment by ninetaLogik** [comment]
@mscholtz so the workPartyRole needs to be checked as well, since this only applies to Volunteers , correct?

**Comment by mscholtz** [comment]
Yes.

On Tue, Apr 21, 2015 at 5:10 PM, ninetaLogik <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> so the workPartyRole needs to be
> checked as well, since this only applies to Volunteers , correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/78#issuecomment-94978912>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
Does this need to happen in the trigger in order to waitlist regs entered directly into SF? Or do we just do it in the reg web service?

**Comment by mscholtz** [comment]
It should happen in the same place where it already determines who goes on
the waitlist.

On Tue, Apr 21, 2015 at 5:18 PM, ninetaLogik <notifications@github.com>
wrote:

> Does this need to happen in the trigger in order to waitlist regs entered
> directly into SF? Or do we just do it in the reg web service?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/78#issuecomment-94979818>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
This should now be done on SF side. Marking for Review. @davisagli is there anything to be done on your end?

**Comment by davisagli** [comment]
If I'm understanding the issue correctly, I don't think anything needs to change on the Pyramid side. Charlie, could you please test this, and if it still doesn't work correctly point us to a specific example?

**Comment by mscholtz** [comment]
@WaBirder57 can you check if this is working as expected, so we can close it?

**Comment by ebskopin** [comment]
This is working.  Closing.
