### ISSUE TITLE
CreateRegistration webservice doesn't save workPartyRole or comments

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#8]
I sent input including values for 'workPartyRole' and 'comments', but these values were not saved to the WP Registration that was created

**Comment by mscholtz** [comment]
@ninetaLogik can we add this to your work this iteration ?

**Comment by ninetaLogik** [comment]
The code to update these is already there and this seems to be working. I just tested it from the staging site and it worked. The role was set to volunteer and comments were set. Nothing to do here.

**Comment by davisagli** [comment]
Okay, I'll close this and reopen with more info if I reproduce the issue again. Thanks for taking a look.
