### ISSUE TITLE
Contacts must meet criteria before being able to be assigned as a Work Party Crew Leader

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#84]
In order to assign an individual as the Crew Leader for a work party they must be have 
- Contact.VMS Permission set to Crew Leader or Admin 
AND
- Contact. Crew Leader = True
AND
- Contact .Inactive Crew Leader = False or Null

**Comment by mscholtz** [comment]
I think this should be a story

**Comment by WaBirder57** [comment]
Created story #225.
