### ISSUE TITLE
test failing in Class.WTA_VMS_TEST_ParticipantAwardCreation

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#85]
Hey @drewpiston , this is the test from story 149, which we never finished.  But as-is, the test is failing (failed assertion).   could you comment out that assertion, and add some comments to the code just to clarify that it's in process and not expected to be working now?  

Just trying to get us to the point where we doing have any failing tests.

FYI, I'm working on moving us to the new sandbox, so please hold off on this until I get you a login there, and then please do it in the new sandbox.  Thanks!

**Comment by drewpiston** [comment]
This is done in the new sandbox.
