### ISSUE TITLE
test failing in WTA_VMS_TEST_WP_Registration_Completion

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#86]
Hi @drewpiston  so we're getting a test err in this one too (line 126).  Not sure if something that we added later ended up conflicting with this, but could you take a look?

Again, let's do this in new sandbox once I give the all-clear there.

FYI, I'd also like to change the name of this test and class.  At first I wasn't grokking what this class does, because it's the WP that's being completed, not a registration.  The comment at the start of the class mostly explains that, but maybe we could add just a bit more detail there?  Thanks!

**Comment by drewpiston** [comment]
Hi Matthew,

Unit test now passing -- I'll close this out.

And yes, I struggled with what to name this class.  I'll add comments right away, but let me know if you have a naming suggestion.

Thanks,
 Drew

**Comment by mscholtz** [comment]
OK, thanks.  I'll move changes over to the new sandbox.  Can you hold off on the other ticket and do it in the new sandbox, though?  Thanks!

**Comment by drewpiston** [comment]
Oh, curses, just saw the prior email (reading my email from top to bottom). Yes, I'll hold off on the other one.

Simple change for this one, too, so happy to recreate in the new sandbox once it's up and running.

**Comment by mscholtz** [comment]
No worries, this one's already done.

In terms of name, up to you.  Could be about closing out the WP, or about assigning hours/days credit, etc.

**Comment by mscholtz** [comment]
Oh, and one other thing I just noticed: can you leave out the "with sharing" declaration?  (both here, and in trigger- or batch-driven classes generally?)  I prefer to only include "with sharing" when we know we need it (primarily for VF controllers etc.)

In the new sandbox, plz.. ;)

**Comment by drewpiston** [comment]
Hi Matthew,

New class name is "WTA_VMS_WP_Registration_Assign_HoursDays".

One thing I'm not sure how to do gracefully is remove the old class from github.  I've already removed it from Salesforce.

Also, are there status for these tickets in github?  I see that it's open and I can close it, but I don't see how to mark it as anything in between.  Maybe I would just add a "Reviewing" tag if someone needs to review it?

Thanks,
 Drew

**Comment by WaBirder57** [comment]
Drew,

 

“Reviewing” works but it is also a note to me to test and then close that ticket (or make additional comments).

 

Charlie

 

Charles Kahle

Information Service Manager

 <http://www.wta.org/> Washington Trails Association

206-388-4511

Charles@wta.org

**Comment by mscholtz** [comment]
Yeah, Reviewing status for the ticket is right.

To remove the class in git, first delete it locally and in SF, then just
commit the deletion in your local repo, then push.  (if you're using a git
client it'll generally show up there as "missing", and you can commit that.)

Thanks!

On Wed, Apr 29, 2015 at 4:09 PM, drewpiston <notifications@github.com>
wrote:

> Hi Matthew,
>
> New class name is "WTA_VMS_WP_Registration_Assign_HoursDays".
>
> One thing I'm not sure how to do gracefully is remove the old class from
> github. I've already removed it from Salesforce.
>
> Also, are there status for these tickets in github? I see that it's open
> and I can close it, but I don't see how to mark it as anything in between.
> Maybe I would just add a "Reviewing" tag if someone needs to review it?
>
> Thanks,
> Drew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/86#issuecomment-97611121>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by drewpiston** [comment]
Ok, I added "reviewing" on this one.  I'd already closed the other one, which was just commenting out some test classes that we aren't ready for yet.

**Comment by skleinfeldt** [comment]
@drewpiston when you mark something reviewing it is also helpful to assign the ticket to the reviewer, usually @WaBirder57 - I'll assign this one.

**Comment by skleinfeldt** [comment]
(Or maybe it should have been @mscholtz ... change it to whomever is right...)
