### ISSUE TITLE
WTA_VMS_RegistrationPayment should allow for opps without any link to registration

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#87]
Hi @ninetaLogik so this class is causing some errs in some non-VMS code that WTA has, and would lead to errs in non-VMS production use.

Not every opp of type "Fee/Purchase" is a payment for a work party registration.  They use that rectype for other things as well.  Line 25 is throwing an err if no Registration rec is linked.

Instead of that, please check if the Registration lookup field is populated in the opp, and only do the query and remaining logic if it is.

I am in the process of moving us to the new sandbox.  So please hold off on this until I give you your login for the new sandbox, and make the changes there.  But if we could get this done this week that would be great.

Thank you!

**Comment by ninetaLogik** [comment]
Sure @mscholtz no prob just let me know when the new sandbox is ready.

**Comment by ninetaLogik** [comment]
@mscholtz This is now done in the vms2 sandbox.
