### ISSUE TITLE
VMS Work Party Reports tab just shows "loading....."

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#88]
When a crew leader clicks on the Reports tab to complete a work party report the tab screen only shows "Loading....."   This is blocking testing.

**Comment by davisagli** [comment]
As always, please give us a specific work party where you know it's not working. The problem may depend on details of the work party or its registrations.

David Glick
(mobile)

**Comment by WaBirder57** [comment]
The May 23-24th Spokane Area work party (http://staging.wta.org:6543/workparty/a2eK0000000wLTKIA2/) is an example but it seems to happen on all that I have tried.

**Comment by davisagli** [comment]
You need to specify a Land Manager for the "Spokane Area" trail segment. It's breaking because the land manager is not set.

**Comment by davisagli** [comment]
I also adjusted it so the report tab will not fail to load just because the land manager is missing.

**Comment by WaBirder57** [comment]
Thanks, working now.
