### ISSUE TITLE
Work Party: registering a friend assigns role of person registering

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#89]
When I register for a work party as an ACL and also add a friend, totally new to Salesforce, that new volunteer is created in Salesforce and registered on the work party.  This new person is given the same work party role as the person adding them as a friend.  The Salesforce record for the friend has the VMS Permission Level set correctly to "Volunteer", just the work party role is incorrect.

**Comment by davisagli** [comment]
This is related to #79

**Comment by mscholtz** [comment]
@WaBirder57 does #79 cover what we need here?  Can I delete this ticket?  And is #79 really low priority?

**Comment by WaBirder57** [comment]
I have added a comment to #79 that covers this ticket.  This ticket #89 can now be deleted.
