### ISSUE TITLE
Registration created for crew leader does not have Days Registered For set

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#90]
When a work party's Work Party Type has "Allow Single Day Registration" checked, registrations for that work party should have the Days Registered For multi-picklist field filled in.

When a registration is automatically created because the work party's Leader is set, the leader should have all of the relevant days selected for the Days Registered For field (e.g. if work party is two days long, Day 1 and Day 2 should be selected). This does not currently happen (the field remains blank).

**Comment by drewpiston** [comment]
This is ready for review!

**Comment by WaBirder57** [comment]
Looks good.
