### ISSUE TITLE
make Website Member ID unique? 

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#92]
currently the field Website Member ID on Contact in SF is not set as Unique, meaning it allows duplicate values across records.  I think we should set this to Unique.   There are already processes in SF webservices that should prevent an API call from VMS from attempting creation of a duplicate rec w/ the same ID

But @WaBirder57 , I know this field predates VMS.  Are there reasons you know of why enforcing uniqueness wouldn't work here?

Also: what about Website Member Name.  I think that's less important, but is uniqueness enforced in Plone? @davisagli

**Comment by davisagli** [comment]
Website Member Id is unique in Plone; I'm not sure about Website Member Name (screen name) given the customizations to the site -- Jesse or Charlie would know.

**Comment by mscholtz** [comment]
also note the bug here: #93 
if we make this unique before we fix that, we could end up w/ validation errs in some rare circumstances:

**Comment by WaBirder57** [comment]
At this time the SF Website User ID field is not unique.

**Comment by davisagli** [comment]
Closing this as a duplicate of #477
