### ISSUE TITLE
bug in contact dedup routine inserts duplicate plone IDs

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#93]
there is a bug in WTA_VMS_ContactFinderCreator that occurs in the following circumstances:

* we have a pre-existing dup in SF, at least 2 contacts w/ the same first/last name and email address, but don't have plone IDs
* we're processing a contact that matches name/email, and has plone ID (i.e. authenticated)

result: both contact recs end up being updated with the incoming plone ID
desired result: only one contact should be updated - the one returned by the method call

I created a test that exposes the err, currently failing: test_duplicate_name_and_email

**Comment by mscholtz** [comment]
@drewpiston did you make any headway on this one?

**Comment by drewpiston** [comment]
No, sadly I did not.

**Comment by mscholtz** [comment]
If you want to use your almost-an-hour to do this, i say sally forth!

**Comment by skleinfeldt** [comment]
Sally seconds the sally-ing

**Comment by drewpiston** [comment]
Sallied forth! Ready for review.
