### ISSUE TITLE
Work Parties w/ time exception should only go on the queue once they're Published

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#95]
WP's where the report is in status Draft should not go on the queue yet

**Comment by mscholtz** [comment]
@ninetaLogik FYI this is the other thing that's needed, but we can tackle it later

**Comment by mscholtz** [comment]
@ninetaLogik I think we should tackle this this week, while the Time Exception stuff is still relatively fresh in our minds.

**Comment by ninetaLogik** [comment]
@mscholtz Just checking that I understand this correctly. This comment: "WP's where the report is in status Draft should not go on the queue yet" refers to the Work Party Report related object, correct? But it seems that a WP can have multiple WP Reports. Is there another field that we can check to determine if the WP is published?

**Comment by mscholtz** [comment]
That is the field I'm talking about, yes.
But no, a WP can only have one related Report object.

On Tue, May 19, 2015 at 7:51 AM, ninetaLogik <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> Just checking that I understand
> this correctly. This comment: "WP's where the report is in status Draft
> should not go on the queue yet" refers to the Work Party Report related
> object, correct? But it seems that a WP can have multiple WP Reports. Is
> there another field that we can check to determine if the WP is published?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-103533755>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
Ok, so I will assume that something will enforce this 1-1 rel between WP and WP Report somehow. Could we have a roll up field from the WP report to the WP (since it's MD rel) so we can determine if the WP is in Draft mode or Published?

**Comment by mscholtz** [comment]
Isn't it already triggering on the Report obj?

On Tue, May 19, 2015 at 9:56 AM, ninetaLogik <notifications@github.com>
wrote:

> Ok, so I will assume that something will enforce this 1-1 rel between WP
> and WP Report somehow. Could we have a roll up field from the WP report to
> the WP (since it's MD rel) so we can determine if the WP is in Draft mode
> or Published?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-103590298>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
The process that submits to the Approval queue fires on WorkParty

**Comment by mscholtz** [comment]
Oh, right.

So we have this WF rule: https://cs9.salesforce.com/01QK00000001EjI
which sets the WP status to Complete when the report becomes Published.

So I was thinking we could just add criteria to the Process to require that
that WP be Complete.

However, it looks like it won't let us check "re-valuated WF Rules" on that
field update, b/c it's setting a field on the parent object.  So I don't
know whether our process will fire.  Suspect not.

We may have to change that WF rule to a trigger.

Unless you have other ideas?


On Tue, May 19, 2015 at 1:30 PM, ninetaLogik <notifications@github.com>
wrote:

> The process that submits to the Approval queue fires on WorkParty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-103659893>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by mscholtz** [comment]
Nineta and I are now thinking that the best approach for this would be to replace the PB with a trigger to submit the WP to the approval queue.  That trigger could also handle recalling it (see #94)

**Comment by mscholtz** [comment]
@ninetaLogik could you work on this ticket this week?  Let me know if you want to talk it out any further, but see comments above from our previous convos.

**Comment by ninetaLogik** [comment]
@mscholtz Just confirming what we need to do here:
1. In the work party trigger (after update) check if either Time Exception (checked) or Status has changed to Complete. If so, and the WP is now Marked for Time Exception AND Complete then submit the WP to the Approval Queue.
2. In the work party trigger (after update) check if Time Exception has changed and is now Unchecked then recall the WP from the Approval Queue.
3. Write unit tests to cover the above scenarios.

**Comment by mscholtz** [comment]
Yes, that's right.  your number 2 is actually what ticket #94 is about, and that's lower priority.  So you don't need to get that done as well right now, unless you have the hours and it's just as easy to do both at once.

**Comment by ninetaLogik** [comment]
And in this trigger we only process one WP at a time correct?

**Comment by mscholtz** [comment]
Yeah, I think that's fine.

On Fri, Jul 31, 2015 at 11:41 AM, ninetaLogik <notifications@github.com>
wrote:

> And in this trigger we only process one WP at a time correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-126780066>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
How should we react if the Submit for Approval fails. Throw an exception?

**Comment by mscholtz** [comment]
Not sure.  In what circumstances would it fail?

On Fri, Jul 31, 2015 at 12:35 PM, ninetaLogik <notifications@github.com>
wrote:

> How should we react if the Submit for Approval fails. Throw an exception?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-126792435>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
I guess even if submission to approval process fails (let's say someone changes the entry criteria for the approval process but does not update the trigger) the exception gets thrown anyway as I found out just now when I was passing in the wrong approval process name.

**Comment by mscholtz** [comment]
I think letting the default exception happen is fine for now.

On Fri, Jul 31, 2015 at 12:56 PM, ninetaLogik <notifications@github.com>
wrote:

> I guess even if submission to approval process fails (let's say someone
> changes the entry criteria for the approval process but does not update the
> trigger) the exception gets thrown anyway as I found out just now when I
> was passing in the wrong approval process name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/95#issuecomment-126797782>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment]
@mscholtz This should now be done. Classes added : WTA_VMS_WP_Manage_Approval and WTA_VMS_TEST_WP_Manage_Approval. 

@WaBirder57 
Testing instructions: 
1.Create new WP with Time Exception=true and Status=Planning - Check that not submitted for Approval
2. Update WP in step1 to set Status=Complete - Check that WP was submitted for Approval
3. Create new WP with Time Exception=true and Status=Complete - Check WP submitted for Approval

**Comment by ebskopin** [comment]
works.
