### ISSUE TITLE
VMS Staging web site only shows "Loading".... instead of WP list

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#98]
Go to: http://staging.wta.org:6543/  .  The web site only shows "Loading...." where the list of work parties should be.

**Comment by cguardia** [comment]
Elastic search was not running. @alecpm just started it. Site works now.

**Comment by WaBirder57** [comment]
Thanks, works now.  Is this a process we will need to know how to start?

**Comment by cguardia** [comment]
Once we are in production, it will be restarted automatically on every deployment.
